--- Makefile.orig	2013-06-03 14:46:00.000000000 +0000
+++ Makefile
@@ -13,17 +13,19 @@ RUN_DEPENDS=	gccmakedep:${PORTSDIR}/deve
 		makedepend:${PORTSDIR}/devel/makedepend \
 		${LOCALBASE}/lib/X11/config/xorg.cf:${PORTSDIR}/x11/xorg-cf-files
 
+USES=		shebangfix
 USE_PERL5=	yes
 
 XORG_CAT=	util
 USE_XORG=	xproto
+SHEBANG_FILES=	mkhtmlindex.pl
 
 # clang's cpp destroys whitespace, particularly hard tabs in makefiles,
 # which is fatal for imake.
 CPPFLAGS+=	-DDEFAULT_CC=\\\"gcc\\\"
 
 .ifdef USE_IMAKE
-.error You have `USE_IMAKE' variable defined either in environment or in make(1) arguments. Please undefine and try again.
+.error You have 'USE_IMAKE' variable defined either in environment or in make(1) arguments. Please undefine and try again.
 .endif
 
 MAN1=		ccmakedep.1 \
@@ -37,14 +39,12 @@ MAN1=		ccmakedep.1 \
 		xmkmf.1
 
 post-patch:
-	@${PERL} -pi -e 's,^#!/usr/bin/perl,#!${PERL},' ${WRKSRC}/mkhtmlindex.pl
 	@${REINPLACE_CMD} 's/test.*-traditional.*;/true;/' ${WRKSRC}/configure
 
 .include <bsd.port.pre.mk>
 
 # Attempt to force use of GNU cpp, if it is installed as /usr/bin/gcpp.
-.if (${OSVERSION} >= 900506 && ${OSVERSION} < 1000000) || \
-	${OSVERSION} >= 1000010
+.if exists(/usr/bin/gcpp)
 CONFIGURE_ENV+=       ac_cv_path_RAWCPP="gcpp"
 .endif
 
