OPTIONS_EXCLUDE+=	ENIGMAIL
LDFLAGS+=		-R${PREFIX}/lib/seamonkey

MOZ_OPTIONS+=	--host=${ARCH}-dports-${OPSYS:tl}${OSREL}
MOZ_OPTIONS+= --disable-webrtc

PULSEAUDIO_LIB_DEPENDS= libpulse.so:${PORTSDIR}/audio/pulseaudio
