--- Makefile.orig	2012-11-17 06:58:51.000000000 +0100
+++ Makefile	2013-01-04 14:58:49.531662000 +0100
@@ -53,21 +53,12 @@
 
 .include <bsd.port.pre.mk>
 
-.if !defined(GNUSTEP_WITH_CLANG)
-.if defined(GNUSTEP_WITH_BASE_GCC)
-.if ${OSVERSION} < 800000
-IGNORE=		does not build on FreeBSD 7
-.endif
-.if ${OSVERSION} >= 900036
-IGNORE=		needs an objective C compiler
-.endif
-.endif
-.endif
-
 .if defined(GNUSTEP_WITH_LIBOBJC2) || defined(GNUSTEP_WITH_CLANG)
 LIB_DEPENDS+=	objc:${PORTSDIR}/${PKGCATEGORY}/libobjc2
 CFLAGS+=	-I${LOCALBASE}/include -DOBJC2RUNTIME=1
 PLIST_SUB+=	WITH_LIB1="@comment "
+.elif ${OPSYS} == "DragonFly"
+PLIST_SUB+=	WITH_LIB1="@comment "
 .else
 PLIST_SUB+=	WITH_LIB1=""
 .endif
