--- Makefile.orig	2024-02-24 12:26:25 UTC
+++ Makefile
@@ -19,16 +19,4 @@ USE_CXXSTD=	gnu++98
 SVN_URL=	svn://anonsvn.kde.org/home/kde/trunk/kdesupport/qimageblitz
 SVN_REVISION=	1548172
 
-do-fetch:
-	@if [ "${FORCE_FETCH_ALL}" = "true" ] || ! [ -f "${DISTDIR}/${DIST_SUBDIR}/${DISTNAME}${EXTRACT_SUFX}" ]; then \
-	  ${MKDIR} ${DISTDIR}/${DIST_SUBDIR} && \
-	  cd ${DISTDIR}/${DIST_SUBDIR} && \
-	    svn co -r ${SVN_REVISION} ${SVN_URL} ${PORTNAME}-${DISTVERSIONFULL} && \
-	    (cd ${PORTNAME}-${DISTVERSIONFULL} && ${RM} -r .svn) && \
-	    ${FIND} ${PORTNAME}-${DISTVERSIONFULL} -and -exec ${TOUCH} -h -d 1970-01-01T00:00:00Z {} \; && \
-	    ${FIND} ${PORTNAME}-${DISTVERSIONFULL} -print0 | LC_ALL=C ${SORT} -z | \
-	        ${TAR} czf ${PORTNAME}-${DISTVERSIONFULL}${EXTRACT_SUFX} --format=ustar --uid 0 --gid 0 --options gzip:!timestamp --no-recursion --null -T - && \
-	    ${RM} -r ${PORTNAME}-${DISTVERSIONFULL}; \
-	fi
-
 .include <bsd.port.mk>
