--- Makefile.orig	2014-09-14 09:36:48 UTC
+++ Makefile
@@ -24,4 +24,7 @@ GH_COMMIT=	2a03577
 GH_PROJECT=	${PORTNAME}
 GH_TAGNAME=	${PORTNAME}-${PORTVERSION}-20140410
 
+post-patch:
+	@${REINPLACE_CMD} -e 's| -Werror||g' ${WRKSRC}/Makefile.in
+
 .include <bsd.port.mk>
