--- Makefile.orig	2021-01-20 16:57:07.876654000 +0100
+++ Makefile	2021-01-24 15:33:38.945915000 +0100
@@ -83,7 +83,7 @@
 DOCSDIR=	${PREFIX}/share/doc/${PORTNAME}-${DISTVERSION}
 
 CFLAGS+=	-I${WRKSRC}/slurm -I${LOCALBASE}/include -fcommon
-LDFLAGS+=	-L${LOCALBASE}/lib -lsysinfo -lprocstat -fcommon
+LDFLAGS+=	-L${LOCALBASE}/lib -lsysinfo -fcommon
 
 # Hack around nonfunctional --disable-gtktest flag
 pre-configure-GUI-off:
