--- Makefile.orig	2024-02-24 12:15:00 UTC
+++ Makefile
@@ -91,7 +91,7 @@ CFLAGS+=	-I${WRKSRC}/slurm -I${LOCALBASE
 		-I${LOCALBASE}/include/level_zero		\
 		-I${LOCALBASE}/include/librdkafka		\
 		-fcommon -D__BSD_VISIBLE=1
-LDFLAGS+=	-L${LOCALBASE}/lib -lsysinfo -lprocstat -fcommon
+LDFLAGS+=	-L${LOCALBASE}/lib -lsysinfo -fcommon
 
 PROC2FIX=	common/callerid.c common/fd.c common/fetch_config.c	\
 		interfaces/proctrack.c	\
