--- Makefile.orig	2015-06-02 11:53:19 UTC
+++ Makefile
@@ -6,6 +6,7 @@ PORTVERSION=	7.8.3
 PORTREVISION=	1
 CATEGORIES=	lang haskell
 MASTER_SITES=	http://www.haskell.org/ghc/dist/${PORTVERSION}/:source \
+		http://leaf.dragonflybsd.org/~marino/dports-src/:dflyboot \
 		LOCAL/pgj/:boot
 DISTFILES=	ghc-${PORTVERSION}-src${EXTRACT_SUFX}:source
 
@@ -64,7 +65,7 @@ OPTIONS_DEFINE+=	BOOT
 OPTIONS_DEFINE+=	BOOTH
 .endif
 
-.include <bsd.port.options.mk>
+.include <bsd.port.pre.mk>
 
 .if ${PORT_OPTIONS:MDYNAMIC}
 # The version number is needed as lang/gcc installs a different version
@@ -73,6 +74,7 @@ LIB_DEPENDS+=	libffi.so.6:${PORTSDIR}/de
 
 .if empty(PORT_OPTIONS:MBOOT)
 
+.if ${OPSYS} == "FreeBSD"
 BOOT_GHC_VERSION=	7.6.3
 
 .if ${ARCH} == "i386"
@@ -85,7 +87,7 @@ DISTFILES+=	ghc-${BOOT_GHC_VERSION}-i386
 DISTFILES+=	ghc-${BOOT_GHC_VERSION}-i386-freebsd8-boot${EXTRACT_SUFX}:boot
 .endif
 
-.elif ${ARCH} == "amd64"
+.elif ${ARCH:S///} == "amd64"
 
 .if ${OSVERSION} >= 1000043
 DISTFILES+=	ghc-${BOOT_GHC_VERSION}-amd64-freebsd10-boot${EXTRACT_SUFX}:boot
@@ -95,6 +97,17 @@ DISTFILES+=	ghc-${BOOT_GHC_VERSION}-amd6
 DISTFILES+=	ghc-${BOOT_GHC_VERSION}-amd64-freebsd8-boot${EXTRACT_SUFX}:boot
 .endif
 
+.endif		# FreeBSD platform list
+
+.elif ${OPSYS} == "DragonFly"
+
+BOOT_GHC_VERSION=	7.6.3
+DISTFILES+=		ghc-${BOOT_GHC_VERSION}-${ARCH}-dragonfly-boot${EXTRACT_SUFX}:dflyboot
+CONFIGURE_TARGET=	${ARCH}-portbld-dragonfly
+CONFIGURE_ENV+=		BOOTDIR=${BOOT_DIR}
+
+.else
+IGNORE=		unsupported ${OPSYS} Operating System
 .endif
 
 .endif # MBOOT
