--- Makefile.orig	2019-05-28 23:17:14 UTC
+++ Makefile
@@ -6,6 +6,7 @@ PORTVERSION=	${GHC_VERSION}
 PORTREVISION=	1
 CATEGORIES=	lang haskell
 MASTER_SITES=	https://www.haskell.org/ghc/dist/${PORTVERSION}/:source \
+		http://leaf.dragonflybsd.org/~marino/dports-src/:dflyboot \
 		LOCAL/arrowd/:boot \
 		https://hackage.haskell.org/package/hscolour-${HSCOLOUR_VERSION}/:docs
 DISTFILES=	ghc-${PORTVERSION}-src${EXTRACT_SUFX}:source \
