--- Makefile.orig	2020-07-17 16:45:23.712967000 +0200
+++ Makefile	2020-07-17 16:37:54.602120000 +0200
@@ -27,9 +27,9 @@
 		--prefix="${PREFIX}"
 
 PLIST_FILES=	include/xmlbird.h \
-		lib/libxmlbird.so \
-		lib/libxmlbird.so.1 \
-		libdata/pkgconfig/xmlbird.pc \
+		lib64/libxmlbird.so \
+		lib64/libxmlbird.so.1 \
+		lib64/pkgconfig/xmlbird.pc \
 		share/vala/vapi/xmlbird.vapi
 
 do-build:
@@ -37,6 +37,6 @@
 
 do-install:
 	(cd ${WRKSRC} && ./install.py --dest="${STAGEDIR}")
-	@${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/libxmlbird.so.1
+	@${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib64/libxmlbird.so.1
 
 .include <bsd.port.mk>
