--- Makefile.orig	2013-04-04 12:29:38.712025000 +0000
+++ Makefile
@@ -51,7 +51,6 @@ OPTIONS_DEFAULT=GIO WEBRTC
 
 .include "${.CURDIR}/../../www/firefox/Makefile.options"
 
-OPTIONS_DEFAULT:=${OPTIONS_DEFAULT:S/OSS/ALSA/}
 
 .include <bsd.port.pre.mk>
 
