--- Makefile.orig	2013-11-05 01:05:03.589388000 +0000
+++ Makefile
@@ -57,10 +57,6 @@ WRKSRC:=	${WRKDIR}/mozilla-release
 USE_GCC?=	yes
 .endif
 
-post-extract:
-	@${SED} -e 's|@FIREFOX_ICON@|${FIREFOX_ICON}|' -e 's|@MOZILLA@|${MOZILLA}|' \
-		-e 's|@MOZILLA_NAME@|${MOZILLA_NAME}|' \
-		<${FILESDIR}/firefox.desktop.in >${WRKDIR}/${MOZILLA}.desktop
 
 post-patch:
 	@${REINPLACE_CMD} -e '/MOZPNG/s/=[0-9]*/=10511/' \
