--- Makefile.orig	2016-01-05 21:10:04 UTC
+++ Makefile
@@ -15,30 +15,33 @@ USE_GSTREAMER=	yes
 
 .include "${.CURDIR}/../../Mk/bsd.gstreamer.mk"
 
-.for all in ${_GSTREAMER_PLUGINS}
-OPTIONS_DEFINE+=	${all:tu}
+ALL_PLUGINS:=	${_GSTREAMER_PLUGINS}
+# Weed out gst-plugins that can not be packaged. or are broken.
+.if defined(PACKAGE_BUILDING)
+# FAAC:    Mp4 Dolby license , no package
+# LAME:    MP3 License , no package
+# VDPAU:   Needs to be build agains running kernel
+DEF_PLUGINS:=	${_GSTREAMER_PLUGINS:Nfaac:Nlame:Nvdpau}
+.else
+DEF_PLUGINS:=	${_GSTREAMER_PLUGINS}
+.endif
+
+.for all in ${ALL_PLUGINS}
 ${all:tu}_DESC=	${all} plugin
-OPTIONS_DEFAULT+=	${all:tu}
+${all:tu}_USE=	GSTREAMER=${all}
 .endfor
 
-.include <bsd.port.pre.mk>
+# Pull out i386-only plugins, add back conditionally
+ALL_PLUGINS:=	${ALL_PLUGINS:Nspc}
+DEF_PLUGINS:=	${DEF_PLUGINS:Nspc}
 
-# Weed out gst-plugins that can not be packaged. or are broken.
-.if defined(PACKAGE_BUILDING)
-PORT_OPTIONS:=	${PORT_OPTIONS:NFAAC} # Mp4 Dolby license , no package
-PORT_OPTIONS:=	${PORT_OPTIONS:NLAME} # MP3 License , no package
-PORT_OPTIONS:=	${PORT_OPTIONS:NPEG2ENC} # Broken
-PORT_OPTIONS:=	${PORT_OPTIONS:NVDPAU} # Needs to be build agains running kernel
-.endif
+OPTIONS_DEFINE=	${ALL_PLUGINS:tu} ${PLUGIN_SPC}
+OPTIONS_DEFAULT=	${DEF_PLUGINS:tu} ${PLUGIN_SPC}
 
-.if ${ARCH} != "i386"
-PORT_OPTIONS:=	${PORT_OPTIONS:NSPC} # i386 only
-.endif
+.include <bsd.port.options.mk>
 
-.for f in ${OPTIONS_DEFINE}
-.if ${PORT_OPTIONS:M${f:tu}}
-USE_GSTREAMER+=	${f:tl}
+.if ${ARCH} == i386
+PLUGIN_SPC=	SPC
 .endif
-.endfor
 
-.include <bsd.port.post.mk>
+.include <bsd.port.mk>
