OPTIONS_DEFAULT:=      ${OPTIONS_DEFAULT:NKGDB}

dfly-patch:
       ${CP} ${DFLY_FILESDIR}/dfly64.mh ${WRKSRC}/gdb/config/i386/
       ${CP} ${DFLY_FILESDIR}/dfly-nat.* ${WRKSRC}/gdb/
       ${CP} ${DFLY_FILESDIR}/i386* ${WRKSRC}/gdb/
       ${CP} ${DFLY_FILESDIR}/amd64* ${WRKSRC}/gdb/
.if ${PORT_OPTIONS:MKGDB}
       ${PATCH} ${PATCH_ARGS} < ${DFLY_FILESDIR}/extrapatch-kgdb
.endif

