--- Makefile.orig	2015-10-18 16:29:03.000000000 +0300
+++ Makefile
@@ -49,7 +49,7 @@ DIALOGNAME=	dialog-1.1-20120706
 MAKE_ENV+=	DIALOGSOURCES=${WRKDIR}/${DIALOGNAME}
 
 do-configure:
-	@cd ${WRKDIR}/${DIALOGNAME}; ./configure
+	@cd ${WRKDIR}/${DIALOGNAME}; ./configure LDFLAGS="${LDFLAGS}"
 
 .endif
 
