--- Makefile.orig	2016-11-19 19:14:39 UTC
+++ Makefile
@@ -49,7 +49,7 @@ DIALOGNAME=	dialog-1.1-20120706
 MAKE_ENV+=	DIALOGSOURCES=${WRKDIR}/${DIALOGNAME}
 
 do-configure:
-	@cd ${WRKDIR}/${DIALOGNAME}; ./configure
+	@cd ${WRKDIR}/${DIALOGNAME}; ${SETENV} ${CONFIGURE_ENV} ./configure LDFLAGS="${LDFLAGS}"
 
 .endif
 
