--- Makefile.orig	2013-06-03 09:23:52.000000000 +0000
+++ Makefile
@@ -19,14 +19,14 @@ PROJECTHOST=	git-core
 GIT_VERSION=	1.8.2.3
 USE_BZIP2=	yes
 USE_GMAKE=	yes
-USES=		iconv shebangfix
+USES=		iconv shebangfix gettext
 SHEBANG_FILES=	filters/html-converters/resources/markdown.pl
 USE_GMAKE=	yes
 USE_OPENSSL=	yes
 CFLAGS+=	-I${LOCALBASE}/include
 MAKE_ARGS+=	CGIT_SCRIPT_PATH=${WWWDIR} \
 		CGIT_CONFIG=${PREFIX}/etc/cgitrc
-LDFLAGS+=	-L${LOCALBASE}/lib
+LDFLAGS+=	-L${LOCALBASE}/lib -liconv -lintl
 MAKE_JOBS_SAFE=	yes
 
 SUB_FILES=	pkg-message
@@ -40,9 +40,11 @@ post-extract:
 	@${MV} ${WRKDIR}/git-${GIT_VERSION} ${WRKSRC}/git
 
 post-patch:
-	@${REINPLACE_CMD} -e '/^CC =/d' ${WRKSRC}/git/Makefile
+	@${REINPLACE_CMD} -e '/^CC =/d' -e '/^CFLAGS =/d' \
+		-e '/^LDFLAGS =/d' ${WRKSRC}/git/Makefile
 	@${REINPLACE_CMD} -e 's,/usr,${PREFIX},g' \
 		-e 's,-Igit,-I.,g' ${WRKSRC}/Makefile
+	@cd ${WRKSRC}; ${RM} ${SHEBANG_FILES}.bak
 
 post-install:
 	@${MKDIR} /var/cache/${PORTNAME}
