--- Makefile.orig	2016-05-06 17:14:59 UTC
+++ Makefile
@@ -50,6 +50,7 @@ OPTIONS_DEFINE=	DOCS
 
 .if ${CHOSEN_COMPILER_TYPE} == "gcc"
 CXXFLAGS+=	-D_GLIBCXX_USE_C99
+LDFLAGS+=       -lboost_system
 .endif
 
 post-extract:
