--- Makefile.orig	2013-05-10 15:33:13.481804000 +0000
+++ Makefile
@@ -26,7 +26,7 @@ BUILD_WRKSRC=	${WRKDIR}/${DISTNAME}/src
 #
 PORTSCOUT=	limit:.*-jumbo
 
-OSNAME=		${OPSYS:tl}
+OSNAME=		freebsd
 CFLAGS+=	-DJOHN_SYSTEMWIDE=1 \
 		-DJOHN_SYSTEMWIDE_HOME=\\"${DATADIR}\\" \
 		-DCFG_FULL_NAME=\\"${PREFIX}/etc/${PORTNAME}.conf\\"
