--- Makefile.orig	2013-05-10 15:33:13.481804000 +0000
+++ Makefile
@@ -26,7 +26,7 @@ BUILD_WRKSRC=	${WRKDIR}/${DISTNAME}/src
 #
 PORTSCOUT=	limit:.*-jumbo
 
-OSNAME=		${OPSYS:L}
+OSNAME=		freebsd
 CFLAGS+=	-DJOHN_SYSTEMWIDE=1 \
 		-DJOHN_SYSTEMWIDE_HOME=\\"${DATADIR}\\" \
 		-DCFG_FULL_NAME=\\"${PREFIX}/etc/${PORTNAME}.conf\\"
@@ -59,6 +59,10 @@ ALL_TARGET=	generic
 BROKEN=		Does not compile on sparc64
 .endif
 
+.if ${PORT_OPTIONS:MOPENMP}
+USE_GCC=	4.7
+.endif
+
 post-patch:
 	@${REINPLACE_CMD} -e 's|= gcc|= ${CC}|' \
 		-e '/^CFLAGS =/s|-O2|${CFLAGS}|' ${WRKSRC}/src/Makefile
