--- Makefile.orig	2013-03-19 10:40:22.000000000 +0000
+++ Makefile
@@ -39,7 +39,7 @@ OPTIONS_DEFAULT=PYTHON
 
 .include <bsd.port.options.mk>
 
-.if ${PORT_OPTIONS:MPYTHON
+.if ${PORT_OPTIONS:MPYTHON}
 
 USE_PYTHON=	yes
 PLIST_SUB+=	PYTHON=""
