--- Makefile.orig	2013-06-15 12:01:35.215015000 +0000
+++ Makefile
@@ -17,8 +17,7 @@ PLIST_FILES=	bin/gccmakedep
 .include <bsd.port.pre.mk>
 
 # Attempt to force use of GNU cpp, if it is installed as /usr/bin/gcpp.
-.if (${OSVERSION} >= 900506 && ${OSVERSION} < 1000000) || \
-    ${OSVERSION} >= 1000010
+.if exists(/usr/bin/gcpp)
 CONFIGURE_ENV+=	ac_cv_path_RAWCPP="gcpp"
 .endif
 
