--- Makefile.orig	2017-02-06 15:16:51 UTC
+++ Makefile
@@ -70,9 +70,8 @@ IGNORE=		cannot build node.js with Libre
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} == "armv6"
+# something is wrong with configure wrt to DF I think
 CONFIGURE_ARGS+=--openssl-no-asm
-.endif
 
 .if ${COMPILER_TYPE} == gcc
 # GCC does not expose std::snprintf() without this define
