--- Makefile.orig	2018-02-28 15:34:53 UTC
+++ Makefile
@@ -18,8 +18,7 @@ OPTIONS_DEFINE=	BUNDLED_SSL DOCS NLS DTR
 OPTIONS_DEFAULT=DTRACE
 OPTIONS_SUB=	yes
 
-OPTIONS_DEFAULT_FreeBSD_10=	BUNDLED_SSL
-OPTIONS_DEFAULT+=		${OPTIONS_DEFAULT_${OPSYS}_${OSREL:R}}
+OPTIONS_DEFAULT+=		BUNDLED_SSL
 
 .if !exists(/usr/sbin/dtrace)
 OPTIONS_EXCLUDE+=	DTRACE
@@ -41,7 +40,7 @@ NLS_LIB_DEPENDS=	libicui18n.so:devel/icu
 
 DTRACE_CONFIGURE_ON=	--with-dtrace
 
-USES=		compiler:c++11-lib gmake python:2.7,build pkgconfig \
+USES=		compiler:c++11-lib gmake python:2,build pkgconfig \
 		localbase shebangfix
 
 HAS_CONFIGURE=	yes
@@ -79,9 +78,8 @@ IGNORE=		cannot build node.js with Libre
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} == armv6 || ${ARCH} == armv7
+# something is wrong with configure wrt to DF I think
 CONFIGURE_ARGS+=--openssl-no-asm
-.endif
 
 .if ${COMPILER_TYPE} == gcc
 # GCC does not expose std::snprintf() without this define
