--- Makefile.orig	2024-02-02 00:06:05 UTC
+++ Makefile
@@ -21,7 +21,7 @@ WRKSRC=		${WRKDIR}/architect-${PORTVERSI
 
 OPTIONS_DEFINE=	DOCS MYSQL_JDBC PGSQL_JDBC
 
-MYSQL_JDBC_RUN_DEPENDS=	${JAVALIBDIR}/mysql-connector-java.jar:databases/mysql-connector-java
+MYSQL_JDBC_RUN_DEPENDS=	${JAVALIBDIR}/mysql-connector-java.jar:databases/mysql-connector-j
 PGSQL_JDBC_RUN_DEPENDS=	${JAVALIBDIR}/postgresql.jar:databases/postgresql-jdbc
 
 do-install:
