USES+=	alias

dfly-patch:
	${REINPLACE_CMD} -e 's@STREQUAL "FreeBSD"@MATCHES "FreeBSD|DragonFly"@g' \
		${WRKSRC}/cmake/FindGRASS.cmake \
		${WRKSRC}/src/app/CMakeLists.txt \
		${WRKSRC}/src/plugins/grass/CMakeLists.txt
