--- Makefile.orig	2013-03-18 11:57:45.899078000 +0000
+++ Makefile
@@ -21,6 +21,7 @@ LANGS=		da fr gl it pl ru sv tr
 
 do-build:
 	cd ${WRKSRC} && ${CC} ${CFLAGS} `pkg-config --cflags --libs gtk+-2.0` \
+		-lintl \
 		gperiodic.c -o gperiodic
 .for lang in ${LANGS}
 	cd ${WRKSRC}/po && msgfmt -f -v -o ${lang}.mo ${lang}.po
