--- Makefile.orig	2017-02-20 18:50:58 UTC
+++ Makefile
@@ -30,7 +30,7 @@ RELEASE_11_0_DISTFILES=	base.txz:R11
 RELEASE_11_0_VARS=	RELEASE=R11_0 CTARGET=aarch64-aux-freebsd11.0
 
 post-extract:
-	/bin/chflags -R noschg ${WRKDIR}
+	/usr/bin/chflags -R noschg ${WRKDIR}
 
 do-install:
 	@${MKDIR} ${STAGEDIR}${PREFIX}/sysroot
