--- oss/50-oss.conf.orig
+++ oss/50-oss.conf
@@ -15,6 +15,19 @@ pcm.oss {
 	}
 }
 
+pcm.dfly_ossplug {
+	@args [ DEVICE ]
+	@args.DEVICE {
+		type string
+		default "/dev/dsp"
+	}
+	type plug
+	slave.pcm {
+		type oss
+		device $DEVICE
+	}
+}
+
 ctl.oss {
 	@args [ DEVICE ]
 	@args.DEVICE {
