--- Makefile.orig	2013-03-01 15:56:37.668584000 +0100
+++ Makefile	2013-03-01 15:56:55.577781000 +0100
@@ -177,7 +177,7 @@
 
 pre-everything::
 	@${ECHO_MSG} ' '
-	@${ECHO_MSG} 'A description of ALT_HOME may be found in the port's Makefile.'
+	@${ECHO_MSG} "A description of ALT_HOME may be found in the port's Makefile."
 	@${ECHO_MSG} ' '
 
 post-install:
