--- Makefile.orig	2012-12-06 17:44:17.000000000 +0100
+++ Makefile	2012-12-10 17:05:31.394163000 +0100
@@ -136,7 +136,7 @@
 .  endif
 .endif # !SLAVE_ONLY
 
-.if ${PORT_OPTIONS:MOSSP_UUID)
+.if ${PORT_OPTIONS:MOSSP_UUID}
 BUILD_DEPENDS+=	${LOCALBASE}/lib/libuuid.a:${PORTSDIR}/misc/ossp-uuid
 CONFIGURE_ARGS+=--with-ossp-uuid
 PLIST_SUB+=	OSSP=""
