--- Makefile.orig	2015-06-06 15:51:03 UTC
+++ Makefile
@@ -50,18 +50,6 @@ PORTDOCS=	AUTHORS CHANGES INSTALL LICENS
 BROKEN=		Base system sendmail not found or too old, rebuild with WITH_SENDMAIL_PORT=yes
 .endif
 
-.if !defined(SENDMAIL_WITHOUT_MILTER)
-.if defined(WITH_SENDMAIL_PORT)
-.if !defined(WITH_SENDMAIL_STATIC_MILTER) && !exists(${LOCALBASE}/lib/libmilter.so.${MILTER_SOVER})
-pre-everything::
-	@${ECHO_MSG}
-	@${ECHO_MSG} You must rebuild sendmail port with SENDMAIL_WITH_SHARED_MILTER
-	@${ECHO_MSG} or set variable WITH_SENDMAIL_STATIC_MILTER
-	@${FALSE}
-.endif
-.endif
-.endif
-
 .if defined(WITH_SENDMAIL_PORT)
 CONFIGURE_ARGS+=--with-sendmail=${MILTERBASE}
 .endif
