--- Makefile.orig	2021-09-06 20:51:01 UTC
+++ Makefile
@@ -1,6 +1,7 @@
 PORTNAME=	aom
 DISTVERSIONPREFIX=	v
 DISTVERSION=	3.1.2
+PORTREVISION=	1
 CATEGORIES=	multimedia
 
 MAINTAINER=	jbeich@FreeBSD.org
