--- Makefile.orig	2015-02-02 18:06:29 UTC
+++ Makefile
@@ -24,16 +24,4 @@ USE_LDCONFIG=	yes
 pre-install:
 	@${MKDIR} ${STAGEDIR}${PREFIX}/include/libutp
 
-post-build:
-	${MAKE} -f ${FILESDIR}/BSDmakefile.utils -C ${WRKSRC}/utp_file PROG_CXX=utp_send
-	${MAKE} -f ${FILESDIR}/BSDmakefile.utils -C ${WRKSRC}/utp_file PROG_CXX=utp_recv
-	${MAKE} -f ${FILESDIR}/BSDmakefile.utils -C ${WRKSRC}/utp_test PROG_CXX=utp_test
-
-post-install:
-	${INSTALL_PROGRAM}	\
-	    ${WRKSRC}/utp_file/utp_send	\
-	    ${WRKSRC}/utp_file/utp_recv	\
-	    ${WRKSRC}/utp_test/utp_test \
-		${STAGEDIR}${PREFIX}/bin/
-
 .include <bsd.port.mk>
