--- Makefile.orig	2013-05-07 18:22:12.418952000 +0000
+++ Makefile
@@ -40,7 +40,11 @@ USE_PYTHON=		yes
 PLIST_SUB+=		PYTHON="@comment "
 .endif
 
+.if ${OPSYS} == DragonFly
+USES+= usb
+.else
 EXTRA_PATCHES=	${FILESDIR}/extra-patch-configure.in
+.endif
 
 post-patch:
 	@${REINPLACE_CMD} -E -e \
