--- Makefile.orig	2013-01-14 17:40:59.898123000 +0100
+++ Makefile	2013-01-14 17:41:31.678167000 +0100
@@ -35,7 +35,7 @@
 CONFIGURE_ARGS+=	--without-boost
 .endif
 
-.if ${OSVERSION} < 800069
+.if ${OPSYS} == "DragonFly" || ${OSVERSION} < 800069
 LIB_DEPENDS+=	usb-0.1:${PORTSDIR}/devel/libusb
 .else
 EXTRA_PATCHES=	${FILESDIR}/extra-patch-configure.in
