--- Makefile.orig	2017-08-26 14:52:26 UTC
+++ Makefile
@@ -7,6 +7,7 @@ MASTERDIR=	${.CURDIR}/../kibana45
 PKGDIR=		${.CURDIR}
 DISTINFO_FILE=	${.CURDIR}/distinfo
 
+IGNORE=		swills lazily reused kibana45 which needs the blocked node4
 RUN_DEPENDS=	node6>=v6.9.0:www/node6
 
 .include "${MASTERDIR}/Makefile"
