--- Makefile.orig	2017-05-07 02:23:36 UTC
+++ Makefile
@@ -27,6 +27,7 @@ USES=			perl5
 USE_PERL5=		configure
 PATCH_WRKSRC=		${WRKDIR}/${DISTNAME}
 WRKSRC=			${WRKDIR}/${DISTNAME}/pidl
+IGNORE=			unused, but pulls in unavailable samba46 port
 
 post-extract:
 			@${RM} -r ${WRKSRC}/lib/Parse/Yapp ${WRKSRC}/lib/wscript_build
