--- Makefile.orig	2019-01-22 15:47:15 UTC
+++ Makefile
@@ -50,7 +50,11 @@ USE_RC_SUBR=	ntopng
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|' \
+		-e 's|FreeBSD|DragonFly|g' \
 		${WRKSRC}/configure.seed
+	${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|' \
+		-e 's|FreeBSD|DragonFly|g' \
+		${WRKSRC}/Makefile.in
 	cd ${WRKSRC} && ${SH} autogen.sh
 
 post-install:
