--- Makefile.orig	2016-03-24 10:17:46.000000000 +0200
+++ Makefile
@@ -37,10 +37,4 @@ post-install:
 	@${MKDIR} ${STAGEDIR}${DOCSDIR}/libs
 	${INSTALL_DATA} ${WRKSRC}/doc/how-fuse-works ${WRKSRC}/doc/kernel.txt ${STAGEDIR}${DOCSDIR}/libs
 
-.include <bsd.port.pre.mk>
-
-.if ${OPSYS} == DragonFly
-IGNORE=	fusefs has not been implemented on DragonFly
-.endif
-
-.include <bsd.port.post.mk>
+.include <bsd.port.mk>
