--- Makefile.orig	2019-05-15 01:19:02 UTC
+++ Makefile
@@ -13,8 +13,6 @@ COMMENT=	FUSE allows filesystem implemen
 LICENSE=	LGPL21
 LICENSE_FILE=	${WRKSRC}/COPYING.LIB
 
-IGNORE_DragonFly=	fusefs has not been implemented on DragonFly
-
 PORTSCOUT=	limit:^2\.
 
 USE_GITHUB=	yes
