--- Makefile.orig	2022-11-06 17:53:15 UTC
+++ Makefile
@@ -13,8 +13,6 @@ WWW=		https://github.com/libfuse/libfuse
 LICENSE=	LGPL21
 LICENSE_FILE=	${WRKSRC}/COPYING.LIB
 
-IGNORE_DragonFly=	fusefs has not been implemented on DragonFly
-
 USES=		autoreconf gettext-tools iconv libtool
 USE_LDCONFIG=	yes
 
