--- Makefile.orig	2013-01-26 11:54:25.094695000 +0100
+++ Makefile	2013-01-26 11:54:36.454711000 +0100
@@ -7,6 +7,7 @@
 
 CATEGORIES=	french www
 DISTNAME=	MTOS-${PORTVERSION}-${PKGNAMEPREFIX:S,-,,}
+PKGNAMEPREFIX=	fr-
 
 COMMENT=	French localization of the MovableType publishing system
 
