--- Makefile.orig	Tue Apr  1 21:50:08 2025
+++ Makefile	Tue Apr
@@ -45,6 +45,7 @@ PLIST_SUB+=	COREDUMP=""
 .endif
 
 post-install:
+.  if ${OPTIONS_DEFAULT:MTESTS}
 	cd ${STAGEDIR}${PREFIX}/ && ${FIND} libexec/libunwind -type f >> ${TMPPLIST}
-
+.  endif
 .include <bsd.port.mk>
