diff --git a/math/sc-im/Makefile b/math/sc-im/Makefile
index 4136e42c087..991d645ae89 100644
--- a/math/sc-im/Makefile
+++ b/math/sc-im/Makefile
@@ -22,7 +22,7 @@ WRKSRC_SUBDIR=        src
 CFLAGS+=       -DXLSX_EXPORT -DXLS
 LIBS+=         -lxlsreader -lxlsxwriter
 MAKE_ENV+=     LDLIBS="${LIBS}"
-MAKE_ARGS+=    CC="${CC}" prefix="${PREFIX}" MANDIR="${MANPREFIX}/man/man1"
+MAKE_ARGS+=    CC="${CC}" prefix="${PREFIX}" MANDIR="${PREFIX}/share/man/man1"

 post-install:
        ${STRIP_CMD} ${STAGEDIR}${PREFIX}/bin/sc-im
diff --git a/math/sc-im/pkg-plist b/math/sc-im/pkg-plist
index b4b174b8874..cfb1ec421e3 100644
