--- Makefile.orig	2013-10-23 19:52:47.608979000 +0000
+++ Makefile
@@ -43,6 +43,6 @@ post-extract:
 
 do-install:
 	@${MKDIR} ${STAGEDIR}${DATADIR}
-	@${INSTALL_SCRIPT} -v ${WRKSRC}/${PORTNAME}.pl ${STAGEDIR}${DATADIR}
+	@${INSTALL_SCRIPT} ${WRKSRC}/${PORTNAME}.pl ${STAGEDIR}${DATADIR}
 
 .include <bsd.port.post.mk>
