--- Makefile.orig	2017-10-07 14:11:22 UTC
+++ Makefile
@@ -11,8 +11,7 @@ COMMENT=	Shows you lines of code that ar
 LICENSE=	MIT
 LICENSE_FILE=	${WRKSRC}/LICENSE
 
-LIB_DEPENDS=	libunwind.so:devel/libunwind \
-		libgmp.so:math/gmp
+LIB_DEPENDS=	libgmp.so:math/gmp
 RUN_DEPENDS=	rubygem-debugger-ruby_core_source>=1.3:devel/rubygem-debugger-ruby_core_source
 
 USES=		gem
