--- Makefile.orig	2013-11-05 12:34:09.592999000 +0000
+++ Makefile
@@ -103,15 +103,13 @@ XPI_ID=		lightning@thunderbird.mozilla.o
 MOZ_OPTIONS+=	--disable-calendar
 .endif
 
-post-extract:
+post-patch:
 	@${SED} -e 's|@PORTNAME_ICON@|${PORTNAME_ICON}|;s|@MOZILLA@|${MOZILLA}|' \
 		<${FILESDIR}/thunderbird.desktop.in >${WRKDIR}/${MOZILLA_EXEC_NAME}.desktop
 .if ${PORT_OPTIONS:MENIGMAIL}
 	@${TAR} -xf ${_DISTDIR}/${EM_DISTFILE} \
 		-C ${WRKSRC}/mailnews/extensions
 .endif
-
-post-patch:
 	@${REINPLACE_CMD} -e '/MOZPNG/s/=[0-9]*/=10511/' \
 		${MOZSRC}/configure.in ${WRKSRC}/configure.in
 	@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|g' \
