--- Makefile.orig	2013-12-24 20:07:48.941070000 +0000
+++ Makefile
@@ -22,6 +22,9 @@ DESKTOP_ENTRIES="zNotes" "Notes managmen
 		"Utility;TextEditor;Qt;" true
 
 OPTIONS_DEFINE=		NLS
+OPTIONS_SUB=		yes
+
+.include <bsd.port.options.mk>
 
 post-patch:
 	@${REINPLACE_CMD} -e '/.path =/s|/usr|$$$$PREFIX|g' \
