--- Makefile.orig	2012-11-17 06:03:23.000000000 +0000
+++ Makefile
@@ -43,9 +43,9 @@ post-extract:
 
 do-build:
 	cd ${WRKSRC} && ${CC} ${CFLAGS} ${PORTNAME}.c -o ${PORTNAME} \
-		`pkg-config --cflags --libs xv`
+		`pkg-config --cflags --libs xv` -lX11
 	cd ${WRKSRC} && ${CC} ${CFLAGS} g${PORTNAME}.c -o g${PORTNAME} \
-		`pkg-config --cflags --libs ${GTK_PC} xv`
+		`pkg-config --cflags --libs ${GTK_PC} xv` -lX11
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/${PORTNAME} ${PREFIX}/bin
