--- Makefile.orig	2016-05-30 14:17:29 UTC
+++ Makefile
@@ -21,12 +21,11 @@ RUN_DEPENDS=	llvm-config38:devel/llvm38
 
 GNU_CONFIGURE=	yes
 CONFIGURE_FLAGS=	--with-llvm=${LOCALBASE}
-CONFIGURE_ENV=	LLVM_CONFIG=${LOCALBASE}/bin/llvm-config38 \
-		CC=${LOCALBASE}/bin/clang38 \
-		CXX=${LOCALBASE}/bin/clang++38 \
-		CPP=${LOCALBASE}/bin/clang-cpp38
 
-USES=	autoreconf gmake libtool perl5
+USES=	gmake perl5
+
+dfly-patch:
+	${REINPLACE_CMD} 's,llvm-config,llvm-config38,g' ${WRKSRC}/configure
 
 .include <bsd.port.pre.mk>
 
