--- Makefile.orig	2013-03-09 22:49:22.426621000 +0100
+++ Makefile
@@ -50,8 +50,6 @@
 
 .include "${.CURDIR}/../../www/firefox/Makefile.options"
 
-OPTIONS_DEFAULT:=${OPTIONS_DEFAULT:S/OSS/ALSA/}
-
 .include <bsd.port.pre.mk>
 
 WRKSRC:=	${WRKDIR}/mozilla-esr17
