--- Makefile.orig	2013-11-05 20:38:31.411888000 +0000
+++ Makefile
@@ -52,12 +52,10 @@ MOZ_OPTIONS=	--program-transform-name='s
 
 WRKSRC:=	${WRKDIR}/mozilla-esr24
 
-post-extract:
+post-patch:
 	@${SED} -e 's|@FIREFOX_ICON@|${FIREFOX_ICON}|' -e 's|@MOZILLA@|${MOZILLA}|' \
 		-e 's|@MOZILLA_NAME@|${MOZILLA_NAME}|' \
 		<${FILESDIR}/firefox.desktop.in >${WRKDIR}/${MOZILLA}.desktop
-
-post-patch:
 	@${REINPLACE_CMD} -e '/MOZPNG/s/=[0-9]*/=10511/' \
 		${WRKSRC}/configure.in
 	@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|g' \
