--- Makefile.orig	2014-03-14 23:07:53.927338000 +0000
+++ Makefile
@@ -13,14 +13,22 @@ LICENSE=	GPLv2
 
 GNU_CONFIGURE=	yes
 
-CPPFLAGS+=	-I${LOCALBASE}/include
-LDFLAGS+=	-L${LOCALBASE}/lib -lusb
+USES=		usb
 
 PLIST_FILES=	bin/dfu-programmer man/man1/dfu-programmer.1.gz
 PORTDOCS=	*
 
 OPTIONS_DEFINE=	DOCS
 
+.include <bsd.port.pre.mk>
+
+.if defined(DF_NEW_USB)
+CPPFLAGS+=	-I${LOCALBASE}/include
+LDFLAGS+=	-L${LOCALBASE}/lib -lusb
+.else
+CONFIGURE_ARGS+= --disable-libusb_1_0
+.endif
+
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/src/${PORTNAME} ${STAGEDIR}${PREFIX}/bin
 	${INSTALL_MAN} ${WRKSRC}/docs/${PORTNAME}.1 \
@@ -28,4 +36,4 @@ do-install:
 	${MKDIR} ${STAGEDIR}${DOCSDIR}
 	${INSTALL_DATA} ${WRKSRC}/README ${STAGEDIR}${DOCSDIR}
 
-.include <bsd.port.mk>
+.include <bsd.port.post.mk>
