--- Makefile.orig	2014-03-31 09:20:56.220900000 +0000
+++ Makefile
@@ -176,9 +176,8 @@ WITH_ED=	vi
 .endif
 
 vaster=		STA${PORTVERSION:R:R}
-INST_DAT=	LICENSE.TERMS astest cata_ele.pickled catalo catapy	\
-		elements materiau
-INST_PY=	bibpyt commande
+INST_DAT=	LICENSE.TERMS astest catalo catapy materiau
+INST_PY=	bibpyt
 INST_SH=	as_run parallel_cp
 DAT2FIX=	astout.export config.txt forma01a.export
 inst_dir=	${PREFIX}/${PORTNAME}/${vaster}
@@ -322,6 +321,9 @@ pre-configure:
 	${PYTHON_CMD} ${PYTHON_LIBDIR}/compileall.py ${WRKSRC}
 	@${PYTHON_CMD} -O ${PYTHON_LIBDIR}/compileall.py ${WRKSRC}
 
+post-patch:
+	${REINPLACE_CMD} -e 's|/usr/ports/french/aster/work|${WRKDIR}|g' ${WRKSRC}/products.py
+
 do-configure:
 	(cd ${CONFIGURE_WRKSRC} && ${PYTHON_CMD} setup.pyo ${DEBUG_FLAGS} test	\
 		| tee ${CONFIGURE_LOG})
@@ -353,8 +355,6 @@ do-build:
 
 do-install:
 	${MKDIR} ${tools_dir} ${inst_dir} ${PREFIX}/${PORTNAME}/bin
-	${INSTALL_PROGRAM} ${WRKSRC}/instdir/${vaster}/asteru ${inst_dir}
-	#${INSTALL_SCRIPT} ${WRKSRC}/instdir/${vaster}/asterd ${inst_dir} # Don't strip!
 	${INSTALL_SCRIPT} ${WRKSRC}/instdir/${vaster}/profile.sh ${inst_dir}
 	${ECHO_CMD} "" >> ${inst_dir}/profile.sh
 	${ECHO_CMD} "HDF5_DISABLE_VERSION_CHECK=1" >> ${inst_dir}/profile.sh
