--- Makefile.orig	2016-04-06 16:46:09 UTC
+++ Makefile
@@ -24,13 +24,10 @@ RUN_DEPENDS=	aclock>0:x11-clocks/aclock
 		cartotheque>0:deskutils/cartotheque \
 		cddb-bundle>0:audio/cddb-bundle \
 		gnustep-cdplayer>0:audio/gnustep-cdplayer \
-		cenon>0:graphics/cenon \
-		displaycalibrator>0:deskutils/displaycalibrator \
 		duncan>0:textproc/duncan \
 		easydiff>0:textproc/easydiff \
 		edenmath>0:math/edenmath \
 		expense>0:finance/expense \
-		fortunate>0:games/fortunate \
 		fortytwo-bdb>0:databases/fortytwo-bdb \
 		fortytwo-encore>0:devel/fortytwo-encore \
 		fortytwo>0:graphics/fortytwo \
@@ -66,7 +63,6 @@ RUN_DEPENDS=	aclock>0:x11-clocks/aclock
 		lusernet>0:news/lusernet \
 		mpdcon>0:audio/mpdcon \
 		nextgo>0:games/nextgo \
-		gnustep-notebook>0:deskutils/gnustep-notebook \
 		paje>0:science/paje \
 		pantomime>0:mail/pantomime \
 		pixen>0:graphics/pixen \
