--- Makefile.orig	2017-08-26 20:55:43 UTC
+++ Makefile
@@ -24,12 +24,10 @@ RUN_DEPENDS=	aclock>0:x11-clocks/aclock
 		cartotheque>0:deskutils/cartotheque \
 		cddb-bundle>0:audio/cddb-bundle \
 		gnustep-cdplayer>0:audio/gnustep-cdplayer \
-		cenon>0:graphics/cenon \
 		duncan>0:textproc/duncan \
 		easydiff>0:textproc/easydiff \
 		edenmath>0:math/edenmath \
 		expense>0:finance/expense \
-		fortunate>0:games/fortunate \
 		fortytwo-bdb>0:databases/fortytwo-bdb \
 		fortytwo-encore>0:devel/fortytwo-encore \
 		fortytwo>0:graphics/fortytwo \
@@ -39,8 +37,6 @@ RUN_DEPENDS=	aclock>0:x11-clocks/aclock
 		gnumail>0:mail/gnumail \
 		gnustep-ftp>0:ftp/gnustep-ftp \
 		gnustep-ladder>0:games/gnustep-ladder \
-		gnustep-slideshowkit>0:graphics/gnustep-slideshowkit \
-		gnustep-slideshow>0:graphics/gnustep-slideshow \
 		gnustep-sudoku>0:games/gnustep-sudoku \
 		gnustep-wrapper>0:deskutils/gnustep-wrapper \
 		gorm>0:devel/gorm \
