
USES+=	localbase:ldflags

OPTIONS_DEFAULT:=	${OPTIONS_DEFAULT:NLLVM}

GCC_BUILD_DEPENDS:=	gmp>0:math/gmp
GCC_RUN_DEPENDS:=	gmp>0:math/gmp
GCC_MAKE_ARGS:=		GCC=gcc GXX=g++
GCC_CFLAGS:=		-I/usr/lib/gcc80/plugin
