--- Makefile.orig	2013-03-29 22:43:58.000000000 +0000
+++ Makefile
@@ -12,6 +12,7 @@ LICENSE=	BSD
 CABAL_SETUP=	Setup.hs
 
 USE_CABAL=	network
+USE_CABAL+=	conduit>=0.4.1
 
 .include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
 .include <bsd.port.mk>
