--- Makefile.orig	2013-12-17 16:00:05.512261000 +0000
+++ Makefile
@@ -26,6 +26,19 @@ USE_XORG=	glproto \
 .include <bsd.port.options.mk>
 
 .if defined(WITH_NEW_XORG)
+.  if ${DFLYVERSION} < 300751
+INTEL_VERSION=	2.21.9
+INTEL_REVISION=	0
+CONFIGURE_ARGS+=	--enable-sna --with-default-accel=sna
+MAKE_JOBS_UNSAFE=yes
+PLIST_SUB+=	OLD="@comment "
+EXTRA_PATCHES+= ${DFLY_PATCHDIR}/extra-src_sna_compiler.h \
+		${DFLY_PATCHDIR}/extra-src__sna__sna_threads.c \
+		${DFLY_PATCHDIR}/extra-src_sna_kgem.c \
+		${DFLY_PATCHDIR}/extra-clang \
+		${DFLY_PATCHDIR}/extra-i915kms
+LIB_DEPENDS+=	xcb-util:${PORTSDIR}/x11/xcb-util
+.  else
 INTEL_VERSION=	2.21.15
 INTEL_REVISION=	1
 CONFIGURE_ENV+=	xorg_cv_cc_flag__Wno_maybe_uninitialized=no
@@ -37,6 +50,7 @@ EXTRA_PATCHES+=	${PATCHDIR}/extra-src__s
 		${PATCHDIR}/extra-clang \
 		${PATCHDIR}/extra-i915kms
 LIB_DEPENDS+=	libxcb-util.so:${PORTSDIR}/x11/xcb-util
+.  endif
 .else
 INTEL_VERSION=	2.7.1
 INTEL_REVISION=	6
