--- Makefile.orig	2014-09-13 06:38:46 UTC
+++ Makefile
@@ -26,17 +26,33 @@ USE_XORG=	glproto \
 .include <bsd.port.options.mk>
 
 .if defined(WITH_NEW_XORG)
+.  if ${DFLYVERSION} < 300702
+INTEL_VERSION=	2.21.9
+INTEL_REVISION=	4
+CONFIGURE_ARGS+=	--enable-sna --with-default-accel=sna
+MAKE_JOBS_UNSAFE=yes
+PLIST_SUB+=	OLD="@comment "
+EXTRA_PATCHES+= ${DFLY_PATCHDIR}/extra-src_sna_compiler.h \
+		${DFLY_PATCHDIR}/extra-src__sna__sna_threads.c \
+		${DFLY_PATCHDIR}/extra-src_sna_kgem.c \
+		${DFLY_PATCHDIR}/extra-clang \
+		${DFLY_PATCHDIR}/extra-i915kms
+LIB_DEPENDS+=	xcb-util:${PORTSDIR}/x11/xcb-util
+.  else
 INTEL_VERSION=	2.21.15
 INTEL_REVISION=	4
 CONFIGURE_ENV+=	xorg_cv_cc_flag__Wno_maybe_uninitialized=no
 CONFIGURE_ARGS+=	--enable-sna
+CONFIGURE_ARGS+=	--with-default-accel=sna
 CONFIGURE_ARGS+=	--disable-glamor
 PLIST_SUB+=	OLD="@comment "
 EXTRA_PATCHES+=	${PATCHDIR}/extra-src__sna__sna_threads.c \
 		${PATCHDIR}/extra-src_sna_kgem.c \
 		${PATCHDIR}/extra-clang \
+		${DFLY_PATCHDIR}/extra-src_sna_sna__display.c \
 		${PATCHDIR}/extra-i915kms
 LIB_DEPENDS+=	libxcb-util.so:${PORTSDIR}/x11/xcb-util
+.  endif
 .else
 INTEL_VERSION=	2.7.1
 INTEL_REVISION=	9
