--- Makefile.orig	2013-10-13 18:45:05.248414000 +0000
+++ Makefile
@@ -61,13 +61,6 @@ CONFIGURE_ARGS+=	--disable-asm
 CONFIGURE_ARGS+=	--enable-debug
 .endif
 
-# Around the time GCC stack protection (aka Propolice) for userland
-# was enabled on src/share/mk/bsd.sys.mk
-# SVN rev 180012 on 2008-06-25 21:33:28Z by ru
-.if ${OSVERSION} >= 800040
-LDFLAGS+=	-fstack-protector
-.endif
-
 .if ${PORT_OPTIONS:MPGO}
 # y4m sample video
 Y4M_VIDEO=example.y4m
