--- Makefile.orig	2022-08-26 11:52:31 UTC
+++ Makefile
@@ -147,8 +147,6 @@ LIB_DEPENDS+=			libinotify.so:devel/libi
 # GNUTLS
 LIB_DEPENDS+=			libgnutls.so:security/gnutls
 LIB_DEPENDS+=			libgcrypt.so:security/libgcrypt
-# NFSv4 ACL glue
-LIB_DEPENDS+=			libsunacl.so:sysutils/libsunacl
 # Jansson
 BUILD_DEPENDS+=			jansson>=2.10:devel/jansson
 RUN_DEPENDS+=			jansson>=2.10:devel/jansson
@@ -263,7 +261,7 @@ CONFIGURE_ARGS+=		\
 				--with-pam \
 				--with-iconv \
 				--with-winbind \
-				--with-regedit \
+				--without-regedit \
 				--disable-rpath \
 				--without-lttng \
 				--without-gettext \
@@ -271,7 +269,7 @@ CONFIGURE_ARGS+=		\
 				--without-fake-kaserver \
 				--without-systemd \
 				--with-libarchive \
-				--with-acl-support \
+				--without-acl-support \
 				--with-sendfile-support \
 				--disable-ctdb-tests
 #				${ICONV_CONFIGURE_BASE}
@@ -411,7 +409,7 @@ SAMBA4_MODULES+=		idmap_ad idmap_rfc2307
 .if ${PORT_OPTIONS:MDEVELOPER}
 SAMBA4_MODULES+=		auth_skel pdb_test gpext_security gpext_registry gpext_scripts perfcount_test \
 				vfs_fake_dfq vfs_skel_opaque vfs_skel_transparent vfs_shadow_copy_test vfs_fake_acls \
-				vfs_nfs4acl_xattr vfs_error_inject vfs_delay_inject
+				vfs_error_inject vfs_delay_inject
 .endif
 # Python bindings
 .if defined(NO_PYTHON)
@@ -546,10 +544,54 @@ SUB_FILES=			pkg-message README.FreeBSD
 
 PORTDOCS=			README.FreeBSD
 
+# XXX(tuxillo): WARNING!!!! This is a hack just to get this port to compile.
+#
+#  Basically, these patches have been brought blindly without further testing.
+#  Most commits belong to fixes for CVE-2020-25719 and CVE-2020-25718 plus
+#  the commit which adds support for krb5 1.20: f1ca16f309a1
+#
+BACKPORTS=	${DFLY_PATCHDIR}/extra-7655a0298e5f55582bf48ec776d8cd8b79fb5dd9.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-7149eeaceb426470b1b8181749d2d081c2fb83a4.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-02fa69c6c73c01d82807be4370e838f3e7c66f35.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-031a8287642e3c4b9d0b7c6b51f3b1d79b227542.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-2f9245f2a549bd89829d7807ec525c54ff61f8e5.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-4796b0a5c1d3948642d17eef9f72d364f0e29de3.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-cdb5690be40f6f6c5e5809783c4a364785f85a6e.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-edd3d61feabf2530c9dc2caff98bfbb5f0a2bd1a.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-8ee6753a6ea782050b5b722ce1ac63a275a94f7c.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-601403504325f2f0e241da0a4eb3e390e73f3c08.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-16f96dbb5d4b2262c5ba85fb32a479f0cb66ed23.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-c70710a0483e500f03e59df4dd759e6033975c15.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-a831ef74c5b2982c108cc16dae9b116e9658dcb8.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-19719003af110c6ed664970cddb353d60805ba91.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-a9ac1f919127cf91a08dd3c20bbeda27af980aef.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-87a769fc0a9cdc75f2f79f5cc8072efa95ff4437.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-01df6559ee6ba86110878da094a3badb50fb75d5.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-ff2f38fae79220e16765e17671972f9a55eb7cce.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-aa2e583fdea4fd93e4e71c54630e32a1035d1e2a.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-558f440f2060934d39bd1b6297e554f47fc44e8c.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-6ec80380dc9372a896f74e95738b01c046411429.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-f4ed37ad6aa0359f4799188d2b1d30571c6b42a6.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-41d906301b8d13f831b155dcec37d88889b9f36c.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-104fc3539090ae9e161945ef9d18d897e3b71fed.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-9b9fd2a0d9ca81aa16ddfe2f7e219b94e2ac158b.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-d14a6a8846493438dca2f974a3a5d5e00a414d72.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-b176ddba2a2e3ec9e74e0b6b40b12d1a1139bdf5.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-80257fa37c49138fb1af0a910a3ea41954096c11.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-43983170fc8671f7c0f0a0a6e1f8a82d9dbc2b60.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-1d3548aeffa2ec136f7cdece112a127241d8be13.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-90febd2a33b88af49af595fe0e995d6ba0f33a1b.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-435719185c3c80539eb3041becf1ec18bcd99bac.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-e95fb04c5dec9f0487010fb59b6ebf99effe873f.patch
+BACKPORTS+=	${DFLY_PATCHDIR}/extra-f1ca16f309a1794f7ce44c4112d3c0d458169158.patch
+
 post-extract:
 				@${RM} -r ${WRKSRC}/pidl/lib/Parse/Yapp
 
 post-patch:
+.for P in ${BACKPORTS}
+				cd ${WRKSRC} && ${GPATCH} -p1 < ${P}
+.endfor
 				@${REINPLACE_CMD} -e 's|$${PKGCONFIGDIR}|${PKGCONFIGDIR}|g' \
 					${PATCH_WRKSRC}/buildtools/wafsamba/pkgconfig.py
 				@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|g' \
