--- Makefile.orig	2013-07-24 06:01:03.000000000 +0000
+++ Makefile
@@ -12,8 +12,6 @@ COMMENT=	Qt/C++ wrapper for ZIP/UNZIP pa
 
 LICENSE=	LGPL21
 
-BROKEN=		Does not build
-
 QMAKE_ARGS=	PREFIX=${PREFIX} ${QMAKE_PRO}
 QMAKE_PRO=	${WRKSRC}/${PORTNAME}.pro
 
