--- Makefile.orig	2013-01-26 11:08:52.500878000 +0100
+++ Makefile	2013-01-26 11:09:08.460901000 +0100
@@ -6,6 +6,7 @@
 #
 
 CATEGORIES=	korean print linux
+PKGNAMEPREFIX=	ko-
 
 MASTERDIR=	${.CURDIR}/../../print/acroread8
 DISTINFO_FILE=	${.CURDIR}/distinfo
