--- Makefile.orig	2015-03-06 11:03:00 UTC
+++ Makefile
@@ -43,7 +43,7 @@ CONFIGURE_ARGS+=	--enable-search-domains
 
 post-install:
 .for INSTALLED_MODULE in ${INSTALLED_MODULES}
-	${LN} -s ${INSTALLED_MODULE}.so.1 ${STAGEDIR}${PREFIX}/lib/${INSTALLED_MODULE}.so
+	${LN} -s lib${INSTALLED_MODULE}.so.2 ${STAGEDIR}${PREFIX}/lib/${INSTALLED_MODULE}.so
 .endfor
 .if ${PORT_OPTIONS:MDOCS}
 	${MKDIR} ${STAGEDIR}${DOCSDIR}/
@@ -53,7 +53,14 @@ post-install:
 
 # TODO: Print a message about the etc directory used for mdns.allow
 # being relative to ${PREFIX}.
-PLIST_FILES=	${INSTALLED_MODULES:C/^/lib\//:C/$/.so/} ${INSTALLED_MODULES:C/^/lib\//:C/$/.so.1/}
+PLIST_FILES=	lib/libnss_mdns.so.2 \
+		lib/libnss_mdns4.so.2 \
+		lib/libnss_mdns6.so.2 \
+		lib/libnss_mdns_minimal.so.2 \
+		lib/libnss_mdns4_minimal.so.2 \
+		lib/libnss_mdns6_minimal.so.2 \
+		lib/nss_mdns.so \
+		lib/nss_mdns_minimal.so
 PORTDOCS=	README README.html
 
 .include <bsd.port.mk>
