--- Makefile.orig	2018-06-05 00:05:45 UTC
+++ Makefile
@@ -393,9 +393,7 @@ post-install:
 .include <bsd.port.pre.mk>
 
 .if !defined(OCV_CORE)
-.if (${OPSYS} == FreeBSD && ${OSVERSION} < 1200000)
 EXTRA_PATCHES+=			${FILESDIR}/extra-patch-modules_sfm_src_libmv__light_libmv_numeric_numeric.cc
 .endif
-.endif
 
 .include <bsd.port.post.mk>
