--- Makefile.orig	2014-01-10 03:00:18.116656000 +0000
+++ Makefile
@@ -118,11 +118,7 @@ CONFIGURE_ARGS+=	--disable-threads
 .endif
 
 .if ${PORT_OPTIONS:MGSSAPI}
-.if defined(HEIMDAL_HOME)
-LDFLAGS+=		-L${LIBDIR} -lgssapi -lkrb5
-.else
-LDFLAGS+=		-L${LIBDIR} -lgssapi_krb5
-.endif
+LIB_DEPENDS+=	libgssapi_krb5.so:${PORTSDIR}/security/krb5
 .endif
 
 .if ${PORT_OPTIONS:MREPLACE_BASE}
