PORTNAME=	fileobj
PORTVERSION=	0.7.23.1
DISTVERSIONPREFIX=	v
CATEGORIES=	editors

MAINTAINER=	zrj@ef.irc
COMMENT=	Portable hex editor with vi like interface

LICENSE=	BSD2CLAUSE

GH_ACCOUNT=	kusumi
USE_GITHUB=	yes

USES=		python tar:bzip2
#USES+=		ncurses:port # can't use when devel/ncurses is installed
USE_PYTHON=	distutils

.include <bsd.port.mk>
