--- Makefile.orig	2013-03-09 17:34:25.000000000 +0100
+++ Makefile	2013-03-09 17:34:41.000000000 +0100
@@ -31,7 +31,7 @@
 GNU_CONFIGURE=	yes
 CONFIGURE_ARGS=	--with-gd-inc=${LOCALBASE}/include \
 		--with-gd-lib=${LOCALBASE}/lib CFLAGS="-I${LOCALBASE}/include" \
-		LDFLAGS="-L${PREFIX}/lib"
+		LDFLAGS="-lm -L${PREFIX}/lib"
 REINPLACE_ARGS=	-i ""
 
 pre-patch:
