--- Makefile.orig	2021-03-01 14:52:13 UTC
+++ Makefile
@@ -118 +118 @@
-GOLD_BUILD_DEPENDS=	${LOCALBASE}/bin/ld.gold:devel/binutils
+GOLD_BUILD_DEPENDS=	${LOCALBASE}/bin/ld.gold:devel/binutils@native
