--- Makefile.orig	2018-09-05 03:07:11 UTC
+++ Makefile
@@ -26,4 +26,7 @@ pre-build:
 	(cd ${WRKSRC}/lib/ss && compile_et ss_err.et && \
 	${REINPLACE_CMD} -f ${FILESDIR}/fix-ss_err.h.sed ss_err.h)
 
+LIB_DEPENDS+= libcom_err.so:security/krb5
+LDFLAGS+= -L${LOCALBASE}/lib
+
 .include "${MASTERDIR}/Makefile"
