--- Makefile.orig	2012-12-03 13:13:36.000000000 +0000
+++ Makefile
@@ -36,5 +36,5 @@ post-install:
 	@${INSTALL_DATA} ${WRKSRC}/tttxt/module.dsc ${PREFIX}/share/ggz/tttxt.dsc
 
 .include <bsd.port.pre.mk>
-.include "${PORTSDIR}/games/libggz/bsd.ggz.mk"
+.include "../../games/libggz/bsd.ggz.mk"
 .include <bsd.port.post.mk>
