--- Makefile.orig	2012-12-03 14:19:55.000000000 +0100
+++ Makefile	2012-12-10 18:30:12.797478000 +0100
@@ -50,11 +50,11 @@
 UTIL_CLASSPATH!=	${ECHO_CMD} ${UTIL_CLASSPATH_JARS:S,^,${JAVALIBDIR}/,:S,$,.jar,} | ${TR} " " ":"
 
 .if !defined(NOPORTDOCS)
-JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.[4-5] -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1
+JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.[4-5] -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1 ; echo
 .if ${JDK_API} != ""
 MAKE_ARGS+=	-Dj2se.apidocs="${JDK_API}"
 .endif
-JAXEN_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jaxen -maxdepth 1 -name javadoc -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1
+JAXEN_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jaxen -maxdepth 1 -name javadoc -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1 ; echo
 .if ${JAXEN_API} != ""
 MAKE_ARGS+=	-Djaxen.apidocs="${JAXEN_API}"
 .endif
