--- Makefile.orig	2022-01-13 04:21:12 UTC
+++ Makefile
@@ -31,9 +31,6 @@ CONFIGURE_ARGS=	--disable-dependency-tra
 
 INSTALL_TARGET=	install-strip
 CFLAGS_i386=	-march=i486
-# This port has a problem with -pthread,
-# force to use -lthr until it's not fixed.
-LDFLAGS+=	-lthr
 
 CONFLICTS_INSTALL=	clamav
 
