--- Makefile.orig	2020-09-25 21:28:46 UTC
+++ Makefile
@@ -2,7 +2,7 @@
 # $FreeBSD$
 
 PORTNAME=	palp
-PORTVERSION=	2.12
+PORTVERSION=	2.11
 CATEGORIES=	math
 MASTER_SITES=	http://hep.itp.tuwien.ac.at/~kreuzer/CY/palp/
 
