dfly-patch:
	${REINPLACE_CMD} -e 's|__FreeBSD__|__DragonFly__|' \
		${WRKSRC}/swift/lib/Immediate/REPL.cpp \
		${WRKSRC}/swift/stdlib/public/stubs/LibcShims.cpp \
		${WRKSRC}/swift/stdlib/public/stubs/Stubs.cpp \
		${WRKSRC}/swift/stdlib/public/runtime/ProtocolConformance.cpp
	${REINPLACE_CMD} -e 's|isOSFreeBSD|isOSDragonFly|g' \
		${WRKSRC}/swift/lib/ClangImporter/ClangImporter.cpp \
		${WRKSRC}/swift/lib/Basic/LangOptions.cpp \
		${WRKSRC}/swift/lib/Basic/Platform.cpp \
		${WRKSRC}/swift/include/swift/Basic/LangOptions.h
