--- Makefile.orig	Tue Apr  1 22:28:34 2025
+++ Makefile	Tue Apr
@@ -87,7 +87,7 @@ CONFIGURE_ARGS=	--sysconfdir=${PREFIX}/etc/nut \
 		--without-python2 \
 		--with-python3=${PYTHON_CMD} \
 		--without-nut_monitor \
-		--with-ltdl --with-nut-scanner \
+		--with-libltdl --with-nut-scanner \
 		--without-augeas-lenses-dir
 
 GNU_CONFIGURE_MANPREFIX=${PREFIX}/share
