--- Makefile.orig	2024-02-24 12:13:44 UTC
+++ Makefile
@@ -86,7 +86,7 @@ CONFIGURE_ARGS=	--sysconfdir=${PREFIX}/e
 		--without-python2 \
 		--with-python3=${PYTHON_CMD} \
 		--without-nut_monitor \
-		--with-ltdl --with-nut-scanner
+		--with-libltdl --with-nut-scanner
 
 CFLAGS+=	-I${LOCALBASE}/include -L${LOCALBASE}/lib -pthread
 LIB_DEPENDS+=	libltdl.so:devel/libltdl
