--- Makefile.orig	2023-11-17 20:00:28 UTC
+++ Makefile
@@ -82,7 +82,7 @@ CONFIGURE_ARGS=	--sysconfdir=${PREFIX}/e
 		--with-python=${PYTHON_CMD} \
 		--without-python2 \
 		--with-python3=${PYTHON_CMD} \
-		--with-ltdl --with-nut-scanner
+		--with-libltdl --with-nut-scanner
 
 CFLAGS+=	-I${LOCALBASE}/include -L${LOCALBASE}/lib -lpthread
 LIB_DEPENDS+=	libltdl.so:devel/libltdl
