--- Makefile.orig	2015-08-04 07:39:15 UTC
+++ Makefile
@@ -15,7 +15,6 @@ LICENSE_COMB=	multi
 
 USES=	gmake iconv libtool tar:bzip2 makeinfo compiler
 PLIST_SUB=	TARGETARCH=${PKGNAMEPREFIX:C/-//g} \
-		OPSYS=${OPSYS:tl} \
 		GCC_TARGET=${GCC_TARGET} \
 		GCC_VERSION=${PORTVERSION}
 
@@ -30,13 +29,15 @@ WRKSRC=	${WRKDIR}/build-gcc
 
 .if empty(GCC_TARGET)
 # We are building for a FreeBSD target
-GCC_TARGET?=	${PKGNAMEPREFIX}portbld-${OPSYS:tl}${OSREL}
-BU_PREFIX?=	${PKGNAMEPREFIX}${OPSYS:tl}
+GCC_TARGET?=	${PKGNAMEPREFIX}portbld-freebsd10
+BU_PREFIX?=	${PKGNAMEPREFIX}freebsd
 EXTRA_PATCHES+= ${FILESDIR}/freebsd-format-extensions
+PLIST_SUB+=	OPSYS=freebsd OSREL=10
 .else
 BU_PREFIX?=	${GCC_TARGET}
 .if defined(FREEBSD_EXTENSION)
 EXTRA_PATCHES+= ${FILESDIR}/freebsd-format-extensions
+PLIST_SUB+=	OPSYS=${OPSYS:tl} OSREL=${OSREL}
 .endif
 .endif
 
