--- Makefile.orig	2018-02-24 02:56:25 UTC
+++ Makefile
@@ -22,19 +22,20 @@ CONFIGURE_ENV=	gcc_gxx_include_dir="/usr
 
 USES=	gmake iconv libtool tar:bzip2 makeinfo compiler
 PLIST_SUB=	TARGETARCH=${PKGNAMEPREFIX:C/-//g} \
-		OPSYS=${OPSYS:tl} \
 		GCC_TARGET=${GCC_TARGET} \
 		GCC_VERSION=${PORTVERSION}
 
 .if empty(GCC_TARGET)
 # We are building for a FreeBSD target
-GCC_TARGET?=	${PKGNAMEPREFIX}unknown-${OPSYS:tl}${OSREL}
-BU_PREFIX?=	${PKGNAMEPREFIX}unknown-${OPSYS:tl}${OSREL}
+GCC_TARGET?=	${PKGNAMEPREFIX}unknown-freebsd10
+BU_PREFIX?=	${PKGNAMEPREFIX}unknown-freebsd10
 EXTRA_PATCHES+= ${FILESDIR}/freebsd-format-extensions
+PLIST_SUB+=	OPSYS=freebsd OSREL=10
 .else
 BU_PREFIX?=	${GCC_TARGET}
 .if defined(FREEBSD_EXTENSION)
 EXTRA_PATCHES+= ${FILESDIR}/freebsd-format-extensions
+PLIST_SUB+=	OPSYS=${OPSYS:tl} OSREL=${OSREL}
 .endif
 .endif
 
