--- Makefile.orig	2019-02-26 19:14:13 UTC
+++ Makefile
@@ -21,7 +21,6 @@ RUN_DEPENDS=	${BU_PREFIX}-as:devel/${PKG
 
 USES=	gmake iconv libtool tar:xz makeinfo compiler:c++11-lang
 PLIST_SUB=	TARGETARCH=${PKGNAMEPREFIX:C/-//g} \
-		OPSYS=${OPSYS:tl} \
 		GCC_TARGET=${GCC_TARGET} \
 		GCC_VERSION=${PORTVERSION}
 
@@ -29,10 +28,11 @@ TARGETARCH=	${PKGNAMEPREFIX:C/-//g}
 
 .if empty(GCC_TARGET)
 # We are building for a FreeBSD target
-GCC_TARGET=	${PKGNAMEPREFIX:S/amd64/x86_64/}unknown-${OPSYS:tl}${OSREL}
+GCC_TARGET=	${PKGNAMEPREFIX:S/amd64/x86_64/}unknown-freebsd10
 EXTRA_PATCHES+= ${FILESDIR}/freebsd-format-extensions \
 		${FILESDIR}/freebsd-libdir
 .endif
+PLIST_SUB+=	OPSYS=freebsd OSREL=10
 BU_PREFIX?=	${GCC_TARGET}
 
 GNU_CONFIGURE=	yes
