--- Makefile.orig	2024-09-23 08:22:45 UTC
+++ Makefile
@@ -133,6 +133,7 @@ MAKE_ENV+=		--with-toolchain-type=${COMP
 CONFIGURE_ARGS+=	--with-toolchain-type=${COMPILER_TYPE}
 CONFIGURE_ARGS+=	--disable-warnings-as-errors
 
+.if ${OPSYS} == "FreeBSD"
 .if ${COMPILER_TYPE} == gcc
 USE_GCC=	yes
 CONFIGURE_ARGS+=	--with-extra-ldflags="-Wl,-rpath=${LOCALBASE}/lib/gcc${GCC_DEFAULT} -L${LOCALBASE}/lib/gcc${GCC_DEFAULT}" \
@@ -154,6 +155,7 @@ ICONV_CFLAGS=	-I${LOCALBASE}/include
 ICONV_LDFLAGS=	-L${LOCALBASE}/lib
 ICONV_LIBS=	${ICONV_LIB}
 .endif
+.endif
 
 post-patch:
 	@${FIND} ${WRKSRC} -name '*.orig' -delete
@@ -174,6 +176,9 @@ post-build:
 
 do-install:
 	@${MKDIR} ${STAGEDIR}${INSTALLDIR}
+.if !defined(BUILD_JRE)
+	${CP} -rv ${JDK_IMAGEDIR}/include/freebsd ${JDK_IMAGEDIR}/include/dragonfly
+.endif
 	@cd ${JDK_IMAGEDIR} && ${COPYTREE_SHARE} . ${STAGEDIR}${INSTALLDIR}
 	@cd ${STAGEDIR}${INSTALLDIR} && \
 		${FIND} bin -type f -exec ${CHMOD} ${BINMODE} {} \;
