--- Makefile.orig	2016-04-06 16:29:17 UTC
+++ Makefile
@@ -80,8 +80,6 @@ LIB_DEPENDS+=		libsasl2.so:security/cyru
 # GNUTLS
 LIB_DEPENDS+=		libgcrypt.so:security/libgcrypt
 LIB_DEPENDS+=		libgnutls.so:security/gnutls
-# NFS4 ACL glue
-LIB_DEPENDS+=		libsunacl.so:sysutils/libsunacl
 # Libarchive
 BUILD_DEPENDS+=		libarchive>=3.1.2:archivers/libarchive
 RUN_DEPENDS+=		libarchive>=3.1.2:archivers/libarchive
@@ -116,7 +114,7 @@ OPTIONS_DEFINE=		ACL_SUPPORT AD_DC ADS A
 			DNSUPDATE DOCS FAM LDAP PAM_SMBPASS \
 			PTHREADPOOL QUOTAS SYSLOG UTMP
 
-OPTIONS_DEFAULT:=	ACL_SUPPORT AD_DC ADS AIO_SUPPORT DEBUG \
+OPTIONS_DEFAULT:=	AD_DC ADS AIO_SUPPORT DEBUG \
 			DNSUPDATE DOCS FAM LDAP \
 			PTHREADPOOL QUOTAS SYSLOG UTMP
 
@@ -150,6 +148,7 @@ NSUPDATE_DESC=		Use samba NSUPDATE utili
 .include <bsd.port.options.mk>
 
 CONFIGURE_ARGS+=	\
+			--without-regedit \
 			--with-pam \
 			--with-iconv \
 			--with-winbind \
