--- Makefile.orig	2016-11-03 02:50:10 UTC
+++ Makefile
@@ -77,8 +77,6 @@ LIB_DEPENDS+=		libpopt.so:devel/popt
 LIB_DEPENDS+=		libinotify.so:devel/libinotify
 # GNUTLS
 LIB_DEPENDS+=		libgnutls.so:security/gnutls
-# NFS4 ACL glue
-LIB_DEPENDS+=		libsunacl.so:sysutils/libsunacl
 # Libarchive
 BUILD_DEPENDS+=		libarchive>=3.1.2:archivers/libarchive
 RUN_DEPENDS+=		libarchive>=3.1.2:archivers/libarchive
@@ -117,7 +115,7 @@ OPTIONS_DEFINE=		ACL_SUPPORT AD_DC ADS A
 			DNSUPDATE DOCS FAM LDAP PAM_SMBPASS \
 			PTHREADPOOL QUOTAS SYSLOG UTMP
 
-OPTIONS_DEFAULT:=	ACL_SUPPORT AD_DC ADS AIO_SUPPORT DEBUG \
+OPTIONS_DEFAULT:=	AD_DC ADS AIO_SUPPORT DEBUG \
 			DNSUPDATE DOCS FAM LDAP \
 			PTHREADPOOL QUOTAS SYSLOG UTMP
 
@@ -150,6 +148,7 @@ NSUPDATE_DESC=		Use samba NSUPDATE utili
 .include <bsd.port.options.mk>
 
 CONFIGURE_ARGS+=	\
+			--without-regedit \
 			--with-pam \
 			--with-iconv \
 			--with-winbind \
