--- Makefile.orig	2012-12-22 09:08:25.202928000 +0100
+++ Makefile	2012-12-22 09:10:46.246214000 +0100
@@ -31,7 +31,7 @@
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} != "amd64" || ${ARCH} != "i386"
+.if !(${ARCH} == "amd64" || ${ARCH} == "i386" || ${ARCH} == "x86_64")
 CONFIGURE_ARGS+=--disable-gallium-intel
 .endif
 
