--- Makefile.orig	2015-10-18 13:35:02 +0200
+++ Makefile
@@ -15,6 +15,9 @@
 USE_XORG=	glproto x11 xext xxf86vm xdamage xfixes dri2proto:both \
 		presentproto xshmfence
 
+OPTIONS_DEFINE=		WAYLAND
+OPTIONS_DEFAULT=	WAYLAND
+
 .include <bsd.port.options.mk>
 .include "${.CURDIR}/Makefile.common"
 
