--- Makefile.orig	2017-08-04 03:13:15 UTC
+++ Makefile
@@ -49,4 +49,7 @@ post-install:
 	@${LN} -s libmysqlclient.so ${STAGEDIR}${PREFIX}/lib/mysql/libmysqlclient_r.so
 	@${LN} -s libmysqlclient.so.20 ${STAGEDIR}${PREFIX}/lib/mysql/libmysqlclient_r.so.20
 
+dfly-patch:
+	${REINPLACE_CMD} -e 's/FreeBSD/DragonFly/' ${WRKSRC}/cmake/plugin.cmake
+
 .include "${MASTERDIR}/Makefile"
