--- Makefile.orig	2021-05-09 13:23:25 UTC
+++ Makefile
@@ -217,11 +217,7 @@ CONFLICTS=	ucd-snmp-4.* net-snmp-5.3.*
 
 .include <bsd.port.pre.mk>
 
-.if ${SSL_DEFAULT} != base
-LCRYPTO=	-lcrypto
-.else
-LCRYPTO=
-.endif
+LCRYPTO=	-lcrypto -lssl -lwrap
 
 pre-everything::
 	@${ECHO_MSG}
