--- Makefile.orig	2016-06-21 05:50:05 UTC
+++ Makefile
@@ -155,7 +155,7 @@ NET_SNMP_SYS_CONTACT?=	nobody@nowhere.in
 NET_SNMP_SYS_LOCATION?=	somewhere
 NET_SNMP_LOGFILE?=	/var/log/snmpd.log
 NET_SNMP_PERSISTENTDIR?=/var/net-snmp
-NET_SNMP_WITH_MIB_MODULE_LIST+=	host disman/event-mib mibII/mta_sendmail mibII/tcpTable ucd-snmp/diskio sctp-mib
+NET_SNMP_WITH_MIB_MODULE_LIST+=	host disman/event-mib mibII/mta_sendmail mibII/tcpTable ucd-snmp/diskio
 
 .if ${OSVERSION} >= 1000000 && ${OSVERSION} < 1100062
 CFLAGS+=	-D_WANT_IFADDR
@@ -215,11 +215,7 @@ CONFLICTS=	ucd-snmp-4.* net-snmp-5.3.*
 
 .include <bsd.port.pre.mk>
 
-.if ${SSL_DEFAULT} != base
-LCRYPTO=	-lcrypto
-.else
-LCRYPTO=
-.endif
+LCRYPTO=	-lcrypto -lssl -lwrap
 
 pre-everything::
 	@${ECHO_MSG}
