--- Makefile.orig	2017-07-17 19:56:10 UTC
+++ Makefile
@@ -93,11 +93,6 @@ CONFIGURE_ARGS+=	--disable-dtrace
 .endif
 .endif
 
-# keep in sync with all platforms where libunwind is available
-.if (${ARCH} == amd64 || ${ARCH} == i386)
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
-
 .if ${ARCH} == "powerpc64"
 USE_GCC=	yes
 .endif
