--- Makefile.orig	2013-12-09 00:53:05.761868000 +0000
+++ Makefile
@@ -21,6 +21,7 @@ MAKE_JOBS_UNSAFE=	yes
 
 NO_STAGE=	yes
 post-patch:
+		@${REINPLACE_CMD} 's|make|$$(MAKE)|g' ${WRKSRC}/Makefile
 #respect CFLAGS
 .		for f in IMlib Lib Programs
 		    @${REINPLACE_CMD} 's|CFLAGS =|CFLAGS+=|g' ${WRKSRC}/MGridGen/${f}/Makefile
