--- Makefile.orig	2020-06-16 22:00:22 UTC
+++ Makefile
@@ -22,20 +22,21 @@ VERSION!=	uname -r
 .endif
 VERSION_ID=	${VERSION:C/^([0-9\.]+).*/\1/}
 
-CONTENTS=	'NAME=FreeBSD\0'$\
+CONTENTS=	'NAME=DragonFly\0'$\
 		'VERSION=${VERSION}\0'$\
 		'VERSION_ID=${VERSION_ID}\0'$\
-		'ID=freebsd\0'$\
-		'ANSI_COLOR="0;31"\0'$\
-		'PRETTY_NAME="FreeBSD ${VERSION}"\0'$\
-		'CPE_NAME=cpe:/o:freebsd:freebsd:${VERSION_ID}\0'$\
-		'HOME_URL=https://freebsd.org/\0'$\
-		'BUG_REPORT_URL=https://bugs.freebsd.org'
+		'ID=dragonfly\0'$\
+		'ANSI_COLOR="0;32"\0'$\
+		'PRETTY_NAME="DragonFly BSD ${VERSION}"\0'$\
+		'CPE_NAME=cpe:/o:dragonflybsd:dragonfly:${VERSION_ID}\0'$\
+		'SUPPORT_URL=http://chat.efnet.org:9090/?nick=dflynick&channels=%23dragonflybsd&Login=Login\0'$\
+		'HOME_URL=https://www.dragonflybsd.org/\0'$\
+		'BUG_REPORT_URL=https://bugs.dragonflybsd.org/'
 
 .include <bsd.port.pre.mk>
 # FreeBSD base gained /etc/os-release in r354922, which
 # corresponds to __FreeBSD_version 1300060
-.if ${OSVERSION} >= 1300060
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1300060
 IGNORE=		/etc/os-release is present in base
 .endif
 
