--- Makefile.orig	2019-05-01 15:14:51 UTC
+++ Makefile
@@ -15,18 +15,19 @@ NO_BUILD=	yes
 
 PLIST_FILES=	etc/os-release
 
-VERSION!=	freebsd-version -u
+VERSION!=	uname -r
 VERSION_ID=	${VERSION:C/^([0-9\.]+).*/\1/}
 
-CONTENTS=	'NAME=FreeBSD\0'$\
+CONTENTS=	'NAME=DragonFly\0'$\
 		'VERSION=${VERSION}\0'$\
 		'VERSION_ID=${VERSION_ID}\0'$\
-		'ID=freebsd\0'$\
-		'ANSI_COLOR="0;31"\0'$\
-		'PRETTY_NAME="FreeBSD ${VERSION}"\0'$\
-		'CPE_NAME=cpe:/o:freebsd:freebsd:${VERSION_ID}\0'$\
-		'HOME_URL=https://freebsd.org/\0'$\
-		'BUG_REPORT_URL=https://bugs.freebsd.org'
+		'ID=dragonfly\0'$\
+		'ANSI_COLOR="0;32"\0'$\
+		'PRETTY_NAME="DragonFly ${VERSION}"\0'$\
+		'CPE_NAME=cpe:/o:dragonflybsd:dragonfly:${VERSION_ID}\0'$\
+		'SUPPORT_URL=http://chat.efnet.org:9090/?nick=dflynick&channels=%23dragonflybsd&Login=Login\0'$\
+		'HOME_URL=https://www.dragonflybsd.org/\0'$\
+		'BUG_REPORT_URL=https://bugs.dragonflybsd.org/'
 
 do-install:
 	${MKDIR} ${STAGEDIR}${PREFIX}/etc
