--- Makefile.orig	2013-12-17 15:37:20.126026000 +0000
+++ Makefile
@@ -22,7 +22,6 @@ CONFIGURE_ARGS=	--disable-dmx --disable-
 SLAVE_PORT=	yes
 PLIST_FILES=	bin/Xnest man/man1/Xnest.1.gz
 
-.include <bsd.port.options.mk>
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/hw/xnest/Xnest ${STAGEDIR}${PREFIX}/bin/
