--- Makefile.orig	2023-02-19 23:45:57 UTC
+++ Makefile
@@ -152,8 +152,6 @@ LIB_DEPENDS+=			libinotify.so:devel/libi
 # GNUTLS
 LIB_DEPENDS+=			libgnutls.so:security/gnutls
 LIB_DEPENDS+=			libgcrypt.so:security/libgcrypt
-# NFSv4 ACL glue
-LIB_DEPENDS+=			libsunacl.so:sysutils/libsunacl
 # Jansson
 BUILD_DEPENDS+=			jansson>=2.10:devel/jansson
 RUN_DEPENDS+=			jansson>=2.10:devel/jansson
@@ -268,7 +266,7 @@ CONFIGURE_ARGS+=		\
 				--with-pam \
 				--with-iconv \
 				--with-winbind \
-				--with-regedit \
+				--without-regedit \
 				--disable-rpath \
 				--without-lttng \
 				--without-gettext \
@@ -276,7 +274,7 @@ CONFIGURE_ARGS+=		\
 				--without-fake-kaserver \
 				--without-systemd \
 				--with-libarchive \
-				--with-acl-support \
+				--without-acl-support \
 				--with-sendfile-support \
 				--disable-ctdb-tests
 #				${ICONV_CONFIGURE_BASE}
@@ -414,7 +412,7 @@ SAMBA4_MODULES+=		idmap_ad idmap_rfc2307
 # This kind of special for this distribution
 SAMBA4_MODULES+=		vfs_freebsd
 
-SAMBA4_MODULES+=		vfs_acl_tdb vfs_acl_xattr vfs_aio_fork vfs_aio_pthread \
+SAMBA4_MODULES+=		vfs_acl_tdb vfs_aio_fork vfs_aio_pthread \
 				vfs_audit vfs_cap vfs_catia vfs_commit vfs_crossrename \
 				vfs_default_quota vfs_dirsort vfs_expand_msdfs \
 				vfs_extd_audit vfs_fake_perms vfs_full_audit \
@@ -423,7 +421,7 @@ SAMBA4_MODULES+=		vfs_acl_tdb vfs_acl_xa
 				vfs_shadow_copy vfs_shadow_copy2 vfs_shell_snap \
 				vfs_streams_depot vfs_streams_xattr vfs_syncops \
 				vfs_time_audit vfs_unityed_media vfs_virusfilter \
-				vfs_widelinks vfs_worm vfs_xattr_tdb vfs_zfsacl
+				vfs_widelinks vfs_worm vfs_xattr_tdb
 
 .if ${PORT_OPTIONS:MDEVELOPER}
 SAMBA4_MODULES+=		auth_skel pdb_test gpext_security gpext_registry \
@@ -568,10 +566,14 @@ SUB_FILES=			pkg-message README.FreeBSD
 
 PORTDOCS=			README.FreeBSD
 
+
 post-extract:
 				@${RM} -r ${WRKSRC}/pidl/lib/Parse/Yapp
 
 post-patch:
+.for P in ${BACKPORTS}
+				cd ${WRKSRC} && ${GPATCH} -p1 < ${P}
+.endfor
 				@${REINPLACE_CMD} -e 's|$${PKGCONFIGDIR}|${PKGCONFIGDIR}|g' \
 					${PATCH_WRKSRC}/buildtools/wafsamba/pkgconfig.py
 				@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|g' \
