--- Makefile.orig	2013-05-03 21:58:42.000000000 +0000
+++ Makefile
@@ -4,15 +4,14 @@
 PORTNAME=	cvs
 PORTVERSION=	0.2
 CATEGORIES=	devel ruby
-MASTER_SITES=	http://cvs.m17n.org/viewcvs/ruby/
+MASTER_SITES=	http://leaf.dragonflybsd.org/~marino/dports-src/
 PKGNAMEPREFIX=	${RUBY_PKGNAMEPREFIX}
-DISTNAME=	ruby-${PORTNAME}.tar.gz\?only_with_tag=ruby-${PORTNAME}-${PORTVERSION:S/./_/g}\&view=tar
+DISTNAME=	ruby-${PORTNAME}-${PORTVERSION}
 DIST_SUBDIR=	ruby
 
 MAINTAINER=	glarkin@FreeBSD.org
 COMMENT=	A Ruby library to provide a high level interface to a CVS repository
 
-BROKEN=		Does not fetch
 
 # optional, but strongly suggested
 #RUN_DEPENDS=	${RUBY_SITEARCHLIBDIR}/flex.so:${PORTSDIR}/devel/ruby-flex_rb
