--- Makefile.orig	2016-01-03 10:27:44 UTC
+++ Makefile
@@ -29,7 +29,7 @@ NO_WRKSUBDIR=	yes
 NO_ARCH=	yes
 
 DATADIR=	share/${PKGNAMEPREFIX:S/-//}
-PLIST=		${WRKDIR}/pkg-plist
+PLIST=		${WRKSRC}/pkg-plist
 
 post-extract:
 	@cd ${WRKSRC}/base && \
