--- Makefile.orig	2014-04-23 13:25:16 UTC
+++ Makefile
@@ -3,9 +3,8 @@
 #   $MCom: ports/graphics/cairo/Makefile,v 1.101 2010/10/29 15:40:04 kwm Exp $
 
 PORTNAME=	cairo
-PORTVERSION=	1.10.2
-PORTREVISION=	10
-PORTEPOCH?=	2
+PORTVERSION=	1.12.16
+PORTEPOCH?=	1
 CATEGORIES=	graphics
 MASTER_SITES=	http://cairographics.org/releases/
 
@@ -21,16 +20,17 @@ LIB_DEPENDS=	libfreetype.so:${PORTSDIR}/
 GNU_CONFIGURE=	yes
 CONFIGURE_ARGS=	--with-html-dir=${DOCSDIR} \
 		--disable-directfb \
+		--disable-gallium \
+		--disable-glesv2 \
+		--disable-wgl \
+		--disable-egl \
 		--enable-tee
-USES=		libtool:keepla pathfix pkgconfig
-USE_XORG=	pixman
+USES=		libtool:keepla pathfix pkgconfig tar:xz
+USE_XORG=	pixman xext
 USE_GNOME=	referencehack
 USE_LDCONFIG=	yes
 INSTALL_TARGET=	install-strip
 
-CPPFLAGS+=	${PTHREAD_CFLAGS}
-LDFLAGS+=	${PTHREAD_LIBS}
-
 OPTIONS_DEFINE=	OPENGL XCB GLIB X11
 OPTIONS_DEFAULT=	XCB GLIB X11
 XCB_DESC=	Enable XCB (X C-language Binding) Support
@@ -82,11 +82,16 @@ PLIST_SUB+=	GLIB="@comment "
 post-patch:
 	@${REINPLACE_CMD} -e '/test/s/==/=/g' \
 		-e '/LIBS/s/-lrt//' \
+		-e '/LIBS/s|-ldld||' \
+		-e '/LIBS/s|-ldl||' \
 		${WRKSRC}/configure
 	@${REINPLACE_CMD} -e 's|-lcairo|-lcairo ${PTHREAD_LIBS}|' \
 		${WRKSRC}/src/*.pc.in
 	@${REINPLACE_CMD} -e '/@CAIRO_HAS_PNG_FUNCTIONS_TRUE@.*=/d' \
 		${WRKSRC}/Makefile.in
+	@${REINPLACE_CMD} -e 's|-ldl||g' \
+		${WRKSRC}/util/*/Makefile.in \
+		${WRKSRC}/boilerplate/Makefile.in
 .if ${PORT_OPTIONS:MOPENGL}
 	@${REINPLACE_CMD} 's|@CAIRO_CFLAGS@|-I$$(top_srcdir)/src/glew &|' \
 		${WRKSRC}/src/Makefile.in
