--- Makefile.orig	2013-05-09 23:20:50.645499000 +0000
+++ Makefile
@@ -22,7 +22,7 @@ MAKE_ARGS+=	PLATFORM=bsd PREFIX=${PREFIX
 		DOCDIR="${DOCSDIR}" \
 		C_COMPILER_OPTIMIZATION_OPTIONS="${CFLAGS}"
 
-NEW_ARCH=	${ARCH:S/i386/x86/:S/amd64/x86-64/}
+NEW_ARCH=	${ARCH:S/i386/x86/:S/amd64/x86-64/:S/x86_64/x86-64/}
 
 MAN1=		chicken.1 chicken-bug.1 chicken-install.1 chicken-profile.1 \
 		chicken-status.1 chicken-uninstall.1 csc.1 csi.1
