--- Makefile.orig	2013-03-08 23:13:08.785440000 +0000
+++ Makefile
@@ -34,9 +34,7 @@ PORTDOCS=	README
 
 .include <bsd.port.options.mk>
 
-.if ${ARCH} == "i386"
 RUN_DEPENDS+=	wine:${PORTSDIR}/emulators/wine-devel
-.endif
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|/bin/bash|/bin/sh|' ${WRKSRC}/version.sh
