--- Makefile.orig	2016-04-06 15:54:08 UTC
+++ Makefile
@@ -34,9 +34,7 @@ OPTIONS_DEFINE=	DOCS
 
 .include <bsd.port.options.mk>
 
-.if ${ARCH} == "i386"
 RUN_DEPENDS+=	wine:emulators/wine-devel
-.endif
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|/bin/bash|/bin/sh|' ${WRKSRC}/version.sh
