--- Makefile.orig	2013-11-19 10:01:03.000000000 +0000
+++ Makefile
@@ -48,8 +48,6 @@ EXTRA_PATCHES+=	${FILESDIR}/extra-patch-
 .endif
 
 .if ${PORT_OPTIONS:MMUSIC}
-DEPRECATED=	Depends on expired games/daimonin-music
-EXPIRATION_DATE=2013-12-19
 RUN_DEPENDS+=	${DATADIR}/media/AnichGiantTrouble.ogg:${PORTSDIR}/games/daimonin-music
 .endif
 
