--- Makefile.orig	2014-08-03 08:18:07.339605000 +0000
+++ Makefile
@@ -32,7 +32,7 @@ MAKE_ARGS+=		LIBPC="${PREFIX}/libdata/pk
 
 PLIST_SUB=		ABI=${ABIFLAGS} \
 			PORTVERSION=${PORTVERSION} \
-			OSMAJOR=${OSVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
+			OSMAJOR=${DFLYVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
 
 OPTIONS_DEFINE=		DEBUG IPV6 NLS PYMALLOC SEM THREADS
 OPTIONS_DEFAULT=	IPV6 NLS PYMALLOC SEM THREADS UCS4
