--- Makefile.orig	2023-01-16 22:58:01 UTC
+++ Makefile
@@ -58,7 +58,7 @@ USE_QT=		core gui help network opengl pr
 USE_XORG=	x11 xcursor xext xfixes xft xinerama xrender
 USE_GL=		gl glu
 
-GNU_HOST=	${ARCH}-portbld-freebsd${OSREL}
+GNU_HOST=	${CONFIGURE_TARGET}
 PLIST_SUB=	GNU_HOST=${GNU_HOST} \
 		OCTAVE_VERSION=${OCTAVE_VERSION}
 LDFLAGS+=	-L${LOCALBASE}/lib/qt5
