For xorg 1.17.2
--- Makefile.orig
+++ Makefile
@@ -113,7 +113,7 @@ CONFIGURE_ARGS+=	\
 
 .include <bsd.port.pre.mk>
 
-TIGERVNC_XORG_PATCH_VER=	114
+TIGERVNC_XORG_PATCH_VER=	117
 
 # import from x11-server/xorg-server/Makefile
 .ifdef WITH_OPENSSL_BASE

