--- Makefile.orig	2016-07-17 02:01:43 UTC
+++ Makefile
@@ -37,10 +37,6 @@ USE_LDCONFIG=	yes
 OPTIONS_SUB=	yes
 GUI_INSTALLS_ICONS=	yes
 
-BUILD_DEPENDS+=	clang36:lang/clang36
-RUN_DEPENDS+=	clang36:lang/clang36
-CC=		clang36
-CXX=		clang++36
 
 CMAKE_ARGS+=	-DBOOST_ROOT=${LOCALBASE}
 CMAKE_ARGS+=	-DUSE_PYTHON_3:BOOL=OFF
