--- Makefile	(revision 334713)
+++ Makefile	(working copy)
@@ -135,7 +135,7 @@
 .endif
 
 .if ${PORT_OPTIONS:MREPLACE_BASE}
-.if ${OSVERSION} >= 1000500
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1000500
 IGNORE=		REPLACE_BASE option not supported on this release
 .endif
 PKGNAMESUFFIX=	-base
@@ -142,7 +142,7 @@
 PREFIX=		/usr
 BIND_DESTETC=	/etc/namedb
 .else
-.if ${OSVERSION} >= 1000500
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1000500
 BIND_DESTETC=	${PREFIX}/etc/namedb
 .else
 BIND_DESTETC=	${PREFIX}/etc
@@ -153,7 +153,7 @@
 			--sysconfdir=${BIND_DESTETC}
 PLIST_SUB+=	BIND_DESTETC="${BIND_DESTETC}"
 
-.if ${OSVERSION} >= 1000500
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1000500
 PLIST_SUB+=	NOBASE=""
 .else
 PLIST_SUB+=	NOBASE="@comment "
@@ -221,7 +221,7 @@
 	${CP} ${WRKSRC}/CHANGES ${WRKSRC}/COPYRIGHT ${WRKSRC}/FAQ \
 	    ${WRKSRC}/NSEC3-NOTES ${WRKSRC}/README* ${DOCSDIR}/
 .endif
-.if ${OSVERSION} >= 1000500
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1000500
 .for FILE in named named.conf
 	${SED} -e 's#%%PREFIX%%#${PREFIX}#g' \
 		-e 's#%%BIND_DESTETC%%#${BIND_DESTETC}#g' \
