--- Makefile.orig	2017-07-11 12:41:07 UTC
+++ Makefile
@@ -1,7 +1,7 @@
 # $FreeBSD$
 
 PORTNAME=	apache24
-PORTVERSION=	2.4.26
+PORTVERSION=	2.4.27
 CATEGORIES=	www ipv6
 MASTER_SITES=	APACHE_HTTPD
 DISTNAME=	httpd-${PORTVERSION}
@@ -165,7 +165,7 @@ post-extract:
 .endfor
 
 post-patch:
-	${REINPLACE_CMD} -e 's," PLATFORM ",FreeBSD,' ${WRKSRC}/server/core.c
+	${REINPLACE_CMD} -e 's," PLATFORM ",DragonFly,' ${WRKSRC}/server/core.c
 	${REINPLACE_CMD} -e 's|logs/error_log|/var/log/httpd-error.log|' \
 		${WRKSRC}/include/httpd.h
 	${REINPLACE_CMD} -e 's|perlbin=.*|perlbin=${PERL}|' \
