--- Makefile.orig	2014-12-13 07:25:22 UTC
+++ Makefile
@@ -102,7 +102,7 @@ post-build:
 	# Fix ".so" macro problem by using "soelim" command.
 	${LN} -sf ${WRKSRC}/Doc ${WRKSRC}/man1
 	${MV} ${WRKSRC}/Doc/zshall.1 ${WRKSRC}/Doc/zshall.1.source
-	cd ${WRKSRC} && ${SOELIM} -r ${WRKSRC}/Doc/zshall.1.source > \
+	cd ${WRKSRC} && ${SOELIM} ${WRKSRC}/Doc/zshall.1.source > \
 		${WRKSRC}/Doc/zshall.1
 .if ${PORT_OPTIONS:MDOCS}
 	@${MKDIR} ${STAGEDIR}${PREFIX}/info
