--- Makefile.orig	2014-01-29 08:48:47.326341000 +0000
+++ Makefile
@@ -48,10 +48,11 @@ XML_LDFLAGS=		$$(pkg-config --libs-only-
 XML_CONFIGURE_WITH=	libxml2
 
 .include <bsd.port.options.mk>
-.include <bsd.port.pre.mk>
 
-.if ${OSVERSION} < 1000040
+.if ${OPSYS} == FreeBSD && ${OSVERSION} < 1000040
 CONFIGURE_ENV+=	LIBUSB1_CFLAGS=" " LIBUSB1_LIBS="-lusb"
+.elif ${OPSYS} == DragonFly
+USES+=		usb
 .endif
 
 post-patch:
@@ -72,4 +73,4 @@ post-patch:
 		'/^SUBDIRS/s|linux-hotplug||' \
 		${WRKSRC}/packaging/Makefile.in
 
-.include <bsd.port.post.mk>
+.include <bsd.port.mk>
