--- Makefile.orig	2013-10-26 23:08:01.759853000 +0000
+++ Makefile
@@ -29,8 +29,10 @@ PLIST_SUB=	VERSION="${PORTVERSION}" VERS
 
 .include <bsd.port.options.mk>
 
-.if ${OSVERSION} < 1000040
+.if ${OPSYS} == FreeBSD && ${OSVERSION} < 1000040
 CONFIGURE_ENV+=	LIBUSB1_CFLAGS=" " LIBUSB1_LIBS="-lusb"
+.elif ${OPSYS} == DragonFly
+USES+=		usb
 .endif
 
 .if ${PORT_OPTIONS:MNLS}
