--- Makefile.orig	2013-05-07 19:00:23.399501000 +0000
+++ Makefile
@@ -36,7 +36,11 @@ PLIST_SUB+=	NLS="@comment "
 USES+=		iconv
 .endif
 
+.if ${OPSYS} == DragonFly
+USES+= usb
+.else
 CONFIGURE_ENV+=	LIBUSB_LIBS="-lusb" LIBUSB_CFLAGS="-I/usr/include"
+.endif
 
 post-patch:
 .for file in configure libgphoto2_port/configure
