--- Makefile.orig	2013-12-19 18:44:28.904333000 +0000
+++ Makefile
@@ -21,7 +21,6 @@ CONFIGURE_ARGS=	--enable-kdrive --enable
 SLAVE_PORT=	yes
 PLIST_FILES=	bin/Xephyr man/man1/Xephyr.1.gz
 
-.include <bsd.port.options.mk>
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/hw/kdrive/ephyr/Xephyr ${STAGEDIR}${PREFIX}/bin/
