--- Makefile.orig	2012-12-03 14:15:59.000000000 +0100
+++ Makefile	2012-12-10 18:08:51.085287000 +0100
@@ -83,9 +83,9 @@
 do-build: build-profile build-shared build-static
 
 .for o in PROFILE SHARED STATIC
-build-${o:L}: patch
+build-${o:tl}: patch
 .if defined(WITH_${o})
-	@${PRINTF} "\n\nBuilding ${o:L} libraries:\n\n\n"
+	@${PRINTF} "\n\nBuilding ${o:tl} libraries:\n\n\n"
 	@cd ${WRKSRC_${o}}/src; ${SETENV} ${MAKE_ENV} EXTRAFLAGS="${FLAGS_${o}}" \
 	${MAKE} ${_MAKE_JOBS} ${MAKE_ARGS} all
 
@@ -107,9 +107,9 @@
 check regression-test test: ${TESTS}
 
 .for o in PROFILE SHARED STATIC
-test-${o:L}: build-${o:L}
+test-${o:tl}: build-${o:tl}
 .if defined(WITH_${o})
-	@${PRINTF} "\n\nTesting ${o:L} libraries:\n\n\n"
+	@${PRINTF} "\n\nTesting ${o:tl} libraries:\n\n\n"
 	@cd ${WRKSRC_${o}}/testing; ${SETENV} ${MAKE_ENV} EXTRAFLAGS="${FLAGS_${o}}" \
 	${MAKE} ${_MAKE_JOBS} ${MAKE_ARGS} all run
 	@${CAT} ${WRKSRC_${o}}/testing/*.out
