--- Makefile.orig	2013-01-24 17:47:07.545042000 +0100
+++ Makefile	2013-01-24 17:47:23.295064000 +0100
@@ -7,6 +7,7 @@
 
 PORTREVISION=	1
 CATEGORIES=	japanese
+PKGNAMEPREFIX=	ja-
 
 MAINTAINER=	ports@FreeBSD.org
 COMMENT=	X11 IRC client using the GTK+ toolkit, and optionally, GNOME
