--- Makefile.orig	2013-01-01 13:05:56.170429000 +0100
+++ Makefile	2013-01-01 13:06:12.290451000 +0100
@@ -27,9 +27,11 @@
 
 .include <bsd.port.pre.mk>
 
+.if ${OPSYS} == "FreeBSD"
 .if ${OSVERSION} < 802516 || (${OSVERSION} >= 900000 && ${OSVERSION} < 900502)
 BUILD_DEPENDS+=	${LOCALBASE}/bin/gperf:${PORTSDIR}/devel/gperf
 CONFIGURE_ENV+=	GPERF=${LOCALBASE}/bin/gperf
 .endif
+.endif
 
 .include <bsd.port.post.mk>
