--- Makefile.orig	2013-01-01 13:05:56.170429000 +0100
+++ Makefile	2013-01-01 13:13:09.601034000 +0100
@@ -27,9 +27,7 @@
 
 .include <bsd.port.pre.mk>
 
-.if ${OSVERSION} < 802516 || (${OSVERSION} >= 900000 && ${OSVERSION} < 900502)
 BUILD_DEPENDS+=	${LOCALBASE}/bin/gperf:${PORTSDIR}/devel/gperf
 CONFIGURE_ENV+=	GPERF=${LOCALBASE}/bin/gperf
-.endif
 
 .include <bsd.port.post.mk>
