--- Makefile.orig	2023-05-13 18:53:02 UTC
+++ Makefile
@@ -28,8 +28,8 @@ CMAKE_OFF=	ENABLE_FORTRAN \
 
 CONFLICTS=	libint2
 
-post-configure: # workaround for clang hanging on unity_1935_cxx.cxx, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265809
-	@cd ${BUILD_WRKSRC} && \
-		${SED} -e 's|%%BUILD_WRKSRC%%|${BUILD_WRKSRC}|g ; s|%%WRKDIR%%|${WRKDIR}|g' < ${FILESDIR}/build.patch | tee p | ${PATCH}
+#post-configure: # workaround for clang hanging on unity_1935_cxx.cxx, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265809
+#	@cd ${BUILD_WRKSRC} && \
+#		${SED} -e 's|%%BUILD_WRKSRC%%|${BUILD_WRKSRC}|g ; s|%%WRKDIR%%|${WRKDIR}|g' < ${FILESDIR}/build.patch | tee p | ${PATCH}
 
 .include <bsd.port.mk>
