--- Makefile.orig	Sat Nov  1 10:56:35 2025
+++ Makefile	Sat Nov
@@ -94,13 +94,6 @@ QMAKE_CONFIGURE_ARGS=	-proprietary-codecs -system-ffmp
 # dependencies correctly in the generated Makefiles, use the right target here.
 ALL_TARGET=	first
 
-# We need ar(1) from ports because the Chromium code uses the @file syntax.
-# We then need to ensure ld(1) from ports is used because of the archives ar(1)
-# generated.
-USE_BINUTILS=	yes
-CC+=		"-B${LOCALBASE}/bin"
-CXX+=		"-B${LOCALBASE}/bin"
-
 # The build system reads the environment variable $NINJA_PATH to decide whether
 # to boostrap ninja or not (and also to invoke it afterwards). CC and CXX are
 # read by some Chromium code to determine which compiler to invoke when running
@@ -170,11 +163,5 @@ post-build:
 	@${REINPLACE_CMD} -e '/${QT5_VERSION} $${_Qt5${module}_FIND_VERSION_EXACT}/s|${QT5_VERSION}|'"$$(${MAKE} -C ../../devel/qt5-core -VQT5_VERSION)"'|' \
 		${BUILD_WRKSRC}/lib/cmake/Qt5${module}/Qt5${module}Config.cmake
 .endfor
-
-post-install:
-	for lib in ${STAGEDIR}${PREFIX}/${QT_LIBDIR_REL}/*.so.${_QT_VERSION:C/-.*//} ; \
-	do \
-		${BRANDELF} -t FreeBSD $$lib ; \
-	done
 
 .include <bsd.port.post.mk>
