--- Makefile.orig	2014-10-20 15:23:15 UTC
+++ Makefile
@@ -51,6 +51,8 @@ LIB_DEPENDS=	libcairo.so:${PORTSDIR}/gra
 		libxml2.so:${PORTSDIR}/textproc/libxml2 \
 		libwebp.so:${PORTSDIR}/graphics/webp
 
+LIB_DEPENDS+=	gssapi_krb5:${PORTSDIR}/security/krb5
+
 RUN_DEPENDS=	${LOCALBASE}/lib/alsa-lib/libasound_module_pcm_oss.so:${PORTSDIR}/audio/alsa-plugins \
 		${LOCALBASE}/lib/X11/fonts/Droid/fonts.dir:${PORTSDIR}/x11-fonts/droid-fonts-ttf \
 		xdg-open:${PORTSDIR}/devel/xdg-utils
@@ -74,6 +76,7 @@ GYP_DEFINES+=	\
 		linux_use_heapchecker=0 \
 		linux_strip_binary=1 \
 		test_isolation_mode=noop \
+		disable_fatal_linker_warnings=1 \
 		disable_nacl=1 \
 		enable_extensions=1 \
 		enable_one_click_signin=1 \
@@ -183,6 +186,7 @@ CONFIGURE_ENV+=	CC="${CC}" \
 		GYP_GENERATORS=ninja \
 		GYP_DEFINES="${GYP_DEFINES}"
 MAKE_ENV+=	BUILDTYPE=${BUILDTYPE} \
+		GYPFLAGS=-DOS=freebsd \
 		GPERF="${LOCALBASE}/bin/gperf"
 MAKE_ARGS=	-C out/${BUILDTYPE}
 
@@ -193,6 +197,7 @@ GYP_DEFINES+=	gcc_version=${CXX:S/g++//}
 EXTRA_PATCHES+=	${FILESDIR}/extra-patch-gcc
 .else
 GYP_DEFINES+=	clang=1
+CXXFLAGS+=	-D__float128=void -D_GLIBCXX_PERMIT_BACKWARD_HASH=1
 CFLAGS+=	-Wno-unknown-warning-option
 EXTRA_PATCHES+=	${FILESDIR}/extra-patch-clang
 CONFIGURE_ENV+=	AR=/usr/bin/ar
@@ -219,12 +224,25 @@ pre-everything::
 
 post-patch:
 	@${REINPLACE_CMD} -e "s|/usr/local|${LOCALBASE}|" \
+		${WRKSRC}/base/base_paths_posix.cc \
+		${WRKSRC}/base/process/process_handle_freebsd.cc \
 		${WRKSRC}/crypto/crypto.gyp \
 		${WRKSRC}/v8/tools/gyp/v8.gyp \
 		${WRKSRC}/v8/build/toolchain.gypi
 	@${REINPLACE_CMD} -e "s|/usr/local|${PREFIX}|" \
 		${WRKSRC}/chrome/common/chrome_paths.cc \
 		${WRKSRC}/base/base.gyp
+	@${FIND} ${WRKSRC} -type f -name \*\.gyp\* | \
+		${GREP} -vE "/v8/|libusb" | ${XARGS} ${GREP} -l '"freebsd"' | \
+		${XARGS} ${REINPLACE_CMD} -e 's|"freebsd"|"dragonfly"|g'
+	@${FIND} ${WRKSRC} -type f -name \*\.py | ${GREP} -v /v8/ | \
+		${XARGS} ${GREP} -l "'freebsd'" | \
+		${XARGS} ${REINPLACE_CMD} -e "s|'freebsd'|'dragonfly'|g"
+	@${REINPLACE_CMD} -e 's|"freebsd"|"dragonfly"|g' \
+		${WRKSRC}/v8/build/standalone.gypi \
+		${WRKSRC}/v8/build/toolchain.gypi \
+		${WRKSRC}/v8/src/d8.gyp \
+		${WRKSRC}/v8/tools/gyp/v8.gyp
 
 pre-configure:
 	# phajdan-jr: list of things *not* to remove, so maybe the script
