--- Makefile.orig	2014-09-13 06:56:23 UTC
+++ Makefile
@@ -35,6 +35,12 @@ USE_SUBMAKE=	yes
 EXTRA_PATCHES=	${FILESDIR}/extra-patch-docs_pkg.8
 .endif
 
+.if defined(PACKAGE_BUILDING)
+MAKE_ARGS+=	PKG_PORTSDIR=/usr/dports
+.else
+MAKE_ARGS+=	PKG_PORTSDIR=${PORTSDIR}
+.endif
+
 .include <bsd.port.pre.mk>
 
 .if defined(WITH_PKG)
