--- Makefile.orig	2014-06-19 22:00:43.083941000 +0000
+++ Makefile
@@ -21,6 +21,11 @@ CFLAGS+=	-O0 -g
 USE_LDCONFIG=	yes
 USES=		libtool tar:xz
 GNU_CONFIGURE=	yes
+.if defined(PACKAGE_BUILDING)
+MAKE_ARGS+=	PKG_PORTSDIR=/usr/dports
+.else
+MAKE_ARGS+=	PKG_PORTSDIR=${PORTSDIR}
+.endif
 
 # Use a submake as 'deinstall install' needs to reevaluate PKG_CMD
 # so that pkg-static is used from the wrkdir
