--- Makefile.orig	2012-11-17 14:23:01.000000000 +0100
+++ Makefile	2012-12-10 14:31:36.405473000 +0100
@@ -119,7 +119,7 @@
 PLIST_SUB+=	RIPNGD="@comment "
 .endif
 
-.if ${PORT_OPTIONS:MVTYSH)
+.if ${PORT_OPTIONS:MVTYSH}
 PLIST_SUB+=	VTYSH=""
 CONFIGURE_ARGS+=--enable-vtysh
 .else
