--- Makefile.orig	2014-08-04 21:09:19.706176000 +0000
+++ Makefile
@@ -21,6 +21,7 @@ LICENSE=	APACHE20 MIT
 LICENSE_COMB=	multi
 
 BUILD_DEPENDS=	cmake:${PORTSDIR}/devel/cmake \
+		${UNZIP_CMD}:${PORTSDIR}/archivers/unzip \
 		v4l_compat>=1.0.20120501:${PORTSDIR}/multimedia/v4l_compat
 LIB_DEPENDS=	libaudio.so:${PORTSDIR}/audio/nas \
 		libffi.so:${PORTSDIR}/devel/libffi \
@@ -79,7 +80,7 @@ pre-configure:
 post-install:
 	${GUNZIP_CMD} -c ${_DISTDIR}/${SQUEAK_SRC}.gz > \
 		${STAGEDIR}${PREFIX}/lib/squeak/${SQUEAK_LIB_DIR}/${SQUEAK_SRC}
-	${UNZIP_NATIVE_CMD} -u ${_DISTDIR}/Squeak${IMAGE_VERSION}.zip \
+	${UNZIP_CMD} -u ${_DISTDIR}/Squeak${IMAGE_VERSION}.zip \
 		-d ${WRKDIR}
 	${INSTALL_DATA} ${IMAGES:S,^,${WRKDIR}/,} \
 		${STAGEDIR}${PREFIX}/lib/squeak
