--- Makefile.orig	2015-08-22 10:04:12 UTC
+++ Makefile
@@ -22,6 +22,7 @@ LICENSE=	APACHE20 MIT
 LICENSE_COMB=	multi
 
 BUILD_DEPENDS=	cmake:${PORTSDIR}/devel/cmake \
+		${UNZIP_CMD}:${PORTSDIR}/archivers/unzip \
 		v4l_compat>=1.0.20120501:${PORTSDIR}/multimedia/v4l_compat
 LIB_DEPENDS=	libaudio.so:${PORTSDIR}/audio/nas \
 		libffi.so:${PORTSDIR}/devel/libffi \
@@ -83,8 +84,8 @@ post-install:
 	${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/squeak/${SQUEAK_LIB_DIR}/so.* \
 		${STAGEDIR}${PREFIX}/lib/squeak/${SQUEAK_LIB_DIR}/squeakvm \
 		${STAGEDIR}${PREFIX}/lib/squeak/${SQUEAK_LIB_DIR}/ckformat
-	${UNZIP_NATIVE_CMD} -u ${_DISTDIR}/${SQUEAK_SRC}.zip -d ${WRKDIR}
-	${UNZIP_NATIVE_CMD} -u ${_DISTDIR}/Squeak${IMAGE_FULL_VERSION}.zip \
+	${UNZIP_CMD} -u ${_DISTDIR}/${SQUEAK_SRC}.zip -d ${WRKDIR}
+	${UNZIP_CMD} -u ${_DISTDIR}/Squeak${IMAGE_FULL_VERSION}.zip \
 		-d ${WRKDIR}
 	${INSTALL_DATA} ${IMAGES:S,^,${WRKDIR}/,} \
 		${STAGEDIR}${PREFIX}/lib/squeak
