--- Makefile.orig	2019-07-11 21:43:05 UTC
+++ Makefile
@@ -12,7 +12,7 @@ COMMENT=	System for Automated Geoscienti
 LICENSE=	GPLv2 LGPL21
 LICENSE_COMB=	multi
 
-BUILD_DEPENDS=	clang${LLVM_VER}:devel/llvm${LLVM_VER} \
+BUILD_DEPENDS=	\
 		swig3.0:devel/swig30
 LIB_DEPENDS=	libcurl.so:ftp/curl \
 		libfftw3.so:math/fftw3 \
@@ -57,7 +57,6 @@ VIGRA_DESC=	Enable 'Vision with Generic
 OPENMP_CONFIGURE_ENABLE=	openmp
 OPENMP_LDFLAGS=		-L${LOCALBASE}/lib -lm
 # Use OpenMP from lang/llvm${LLVM_VER}
-OPENMP_LDFLAGS+=	-L${LOCALBASE}/llvm${LLVM_VER}/lib -lomp
 PGSQL_CONFIGURE_OFF=	--with-postgresql=no
 PGSQL_CONFIGURE_ON=	--with-postgresql=${LOCALBASE}/bin/pg_config
 PGSQL_USES=		pgsql
@@ -68,12 +67,6 @@ INSTALL_TARGET=	install-strip
 
 .include <bsd.port.pre.mk>
 
-# make describe needs them here
-LLVM_VER=	80
-CPP=		clang-cpp${LLVM_VER}
-CC=		clang${LLVM_VER}
-CXX=		clang++${LLVM_VER}
-
 SUB_FILES=	pkg-message
 
 post-extract:
@@ -103,12 +96,6 @@ post-patch:
 	@${REINPLACE_CMD} -e 's|PORTVERSION|${PORTVERSION}|' \
 		${WRKSRC}/src/saga_core/saga_gui/dlg_about.cpp
 
-post-patch-OPENMP-on:
-	@${REINPLACE_CMD} -e 's|-lgomp|-lomp|' \
-		${WRKSRC}/configure.ac \
-		${WRKSRC}/configure \
-		${WRKSRC}/src/accessories/templates/template4saga-tools/my_tool_library/Makefile
-
 post-configure:
 	@${REINPLACE_CMD} -e 's|cd $$(pkgdatadir);|cd ${STAGEDIR}${DATADIR};|g' \
 		${WRKSRC}/src/saga_core/saga_gui/Makefile
