--- Makefile.orig	2013-12-28 17:05:29.340151000 +0000
+++ Makefile
@@ -3,17 +3,17 @@
 
 PORTNAME=	pysvg
 PORTVERSION=	0.2.1
+PORTREVISION=	1
 CATEGORIES=	graphics python
 MASTER_SITES=	GOOGLE_CODE
 
 MAINTAINER=	duchateau.olivier@gmail.com
 COMMENT=	pySVG - creating svg with python
 
-USE_PYDISTUTILS=yes
+USE_PYDISTUTILS=	yes
+PYDISTUTILS_AUTOPLIST=	yes
+
 USE_PYTHON=	-2.7
 USE_ZIP=	yes
 
-PLIST_SUB=	PYDISTUTILS_EGGINFO=${PYDISTUTILS_EGGINFO}
-
-NO_STAGE=	yes
 .include <bsd.port.mk>
