--- Makefile.orig	2016-04-06 16:47:47 UTC
+++ Makefile
@@ -15,12 +15,12 @@ LIB_DEPENDS=	libIlmImf.so:graphics/OpenE
 		libwebp.so:graphics/webp \
 		libslp.so:net/openslp \
 		libsmbclient.so:net/samba-libsmbclient \
-		libssh.so:security/libssh \
 		libqzeitgeist.so:sysutils/qzeitgeist
 # Explicitly depend on libssh to avoid interference with ssh.4 from
 # compat7x.
-BUILD_DEPENDS=	${LOCALBASE}/lib/libssh.so:security/libssh
-RUN_DEPENDS=	cagibid:net/cagibi
+BUILD_DEPENDS=	libssh>0.7:security/libssh
+RUN_DEPENDS=	libssh>0.7:security/libssh \
+		cagibid:net/cagibi
 
 USE_KDE4=	kactivities kdelibs kdeprefix oxygen \
 		attica automoc4 pimlibs strigi nepomuk-core
