--- Makefile.orig	2017-07-05 16:06:45 UTC
+++ Makefile
@@ -12,7 +12,6 @@ LIB_DEPENDS=	libIlmImf.so:graphics/OpenE
 		libexiv2.so:graphics/exiv2 \
 		libwebp.so:graphics/webp \
 		libslp.so:net/openslp \
-		libssh.so:security/libssh \
 		libqzeitgeist.so:sysutils/qzeitgeist \
 		libImath-2_2.so:graphics/ilmbase \
 		libassuan.so:security/libassuan \
@@ -21,10 +20,11 @@ LIB_DEPENDS=	libIlmImf.so:graphics/OpenE
 		libgpgme.so:security/gpgme
 # Explicitly depend on libssh to avoid interference with ssh.4 from
 # compat7x.
-BUILD_DEPENDS=	${LOCALBASE}/lib/libssh.so:security/libssh
-RUN_DEPENDS=	cagibid:net/cagibi
+BUILD_DEPENDS=	libssh>0.7:security/libssh
+RUN_DEPENDS=	libssh>0.7:security/libssh \
+		cagibid:net/cagibi
 
-USES=		cmake:outsource gettext jpeg kde:4 samba:lib shared-mime-info \
+USES=		cmake:outsource gmake gettext jpeg kde:4 samba:lib shared-mime-info \
 		shebangfix tar:xz
 USE_KDE=	kactivities kdelibs oxygen-icons5 \
 		attica automoc4 pimlibs soprano strigi nepomuk-core
