--- Makefile.orig	2017-03-29 23:44:29 UTC
+++ Makefile
@@ -11,7 +11,6 @@ LIB_DEPENDS=	libIlmImf.so:graphics/OpenE
 		libexiv2.so:graphics/exiv2 \
 		libwebp.so:graphics/webp \
 		libslp.so:net/openslp \
-		libssh.so:security/libssh \
 		libqzeitgeist.so:sysutils/qzeitgeist \
 		libImath-2_2.so:graphics/ilmbase \
 		libassuan.so:security/libassuan \
@@ -20,8 +19,9 @@ LIB_DEPENDS=	libIlmImf.so:graphics/OpenE
 		libgpgme.so:security/gpgme
 # Explicitly depend on libssh to avoid interference with ssh.4 from
 # compat7x.
-BUILD_DEPENDS=	${LOCALBASE}/lib/libssh.so:security/libssh
-RUN_DEPENDS=	cagibid:net/cagibi
+BUILD_DEPENDS=	libssh>0.7:security/libssh
+RUN_DEPENDS=	libssh>0.7:security/libssh \
+		cagibid:net/cagibi
 
 USES=		cmake:outsource gettext gmake jpeg kde:4 samba:lib shared-mime-info \
 		shebangfix tar:xz
