--- Makefile.orig	2015-08-07 21:59:13 UTC
+++ Makefile
@@ -31,7 +31,7 @@ RUN_DEPENDS?=	dconf-editor:${PORTSDIR}/d
 		${LOCALBASE}/share/gnome-background-properties/gnome-backgrounds.xml:${PORTSDIR}/x11-themes/gnome-backgrounds \
 		caribou>=0:${PORTSDIR}/accessibility/caribou \
 		${LOCALBASE}/share/sounds/freedesktop/index.theme:${PORTSDIR}/audio/freedesktop-sound-theme \
-		ekiga:${PORTSDIR}/net-im/ekiga
+#		ekiga:${PORTSDIR}/net-im/ekiga
 
 CONFLICTS?=	gnome3-lite-[0-9]*
 
@@ -72,7 +72,6 @@ RUN_DEPENDS+=	empathy>=3.0.0:${PORTSDIR}
 		gconf-editor>=3.0.0:${PORTSDIR}/sysutils/gconf-editor \
 		gdm>=3.0.0:${PORTSDIR}/x11/gdm \
 		evolution>=3.0.0:${PORTSDIR}/mail/evolution \
-		cheese>=3.0.0:${PORTSDIR}/multimedia/cheese \
 		alacarte>=3.0.0:${PORTSDIR}/deskutils/alacarte
 
 .endif # !gnome3-lite section
