--- Makefile.orig	2014-11-22 17:14:19.478406000 +0000
+++ Makefile
@@ -39,7 +39,8 @@ RUN_DEPENDS?=	dconf-editor:${PORTSDIR}/d
 		caribou>=0:${PORTSDIR}/accessibility/caribou \
 		${LOCALBASE}/share/help/C/gnome-help/index.page:${PORTSDIR}/misc/gnome-user-docs \
 		${LOCALBASE}/share/sounds/freedesktop/index.theme:${PORTSDIR}/audio/freedesktop-sound-theme \
-		ekiga:${PORTSDIR}/net-im/ekiga
+
+#		ekiga:${PORTSDIR}/net-im/ekiga
 
 NO_BUILD=	yes
 NO_MTREE=	yes
@@ -74,9 +75,11 @@ RUN_DEPENDS+=	empathy>=3.0.0:${PORTSDIR}
 		gconf-editor>=3.0.0:${PORTSDIR}/sysutils/gconf-editor \
 		gdm>=3.0.0:${PORTSDIR}/x11/gdm \
 		evolution>=3.0.0:${PORTSDIR}/mail/evolution \
-		cheese>=3.0.0:${PORTSDIR}/multimedia/cheese \
 		alacarte>=3.0.0:${PORTSDIR}/deskutils/alacarte
 
+#		cheese>=3.0.0:${PORTSDIR}/multimedia/cheese \
+
+
 .if ${PORT_OPTIONS:MMAPI}
 RUN_DEPENDS+=	evolution-mapi>=3.0.0:${PORTSDIR}/mail/evolution-mapi
 .endif
