--- Makefile.orig	2020-10-28 15:56:06 UTC
+++ Makefile
@@ -71,7 +71,6 @@ RUN_DEPENDS+=	epiphany>=3.0.0:www/epipha
 		gconf-editor>=3.0.0:sysutils/gconf-editor \
 		gnome-color-manager>=0:graphics/gnome-color-manager \
 		evolution>=3.0.0:mail/evolution \
-		cheese>=3.0.0:multimedia/cheese
 
 .endif # !gnome3-lite section
 
