--- Makefile.orig	2013-05-07 19:14:48.396263000 +0000
+++ Makefile
@@ -77,7 +77,12 @@ LCDPROC_DRIVERS=bayrad \
 .include <bsd.port.options.mk>
 
 .if ${PORT_OPTIONS:MUSB}
+.if ${OPSYS} == DragonFly
+USES+=			usb
+CONFIGURE_ARGS+=	--with-libusb
+.else
 CONFIGURE_ARGS+=	--with-libusb=/usr
+.endif
 PLIST_SUB+=		USB=""
 LCDPROC_DRIVERS+=IOWarrior \
 		picolcd \
