--- Makefile.orig	2016-04-06 15:43:27 UTC
+++ Makefile
@@ -10,17 +10,17 @@ PKGNAMEPREFIX=	p5-
 MAINTAINER=	perl@FreeBSD.org
 COMMENT=	Perl5 module for terminal screen handling and optimization
 
-USES=		perl5
+USES=		ncurses perl5
 USE_PERL5=	configure
 
 CONFIGURE_ARGS=	PANELS MENUS FORMS
-CONFIGURE_ENV=	CURSES_CFLAGS="-I${WRKSRC}/usr/include/ncurses"
+CONFIGURE_ENV=	CURSES_CFLAGS="${CFLAGS:M-I*} -I${WRKSRC}/usr/include/ncurses"
 
 OPTIONS_DEFINE=	NCURSESW
 NCURSESW_DESC=	Wide-character-capable support by ncursesw library
-NCURSESW_CONFIGURE_ENV=		CURSES_LDFLAGS="-L/usr/lib/ -lncursesw" \
+NCURSESW_CONFIGURE_ENV=		CURSES_LDFLAGS="${LDFLAGS:M-L*} -L/usr/lib/ -lncursesw" \
 				CURSES_LIBTYPE="ncursesw"
-NCURSESW_CONFIGURE_ENV_OFF=	CURSES_LDFLAGS="-L/usr/lib/ -lncurses"
+NCURSESW_CONFIGURE_ENV_OFF=	CURSES_LDFLAGS="${LDFLAGS:M-L*} -L/usr/lib/ -lncurses"
 
 pre-configure:
 	@${LN} -sf ${WRKSRC}/hints/c-freebsd.ncurses.h \
