--- Makefile.orig	2023-04-11 18:59:46 UTC
+++ Makefile
@@ -13,19 +13,19 @@ LICENSE_COMB=	dual
 LICENSE_FILE_ART10=	${WRKSRC}/Artistic
 LICENSE_FILE_GPLv1+ =	${WRKSRC}/Copying
 
-USES=		perl5 shebangfix
+USES=		ncurses perl5 shebangfix
 USE_PERL5=	configure
 
 CONFIGURE_ARGS=	PANELS MENUS FORMS
-CONFIGURE_ENV=	CURSES_CFLAGS="-I${WRKSRC}/usr/include/ncurses"
+CONFIGURE_ENV=	CURSES_CFLAGS="${CFLAGS:M-I*} -I${WRKSRC}/usr/include/ncurses"
 
 SHEBANG_FILES=	makeConfig
 
 OPTIONS_DEFINE=	NCURSESW
 NCURSESW_DESC=	Wide-character-capable support by ncursesw library
-NCURSESW_CONFIGURE_ENV=		CURSES_LDFLAGS="-L/usr/lib/ -lncursesw" \
+NCURSESW_CONFIGURE_ENV=		CURSES_LDFLAGS="${LDFLAGS:M-L*} -L/usr/lib/ -lncursesw" \
 				CURSES_LIBTYPE="ncursesw"
-NCURSESW_CONFIGURE_ENV_OFF=	CURSES_LDFLAGS="-L/usr/lib/ -lncurses"
+NCURSESW_CONFIGURE_ENV_OFF=	CURSES_LDFLAGS="${LDFLAGS:M-L*} -L/usr/lib/ -lncurses"
 
 pre-configure:
 	@${LN} -fs ${WRKSRC}/hints/c-freebsd.ncurses.h ${WRKSRC}/c-config.h
