--- Makefile.orig	2019-05-01 21:18:47 UTC
+++ Makefile
@@ -18,15 +18,9 @@ MAKE_ENV=	STAGEDIR="${STAGEDIR}"
 
 MAKEFILE=	${FILESDIR}/BSDmakefile
 
-post-build:
-	${SETENV} ${MAKE_ENV} ${MAKE} -C ${WRKSRC} -f \
-		${FILESDIR}/Makefile.example
+MAKE_ARGS+=    NO_WERROR=yes
 
 pre-install:
 	${MKDIR} ${STAGEDIR}${PREFIX}/include/dht
 
-post-install:
-	${SETENV} ${MAKE_ENV} ${MAKE} -C ${WRKSRC} -f \
-		${FILESDIR}/Makefile.example install
-
 .include <bsd.port.mk>
