--- Makefile.orig	2017-05-07 03:07:12 UTC
+++ Makefile
@@ -15,13 +15,7 @@ MAKEFILE=	${FILESDIR}/BSDmakefile
 USE_LDCONFIG=	yes
 USES=	uidfix
 MAKE_ENV+=	STAGEDIR="${STAGEDIR}"
-
-post-build:
-	${SETENV} ${MAKE_ENV} ${MAKE} -C ${WRKSRC} -f \
-		${FILESDIR}/Makefile.example
-post-install:
-	${SETENV} ${MAKE_ENV} ${MAKE} -C ${WRKSRC} -f \
-		${FILESDIR}/Makefile.example install
+MAKE_ARGS+=	NO_WERROR=yes
 
 pre-su-install:
 	${MKDIR} ${STAGEDIR}${PREFIX}/include/dht
