--- Makefile.orig	2019-04-26 19:09:03 UTC
+++ Makefile
@@ -18,13 +18,9 @@ MAKE_ENV+=	STAGEDIR="${STAGEDIR}"
 
 MAKEFILE=	${FILESDIR}/BSDmakefile
 
+MAKE_ARGS+=    NO_WERROR=yes
+
 post-build:
-	${SETENV} ${MAKE_ENV} ${MAKE} -C ${WRKSRC} -f \
-		${FILESDIR}/Makefile.example
 	${MKDIR} ${STAGEDIR}${PREFIX}/include/dht
 
-post-install:
-	${SETENV} ${MAKE_ENV} ${MAKE} -C ${WRKSRC} -f \
-		${FILESDIR}/Makefile.example install
-
 .include <bsd.port.mk>
