--- Makefile.orig	2022-10-12 11:05:00 UTC
+++ Makefile
@@ -63,5 +63,9 @@ post-patch:
 .if ${OPSYS} == FreeBSD
 	@${REINPLACE_CMD} 's|altq/|net/&|' ${WRKSRC}/platform/FreeBSD/sm_pfq.c
 .endif
+	@${MKDIR} ${WRKSRC}/platform/DragonFly
+	(cd ${WRKSRC}/platform && \
+		 ${FIND} FreeBSD -type f \! -name sm_smart.c | \
+		 ${XARGS} -n1 -I foo ${CP} foo DragonFly/)
 
 .include <bsd.port.post.mk>
