--- Makefile.orig	2015-05-12 18:47:48 UTC
+++ Makefile
@@ -67,5 +67,9 @@ post-patch:
 .if ${OSVERSION} >= 1100070
 	@${REINPLACE_CMD} 's|altq/|net/&|' ${WRKSRC}/platform/FreeBSD/sm_pfq.c
 .endif
+	@${MKDIR} ${WRKSRC}/platform/DragonFly
+	(cd ${WRKSRC}/platform && \
+		 ${FIND} FreeBSD -type f \! -name sm_smart.c | \
+		 ${XARGS} -n1 -I foo ${CP} foo DragonFly/)
 
 .include <bsd.port.post.mk>
