--- Makefile.orig	2013-03-16 18:47:41.383160000 +0000
+++ Makefile
@@ -38,9 +38,6 @@ OPTIONS=	LDAP "LDAP keyserver interface"
 
 .if ${CC} == "clang" || ${OSVERSION} >= 1000024
 CFLAGS:=	${CFLAGS:S/$/ -std=c89/}
-.if (${ARCH} == "i386")
-CFLAGS:=	${CFLAGS:S/$/ -fheinous-gnu-extensions/}
-.endif
 .endif
 
 .if defined(WITH_LIBICONV)
