--- Makefile.orig	2017-08-12 22:42:24 UTC
+++ Makefile
@@ -10,7 +10,7 @@ COMMENT=	Cross-platform application and
 
 # * phonon4 is not part of Qt itself.
 # * we don't want to pull in wayland just yet.
-USE_QT5=	${_USE_QT_ALL:Nphonon4:Ndeclarative:Nwayland:S/$/_run/}
+USE_QT5=	${_USE_QT_ALL:Nphonon4:Ndeclarative:Nwayland:Nexamples:S/$/_run/}
 USES=		metaport
 
 .include <bsd.port.mk>
