# For check-plist and disabled options
OPTIONS_SUB=	yes

# exclude fake crud
OPTIONS_DEFAULT:=	${OPTIONS_DEFAULT:NBATCH:NHYPRE:NMPI:NMPICH:NMUMPS:NPARMETIS:NPETSC:NBLAS:NSCOTCH}
OPTIONS_EXCLUDE+=	DOCS
CFLAGS:=	${CFLAGS:N-D__XSI_VISIBLE*}


dfly-patch:
	${REINPLACE_CMD} -e '/#define _POSIX_C_SOURCE/d' \
		${WRKSRC}/src/base/cs_timer.c
