--- Makefile.orig	2015-04-08 18:07:46 UTC
+++ Makefile
@@ -80,8 +80,6 @@ LIB_DEPENDS+=		libsasl2.so:${PORTSDIR}/s
 # GNUTLS
 LIB_DEPENDS+=		libgcrypt.so:${PORTSDIR}/security/libgcrypt
 LIB_DEPENDS+=		libgnutls.so:${PORTSDIR}/security/gnutls
-# NFS4 ACL glue
-LIB_DEPENDS+=		libsunacl.so:${PORTSDIR}/sysutils/libsunacl
 # External Samba dependencies
 # IDL compiler
 BUILD_DEPENDS+=		p5-Parse-Pidl>=4.0.0:${PORTSDIR}/devel/p5-Parse-Pidl
@@ -140,6 +138,8 @@ BIND99_DESC=		Use bind99 as AD DC DNS se
 BIND910_DESC=		Use bind910 as AD DC DNS server frontend
 NSUPDATE_DESC=		Use samba NSUPDATE utility for AD DC
 
+OPTIONS_EXCLUDE_DragonFly=	ACL_SUPPORT
+
 .include <bsd.port.options.mk>
 
 CONFIGURE_ARGS+=	\
