
# wrong MF, exclude MPI
OPTIONS_DEFAULT:=	${OPTIONS_DEFAULT:NMPI}

# XXX Meh, this is a hack for the .pre inclusion
.if !target(dfly-patch)
dfly-patch:
	${REINPLACE_CMD} -e "/FC_SERIAL=/s@gfortran.*@${FC}@g" \
		${BUILD_WRKSRC}/fortran.mk
.endif
