--- Makefile.orig	2016-12-31 17:03:06 UTC
+++ Makefile
@@ -26,7 +26,7 @@ WOLFDIR=	"libexec/${PORTNAME}"
 MAKE_ARGS=	BINDIR="${STAGEDIR}${PREFIX}/bin" \
 		COPYDIR="${STAGEDIR}${PREFIX}/${WOLFDIR}"
 
-PLIST_SUB=	ARCH="${ARCH}" WOLFDIR="${WOLFDIR}"
+PLIST_SUB=	ARCH="${ARCH:S/x86_64/amd64/}" WOLFDIR="${WOLFDIR}"
 
 SUB_FILES=	iowolfsp iowolfmp iowolfded pkg-message
 SUB_LIST=	ARCH="${ARCH}" WOLFDIR="${PREFIX}/${WOLFDIR}" \
