--- Makefile.orig	2019-04-26 19:41:18 UTC
+++ Makefile
@@ -32,7 +32,7 @@ MAKE_ARGS=	BINDIR="${STAGEDIR}${PREFIX}/
 # cf. PR 226980
 LLD_UNSAFE=	yes
 
-PLIST_SUB=	ARCH="${ARCH}" \
+PLIST_SUB=	ARCH="${ARCH:S/x86_64/amd64/}" \
 		WOLFDIR="${WOLFDIR}"
 
 SUB_FILES=	iowolfded iowolfmp iowolfsp pkg-message
