--- Makefile.orig	2012-11-17 05:58:35.000000000 +0000
+++ Makefile
@@ -6,14 +6,11 @@
 #
 
 PKGNAMESUFFIX=	26
-DISTFILES?=	793.gz 794.gz 795.gz 796.gz 797.gz 798.gz 799.gz \
-		800.gz 802.gz 816.gz 817.gz 818.gz 819.gz 820.gz 821.gz
 
 FILESDIR=	${.CURDIR}/files
 PKGDIR=		${.CURDIR}
 MASTERDIR=	${.CURDIR}/../kanji18
 DISTINFO_FILE=	${.CURDIR}/distinfo
-README_FILE?=	793.gz
 RESIZESED_FILE?=	26to24.sed
 RESIZED_ALIAS_FILE?=	kanji24.alias
 
