--- Makefile.orig	2019-05-17 22:24:19 UTC
+++ Makefile
@@ -36,8 +36,10 @@ FLINT_DESC=		Link with libflint.so
 FLINT_BUILD_DEPENDS=	${LOCALBASE}/lib/libflint.so:math/flint2
 FLINT_CONFIGURE_ENABLE=	flint
 FLINT_LDFLAGS=		-lpthread
+.if 0 #${OPSYS} == FreeBSD
 OPENMP_BUILD_DEPENDS=	${LOCALBASE}/lib/libomp.so:devel/openmp
 OPENMP_CONFIGURE_ENABLE=	openmp
+.endif
 
 do-install:
 	${MKDIR} ${STAGEDIR}${PREFIX}/include/libnormaliz
