--- Makefile.orig	2017-07-04 17:56:57 UTC
+++ Makefile
@@ -11,11 +11,12 @@ MAINTAINER=	sunpoet@FreeBSD.org
 COMMENT=	Relocalizable fast lexical scanner
 
 LICENSE=	BSD3CLAUSE
-LICENSE_FILE=	${WRKSRC}/COPYING
 
 CONFIGURE_ENV=	YACC="${YACC}"
 GNU_CONFIGURE=	yes
 TEST_TARGET=	bigcheck
 USES=		tar:tgz
 
+MAKE_JOBS_UNSAFE=	yes
+
 .include <bsd.port.mk>
