--- Makefile.orig	2017-05-07 02:28:18 UTC
+++ Makefile
@@ -5,6 +5,7 @@ PKGNAMESUFFIX=	-utils
 MAINTAINER=	asomers@FreeBSD.org
 COMMENT=	QEMU userland utilities
 
+IGNORE=		Slave of emulators/qemu which does not build in dports yet
 HAS_CONFIGURE=	yes
 USES=		cpe gmake pkgconfig perl5 python:2,build tar:bzip2
 USES+=		gettext-runtime
