--- Makefile.orig	2015-02-14 22:43:20 UTC
+++ Makefile
@@ -79,9 +79,6 @@ DEBUG_CONFIGURE_OFF=	--disable-debug-sym
 
 .include <bsd.port.options.mk>
 
-# Shutup warning spam
-CXXFLAGS+=	-Wno-c++11-extensions
-
 .if ${ARCH} == powerpc64
 CFLAGS+=	-mminimal-toc
 .endif
@@ -103,6 +100,7 @@ CFLAGS+=	-march=i586
 .endif
 
 .if ${CHOSEN_COMPILER_TYPE} == clang
+CXXFLAGS+=	-Wno-c++11-extensions	# Shutup warning spam
 CXXFLAGS+=	-Qunused-arguments
 .endif
 
