--- Makefile.orig	2023-11-17 19:56:19 UTC
+++ Makefile
@@ -8,10 +8,12 @@ COMMENT=	Meta-port for Wireguard
 WWW=		https://www.wireguard.com
 
 RUN_DEPENDS=	wg-quick:net/wireguard-tools \
-		${KMODDIR}/if_wg.ko:net/wireguard-kmod
+		wireguard-go:net/wireguard-go
 
-DEPRECATED=	Only useful for FreeBSD 12 which is EoL soon
-EXPIRATION_DATE=	2023-12-31
+# Change run depends and the below expiration items when
+# we get in kernel wg
+#DEPRECATED=	Only useful for FreeBSD 12 which is EoL soon
+#EXPIRATION_DATE=	2023-12-31
 
 USES=	metaport
 
