--- Makefile.orig	2021-11-07 15:21:05 UTC
+++ Makefile
@@ -10,6 +10,6 @@ RUN_DEPENDS=	wg-quick:net/wireguard-tool
 
 USES=	metaport
 
-RUN_DEPENDS+=	${KMODDIR}/if_wg.ko:net/wireguard-kmod
+RUN_DEPENDS+=	wireguard-go:net/wireguard-go
 
 .include <bsd.port.mk>
