--- Makefile.orig	2016-03-09 09:34:36 UTC
+++ Makefile
@@ -45,7 +45,6 @@ PLIST_FILES=	%%DATADIR%%/en_CA${CA_VARIA
 		%%DATADIR%%/en_GB.dic \
 		%%DATADIR%%/en_GB.aff \
 
-COPY=		-lh	# Use hardlinks rather than copies under stage/
 
 .for c in CA GB US
 .	for v in STANDARD ISE IZE LARGE
