--- Makefile.orig	2021-02-10 16:44:03 UTC
+++ Makefile
@@ -22,7 +22,7 @@ OPTIONS_DEFINE=	DOCS EXAMPLES
 
 .include <bsd.port.pre.mk>
 
-.if ${GCC_DEFAULT} >= 10
+.if ${_GCC_VER} >= 10
 # workaround for Rank mismatch in argument 'lines' at (1) (rank-1 and scalar)
 FFLAGS+=	-fallow-argument-mismatch
 .endif
