--- Makefile.orig	2016-08-20 18:01:45 UTC
+++ Makefile
@@ -16,6 +16,7 @@ LIB_DEPENDS+=	libboost_chrono.so:devel/b
 		libboost_system.so:devel/boost-libs
 
 USES+=		compiler:c++11-lang iconv:wchar_t libtool pathfix pkgconfig ssl
+USE_CXXSTD=	c++11
 GNU_CONFIGURE=	yes
 USE_LDCONFIG=	yes
 TEST_TARGET=	check
