--- Makefile.orig	2017-04-02 16:11:38 UTC
+++ Makefile
@@ -28,6 +28,6 @@ do-install:
 	${INSTALL_DATA} ${DISTDIR}/mpg123el.cgi?${PORTVERSION} ${STAGEDIR}${ELISPDIR}/${PORTNAME}
 # For XEmacs
 	@${MKDIR} ${STAGEDIR}${XELISPDIR}
-	${INSTALL} -lr ${STAGEDIR}${ELISPDIR}/${PORTNAME} ${STAGEDIR}${XELISPDIR}/${PORTNAME}
+	${LN} -sf ${ELISPDIR}/${PORTNAME} ${STAGEDIR}${XELISPDIR}/${PORTNAME}
 
 .include <bsd.port.mk>
