--- Makefile.orig	2013-02-18 19:15:30.277030000 +0100
+++ Makefile	2013-02-18 19:15:56.515746000 +0100
@@ -30,10 +30,12 @@
 .include "../evas-core/Makefile.inc"
 CONFIGURE_ARGS+=	--enable-gl-xlib
 
+LDFLAGS+=	-L${LOCALBASE}/lib -levas
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/\.libs,${LOCALBASE}/lib,' \
-		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,-levas,' \
+		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,,' \
 		${BUILD_WRKSRC}/Makefile.in \
 		${WRKSRC}/src/modules/engines/gl_common/Makefile.in
 
