--- Makefile.orig	2013-11-02 09:06:48.748449000 +0000
+++ Makefile
@@ -39,7 +39,7 @@ BAZAAR_RUN_DEPENDS=	${LOCALBASE}/bin/bzr
 
 .include <bsd.port.options.mk>
 
-.if ${OSVERSION} > 1000000
+.if ${OPSYS} == FreeBSD && ${OSVERSION} > 1000000
 RUN_DEPENDS+=	cvs:${PORTSDIR}/devel/cvs
 .endif
 
