--- Makefile.orig	2013-04-05 23:05:45.680425000 +0000
+++ Makefile
@@ -119,9 +119,9 @@ do-install:
 	@${MKDIR} ${DOCSDIR}
 .for portdoc in ${PORTDOCS}
 	@if [ -f ${WRKDIR}/${portdoc} ]; then \
-		${INSTALL_DATA} -v ${WRKDIR}/${portdoc} ${DOCSDIR}/; \
+		${INSTALL_DATA} ${WRKDIR}/${portdoc} ${DOCSDIR}/; \
 	else \
-		${INSTALL_DATA} -v ${WRKSRC}/${portdoc} ${DOCSDIR}/; \
+		${INSTALL_DATA} ${WRKSRC}/${portdoc} ${DOCSDIR}/; \
 	fi
 .endfor
 .endif
