--- Makefile.orig	2013-01-26 11:51:09.694422000 +0100
+++ Makefile	2013-01-26 11:52:07.824504000 +0100
@@ -7,6 +7,7 @@
 
 CATEGORIES=	japanese www
 DISTNAME=	MTOS-${PORTVERSION}-${PKGNAMEPREFIX:S,-,,}
+PKGNAMEPREFIX=	ja-
 
 COMMENT=	Japanese localization of the MovableType publishing system
 
