--- Makefile.orig	2024-02-09 23:53:07 UTC
+++ Makefile
@@ -13,7 +13,7 @@ WWW=		https://doomlegacy.sourceforge.net
 
 LICENSE=	GPLv2
 
-USES=		gl gmake sdl tar:bzip2
+USES=		gl alias gmake sdl tar:bzip2
 USE_GL=		gl glu
 USE_SDL=	mixer sdl
 MAKE_ARGS=	OS=${OPSYS:tu}
