--- Makefile.orig	2019-12-06 19:11:29 UTC
+++ Makefile
@@ -18,7 +18,7 @@ BROKEN=		unfetchable
 
 LICENSE=	GPLv2
 
-USES=		gl gmake sdl tar:bzip2
+USES=		gl alias gmake sdl tar:bzip2
 USE_GL=		glu
 USE_SDL=	mixer sdl
 
@@ -48,7 +48,7 @@ post-patch: .SILENT
 .endif
 
 pre-build:
-	${ECHO_CMD} CC_ENVIRONMENT=1 OS=${OPSYS:tu} | \
+	${ECHO_CMD} CC_ENVIRONMENT=1 OS=FREEBSD | \
 		${XARGS} -n 1 >> ${BUILD_WRKSRC}/make_options
 	${MAKE_CMD} -C ${BUILD_WRKSRC} dirs
 	${MAKE_CMD} -C ${BUILD_WRKSRC} depend
