--- Makefile.orig	2012-11-17 06:00:10.000000000 +0000
+++ Makefile
@@ -1,9 +1,5 @@
-# New ports collection makefile for:	Net::CIDR::MobileJP
-# Date created:		19 Jul 2010
-# Whom:			Jun Kuriyama <kuriyama@FreeBSD.org>
-#
+# Created by: Jun Kuriyama <kuriyama@FreeBSD.org>
 # $FreeBSD: ports/net/p5-Net-CIDR-MobileJP/Makefile,v 1.5 2012/11/17 06:00:10 svnexp Exp $
-#
 
 PORTNAME=	Net-CIDR-MobileJP
 PORTVERSION=	0.24
@@ -17,7 +13,7 @@ COMMENT=	Perl extension for mobile IP ad
 RUN_DEPENDS=	\
 	p5-File-ShareDir>=1.02:${PORTSDIR}/devel/p5-File-ShareDir \
 	p5-Net-CIDR-Lite>=0.21:${PORTSDIR}/net/p5-Net-CIDR-Lite \
-	ja-p5-WWW-MobileCarrierJP>=0.55:${PORTSDIR}/japanese/p5-WWW-MobileCarrierJP \
+	p5-WWW-MobileCarrierJP>=0.55:${PORTSDIR}/japanese/p5-WWW-MobileCarrierJP \
 	p5-YAML>0:${PORTSDIR}/textproc/p5-YAML
 BUILD_DEPENDS:=	${RUN_DEPENDS}
 
