--- Makefile.orig	2015-12-30 21:10:29 UTC
+++ Makefile
@@ -48,7 +48,7 @@ post-patch:
 
 do-configure:
 	@(cd ${WRKSRC} && ${SETENV} MAITCHFLAGS="${MAITCHFLAGS}" \
-		${PYTHON_CMD} mscript.py configure)
+		${PYTHON_CMD} mscript.py configure --disable-gettext)
 
 do-build:
 	@(cd ${WRKSRC} && ${PYTHON_CMD} mscript.py build)
@@ -88,9 +88,5 @@ do-install-DOCS-on:
 .for i in AUTHORS ChangeLog README
 	(cd ${WRKSRC} && ${INSTALL_DATA} ${i} ${STAGEDIR}${DOCSDIR})
 .endfor
-.for i in en es fr lib pt_BR ru uk
-	@${MKDIR} ${STAGEDIR}${DOCSDIR}/${i}
-	(cd ${WRKSRC}/Help/${i} && ${INSTALL_DATA} * ${STAGEDIR}${DOCSDIR}/${i})
-.endfor
 
 .include <bsd.port.mk>
