--- Makefile.orig	2013-02-18 18:56:00.877382000 +0100
+++ Makefile	2013-02-18 18:56:39.015482000 +0100
@@ -30,10 +30,12 @@
 .include "../evas-core/Makefile.inc"
 CONFIGURE_ARGS+=	--enable-image-loader-png
 
+LDFLAGS+=	-L${LOCALBASE}/lib -levas
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/\.libs,${LOCALBASE}/lib,' \
-		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,-levas,' \
+		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,,' \
 		${MAKEDIRS:S,$,/Makefile.in,}
 
 do-build:
