--- Makefile.orig	2013-05-12 09:11:17.216502000 +0000
+++ Makefile
@@ -3,7 +3,7 @@
 
 PORTNAME=	aws
 PORTVERSION=	2.10.0
-PORTREVISION=	1
+PORTREVISION=	2
 CATEGORIES=	www
 MASTER_SITES=	http://downloads.dragonlace.net/src/
 
