--- Makefile.orig	2015-05-12 18:51:16 UTC
+++ Makefile
@@ -58,6 +58,7 @@ post-extract:
 	@${CHMOD} +x ${WRKSRC}/scripts/build/checkHtmlFileDates
 
 post-install:
+	${RMDIR} ${STAGEDIR}${PREFIX}/include/event2
 	@${MKDIR} ${STAGEDIR}${EXAMPLESDIR}
 	@${INSTALL_DATA} ${WRKSRC}/conf/* ${STAGEDIR}${EXAMPLESDIR}
 	@${MKDIR} ${STAGEDIR}${DOCSDIR}
