--- Makefile.orig	2020-05-27 21:31:20 UTC
+++ Makefile
@@ -49,7 +49,7 @@ do-build:
 
 do-install:
 .for GO_BIN_TARGET in ${GO_BIN_TARGETS}
-	${INSTALL_PROGRAM} ${GO_WRKSRC}/target/freebsd-${ARCH:S/^i//}/${GO_BIN_TARGET} ${STAGEDIR}${PREFIX}/bin
+	${INSTALL_PROGRAM} ${GO_WRKSRC}/target/${OPSYS:tl}-${ARCH:S/x86_64/amd64/}/${GO_BIN_TARGET} ${STAGEDIR}${PREFIX}/bin
 .endfor
 
 post-install-SENSU_AGENT-on:
