--- Makefile.orig	Tue Apr  1 21:46:26 2025
+++ Makefile	Tue Apr
@@ -32,7 +32,7 @@ PORTDOCS=	javadoc platform-${PORTVERSION}-javadoc.jar
 
 OPTIONS_DEFINE=	DOCS
 
-ANT_ARCH=	${ARCH:S/amd64/x86-64/:S/armv6/arm/:S/armv7/arm/:S/i386/x86/:S/powerpc/ppc/}
+ANT_ARCH=	${ARCH:S/amd64/x86-64/:S/armv6/arm/:S/armv7/arm/:S/i386/x86/:S/x86_64/x86-64/:S/powerpc/ppc/}
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|' \
@@ -42,7 +42,7 @@ post-build-DOCS-on:
 	cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} ${ANT} javadoc
 
 do-install:
-	${INSTALL_DATA} ${WRKSRC}/build/freebsd-${ANT_ARCH}.jar \
+	${INSTALL_DATA} ${WRKSRC}/build/dragonflybsd-${ANT_ARCH}.jar \
 		${STAGEDIR}${JAVAJARDIR}/jna-platform.jar
 	${INSTALL_DATA} ${WRKSRC}/build/jna.jar \
 		${STAGEDIR}${JAVAJARDIR}/jna.jar
