--- Makefile.orig	2018-11-22 03:13:31 UTC
+++ Makefile
@@ -35,7 +35,7 @@ TEST_TARGET=	test
 
 OPTIONS_DEFINE=	DOCS
 
-ANT_ARCH=	${ARCH:S/amd64/x86-64/:S/i386/x86/:S/powerpc64/ppc64/}
+ANT_ARCH=	${ARCH:S/amd64/x86-64/:S/i386/x86/:S/x86_64/x86-64/:S/powerpc64/ppc64/}
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|' \
@@ -45,7 +45,7 @@ post-build-DOCS-on:
 	cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} ${ANT} javadoc
 
 do-install:
-	${INSTALL_DATA} ${WRKSRC}/build/freebsd-${ANT_ARCH}.jar \
+	${INSTALL_DATA} ${WRKSRC}/build/${OPSYS:tl}-${ANT_ARCH}.jar \
 		${STAGEDIR}${JAVAJARDIR}/jna-platform.jar
 	${INSTALL_DATA} ${WRKSRC}/build/jna.jar \
 		${STAGEDIR}${JAVAJARDIR}/jna.jar
