--- Makefile.orig	2013-12-25 00:01:52.000000000 +0000
+++ Makefile
@@ -72,7 +72,7 @@ SCONS_TARGET=	core tools
 
 .include <bsd.port.pre.mk>
 
-.if ${OSVERSION} >= 1000024
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1000024
 EXTRA_PATCHES=	${PATCHDIR}/clang-patch-src_mongo_db_fts_stemmer.cpp \
 		${PATCHDIR}/clang-patch-src_mongo_platform_unordered_map.h \
 		${PATCHDIR}/clang-patch-src_mongo_platform_unordered_set.h \
