--- Makefile.orig	2013-04-14 11:52:47.200537000 +0000
+++ Makefile
@@ -12,7 +12,7 @@ COMMENT=	Fast, teachable, learning spam
 
 .if !defined(MASTERDIR) || ${MASTERDIR} == ${.CURDIR}
 # building master port
-USE_BDB=	41+
+USE_BDB=	44
 .endif
 
 OPTIONS_DEFINE=		GSL UNICODE
