--- Makefile.orig	2014-03-31 09:24:19.827551000 +0000
+++ Makefile
@@ -21,26 +21,9 @@ USE_PERL5=	build
 
 BUILD_DEPENDS=	p5-XML-Parser>=0:${PORTSDIR}/textproc/p5-XML-Parser
 
-# We cannot use ${ARCH} nor ${UNAME} which are defined in bsd.port.mk, here.
-UNAME?=		/usr/bin/uname
-ARCH!=		${UNAME} -p
-.if !defined(OSVERSION)
-AWK?=		/usr/bin/awk
-SYSCTL?=	/sbin/sysctl
-.if exists(/usr/include/sys/param.h)
-OSVERSION!=	${AWK} '/^\#define __FreeBSD_version/ {print $$3}' < /usr/include/sys/param.h
-.elif exists(/usr/src/sys/sys/param.h)
-OSVERSION!=	${AWK} '/^\#define __FreeBSD_version/ {print $$3}' < /usr/src/sys/sys/param.h
-.else
-OSVERSION!=	${SYSCTL} -n kern.osreldate
-.endif
-.endif
 
 OPTIONS_DEFINE=		DICT_RUBY EST MYSQL PYTHON RUBY UNIHAN
 OPTIONS_DEFAULT=	PYTHON
-.if ${ARCH} != "sparc64" && ${OSVERSION} < 700042
-OPTIONS_DEFAULT+=	UNIHAN
-.endif
 OPTIONS_SUB=		yes
 DICT_RUBY_DESC=		Enable Ruby based dictionary module
 DICT_RUBY_CONFIGURE_ENABLE=	dict-ruby
@@ -72,9 +55,6 @@ BROKEN=		Broken with gem version of glib
 .if ${OSVERSION} >= 700042
 BROKEN=		Broken with Unihan with gcc 4.2
 .endif
-.if ${ARCH} == "sparc64"
-BROKEN=	Not buildable with Unihan on sparc64
-.endif
 MASTER_SITES+=	ftp://ftp.unicode.org/Public/UNIDATA/:unihan
 DISTFILES+=	Unihan.zip:unihan
 EXTRACT_DEPENDS+=	${UNZIP_CMD}:${PORTSDIR}/archivers/unzip
