--- Makefile.orig	2018-04-27 13:59:10 UTC
+++ Makefile
@@ -16,7 +16,6 @@ RUN_DEPENDS=	bash:shells/bash
 
 CONFLICTS=	pfstmo-1.* pfscalibration-1.*
 
-LDFLAGS+=	-lthr
 
 USES=		cmake:outsource tar:tgz dos2unix jpeg perl5
 USE_PERL5=	run
