--- Makefile.orig	2021-07-04 01:18:27 UTC
+++ Makefile
@@ -17,7 +17,6 @@ RUN_DEPENDS=	bash:shells/bash
 CONFLICTS=	pfstmo-1.* pfscalibration-1.*
 
 CFLAGS+=	-I${LOCALBASE}/include/Imath
-LDFLAGS+=	-lthr
 
 USES=		cmake tar:tgz dos2unix jpeg perl5
 USE_PERL5=	run
