--- Makefile.orig	2017-05-07 02:49:34 UTC
+++ Makefile
@@ -42,12 +42,12 @@ HAS_CONFIGURE=	yes
 
 CONFIGURE_ENV=	CC=avr-gcc PREFIX=${PREFIX}
 .if ${PORT_OPTIONS:MDOXYGEN}
-CONFIGURE_ARGS=	--build=`./config.guess` --host=avr \
+CONFIGURE_ARGS=	--build=${CONFIGURE_TARGET} --host=avr \
 	--enable-doc --disable-versioned-doc --prefix=${PREFIX} \
 	--mandir=${PREFIX}/share/doc/avr-libc/man
 PLIST_DOC=	${PKGDIR}/pkg-plist.doc
 .else
-CONFIGURE_ARGS=	--build=`./config.guess` --host=avr --prefix=${PREFIX}
+CONFIGURE_ARGS=	--build=${CONFIGURE_TARGET} --host=avr --prefix=${PREFIX}
 PLIST_DOC=
 .endif
 
