--- Makefile.orig	2024-09-23 07:59:31 UTC
+++ Makefile
@@ -24,7 +24,7 @@ RUN_DEPENDS=	avr-as:devel/binutils@avr \
 USES=		gettext-tools gmake tar:bzip2
 
 HAS_CONFIGURE=	yes
-CONFIGURE_ARGS=	--build=`./config.guess` --host=avr --prefix=${PREFIX}
+CONFIGURE_ARGS=	--build=${CONFIGURE_TARGET} --host=avr --prefix=${PREFIX}
 CONFIGURE_ENV=	CC=avr-gcc PREFIX=${PREFIX}
 
 OPTIONS_DEFINE=	DOXYGEN
