--- Makefile.orig	2015-04-08 18:01:49 UTC
+++ Makefile
@@ -24,10 +24,6 @@ OPTIONS_DEFINE=	DOCS
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} == "i386" || ${ARCH} == "amd64"
-BUILD_DEPENDS=	yasm:${PORTSDIR}/devel/yasm
-.endif
-
 post-install:
 	cd ${WRKSRC}/src/MACLib && ${INSTALL_DATA} BitArray.h \
 		Prepare.h UnBitArrayBase.h ${STAGEDIR}${PREFIX}/include/mac
