--- Makefile.orig	2017-01-24 05:53:19 UTC
+++ Makefile
@@ -52,7 +52,7 @@ post-configure:
 	${REINPLACE_CMD} -e 's,tclstub,tcl,'	\
 		-e 's,-DPACKAGE_[^=]*=."[^"]*",,g' ${WRKSRC}/Makefile
 
-post-build test:
+test:
 	${SETENV} HOME=${WRKDIR} ${MAKE_CMD} -C ${WRKSRC} test | ${AWK} '\
 		/Failed/ && $$NF {failed=1}	\
 		END {exit failed}	\
