--- Makefile.orig	2013-03-24 22:50:56.000636000 +0000
+++ Makefile
@@ -100,8 +100,10 @@ CONFIGURE_ARGS+=	--without-iconv
 
 .if ${PORT_OPTIONS:MPERL}
 USE_PERL5=		yes
+.  if exists(${LOCALBASE}/bin/perl)
 PERL_ARCHNAME!=		perl -V:archname 2>/dev/null || true
 PLIST_SUB+=		WITH_PERL="" PERL_ARCHNAME="${PERL_ARCHNAME:S/archname='//:S/';//}"
+.  endif
 CONFIGURE_ARGS+=	--with-perl-lib=${PREFIX}/lib/${PORTNAME}/perl
 .else
 CONFIGURE_ARGS+=	--without-perl
