--- Makefile.orig	2013-05-07 18:15:35.022270000 +0000
+++ Makefile
@@ -65,6 +65,8 @@ CONFIGURE_ARGS+=	--disable-libical
 
 . if ! ${PORT_OPTIONS:MUSB}
 CONFIGURE_ARGS+=	--disable-libusb
+.else
+USES+= usb
 .endif
 
 .if ${PORT_OPTIONS:MPCSC}
