--- Makefile.orig	Fri Mar 28 19:36:39 2025
+++ Makefile	Fri Mar
@@ -23,6 +23,7 @@ USE_QT=		buildtools:build concurrent core dbus declara
 		quickcontrols2 sql svg websockets widgets xml
 
 CMAKE_ARGS=	-DBUILD_UPDATER:BOOL=OFF \
+		-DCMAKE_INSTALL_MANDIR:STRING=share/man \
 		-DWITH_STACK_PROTECTOR:BOOL=OFF
 
 PLIST_SUB=	VERSION=${PORTVERSION}
