--- a/deskutils/nextcloudclient/Makefile
+++ b/deskutils/nextcloudclient/Makefile
@@ -23,7 +23,6 @@ USE_QT=               buildtools:build concurrent core dbus declarative graphicaleffects \
                quickcontrols2 sql svg websockets widgets xml

 CMAKE_ARGS=    -DBUILD_UPDATER:BOOL=OFF \
-               -DCMAKE_INSTALL_MANDIR:STRING=man \
                -DWITH_STACK_PROTECTOR:BOOL=OFF

 PLIST_SUB=     VERSION=${PORTVERSION}
