--- Makefile.orig	2024-02-24 12:15:50 UTC
+++ Makefile
@@ -27,21 +27,10 @@ DOCS_INFO=		chpp
 
 .include <bsd.port.pre.mk>
 
-post-extract:
-.for i in getopt.h regex.h gc/gc.h
-	@cd ${WRKSRC} && ${MV} -f ${i} ${i}.dist
-.endfor
-
 post-patch:
 	@${REINPLACE_CMD} -e \
-		's| getopt.c getopt.h getopt1.c | | ; \
-		 s| regex.c regex.h | | ; \
-		 /LDADD/s| gc/gc.a | -lgc -lgnuregex | ; \
+		 '/LDADD/s| gc/gc.a | -lgc -lgnuregex | ; \
 		 s|^YFLAGS|AM_YFLAGS|' ${WRKSRC}/Makefile.am
-.for i in arrayops.c stringops.c
-	@${REINPLACE_CMD} -e \
-		's|"../regex.h"|<gnu/regex.h>|' ${WRKSRC}/builtins/${i}
-.endfor
 
 post-patch-DOCS-off:
 	@${REINPLACE_CMD} -e \
