--- Makefile.orig	2013-03-19 13:04:30.000000000 +0000
+++ Makefile
@@ -7,7 +7,7 @@
 PORTNAME=	cmph
 PORTVERSION=	2.0
 CATEGORIES=	devel
-MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTNAME}-${PORTVERSION}
+MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/
 
 MAINTAINER=	jessekempf@gmail.com
 COMMENT=	Minimal perfect hashes for C
