--- Makefile.orig	2016-04-10 12:05:14 UTC
+++ Makefile
@@ -46,7 +46,11 @@ JAVA_ARCH = ${ARCH}
 do-build:
 	${MKDIR} ${WRKDIR}/snappy/org/xerial/snappy/native/${OPSYS}/${JAVA_ARCH}
 	${CP} ${LOCALBASE}/lib/libsnappyjava.so ${WRKDIR}/snappy/org/xerial/snappy/native/${OPSYS}/${JAVA_ARCH}
-	cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} ${LOCALBASE}/share/java/maven33/bin/mvn --offline -Dmaven.repo.local=${WRKDIR}/m2 clean package -Dhadoop.version=2.7.2 -Pyarn -Phadoop-2.6 -DskipTests
+	cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} \
+		${LOCALBASE}/share/java/maven33/bin/mvn --offline \
+		-Dmaven.repo.local=${WRKDIR}/m2 clean package \
+		-Dhadoop.version=2.7.2 -Pyarn -Phadoop-2.6 -DskipTests \
+		-Duser.home=${WRKDIR}
 	${JAR} uvf ${WRKSRC}/assembly/target/scala*/*assembly*hadoop*.jar -C ${WRKDIR}/snappy org
 
 post-build:
