# for now, disabled Firebird SQL support.  It emits
# z->z_Magic == ZALLOC_SLAB_MAGIC in _slabfree when running
# the CppunitTest_dbaccess_firebird_test unit test
CONFIGURE_ARGS+=	--disable-firebird-sdbc

CONFIGURE_ARGS+=	--with-os-version=${DFLYVERSION} \
			--with-vendor="DragonFly dports"

REPLACE_LIST= \
	external/curl/ExternalProject_curl.mk \
	external/liblangtag/ExternalProject_langtag.mk \
	external/libxmlsec/ExternalProject_xmlsec.mk \
	external/libxslt/ExternalProject_xslt.mk \
	external/nss/ExternalProject_nss.mk \
	external/openssl/ExternalProject_openssl.mk \
	external/redland/ExternalProject_raptor.mk \
	external/redland/ExternalProject_rasqal.mk \
	external/redland/ExternalProject_redland.mk \
	include/osl/endian.h \
	registry/workben/makefile.mk \
	sal/osl/unx/system.cxx \
	sc/Module_sc.mk \
	solenv/bin/modules/installer/parameter.pm \
	soltools/mkdepend/main.c \
	stoc/source/corereflection/criface.cxx \
	sw/Module_sw.mk \
	vcl/qa/cppunit/BitmapTest.cxx \
	vcl/unx/generic/app/saldata.cxx \
	vcl/unx/generic/dtrans/X11_selection.cxx \
	vcl/unx/generic/gdi/salbmp.cxx \
	vcl/unx/generic/printer/printerinfomanager.cxx \
	vcl/unx/kde/kdedata.cxx \
	desktop/unx/source/start.c \
	jvmfwk/plugins/sunmajor/pluginlib/sunversion.cxx \
	jvmfwk/plugins/sunmajor/pluginlib/sunversion.hxx \
	sal/osl/unx/process_impl.cxx \
	sal/osl/unx/sockimpl.hxx \
	sal/osl/unx/pipe.cxx \
	vcl/unx/gtk3/gtk3gtkdata.cxx \
	vcl/unx/gtk/gtkdata.cxx

# Avoid stripping in /tmp, it takes too much space for poudriere
# Also, ooinstall is fed wrong TMPDIR which is redefined a few times
# So let's just hardcode it for now

dfly-patch:
	${REINPLACE_CMD} -e 's|$$ENV{TMPDIR};|"${WRKDIR}";|' \
		${WRKSRC}/solenv/bin/ooinstall
	(cd ${WRKSRC} && \
		${REINPLACE_CMD} -e 's|FREEBSD|DRAGONFLY|' ${REPLACE_LIST})
.for F in ${REPLACE_LIST}
	@/usr/bin/cmp -s ${WRKSRC:Q}/${F} ${WRKSRC:Q}/${F}.bak && \
		echo "${F} was not altered" || /usr/bin/true
.endfor
