--- Makefile.orig	2019-12-24 15:50:26 UTC
+++ Makefile
@@ -12,7 +12,7 @@ LICENSE=	GPLv3
 LICENSE_FILE=	${WRKSRC}/LICENSE.md
 
 LIB_DEPENDS=	libGraphicsMagick++.so:graphics/GraphicsMagick \
-		libomp.so:devel/openmp
+
 
 USES=		compiler:c++17-lang desktop-file-utils gl qmake qt:5 localbase pkgconfig
 USE_GITHUB=	yes
@@ -20,6 +20,6 @@ USE_QT=		core gui network printsupport w
 USE_GL=		gl
 
 CXXFLAGS+=	`pkg-config --cflags GraphicsMagick++`
-LDFLAGS+=	`pkg-config --libs GraphicsMagick++` ${LOCALBASE}/lib/libomp.so
+LDFLAGS+=	`pkg-config --libs GraphicsMagick++`
 
 .include <bsd.port.mk>
