--- Makefile.orig	2013-11-05 18:56:59.831363000 +0000
+++ Makefile
@@ -119,12 +119,6 @@ XPI_ID=		lightning@seamonkey.mozilla.org
 MOZ_OPTIONS+=	--disable-calendar
 .endif
 
-.if ${PORT_OPTIONS:MMAILNEWS} && ${PORT_OPTIONS:MENIGMAIL}
-post-extract:
-	@${TAR} -xf ${_DISTDIR}/${EM_DISTFILE} \
-		-C ${WRKSRC}/mailnews/extensions
-.endif
-
 post-patch:
 	@${REINPLACE_CMD} -e '/MOZPNG/s/=[0-9]*/=10511/' \
 		${MOZSRC}/configure.in ${WRKSRC}/configure.in
@@ -136,6 +130,8 @@ post-patch:
 		< ${FILESDIR}/seamonkey.desktop.in > \
 		${WRKDIR}/${MOZILLA}.desktop
 .if ${PORT_OPTIONS:MMAILNEWS} && ${PORT_OPTIONS:MENIGMAIL}
+	@${TAR} -xf ${_DISTDIR}/${EM_DISTFILE} \
+		-C ${WRKSRC}/mailnews/extensions
 	@${REINPLACE_CMD} -e 's,/usr/bin/perl,${PERL},' \
 		${WRKSRC}/mailnews/extensions/enigmail/makemake
 	@${REINPLACE_CMD} -e '/^xpi/s/$$/ all/' \
