--- Makefile.orig	2013-05-09 22:22:09.957066000 +0000
+++ Makefile
@@ -38,7 +38,7 @@ MAN3=		Itcl_RegisterC.3 Itcl_Stack.3 Itc
 .include <bsd.port.pre.mk>
 
 post-patch:
-	${REINPLACE_CMD} -r '/^includedir/s|/include|/include/itcl${PORTVERSION:R}|' \
+	${REINPLACE_CMD} -E '/^includedir/s|/include|/include/itcl${PORTVERSION:R}|' \
 	    ${WRKSRC}/${CONFIGURE_SCRIPT}
 
 post-build test:
