--- Makefile.orig	2014-03-30 08:06:33.296258000 +0000
+++ Makefile
@@ -34,9 +34,6 @@ CONFIGURE_ARGS=	--disable-nautilus
 PORTDOCS=	AUTHORS COPYING ChangeLog INSTALL NEWS README \
 		dbus.txt keyboard_shortcuts.txt plugin-interaction.txt
 
-GLIB_SCHEMAS=	apps.gecko-mediaplayer.preferences.gschema.xml \
-		apps.gnome-mplayer.preferences.enums.xml \
-		apps.gnome-mplayer.preferences.gschema.xml
 
 .include <bsd.port.options.mk>
 
