--- Makefile.orig	2014-02-10 09:19:05.839611000 +0000
+++ Makefile
@@ -21,8 +21,10 @@ USE_XZ=		yes
 USE_PYTHON=	2
 USE_LDCONFIG=	yes
 ALL_TARGET=	native
-MAKE_ARGS=	library=shared
+MAKE_ENV+=	GYPFLAGS=-DOS=freebsd
+MAKE_ENV+=	library=shared
 MAKE_ENV+=	CC.host=${CC} CXX.host=${CXX} LINK.host=${CXX} LINK.target=${CXX}
+CFLAGS+=	-D__FreeBSD__=1
 
 .include <bsd.port.pre.mk>
 
