--- Makefile.orig	2013-03-09 22:25:12.399299000 +0000
+++ Makefile
@@ -17,18 +17,11 @@ USE_XZ=		yes
 USE_PYTHON=	2.6+
 USE_LDCONFIG=	yes
 ALL_TARGET=	native
-MAKE_ARGS=	library=shared
+MAKE_ENV+=	GYPFLAGS=-DOS=freebsd
+MAKE_ENV+=	library=shared
+USE_GCC=	4.7
 
 .include <bsd.port.pre.mk>
-
-.if ${CC:T:Mclang} == "clang" || ${CXX:T:Mclang++} == "clang++" || ${OSVERSION} >= 1000024
-MAKE_ENV+=	LINK=clang++
-CFLAGS+=	-Wno-unused-private-field
-.else
-MAKE_ARGS+=	strictaliasing=off
-USE_GCC=	any
-.endif
-
 ONLY_FOR_ARCHS=	i386 amd64
 
 post-patch:
