--- Makefile.orig	2013-03-17 21:46:59.592438000 +0000
+++ Makefile
@@ -25,7 +25,7 @@ MAKE_ARGS=	CC="${CC}" \
 		CFLAGS="${CFLAGS}" \
 		INCDIR="`pkg-config --cflags gtk+-2.0` -I${LOCALBASE}/include" \
 		LIBDIR="" \
-		LIBS="-lical -lXpm"
+		LIBS="-lical -lXpm -lm"
 CPPFLAGS+=	-I${LOCALBASE}/include
 LDFLAGS+=	-L${LOCALBASE}/lib
 
