--- Makefile.orig	2013-03-08 23:13:09.025426000 +0000
+++ Makefile
@@ -16,12 +16,10 @@ COMMENT=	Qt graphical frontend for dvdau
 
 BUILD_DEPENDS=	dvdauthor:${PORTSDIR}/multimedia/dvdauthor \
 		mpeg2enc:${PORTSDIR}/multimedia/mjpegtools \
-		dvd-slideshow:${PORTSDIR}/multimedia/dvd-slideshow \
 		qmake:${PORTSDIR}/devel/qmake
 
 RUN_DEPENDS=	dvdauthor:${PORTSDIR}/multimedia/dvdauthor \
 		mpeg2enc:${PORTSDIR}/multimedia/mjpegtools \
-		dvd-slideshow:${PORTSDIR}/multimedia/dvd-slideshow \
 		dv2sub:${PORTSDIR}/multimedia/dv2sub \
 		bash:${PORTSDIR}/shells/bash
 
@@ -29,13 +27,10 @@ DATA_FILES=	silence.mp2 html/en/audio_st
 		qdvdauthor_ca.qm qdvdauthor_de.qm qdvdauthor_eo.qm \
 		qdvdauthor_es.qm qdvdauthor_fr.qm qdvdauthor_it.qm \
 		qdvdauthor_pl.qm qplayer_ca.qm qplayer_de.qm \
-		qplayer_es.qm qplayer_fr.qm qslideshow_ca.qm \
-		qslideshow_de.qm qslideshow_es.qm qslideshow_fr.qm \
-		qslideshow_it.qm qrender_ca.qm qrender_de.qm \
+		qplayer_es.qm qplayer_fr.qm qrender_ca.qm qrender_de.qm \
 		qrender_es.qm
 
 PLIST_FILES=	bin/qdvdauthor \
-		bin/qslideshow \
 		bin/qplayer \
 		bin/qrender \
 		share/pixmaps/qdvdauthor.png \
@@ -54,7 +49,7 @@ USE_QT_VER=	3
 QT_NONSTANDARD=	yes
 CONFIGURE_ENV=	QMAKESPEC=${LOCALBASE}/share/qt/mkspecs/freebsd-g++
 CONFIGURE_ARGS=	--prefix=${PREFIX} --qt-dir=${LOCALBASE} --with-qt-lib=qt-mt \
-		--build-qslideshow --build-qplayer
+		--build-qplayer
 NO_BUILD=	yes
 
 OPTIONS=	NETPBM "Create mpeg2 streams for movie menus" on \
@@ -125,7 +120,6 @@ RUN_DEPENDS+=	mctoolame:${PORTSDIR}/audi
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/bin/qdvdauthor ${PREFIX}/bin/qdvdauthor
-	${INSTALL_PROGRAM} ${WRKSRC}/bin/qslideshow ${PREFIX}/bin/qslideshow
 	${INSTALL_PROGRAM} ${WRKSRC}/bin/qplayer    ${PREFIX}/bin/qplayer
 	${INSTALL_PROGRAM} ${WRKSRC}/bin/qrender    ${PREFIX}/bin/qrender
 
@@ -144,9 +138,7 @@ do-install:
 .endfor
 .for locale in ca de es fr
 	${INSTALL_DATA} ${WRKSRC}/qdvdauthor/i18n/qplayer_${locale}.qm     ${DATADIR}
-	${INSTALL_DATA} ${WRKSRC}/qdvdauthor/i18n/qslideshow_${locale}.qm  ${DATADIR}
 .endfor
-	${INSTALL_DATA} ${WRKSRC}/qdvdauthor/i18n/qslideshow_it.qm  ${DATADIR}
 .for locale in ca de es
 	${INSTALL_DATA} ${WRKSRC}/qdvdauthor/i18n/qrender_${locale}.qm  ${DATADIR}
 .endfor
