--- Makefile.orig	2013-08-13 09:42:30.380185000 +0000
+++ Makefile
@@ -26,7 +26,7 @@ RUBYGEM_AUTOPLIST=	yes
 .include <bsd.port.options.mk>
 
 .if ${PORT_OPTIONS:MAPACHE22}
-USE_APACHE_RUN=	22+
+USE_APACHE=	22+
 .endif
 
 .if ${PORT_OPTIONS:MNGINX}
