--- Makefile.orig	2021-02-12 09:56:47 UTC
+++ Makefile
@@ -103,8 +103,8 @@ post-install:
 	${LN} -sf ../../${GEM_LIB_DIR}/buildout/apache2/mod_passenger.so ${STAGEDIR}${PREFIX}/${APACHEMODDIR}/mod_passenger.so
 	@${ECHO} "${APACHEMODDIR}/mod_passenger.so" >> ${TMPPLIST}
 .endif
-	@${RM} ${STAGEDIR}${PREFIX}/${GEM_LIB_DIR}/bin/passenger-install-apache2-module \
-		${STAGEDIR}${PREFIX}/${GEM_LIB_DIR}/bin/passenger-install-nginx-module
+	@${RM} ${STAGEDIR}${PREFIX}/bin/passenger-install-apache2-module \
+		${STAGEDIR}${PREFIX}/bin/passenger-install-nginx-module
 
 post-install-SYMLINK-on:
 	${LN} -s ${GEM_NAME} ${STAGEDIR}${PREFIX}/${GEMS_DIR}/${PORTNAME}
