--- Makefile.orig	2013-11-12 10:12:36.720242000 +0000
+++ Makefile
@@ -29,8 +29,5 @@ INSTALLS_ICONS=	yes
 MAKE_ARGS+=	PREFIX=${PREFIX}
 MAKE_ENV+=	MANDIR=${STAGEDIR}${MANPREFIX}/man
 
-post-patch:
-	@${REINPLACE_CMD} -e 's,/dev/modem,/dev/cuaU0,g' \
-		${WRKSRC}/src/modems/hayes.c
 
 .include <bsd.port.mk>
