--- Makefile.orig	2014-04-17 12:16:06.570567000 +0000
+++ Makefile
@@ -32,7 +32,7 @@ MAKE_ARGS+=		INSTALL_SHARED="${INSTALL_L
 MAKE_ARGS+=		LIBPC="${PREFIX}/libdata/pkgconfig"			# Until pathfix gets support for files other than Makefile.in
 
 PLIST_SUB=		VER=${PYTHON_VER} ABI=${ABIFLAGS} XY=${PYTHON_SUFFIX} \
-			OSMAJOR=${OSVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
+			OSMAJOR=${DFLYVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
 
 OPTIONS_DEFINE=		DEBUG IPV6 NLS PYMALLOC THREADS TSC
 OPTIONS_DEFAULT=	IPV6 NLS PYMALLOC THREADS
