--- Makefile.orig	2016-04-09 11:12:05 UTC
+++ Makefile
@@ -12,7 +12,7 @@ COMMENT=	Convert CVS module to darcs rep
 
 LICENSE=	GPLv2
 
-BUILD_DEPENDS=	cvs:devel/cvs \
+BUILD_DEPENDS=	\
 		darcs:devel/hs-darcs \
 		cvsps:devel/cvsps \
 		p5-libwww>=0:www/p5-libwww
