--- Makefile.orig	2013-07-28 19:48:40.000000000 +0000
+++ Makefile
@@ -12,8 +12,7 @@ COMMENT=	Convert CVS module to darcs rep
 
 LICENSE=	GPLv2
 
-BUILD_DEPENDS=	cvs:${PORTSDIR}/devel/cvs \
-		darcs:${PORTSDIR}/devel/hs-darcs \
+BUILD_DEPENDS=	darcs:${PORTSDIR}/devel/hs-darcs \
 		cvsps:${PORTSDIR}/devel/cvsps \
 		p5-libwww>=0:${PORTSDIR}/www/p5-libwww
 RUN_DEPENDS:=	${BUILD_DEPENDS}
