--- Makefile.orig	2013-10-16 23:44:35.264463000 +0000
+++ Makefile
@@ -87,6 +87,7 @@ do-install:
 	    ${WRKSRC}/popa3d ${STAGEDIR}${PREFIX}/libexec/popa3d
 	${INSTALL_MAN} ${WRKSRC}/popa3d.8 ${STAGEDIR}${MANPREFIX}/man/man8/
 .if ${PORT_OPTIONS:MSMTP_AFTER_POP3} && !defined(WITHOUT_POPAUTH_M4)
+	mkdir -p ${CFDIR}/hack
 	${INSTALL_DATA} ${FILESDIR}/popauth.m4 ${STAGEDIR}${CFDIR}/hack/
 .endif
 
@@ -99,10 +100,6 @@ do-install:
 .endif
 .endif
 
-.if exists(${LOCALBASE}/share/sendmail/cf/mailer/uucp.m4)
 CFDIR=		${LOCALBASE}/share/sendmail/cf
-.else
-CFDIR=		/usr/share/sendmail/cf
-.endif
 
 .include <bsd.port.post.mk>
