--- Makefile.orig	2013-10-16 23:44:35.264463000 +0000
+++ Makefile
@@ -99,10 +99,6 @@ do-install:
 .endif
 .endif
 
-.if exists(${LOCALBASE}/share/sendmail/cf/mailer/uucp.m4)
 CFDIR=		${LOCALBASE}/share/sendmail/cf
-.else
-CFDIR=		/usr/share/sendmail/cf
-.endif
 
 .include <bsd.port.post.mk>
