--- Makefile.orig	2012-12-03 14:15:05.000000000 +0100
+++ Makefile	2012-12-10 18:19:09.212327000 +0100
@@ -32,7 +32,7 @@
 
 .include <bsd.port.pre.mk>
 
-JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.? -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1
+JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.? -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1 ; echo
 .if ${JDK_API} != ""
 MAKE_ARGS+=	-Djavadoc.links=${JDK_API}
 .endif
