--- Makefile.orig	2013-01-26 11:12:54.161216000 +0100
+++ Makefile	2013-01-26 11:13:06.561233000 +0100
@@ -8,6 +8,7 @@
 PORTVERSION=	9.4.2
 PORTREVISION=	1
 CATEGORIES=	french print linux
+PKGNAMEPREFIX=	fr-
 
 MASTERDIR=	${.CURDIR}/../../print/acroread9
 DISTINFO_FILE=	${.CURDIR}/distinfo
