--- Makefile.orig	2013-10-20 19:51:30.987212000 +0000
+++ Makefile
@@ -23,5 +23,5 @@ NPAPI_WRKSRC=	${WRKSRC}/src/.libs
 NPAPI_FILES=	xineplugin.so
 
 NO_STAGE=	yes
-.include "${.CURDIR}/../linux-mplayer-plugin/Makefile.npapi"
+.include "${.CURDIR}/../../Mk/bsd.npapi.mk"
 .include <bsd.port.mk>
