--- sockets_arginfo.h.orig	2026-07-28 13:06:52 UTC
+++ sockets_arginfo.h
@@ -412,11 +412,19 @@ static void register_sockets_symbols(int module_number
 	REGISTER_LONG_CONSTANT("SO_BINDTOIFINDEX", SO_BINDTOIFINDEX, CONST_PERSISTENT);
 #endif
 #if defined(SO_USER_COOKIE)
+	REGISTER_LONG_CONSTANT("SO_USER_COOKIE", SO_USER_COOKIE, CONST_PERSISTENT);
+#endif
+#if defined(SO_LABEL)
 	REGISTER_LONG_CONSTANT("SO_LABEL", SO_LABEL, CONST_PERSISTENT);
+#endif
+#if defined(SO_PEERLABEL)
 	REGISTER_LONG_CONSTANT("SO_PEERLABEL", SO_PEERLABEL, CONST_PERSISTENT);
+#endif
+#if defined(SO_LISTENQLIMIT)
 	REGISTER_LONG_CONSTANT("SO_LISTENQLIMIT", SO_LISTENQLIMIT, CONST_PERSISTENT);
+#endif
+#if defined(SO_LISTENQLEN)
 	REGISTER_LONG_CONSTANT("SO_LISTENQLEN", SO_LISTENQLEN, CONST_PERSISTENT);
-	REGISTER_LONG_CONSTANT("SO_USER_COOKIE", SO_USER_COOKIE, CONST_PERSISTENT);
 #endif
 #if defined(SO_SETFIB)
 	REGISTER_LONG_CONSTANT("SO_SETFIB", SO_SETFIB, CONST_PERSISTENT);
