--- Makefile.orig	2017-01-04 15:53:10 UTC
+++ Makefile
@@ -27,7 +27,7 @@ NO_WRKSUBDIR=	yes
 
 PLIST_FILES=	sbin/MegaCli
 
-MEGACLI_ARCH=	MegaCli${ARCH:S/i386//:S/amd64/64/}
+MEGACLI_ARCH=	MegaCli${ARCH:S/i386//:S/amd64/64/:S/x86_64/64/}
 
 post-extract:
 	@${MV} ${WRKSRC}/FreeBSD/MegaCLI.zip ${WRKSRC}/FreeBSD/MegaCli.zip
