--- Makefile.orig	2013-12-24 23:17:59.110326000 +0000
+++ Makefile
@@ -22,7 +22,7 @@ NO_WRKSUBDIR=	yes
 
 PLIST_FILES=	sbin/MegaCli
 
-MEGACLI_ARCH=	MegaCli${ARCH:S/i386//:S/amd64/64/}
+MEGACLI_ARCH=	MegaCli${ARCH:S/i386//:S/amd64/64/:S/x86_64/64/}
 
 post-extract:
 	@${MV} ${WRKSRC}/freebsd/MegaCLI.zip ${WRKSRC}/freebsd/MegaCli.zip
