--- Makefile.orig	2013-03-18 18:18:40.676352000 +0000
+++ Makefile
@@ -25,12 +25,7 @@ PORTDOCS=	CHANGELOG CREDITS README
 
 .include <bsd.port.options.mk>
 
-# more fully-featured rar needs i386
-.if ${ARCH} == "i386"
-RUN_DEPENDS+=	rar:${PORTSDIR}/archivers/rar
-.else
 RUN_DEPENDS+=	unrar:${PORTSDIR}/archivers/unrar
-.endif
 
 post-install:
 	@if [ ! -f ${PREFIX}/etc/hellanzb.conf ]; then \
