--- Makefile.orig	2016-04-06 16:30:38 UTC
+++ Makefile
@@ -27,12 +27,7 @@ OPTIONS_DEFINE=	DOCS
 
 .include <bsd.port.options.mk>
 
-# more fully-featured rar needs i386
-.if ${ARCH} == "i386"
-RUN_DEPENDS+=	rar:archivers/rar
-.else
 RUN_DEPENDS+=	unrar:archivers/unrar
-.endif
 
 post-install-DOCS-on:
 	@${MKDIR} ${STAGEDIR}${DOCSDIR}
