--- Makefile.orig	2013-01-15 17:46:00.000000000 +0000
+++ Makefile
@@ -26,10 +26,12 @@ MAKEDIRS=	${WRKSRC}/src/modules/loaders/
 .include "../evas-core/Makefile.inc"
 CONFIGURE_ARGS+=	--enable-image-loader-wbmp
 
+LDFLAGS+=	-l${LOCALBASE}/lib -levas
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/\.libs,${LOCALBASE}/lib,' \
-		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,-levas,' \
+		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,,' \
 		${MAKEDIRS:S,$,/Makefile.in,}
 
 do-build:
