--- Makefile.orig	2013-10-13 18:14:51.597481000 +0000
+++ Makefile
@@ -34,7 +34,7 @@ USES+=		gmake
 # KMS support in the kernel is only build on these archs, disable others
 .if ${ARCH} == "amd64" || ${ARCH} == "i386"
 CONFIGURE_ARGS+=--enable-libkms
-EXTRA_PATCHES+=	${FILESDIR}/extra-xf86drmMode.c
+EXTRA_PATCHES+=	${DFLY_FILESDIR}/extra-xf86drmMode.c
 PLIST_SUB+=	KMS="" NOUVEAU=""
 .else
 CONFIGURE_ARGS+=--disable-libkms
@@ -81,8 +81,7 @@ PLIST_SUB+=	RADEON_DRIVERS="@comment "
 .endif
 
 pre-patch:
-	@${REINPLACE_CMD} 's|{libdir}/pkgconfig|{prefix}/libdata/pkgconfig|g; \
-			   s,i?86|x86_64),i?86|amd64|x86_64),g' \
+	@${REINPLACE_CMD} 's|{libdir}/pkgconfig|{prefix}/libdata/pkgconfig|g;' \
 		${WRKSRC}/configure
 
 .include <bsd.port.mk>
