--- Makefile.orig	2014-08-02 08:56:45.492704000 +0000
+++ Makefile
@@ -77,8 +77,7 @@ PLIST_SUB+=	RADEON_DRIVERS="@comment "
 .endif
 
 pre-patch:
-	@${REINPLACE_CMD} 's|{libdir}/pkgconfig|{prefix}/libdata/pkgconfig|g; \
-			   s,i?86|x86_64),i?86|amd64|x86_64),g' \
+	@${REINPLACE_CMD} 's|{libdir}/pkgconfig|{prefix}/libdata/pkgconfig|g;' \
 		${WRKSRC}/configure
 
 post-install:
