--- Makefile.orig	2014-10-20 15:21:33 UTC
+++ Makefile
@@ -61,8 +61,7 @@ PLIST_SUB+=	RADEON_DRIVERS="@comment "
 .endif
 
 pre-patch:
-	@${REINPLACE_CMD} 's|{libdir}/pkgconfig|{prefix}/libdata/pkgconfig|g; \
-			   s,i?86|x86_64),i?86|amd64|x86_64),g' \
+	@${REINPLACE_CMD} 's|{libdir}/pkgconfig|{prefix}/libdata/pkgconfig|g;' \
 		${WRKSRC}/configure
 
 .include <bsd.port.mk>
