--- Makefile.orig	2013-02-18 19:38:25.453101000 +0100
+++ Makefile	2013-02-18 19:39:21.720592000 +0100
@@ -87,12 +87,14 @@
 WITH_X11=	yes
 .endif
 
+LDFLAGS+=	-L${LOCALBASE}/lib -lecore
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/ecore/\.libs,${LOCALBASE}/lib,'\
 		-e 's,\$$\(top_builddir\)/src/lib/ecore_input/\.libs,${LOCALBASE}/lib,'\
-		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,-lecore,'\
-		-e 's,\$$\(top_builddir\)/src/lib/ecore_input/libecore_input\.la,-lecore_input,'\
+		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,,'\
+		-e 's,\$$\(top_builddir\)/src/lib/ecore_input/libecore_input\.la,,'\
 		${BUILD_WRKSRC}/Makefile.in \
 		${BUILD_WRKSRC}/xcb/Makefile.in \
 		${BUILD_WRKSRC}/xlib/Makefile.in
