--- Makefile.orig	2013-10-18 22:32:13.000000000 +0000
+++ Makefile
@@ -29,7 +29,7 @@ post-patch:
 do-build:
 	cd ${WRKSRC} && ${CC} ${CFLAGS} main.cpp -o ${PORTNAME} \
 		`${SDL_CONFIG} --cflags --libs` -lSDL_ttf -lSDL_mixer \
-		-lSDL_image -lGL -lGLU
+		-lSDL_image -lGL -lGLU -lm -lstdc++
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/${PORTNAME} ${STAGEDIR}${PREFIX}/bin
