--- Makefile.orig	2020-06-28 18:44:21 UTC
+++ Makefile
@@ -113,7 +113,7 @@ PORTDOCS=	*
 
 .include <bsd.port.options.mk>
 
-ARCHOS_PATTERN=	*-${ARCH:S/amd64/x86-64/:S/i386/x86/}-${OPSYS:tl}*
+ARCHOS_PATTERN=	*-${ARCH:S/amd64/x86-64/:S/i386/x86/:S/x86_64/x86-64/}-${OPSYS:tl}*
 BOOT_WRKSRC=	${WRKDIR}/${PORTNAME}-${SBCL_BOOT_LIST:M${ARCHOS_PATTERN}}
 
 # for port maintenance, invoke "make makesum PLUS_BOOTSTRAPS=1"
@@ -126,7 +126,7 @@ DISTFILES:=	${DISTFILES} ${PORTNAME}-${B
 .endif
 
 # Old FreeBSD bootstraps feature the older core name for SBCL bootstrap
-.if ${OPSYS} == FreeBSD
+.if ${OPSYS} == FreeBSD || ${OPSYS} == DragonFly
 CORE=	sbcl.core
 .else
 CORE=	sbcl_core
