--- Makefile.orig	2020-07-21 11:25:36.830243000 +0200
+++ Makefile	2020-07-21 11:27:19.870415000 +0200
@@ -53,7 +53,7 @@
 
 # All options explained into file: ${WRKSRC}/base-target-features.lisp-expr
 OPTIONS_DEFINE=	DOCS QSHOW RENAME SAFEPOINT THREADS UNICODE XREF ZLIB
-OPTIONS_DEFAULT=	RENAME SBCL THREADS UNICODE
+OPTIONS_DEFAULT=	RENAME SBCL UNICODE
 
 QSHOW_DESC=	C runtime with low-level debugging output
 RENAME_DESC=	Rename suffix .core to _core
@@ -113,7 +113,7 @@
 
 .include <bsd.port.options.mk>
 
-ARCHOS_PATTERN=	*-${ARCH:S/amd64/x86-64/:S/i386/x86/}-${OPSYS:tl}*
+ARCHOS_PATTERN=	*-${ARCH:S/amd64/x86-64/:S/i386/x86/:S/x86_64/x86-64/}-${OPSYS:tl}*
 BOOT_WRKSRC=	${WRKDIR}/${PORTNAME}-${SBCL_BOOT_LIST:M${ARCHOS_PATTERN}}
 
 # for port maintenance, invoke "make makesum PLUS_BOOTSTRAPS=1"
@@ -126,7 +126,7 @@
 .endif
 
 # Old FreeBSD bootstraps feature the older core name for SBCL bootstrap
-.if ${OPSYS} == FreeBSD
+.if ${OPSYS} == FreeBSD || ${OPSYS} == DragonFly
 CORE=	sbcl.core
 .else
 CORE=	sbcl_core
