--- Makefile.orig	2019-02-28 12:43:56 UTC
+++ Makefile
@@ -16,6 +16,7 @@ MASTERDIR=	${.CURDIR}/../percona57-serve
 PKGMESSAGE=	${.CURDIR}/pkg-message
 PATCHDIR=	${MASTERDIR}/files
 FILESDIR=	${.CURDIR}/files
+DFLY_PATCHDIR=	${.CURDIR}/dragonfly
 PLIST=		${.CURDIR}/pkg-plist
 DESCR=		${.CURDIR}/pkg-descr
 
