--- Makefile.orig	2012-12-03 13:19:58.000000000 +0000
+++ Makefile
@@ -5,7 +5,7 @@
 # $FreeBSD: ports/textproc/ocaml-tyxml/Makefile,v 1.2 2012/11/17 06:02:03 svnexp Exp $
 
 PORTNAME=	tyxml
-PORTVERSION=	2.0.1
+PORTVERSION=	2.2.0
 CATEGORIES=	textproc
 MASTER_SITES=	http://ocsigen.org/download/
 PKGNAMEPREFIX=	ocaml-
@@ -22,8 +22,8 @@ USE_OCAMLFIND_PLIST=	yes
 
 SA_DIR=			${LOCALBASE}/${OCAML_SITELIBDIR}
 
-BUILD_DEPENDS+=		${SA_DIR}/netstring/netstring.a:${PORTSDIR}/www/ocaml-net
-RUN_DEPENDS+=		${SA_DIR}/netstring/netstring.a:${PORTSDIR}/www/ocaml-net
+BUILD_DEPENDS+=		ocaml-net>=3.6:${PORTSDIR}/www/ocaml-net
+RUN_DEPENDS+=		ocaml-net>=3.6:${PORTSDIR}/www/ocaml-net
 
 .include <bsd.port.pre.mk>
 
