--- Makefile.orig	2014-08-20 19:32:13.018429000 +0000
+++ Makefile
@@ -207,6 +207,9 @@ basic_auth+=	NIS
 # POLA: allow the old global make.conf(5) (pre src.conf(5)) defines, too:
 .if ${PORT_OPTIONS:MAUTH_KERB} && !defined(NO_KERBEROS) && !defined(WITHOUT_KERBEROS)
 negotiate_auth=	kerberos wrapper
+.  if ${OPSYS} == DragonFly
+LIB_DEPENDS+=	libkrb5.so:${PORTSDIR}/security/krb5
+.  endif
 # the kerberos_ldap_group external helper depends on LDAP and SASL:
 .if ${PORT_OPTIONS:MAUTH_LDAP} && ${PORT_OPTIONS:MAUTH_SASL}
 external_acl+=	kerberos_ldap_group
