--- Makefile.orig	2021-03-01 14:52:13 UTC
+++ Makefile
@@ -130 +130 @@
-GOLD_BUILD_DEPENDS=	${LOCALBASE}/bin/ld.gold:devel/binutils
+GOLD_BUILD_DEPENDS=	${LOCALBASE}/bin/ld.gold:devel/binutils@native
@@ -575 +575 @@
-post-install-LLD-on:
+post-install-LLD_LINK-on:
