--- Makefile.orig	2020-10-28 10:29:58 UTC
+++ Makefile
@@ -70,6 +70,15 @@ USE_XORG+=		xcb xrandr
 MESA_PLATFORMS+=	wayland
 .endif
 
+# gallium drivers are installed separately in graphics/mesa-gallium port
+.if ${OPSYS} == DragonFly
+OPTIONS_EXCLUDE:=	VAAPI VDPAU
+DRI_DRIVERS:=		R100 R200 I915 I965 SWRAST
+GALLIUM_DRIVERS:=
+VULKAN_DRIVERS:=	# requires render nodes on INTEL # AMD vulkan driver requires llvm
+MESON_ARGS+=		-Dgallium-xvmc=false -Dgallium-xa=false -Dgallium-va=false -Dgallium-vdpau=false
+.endif
+
 MESON_ARGS+=	-Ddri-drivers="${DRI_DRIVERS:ts,:tl}" \
 			-Dgallium-drivers="${GALLIUM_DRIVERS:ts,:tl}" \
 			-Dvulkan-drivers="${VULKAN_DRIVERS:ts,:tl}" \
@@ -78,9 +87,9 @@ MESON_ARGS+=	-Ddri-drivers="${DRI_DRIVER
 # Disable some options
 MESON_ARGS+=	-Dgallium-xa=disabled \
 		-Dgles1=disabled \
-		-Dgles2=disabled \
+		-Dgles2=enabled \
 		-Dglx=disabled \
-		-Degl=disabled \
+		-Degl=enabled \
 		-Dosmesa=none \
 		-Dtools=""
 
