--- Makefile.orig	2019-02-17 01:36:00.777096000 +0100
+++ Makefile	2019-02-17 01:35:51.766933000 +0100
@@ -3,6 +3,7 @@
 
 PORTNAME=	mesa-dri
 PORTVERSION=	${MESAVERSION}
+PORTREVISION=	1
 CATEGORIES=	graphics
 
 COMMENT=	OpenGL hardware acceleration drivers for DRI2+
@@ -66,6 +67,8 @@
 . endif
 .endif
 
+VULKAN_DRIVERS:=	# nothing, won't build on DF
+
 .if ${VULKAN_DRIVERS}
 BUILD_DEPENDS+=		${PYTHON_PKGNAMEPREFIX}mako>0:textproc/py-mako@${PY_FLAVOR}
 .endif
