WUT??? DELET ALL!

--- Makefile	2021-03-01 14:52:31 UTC
+++ Makefile
@@ -18 +17,0 @@
-BUILD_DEPENDS=	${LOCALBASE}/bin/ar:devel/binutils
@@ -77,9 +75,0 @@
-DEBUG_CMAKE_ON=		-DCMAKE_AR=${LOCALBASE}/bin/ar \
-			-DCMAKE_RANLIB=${LOCALBASE}/bin/ranlib \
-			-DCMAKE_LINKER=${LOCALBASE}/bin/ld
-DEBUG_CXXFLAGS=		-B${LOCALBASE}/bin
-
-DEBUG_CMAKE_OFF=	-DCMAKE_AR=/usr/bin/ar \
-			-DCMAKE_RANLIB=/usr/bin/ranlib \
-			-DCMAKE_LINKER=/usr/bin/ld
-DEBUG_CXXFLAGS_OFF=	-B/usr/bin
@@ -100,7 +89,0 @@
-
-pre-configure:
-# .if !exists() evaluates too early before cairo has a chance to be installed
-	@if ! pkg-config --exists cairo-egl; then \
-		${ECHO_MSG} "${PKGNAME}: Needs cairo with OPENGL support enabled."; \
-		${FALSE}; \
-	fi
