--- Makefile.orig	2021-02-22 18:14:37 UTC
+++ Makefile
@@ -53,10 +53,6 @@ MDNS_DESC=	Enable Bonjour/Rendezvous sup
 USES+=		fam
 .endif
 
-.if exists(${LOCALBASE}/lib/libkrb5.so)
-LIB_DEPENDS+=	libkrb5.so:security/heimdal
-.endif
-
 .if ${PORT_OPTIONS:MSAMBA}
 CONFIGURE_ARGS+=--with-samba-includes=${SAMBAINCLUDES} --with-samba-libs=${SAMBALIBS}
 USES+=		samba:lib
