--- Makefile.orig
+++ Makefile
@@ -1,24 +1,21 @@
 PORTNAME=	valgrind
-DISTVERSION=	3.27.1
+DISTVERSION=	3.15.0
 PORTEPOCH=	1
 CATEGORIES=	devel
-MASTER_SITES=	SOURCEWARE/valgrind
 
 MAINTAINER=	pjfloyd@wanadoo.fr
 COMMENT=	Memory debugging and profiling tool
 WWW=		https://www.valgrind.org/
 
-LICENSE=	GPLv3
+LICENSE=	GPLv2
 LICENSE_FILE=	${WRKSRC}/COPYING
 
 ONLY_FOR_ARCHS=	aarch64 amd64 i386
 
-USES=		autoreconf cpe gmake pathfix perl5 pkgconfig shebangfix \
-		python:run tar:bz2
+USES=		autoreconf cpe gmake pathfix perl5 pkgconfig shebangfix
 USE_PERL5=	build
 SHEBANG_FILES=	callgrind/callgrind_annotate.in callgrind/callgrind_control.in \
-		cachegrind/cg_merge.in cachegrind/cg_diff.in \
-		cachegrind/cg_annotate.in
+		cachegrind/cg_diff.in cachegrind/cg_annotate.in
 GNU_CONFIGURE=	yes
 CONFIGURE_ENV+=	ac_cv_path_PERL=${PERL}
 
@@ -28,6 +25,11 @@
 
 CONFLICTS=	valgrind-devel
 
+USE_GITHUB=	yes
+GH_ACCOUNT=	1338-1
+GH_PROJECT=	valgrind-dragonfly
+GH_TAGNAME=	dragonfly
+
 # Valgrind needs to read debuginfo from its own preload shared libraries
 # (quote from README_PACKAGERS
 #-- Don't strip the debug info off lib/valgrind/$platform/vgpreload*.so
@@ -39,10 +41,10 @@
 PORTDOCS=		html
 
 OPTIONS_DEFINE=		DOCS MANPAGES MPI
-OPTIONS_DEFINE_amd64=	32BIT
+OPTIONS_DEFINE_x86_64=	32BIT
 OPTIONS_DEFAULT=	MANPAGES
 .if exists(${LIB32_PATH})
-OPTIONS_DEFAULT_amd64=	32BIT
+OPTIONS_DEFAULT_x86_64=	32BIT
 .endif
 OPTIONS_SUB=		yes
 
@@ -59,7 +61,7 @@
 
 PLIST_SUB+=	ARCH=${ARCH:S/i386/x86/:S/aarch64/arm64/}
 
-.if ${ARCH} == "amd64"
+.if ${ARCH} == "x86_64"
 PLIST_SUB+=		AMD64=""
 . if !${PORT_OPTIONS:M32BIT}
 CONFIGURE_ARGS+=	--enable-only64bit
