--- Makefile.orig	2021-08-16 09:11:02 UTC
+++ Makefile
@@ -1,10 +1,7 @@
 # Created by: Simon Barner <barner@gmx.de>
 
 PORTNAME=	valgrind
-PORTVERSION=	3.17.0.g20210319
-DISTVERSIONPREFIX=	freebsd-
-PORTREVISION=	0
-PORTEPOCH=	1
+PORTVERSION=	3.15.0
 CATEGORIES=	devel
 MASTER_SITES=	https://valgrind.org/
 
@@ -27,9 +24,9 @@ LIB32_PATH?=	/usr/lib32/libc.so
 CONFLICTS=	valgrind-[0-9]*
 
 USE_GITHUB=	yes
-GH_ACCOUNT=	paulfloyd
-GH_PROJECT=	freebsd_valgrind
-GH_TAGNAME=	d333c54
+GH_ACCOUNT=	1338-1
+GH_PROJECT=	valgrind-dragonfly
+GH_TAGNAME=	dragonfly
 
 CONFIGURE_ENV+=	ac_cv_path_PERL=${PERL}
 
@@ -54,6 +51,10 @@ MPI_LIB_DEPENDS=	libmpich.so:net/mpich
 
 .include <bsd.port.options.mk>
 
+.if ${PORT_OPTIONS:MDOCS}
+CONFIGURE_ARGS+=	--docdir=${DOCSDIR}
+.endif
+
 .if ${ARCH} == "x86_64"
 PLIST_SUB+=	AMD64=""
 . if !${PORT_OPTIONS:M32BIT}
@@ -71,10 +72,15 @@ PLIST_SUB+=	AMD64="@comment "
 PLIST_SUB+=	X86=""
 .endif
 
-.if !${PORT_OPTIONS:MDOCS}
 post-patch:
+.if !${PORT_OPTIONS:MDOCS}
 	@${RM} -r ${WRKSRC}/docs/html
 .endif
+.if ${PORT_OPTIONS:MMANPAGES}
+	${REINPLACE_CMD} -e \
+		's|@XML_MAN_STYLES_CUSTOM@|share/xsl/docbook/manpages/docbook.xsl|g' \
+		${WRKSRC}/docs/Makefile.am
+.endif
 
 post-build:
 .if ${PORT_OPTIONS:MMANPAGES}
