--- Makefile.orig	2020-09-06 22:52:52 UTC
+++ Makefile
@@ -15,7 +15,9 @@ LICENSE_FILE=	${WRKSRC}/COPYING
 BUILD_DEPENDS=	lame:audio/lame \
 		flac:audio/flac \
 		oggenc:audio/vorbis-tools
-RUN_DEPENDS:=	${BUILD_DEPENDS}
+RUN_DEPENDS=	lame:audio/lame \
+		flac:audio/flac \
+		oggenc:audio/vorbis-tools
 LIB_DEPENDS=	libboost_system.so:devel/boost-libs \
 		libpng.so:graphics/png \
 		libmad.so:audio/libmad \
