--- Makefile.orig	2012-11-17 06:01:44.000000000 +0000
+++ Makefile
@@ -12,6 +12,8 @@ MNAME=	gssapi
 
 CONFIGURE_ARGS+=--enable-gssapi-krb5
 
+LIB_DEPENDS+= krb5:${PORTSDIR}/security/krb5
+
 PLIST_FILES+=	lib/rsyslog/imgssapi.la \
 		lib/rsyslog/imgssapi.so \
 		lib/rsyslog/lmgssutil.la \
