--- Makefile.orig	2016-01-31 00:37:00 UTC
+++ Makefile
@@ -16,13 +16,13 @@ LIB_DEPENDS=	libnspr4.so:${PORTSDIR}/dev
 CONFLICTS=	njs-[0-9]*
 
 MAKE_ARGS+=	JS_THREADSAFE=YES \
-		PROG_LIBS="-lreadline -ltermcap -lm -lpthread" \
+		PROG_LIBS="-lreadline -lncurses -lm -lpthread" \
 		LDFLAGS="-L${LOCALBASE}/lib"
 CFLAGS+=	-I${LOCALBASE}/include/nspr
 
 BROKEN_sparc64=		Does not build on sparc64: fails to link
 
-USES=		gmake readline
+USES=		gmake ncurses readline
 MAKEFILE=	Makefile.ref
 ALL_TARGET=	${OPSYS}`${UNAME} -r`_DBG.OBJ/js
 MAKE_ENV+=	CCC="${CXX}"
