--- Makefile.orig	2014-03-31 09:30:12.461750000 +0000
+++ Makefile
@@ -21,7 +21,7 @@ JAVA_VERSION=	1.6+
 USE_ANT=	yes
 
 do-install:
-	${INSTALL_DATA} -v ${WRKSRC}/dist/abcl.jar ${STAGEDIR}${JAVAJARDIR}
+	${INSTALL_DATA} ${WRKSRC}/dist/abcl.jar ${STAGEDIR}${JAVAJARDIR}
 	${INSTALL_SCRIPT} ${WRKDIR}/abcl ${STAGEDIR}${PREFIX}/bin
 
 .include <bsd.port.mk>
