--- Makefile.orig	2016-04-09 10:04:01 UTC
+++ Makefile
@@ -12,6 +12,7 @@ ONLY_FOR_ARCHS=	amd64
 
 MASTERDIR=	${.CURDIR}/../rust
 PATCHDIR=	${.CURDIR}/files
+DFLY_PATCHDIR=	${.CURDIR}/dragonfly
 DISTINFO_FILE=	${.CURDIR}/distinfo
 PLIST=		${.CURDIR}/pkg-plist
 
@@ -34,6 +35,7 @@ CONFLICTS_BUILD=	rust # see FIXME in lan
 CONFLICTS_INSTALL=	rust
 
 RUST_BOOT_SIG_amd64=	2016-02-17-4d3eebf-freebsd-x86_64-f38991fbb81c1cd8d0bbda396f98f13a55b42804
+RUST_BOOT_SIG_x86_64=	2016-02-17-4d3eebf-dragonfly-x86_64-765bb5820ad406e966ec0ac51c8070b656459b02
 
 PORT_LLVM_EXTRACT_ONLY_OFF=	${DISTFILE_llvm}
 PORT_LLVM_GH_PROJECT_OFF=	llvm:llvm
