--- Makefile.orig	2014-07-27 19:10:22.859596000 +0000
+++ Makefile
@@ -27,7 +27,7 @@ USE_AUTOTOOLS=	aclocal autoconf automake
 ACLOCAL_ARGS=	--force -I m4
 AUTOMAKE_ARGS=	--gnu --add-missing --copy
 CXXFLAGS+=	-fPIC
-LDFLAGS+=	-L${LOCALBASE}/lib -lintl
+LDFLAGS+=	-L${LOCALBASE}/lib -lintl -lX11
 CONFIGURE_ARGS+=--with-system-lua \
 		--with-lua-pkg=lua-${LUA_VER}
 CONFIGURE_ENV+=	FOX_CFLAGS="${FOX_CFLAGS}" \
