--- Makefile.orig	2013-04-22 18:04:49.000000000 +0000
+++ Makefile
@@ -28,7 +28,7 @@ ACLOCAL_ARGS=	--force -I m4
 AUTOMAKE_ARGS=	--gnu --add-missing --copy
 USE_GMAKE=	yes
 CXXFLAGS+=	-fPIC -Wno-invalid-source-encoding -Wno-format
-LDFLAGS+=	-L${LOCALBASE}/lib -lintl
+LDFLAGS+=	-L${LOCALBASE}/lib -lintl -lX11
 CONFIGURE_ARGS+=--with-system-lua \
 		--with-lua-pkg=lua-${LUA_VER}
 CONFIGURE_ENV+=	FOX_CFLAGS="${FOX_CFLAGS}" \
