--- Makefile.orig	2014-07-15 14:39:40.583260000 +0000
+++ Makefile
@@ -30,6 +30,7 @@ USE_WX=		3.0
 WX_UNICODE=	yes
 
 CFLAGS+=	-I${LOCALBASE}/include/libpng15
+LDFLAGS+=	-L${LOCALBASE}/lib -lssl -lcrypto
 WRKSRC=		${WRKDIR}/${PORTNAME}-3.9.0
 
 OPTIONS_DEFINE=	EDITOR
@@ -43,6 +44,13 @@ post-patch:
 		s,/usr/local/lib/lua51,${LUA_LIBDIR},g ; \
 		s,lua5.2,lua-${LUA_VER},g' \
 		${WRKSRC}/mk/cmake/Modules/FindLUA.cmake
+	@${REINPLACE_CMD} -e 's|__FreeBSD__|__DragonFly__|g' \
+		${WRKSRC}/source/glest_game/facilities/game_util.cpp \
+		${WRKSRC}/source/glest_game/main/main.cpp \
+		${WRKSRC}/source/shared_lib/sources/feathery_ftp/ftpTargetPosix.c \
+		${WRKSRC}/source/shared_lib/sources/platform/posix/socket.cpp \
+		${WRKSRC}/source/shared_lib/sources/platform/common/platform_common.cpp \
+		${WRKSRC}/source/shared_lib/include/util/leak_dumper.h
 
 do-install:
 	${STRIP_CMD} ${WRKSRC}/source/glest_game/megaglest
