--- Makefile.orig	2012-12-10 23:28:27.000000000 +0100
+++ Makefile	2012-12-28 19:23:56.885454000 +0100
@@ -13,7 +13,7 @@
 MAINTAINER=	ports@FreeBSD.org
 COMMENT=	Audio system for the KDE integrated X11 desktop
 
-LIB_DEPENDS+=	asound:${PORTSDIR}/audio/alsa-lib \
+LIB_DEPENDS+=	\
 		audiofile:${PORTSDIR}/audio/libaudiofile \
 		mad:${PORTSDIR}/audio/libmad \
 		ogg:${PORTSDIR}/audio/libogg \
