--- Makefile.orig	2013-05-07 13:30:20.915826000 +0000
+++ Makefile
@@ -13,7 +13,7 @@ DIST_SUBDIR=	KDE
 MAINTAINER=	ports@FreeBSD.org
 COMMENT=	Audio system for the KDE integrated X11 desktop
 
-LIB_DEPENDS+=	asound:${PORTSDIR}/audio/alsa-lib \
+LIB_DEPENDS+=	\
 		audiofile:${PORTSDIR}/audio/libaudiofile \
 		mad:${PORTSDIR}/audio/libmad \
 		ogg:${PORTSDIR}/audio/libogg \
@@ -46,6 +46,7 @@ USE_LDCONFIG=	yes
 QTCPPFLAGS+=	-L${LOCALBASE}/lib
 DO_NOT_COMPILE+=gmcop
 _NO_KDE_FINAL=	yes
+USE_PERL5_BUILD=yes
 
 CFLAGS+=	-DHAVE_VASPRINTF
 CONFIGURE_ENV+=	DO_NOT_COMPILE="${DO_NOT_COMPILE}"
