--- Makefile.orig	2013-12-27 19:23:30.216300000 +0000
+++ Makefile
@@ -33,7 +33,7 @@ DESKTOP_ENTRIES="Fish Supper" \
 
 .include <bsd.port.options.mk>
 
-.if ${OSVERSION} > 1000000
+.if ${OPSYS} == FreeBSD && ${OSVERSION} > 1000000
 post-patch:
 	@${REINPLACE_CMD} -e 's|std::tr1::shared_ptr|std::shared_ptr|g' ${WRKSRC}/src/*.h ${WRKSRC}/src/*.cpp
 .endif
