--- Makefile.orig	2013-05-30 11:28:53.000000000 +0000
+++ Makefile
@@ -3,6 +3,7 @@
 
 PORTNAME=	bitcoin
 PORTVERSION=	0.8.2
+PORTREVISION=	1
 CATEGORIES=	net-p2p finance
 
 MAINTAINER=	robbak@robbak.com
@@ -20,7 +21,7 @@ QRCODES_DESC=	Build with QR code display
 USE_GITHUB=	yes
 GH_ACCOUNT=	bitcoin
 GH_PROJECT=	bitcoin
-GH_COMMIT=	09e437b
+GH_COMMIT=	94933c3
 GH_TAGNAME=	v${PORTVERSION}
 
 USE_GMAKE=	yes
