--- Makefile.orig	2024-09-23 14:19:48 UTC
+++ Makefile
@@ -63,7 +63,7 @@ CONFIGURE_ENV+=	LLVM_CONFIG=llvm-config$
 .include <bsd.port.pre.mk>
 
 .if ${ARCH} == amd64
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 .if ${CHOSEN_COMPILER_TYPE} == gcc
