--- Makefile.orig	2022-07-27 23:58:19 UTC
+++ Makefile
@@ -55,7 +55,7 @@ PLIST_SUB=	SP_VER=${SP_VER}
 .include <bsd.port.pre.mk>
 
 .if ${ARCH} == amd64
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=      x86_64-portbld-${OPSYS:tl}${OSREL}
 .elif ${ARCH} == powerpc
 EXTRA_PATCHES=	${FILESDIR}/extra-patch-config_makefiles_rust.mk
 .endif
