--- Makefile.orig	2013-01-26 10:43:54.078785000 +0100
+++ Makefile	2013-01-26 10:44:06.748803000 +0100
@@ -6,6 +6,7 @@
 #
 
 CATEGORIES=	french print linux
+PKGNAMEPREFIX=	fr-
 
 MASTERDIR=	${.CURDIR}/../../print/acroread8
 DISTINFO_FILE=	${.CURDIR}/distinfo
