--- Makefile.orig	2014-11-09 19:11:02.094096000 +0000
+++ Makefile
@@ -201,7 +201,6 @@ FILENOTIFY_USE=		GNOME=glib20
 USE_GCC=		any
 .endif
 
-DBUS_PTHREAD_LIBS=	${CC} -dumpspecs | ${GREP} -m 1 pthread: | ${SED} -e 's|^.*%{\!pg: %{pthread:||' -e 's|}.*$$||' || ${TRUE}
 
 .if ${PORT_OPTIONS:MX11}
 
@@ -248,10 +247,6 @@ post-patch:
 	@${REINPLACE_CMD} -e 's/^Terminal=.*$$/Terminal=true/' ${WRKSRC}/etc/emacs.desktop
 .endif
 
-post-configure:
-	@${REINPLACE_CMD} -e "s/^\(DBUS_LIBS.*\)-pthread\(.*\)$$/\1$$(${DBUS_PTHREAD_LIBS})\2/" \
-	 ${WRKSRC}/src/Makefile
-
 post-install:
 	@${RM} -rf ${STAGEDIR}/var/games/emacs
 .if ${PORT_OPTIONS:MSOURCES}
