--- Makefile.orig	2013-12-09 09:52:00.892525000 +0000
+++ Makefile
@@ -42,7 +42,7 @@ CFLAGS+=	-O3 -ffast-math
 .endif
 
 do-build:
-	cd ${BUILD_WRKSRC} && ${CC} ${CFLAGS} -o caph -I../include *.c \
+	cd ${BUILD_WRKSRC} && ${CC} ${CFLAGS} -o caph -I../include *.c -lm \
 		`${SDL_CONFIG} --libs --cflags` -D_OPENGL -lGL -lpng ${ICONV_LIB}
 
 post-patch:
