--- Makefile.orig	2013-01-19 02:36:55.209891000 +0100
+++ Makefile	2013-01-19 02:45:12.750586000 +0100
@@ -21,6 +21,7 @@
 USE_BZIP2=	yes
 USE_SDL=	sdl
 USE_GL=		gl
+USE_ICONV=	yes
 
 BUILD_WRKSRC=	${WRKSRC}/src
 
@@ -43,7 +44,7 @@
 
 do-build:
 	cd ${BUILD_WRKSRC} && ${CC} ${CFLAGS} -o caph -I../include *.c \
-		`${SDL_CONFIG} --libs --cflags` -D_OPENGL -lGL -lpng
+	   `${SDL_CONFIG} --libs --cflags` -D_OPENGL -lGL -lpng -lm -liconv
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|../share/caph|${DATADIR}|' ${BUILD_WRKSRC}/caph.c
