--- Makefile.orig	2014-01-10 03:15:09.121636000 +0000
+++ Makefile
@@ -36,9 +36,6 @@ LIB_DEPENDS+=	libgdbm.so:${PORTSDIR}/dat
 LIB_DEPENDS+=	libgmp.so:${PORTSDIR}/math/gmp
 .endif
 
-.if ${OSVERSION} >= 900000
-# 'obj/obj-api.h' deprecated on gcc4.7, so ofc require gcc4.6 or early version.
-USE_GCC=	4.6
-.endif
+USE_GCC=	any
 
 .include <bsd.port.mk>
