--- Makefile.orig	Tue Apr  1 22:24:17 2025
+++ Makefile	Tue Apr
@@ -15,7 +15,7 @@ LICENSE_FILE=	${WRKSRC}/LICENSE
 LIB_DEPENDS=	libdaq.so:net/libdaq \
 		libdnet.so:net/libdnet \
 		libhwloc.so:devel/hwloc2 \
-		libpcap.so:net/libpcap \
+		libpcap.so.1:net/libpcap \
 		libpcre2-8.so:devel/pcre2 \
 		libuuid.so:misc/e2fsprogs-libuuid
 
