--- Makefile.orig	2014-01-30 10:33:57.546880000 +0000
+++ Makefile
@@ -49,8 +49,11 @@ PLIST_SUB+=	NLS="@comment "
 .endif
 
 .if ${PORT_OPTIONS:MSSH}
-LIB_DEPENDS+=	libssh.so:${PORTSDIR}/security/libssh
-.if ${OSVERSION} >= 800040
+LIB_DEPENDS+=	${LOCALBASE}/lib/libssh.so:${PORTSDIR}/security/libssh
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 800040
+LDFLAGS+=	-fstack-protector
+.endif
+.if ${OPSYS} == DragonFly
 LDFLAGS+=	-fstack-protector
 .endif
 .else
