--- Makefile.orig	2015-10-08 17:09:00 UTC
+++ Makefile
@@ -21,6 +21,7 @@ CONFIGURE_ARGS=	--disable-xvfb --disable
 		--enable-dmx --localstatedir=/var --without-dtrace
 
 SLAVE_PORT=	yes
+USE_XORG+=	presentproto
 
 do-install:
 	cd ${WRKSRC}/hw/dmx; DESTDIR=${STAGEDIR} ${MAKE} install
