--- Makefile.orig	2014-11-19 12:37:13.881074000 +0000
+++ Makefile
@@ -58,7 +58,8 @@ WEATHER_DESC=	Weather calendar backend
 
 .if ${PORT_OPTIONS:MKERBEROS}
 CONFIGURE_ARGS+=	--with-krb5=/usr
-KRB5_LIB=		`/usr/bin/krb5-config gssapi --libs`
+KRB5_LIB=	`${LOCALBASE}/bin/krb5-config gssapi --libs`
+BUILD_DEPENDS+= krb5-config:${PORTSDIR}/security/krb5
 .endif
 
 .if ${PORT_OPTIONS:MWEATHER}
