--- Makefile.orig	2014-05-05 11:40:19.851323000 +0000
+++ Makefile
@@ -12,6 +12,7 @@ DIST_SUBDIR=	gnome2
 MAINTAINER=	gnome@FreeBSD.org
 COMMENT=	The data backends for the Evolution integrated mail/PIM suite
 
+BUILD_DEPENDS=	gperf:${PORTSDIR}/devel/gperf
 LIB_DEPENDS=	libsoup-2.4.so:${PORTSDIR}/devel/libsoup \
 		libgdata.so:${PORTSDIR}/devel/libgdata \
 		libdbus-glib-1.so:${PORTSDIR}/devel/dbus-glib \
@@ -50,7 +51,8 @@ KERBEROS_CONFIGURE_OFF=	--without-krb5
 .include <bsd.port.options.mk>
 
 .if ${PORT_OPTIONS:MKERBEROS}
-KRB5_LIB=	`/usr/bin/krb5-config gssapi --libs`
+KRB5_LIB=	`${LOCALBASE}/bin/krb5-config gssapi --libs`
+BUILD_DEPENDS+= krb5-config:${PORTSDIR}/security/krb5
 .endif
 
 EDS_BDB_MSG=	"!!!WARNING!!!: Berkeley Database version is ${BDB_VER}.  If this is an upgrade, you may experience problems if you or any other Evolution-data-server users were previously using BDB_VER 41."
