--- Makefile.orig	2015-10-30 09:48:22 UTC
+++ Makefile
@@ -38,10 +38,10 @@ PLATFORM_VER=	1
 PLATFORM_VER=	9
 .  endif
 .else
-BROKEN=		${OPSYS} platform is not supported
+PLATFORM_VER=	4
 .endif
 
-LIBNAME=	libsigar-${ARCH:S,i386,x86,}-freebsd-${LATFORM_VER}.so
+LIBNAME=	libsigar-${ARCH:S,i386,x86,}-${OPSYS:tl}-${LATFORM_VER}.so
 
 PLIST_FILES=	%%JAVAJARDIR%%/${PORTNAME}.jar \
 		%%JAVAJARDIR%%/${LIBNAME}
