--- Makefile.orig	2015-04-08 18:04:26 UTC
+++ Makefile
@@ -15,7 +15,6 @@ USES=		metaport
 RUN_DEPENDS=	baobab>=3.0:${PORTSDIR}/deskutils/baobab \
 		gnome-screenshot>=3.0:${PORTSDIR}/deskutils/gnome-screenshot \
 		gnote>=3.0:${PORTSDIR}/deskutils/gnote \
-		gnome-contacts>=3.0:${PORTSDIR}/deskutils/gnome-contacts \
 		gnome-search-tool>=3.0:${PORTSDIR}/deskutils/gnome-search-tool \
 		gnome-dictionary>=3.0:${PORTSDIR}/deskutils/gnome-dictionary \
 		gnome-system-log>=3.0:${PORTSDIR}/deskutils/gnome-system-log \
