--- Makefile.orig	2014-11-21 21:26:29.476618000 +0000
+++ Makefile
@@ -14,8 +14,6 @@ COMMENT=	GNOME 3 support utilities
 
 RUN_DEPENDS=	baobab>=3.0:${PORTSDIR}/deskutils/baobab \
 		gnome-screenshot>=3.0:${PORTSDIR}/deskutils/gnome-screenshot \
-		gnote>=3.0:${PORTSDIR}/deskutils/gnote \
-		gnome-contacts>=3.0:${PORTSDIR}/deskutils/gnome-contacts \
 		gnome-search-tool>=3.0:${PORTSDIR}/deskutils/gnome-search-tool \
 		gnome-dictionary>=3.0:${PORTSDIR}/deskutils/gnome-dictionary \
 		gnome-system-log>=3.0:${PORTSDIR}/deskutils/gnome-system-log \
@@ -26,6 +24,9 @@ RUN_DEPENDS=	baobab>=3.0:${PORTSDIR}/des
 		gnome-maps>=3.0:${PORTSDIR}/deskutils/gnome-maps \
 		gnome-weather>=3.0:${PORTSDIR}/deskutils/gnome-weather
 
+#		gnote>=3.0:${PORTSDIR}/deskutils/gnote \
+#		gnome-contacts>=3.0:${PORTSDIR}/deskutils/gnome-contacts \
+
 NO_BUILD=	yes
 NO_INSTALL=	yes
 NO_MTREE=	yes
