--- Makefile.orig	2018-11-28 17:45:23 UTC
+++ Makefile
@@ -13,7 +13,7 @@ COMMENT=	Phylogenetic tree drawing progr
 
 LICENSE=	NONE
 
-BUILD_DEPENDS=	blastall:biology/ncbi-toolkit
+BUILD_DEPENDS=	cdscan:biology/ncbi-toolkit
 
 MAKEFILE=	makefile
 
