--- Makefile.orig	2013-10-19 23:51:31.983046000 +0000
+++ Makefile
@@ -57,7 +57,7 @@ GG_EMOTS_DISTFILES=	${GG6_EMOTS_DISTFILE
 NO_STAGE=	yes
 .include <bsd.port.options.mk>
 
-.if ${OSVERSION} > 1000051
+.if ${OPSYS} == FreeBSD && ${OSVERSION} > 1000051
 LDFLAGS+=	-lexecinfo
 .endif
 
