OPTIONS_EXCLUDE+=	ENIGMAIL
LDFLAGS+=		-R${PREFIX}/lib/thunderbird
MAKE_ENV+=		AR=/usr/bin/ar LD=/usr/bin/ld

MOZ_OPTIONS+=	--host=${ARCH}-dports-${OPSYS:tl}${OSREL}
MOZ_OPTIONS+=	--disable-webrtc

PULSEAUDIO_LIB_DEPENDS= libpulse.so:${PORTSDIR}/audio/pulseaudio
