--- Makefile.orig	2021-10-09 11:07:19 UTC
+++ Makefile
@@ -2,6 +2,7 @@
 
 PORTNAME=	libressl
 PORTVERSION=	3.3.3
+PORTREVISION=	1
 CATEGORIES=	security devel
 MASTER_SITES=	OPENBSD/LibreSSL
 
@@ -45,7 +46,9 @@ USES=		cpe libtool pathfix pkgconfig
 USE_LDCONFIG=	yes
 OPTIONS_SUB=	yes
 CFLAGS+=	-fpic -DPIC -Wl,-rpath,${PREFIX}/lib -Wl,--as-needed
+.if 0 #${OPSYS} == FreeBSD
 LDFLAGS+=	-pthread
+.endif
 
 INSTALL_TARGET=	install-strip
 TEST_TARGET=	check
