--- Makefile.orig	2013-02-05 10:18:56.000000000 +0000
+++ Makefile
@@ -21,6 +21,8 @@ USE_QT4=	corelib gui network moc_build q
 HAS_CONFIGURE=	yes
 MAKE_JOBS_SAFE=	yes
 
+QMAKEFLAGS=	QMAKE_LFLAGS="-lz"
+
 PLIST_SUB=	_DB=${_DB} DB_DIR=${DB_DIR} _DB_F=${_DB_F}
 
 QT_VER=		4
