--- Makefile.orig	2016-04-06 16:12:52 UTC
+++ Makefile
@@ -47,13 +47,15 @@ SUB_LIST=		PYTHON_SUFFIX=${PYTHON_SUFFIX
 
 PLIST_SUB=		XYDOT=${PYTHON_VER} XY=${PYTHON_SUFFIX} \
 			XYZDOT=${PYTHON_PORTVERSION} ABI=${ABIFLAGS} \
-			OSMAJOR=${OSVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
+			OSMAJOR=${DFLYVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
 
 OPTIONS_DEFINE=		DEBUG IPV6 LIBFFI NLS PYMALLOC THREADS TSC
 OPTIONS_DEFAULT=	LIBFFI PYMALLOC THREADS
 OPTIONS_RADIO=		HASH
 OPTIONS_RADIO_HASH=	FNV SIPHASH
 OPTIONS_SUB=		yes
+OPTIONS_DEFINE+=	EXPAT
+OPTIONS_DEFAULT+=	EXPAT
 
 LIBFFI_DESC=		Use libffi from ports instead of bundled version
 NLS_DESC=		Enable gettext support for the locale module
@@ -63,7 +65,9 @@ TSC_DESC=		Enable processor timestamp co
 HASH_DESC=		Hash Algorithm (PEP-456)
 FNV_DESC=		Modified Fowler-Noll-Vo Algorithm
 SIPHASH_DESC=		SipHash24 Algorithm
+EXPAT_DESC=		Use expat from ports instead of bundled version
 
+EXPAT_CONFIGURE_ON=	--with-system-expat
 FNV_CONFIGURE_ON=	--with-hash-algorithm=fnv
 SIPHASH_CONFIGURE_ON=	--with-hash-algorithm=siphash24
 
@@ -72,6 +76,7 @@ IPV6_CONFIGURE_ENABLE=	ipv6
 
 LIBFFI_CONFIGURE_ON=	--with-system-ffi
 LIBFFI_LIB_DEPENDS=	libffi.so:devel/libffi
+EXPAT_LIB_DEPENDS=	libexpat.so:textproc/expat2
 
 # Use CPPFLAGS over CFLAGS due to -I ordering, causing elementtree and pyexpat
 # to break in Python 2.7, or preprocessor complaints in Python >= 3.3
@@ -124,6 +129,10 @@ DISABLED_EXTENSIONS+=	nis
 PLIST_SUB+=	NO_NIS=""
 .endif
 
+post-patch:
+	${REINPLACE_CMD} -e 's|`uname -r`|"${_OSRELEASE}"|g' \
+		${WRKSRC}/configure
+
 post-install:
 .if ! ${PORT_OPTIONS:MDEBUG}
 	${RM} -f ${STAGEDIR}${PREFIX}/lib/libpython3.so						# Upstream Issue: http://bugs.python.org/issue17975
