--- Makefile.orig	2020-02-14 00:10:07 UTC
+++ Makefile
@@ -14,6 +14,7 @@ LICENSE_FILE=	${WRKSRC}/COPYING
 
 LIB_DEPENDS=	libexpat.so:textproc/expat2 \
 		libmozjs-60.so:lang/spidermonkey60
+LIB_DEPENDS+=	libxml2.so:textproc/libxml2
 RUN_DEPENDS=	dbus-launch:devel/dbus
 
 USERS=		polkitd
@@ -29,7 +30,6 @@ CONFIGURE_ARGS=	--disable-gtk-doc-html \
 		--without-html-dir \
 		--with-authfw=pam \
 		--with-pam-include=system \
-		--with-os-type=freebsd \
 		--with-polkitd-user=${USERS} \
 		--disable-static \
 		--disable-examples \
