--- Makefile.orig	2017-07-03 01:50:41 UTC
+++ Makefile
@@ -16,12 +16,11 @@ LICENSE_FILE=	${WRKSRC}/../COPYING
 
 BUILD_DEPENDS=	yasm:devel/yasm
 
-USES=		cmake pathfix tar:bz2
+USES=		cmake:noninja pathfix tar:bz2
 USE_LDCONFIG=	yes
-CMAKE_ARGS=	-DENABLE_PIC=on -DENABLE_TESTS=on -DPLATFORM_LIBS=md
+CMAKE_ARGS=	-DENABLE_PIC=on -DENABLE_TESTS=on
 CFLAGS_mips=	-DNO_ATOMICS # cannot use lang/gcc
 CFLAGS_mips64=	-DNO_ATOMICS # cannot use lang/gcc
-EXTRACT_AFTER_ARGS+=	--exclude "md5*"
 
 WRKSRC=		${WRKDIR}/multicoreware-${PORTNAME}-3037c1448549/source
 
