--- Makefile.orig	2017-01-27 18:40:24 UTC
+++ Makefile
@@ -18,11 +18,10 @@ BUILD_DEPENDS=	yasm:devel/yasm
 
 USES=		cmake pathfix tar:bz2
 USE_LDCONFIG=	yes
-CMAKE_ARGS=	-DENABLE_TESTS=on -DPLATFORM_LIBS=md
+CMAKE_ARGS=	-DENABLE_TESTS=on
 CFLAGS_aarch64=	-fPIC
 CFLAGS_mips=	-DNO_ATOMICS # cannot use lang/gcc
 CFLAGS_mips64=	-DNO_ATOMICS # cannot use lang/gcc
-EXTRACT_AFTER_ARGS+=	--exclude "md5*"
 
 WRKSRC=		${WRKDIR}/multicoreware-${PORTNAME}-be14a7e9755e/source
 
