--- Makefile.orig	2024-03-03 23:36:36 UTC
+++ Makefile
@@ -57,7 +57,7 @@ VMAF_DESC=	Per frame and aggregate VMAF
 USE_LDCONFIG=	yes
 CMAKE_ARGS=	-DENABLE_TESTS=on -DENABLE_HDR10_PLUS:BOOL=true -DGIT_ARCHETYPE=1
 LDFLAGS_i386=	-Wl,-znotext
-EXTRACT_AFTER_ARGS+=	--exclude compat --exclude md5\.* --strip-components=1
+EXTRACT_AFTER_ARGS+=	--exclude compat --strip-components=1
 PATCH_WRKSRC=	${WRKSRC:H}
 WRKSRC=		${WRKDIR}/source
 
