--- Makefile.orig	2016-04-06 16:03:08 UTC
+++ Makefile
@@ -84,21 +84,12 @@ NOPRECIOUSMAKEVARS=	yes
 
 ONLY_FOR_ARCHS=	amd64 i386
 
-BOOTSTRAP_JDKS=	${LOCALBASE}/openjdk6 \
-		${LOCALBASE}/bootstrap-openjdk
-
-# do we have valid native jdk installed?
-.for CJDK in ${BOOTSTRAP_JDKS}
-.  if !defined(BOOTSTRAPJDKDIR) && exists(${CJDK}/bin/javac)
-BOOTSTRAPJDKDIR=	${CJDK}
-.  endif
-.endfor
-
-# if no valid jdk found, set dependency
-.if !defined(BOOTSTRAPJDKDIR)
-BOOTSTRAPJDKDIR?=	${LOCALBASE}/bootstrap-openjdk
-BUILD_DEPENDS+=		${BOOTSTRAPJDKDIR}/bin/javac:java/bootstrap-openjdk
-.endif
+JDK_ARCH=		${ARCH:S/x86_64/amd64/}
+MASTER_SITES+=		http://leaf.dragonflybsd.org/~marino/dports-src/:bootstrap
+BOOTSTRAP_DISTFILE=	bootstrap-openjdk-b28_5.dfly-3.7-${JDK_ARCH}.tar.xz
+DISTFILES+=		${BOOTSTRAP_DISTFILE}:bootstrap
+EXTRACT_ONLY+=		${BOOTSTRAP_DISTFILE}
+BOOTSTRAPJDKDIR?=	${WRKDIR}/bootstrap
 
 MAKE_ENV=	LANG=C LC_ALL=C OS= \
 		ALT_JDK_IMPORT_PATH=${BOOTSTRAPJDKDIR} \
@@ -123,9 +114,9 @@ MAKE_ENV+=	HOTSPOT_BUILD_JOBS=${MAKE_JOB
 
 .if ${PORT_OPTIONS:MDEBUG}
 ALL_TARGET=	debug_build
-OPENJDK_OSARCH=	bsd-${ARCH:S/i386/i586/}-debug
+OPENJDK_OSARCH=	bsd-${ARCH:S/i386/i586/:S/x86_64/amd64/}-debug
 .else
-OPENJDK_OSARCH=	bsd-${ARCH:S/i386/i586/}
+OPENJDK_OSARCH=	bsd-${ARCH:S/i386/i586/:S/x86_64/amd64/}
 .endif
 
 # disable FASTDEBUG_BUILD by default to improve compile time.
@@ -294,8 +285,8 @@ do-install:
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}/j2re-image && \
 	    ${COPYTREE_BIN} bin ${STAGEDIR}${PREFIX}/openjdk6-jre
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}/j2re-image && \
-	    ${INSTALL_PROGRAM} lib/${ARCH}/jexec \
-	    ${STAGEDIR}${PREFIX}/openjdk6-jre/lib/${ARCH}
+	    ${INSTALL_PROGRAM} lib/${JDK_ARCH}/jexec \
+	    ${STAGEDIR}${PREFIX}/openjdk6-jre/lib/${JDK_ARCH}
 .else
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}/j2sdk-image && \
 	    ${COPYTREE_SHARE} . ${STAGEDIR}${PREFIX}/openjdk6 \
@@ -303,11 +294,13 @@ do-install:
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}/j2sdk-image && \
 	    ${COPYTREE_BIN} "bin jre/bin" ${STAGEDIR}${PREFIX}/openjdk6
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}/j2sdk-image && \
-	    ${INSTALL_PROGRAM} jre/lib/${ARCH}/jexec \
-	    ${STAGEDIR}${PREFIX}/openjdk6/jre/lib/${ARCH}
+	    ${INSTALL_PROGRAM} jre/lib/${JDK_ARCH}/jexec \
+	    ${STAGEDIR}${PREFIX}/openjdk6/jre/lib/${JDK_ARCH}
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}/btjars && \
 	    ${INSTALL_DATA} compilefontconfig.jar javazic.jar \
 	    ${STAGEDIR}${PREFIX}/openjdk6/jre/lib
+	@cd ${STAGEDIR}${PREFIX}/openjdk6/include && \
+	    ln -s dragonfly freebsd
 .if ${PORT_OPTIONS:MFASTDEBUG}
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}-fastdebug/j2sdk-image && \
 	    ${COPYTREE_SHARE} . ${STAGEDIR}${PREFIX}/openjdk6-fastdebug \
@@ -316,8 +309,8 @@ do-install:
 	    ${COPYTREE_BIN} "bin jre/bin" \
 	    ${STAGEDIR}${PREFIX}/openjdk6-fastdebug
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}-fastdebug/j2sdk-image && \
-	    ${INSTALL_PROGRAM} jre/lib/${ARCH}/jexec \
-	    ${STAGEDIR}${PREFIX}/openjdk6-fastdebug/jre/lib/${ARCH}
+	    ${INSTALL_PROGRAM} jre/lib/${JDK_ARCH}/jexec \
+	    ${STAGEDIR}${PREFIX}/openjdk6-fastdebug/jre/lib/${JDK_ARCH}
 .endif
 .endif
 	@${ECHO_CMD} "#!/bin/sh" > ${PKGDEINSTALL}
