--- Makefile.orig	2019-12-22 19:07:38.000000000 +0000
+++ Makefile
@@ -150,8 +150,6 @@
 # GNUTLS
 LIB_DEPENDS+=			libgnutls.so:security/gnutls
 LIB_DEPENDS+=			libgcrypt.so:security/libgcrypt
-# NFSv4 ACL glue
-LIB_DEPENDS+=			libsunacl.so:sysutils/libsunacl
 # Jansson
 BUILD_DEPENDS+=			jansson>=2.10:devel/jansson
 RUN_DEPENDS+=			jansson>=2.10:devel/jansson
@@ -260,7 +258,7 @@
 				--with-pam \
 				--with-iconv \
 				--with-winbind \
-				--with-regedit \
+				--without-regedit \
 				--disable-rpath \
 				--without-lttng \
 				--without-gettext \
@@ -269,7 +267,7 @@
 				--without-systemd \
 				--enable-gnutls \
 				--with-libarchive \
-				--with-acl-support \
+				--without-acl-support \
 				--with-sendfile-support \
 				--disable-ctdb-tests \
 
@@ -405,7 +403,7 @@
 .if ${PORT_OPTIONS:MDEVELOPER}
 SAMBA4_MODULES+=		auth_skel pdb_test gpext_security gpext_registry gpext_scripts perfcount_test \
 				vfs_fake_dfq vfs_skel_opaque vfs_skel_transparent vfs_shadow_copy_test vfs_fake_acls \
-				vfs_nfs4acl_xattr vfs_error_inject vfs_delay_inject
+				vfs_error_inject vfs_delay_inject
 .endif
 # Python bindings
 .if defined(NO_PYTHON)
