--- Makefile.orig	2015-06-09 15:52:54 UTC
+++ Makefile
@@ -2,7 +2,7 @@
 # $FreeBSD$
 
 PORTNAME=	libraw
-PORTVERSION=	0.16.2
+PORTVERSION=	0.16.0
 CATEGORIES=	graphics
 MASTER_SITES=	http://www.libraw.org/data/
 DISTNAME=	LibRaw-${PORTVERSION}
