--- Makefile.orig	2013-10-13 18:39:10.659417000 +0000
+++ Makefile
@@ -88,7 +88,11 @@ OPTIONS_SINGLE_DB=	MYSQL PGSQL SQLITE
 OPTIONS_SINGLE_ODBC=	IODBC UNIXODBC
 
 NO_STAGE=	yes
-.include <bsd.port.options.mk>
+.include <bsd.port.pre.mk>
+
+.if !empty(ICONV_LIB)
+CONFIGURE_ARGS+=	--with-iconv=${LOCALBASE}
+.endif
 
 .if ${PORT_OPTIONS:MMYSQL}
 ZABBIX_REQUIRE=	" mysql"
@@ -195,4 +199,4 @@ post-install:
 .endif
 .endif # if ${ZABBIX_BUILD} != "frontend"
 
-.include <bsd.port.mk>
+.include <bsd.port.post.mk>
