--- Makefile.orig	2013-09-16 11:58:02.720324000 +0000
+++ Makefile
@@ -87,7 +87,11 @@ OPTIONS_SINGLE=	DB ODBC
 OPTIONS_SINGLE_DB=	MYSQL PGSQL SQLITE
 OPTIONS_SINGLE_ODBC=	IODBC UNIXODBC
 
-.include <bsd.port.options.mk>
+.include <bsd.port.pre.mk>
+
+.if !empty(ICONV_LIB)
+CONFIGURE_ARGS+=	--with-iconv=${LOCALBASE}
+.endif
 
 .if ${PORT_OPTIONS:MMYSQL}
 ZABBIX_REQUIRE=	" mysql"
@@ -194,4 +198,4 @@ post-install:
 .endif
 .endif # if ${ZABBIX_BUILD} != "frontend"
 
-.include <bsd.port.mk>
+.include <bsd.port.post.mk>
