--- Makefile.orig	2015-03-26 10:36:11 UTC
+++ Makefile
@@ -21,7 +21,7 @@ USE_LDCONFIG=	yes
 INSTALL_TARGET=	install-strip
 
 CPPFLAGS+=	-I${LOCALBASE}/include
-LDFLAGS+=	-lpthread -lgnuregex -L${LOCALBASE}/lib
+LDFLAGS+=	-lpthread -L${LOCALBASE}/lib
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|CXXFLAGS="-s"|CXXFLAGS="$$CXXFLAGS"|g ; \
@@ -29,9 +29,5 @@ post-patch:
 .for file in vdk-config.in vdk.pc.in
 	@${REINPLACE_CMD} -e 's|-lpthread|${LDFLAGS}|g' ${WRKSRC}/${file}
 .endfor
-.for file in FileDialog.h gtksourcebuffer.h gtksourcetag.h
-	@${REINPLACE_CMD} -e \
-		's|<.*regex\.h>|<gnu/regex.h>|g' ${WRKSRC}/include/vdk/${file}
-.endfor
 
 .include <bsd.port.mk>
