--- Makefile.orig	2020-11-03 10:53:10 UTC
+++ Makefile
@@ -61,7 +61,7 @@ PLIST_SUB=	SP_VER=${SP_VER}
 .include <bsd.port.pre.mk>
 
 .if ${ARCH} == amd64
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 # Require newer Clang than what's in base system unless user opted out
