--- Makefile.orig	2012-12-17 00:23:02.503996000 +0000
+++ Makefile
@@ -26,6 +26,7 @@ do-install:
 	@cd ${WRKDIR} && tar cf - xml2rfc | \
 		tar -C ${PREFIX}/lib/${XXE_DIR}/addon -xf -
 
-.include "../xxe/Makefile.inc"
+IGNORE= Do not build until editors/xxe builds again
+#.include "../xxe/Makefile.inc"
 
 .include <bsd.port.mk>
