--- Makefile.orig	2012-12-13 07:08:00.000000000 +0000
+++ Makefile
@@ -2,16 +2,16 @@
 # $FreeBSD: ports/devel/omake/Makefile,v 1.14 2012/12/13 07:08:00 svnexp Exp $
 
 PORTNAME=	omake
-PORTVERSION=	0.9.8.5
-PORTREVISION=	1
+PORTVERSION=	${OMVERSION}rc1
 CATEGORIES=	devel
 MASTER_SITES=	http://main.metaprl.org/download/omake/
-DISTNAME=	${PORTNAME}-${PORTVERSION}-3
+DISTNAME=	${PORTNAME}-${OMVERSION}-0.rc1
 
 MAINTAINER=	ports@FreeBSD.org
 COMMENT=	A flexible build system
 
-WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}
+OMVERSION=	0.9.8.6
+WRKSRC=		${WRKDIR}/${PORTNAME}-${OMVERSION}
 USE_OCAML=	yes
 NO_OCAML_RUNDEPENDS=yes
 USE_NCURSES=	yes
