--- Makefile.orig	2024-09-23 14:16:15 UTC
+++ Makefile
@@ -58,7 +58,7 @@ PLIST_SUB=	SP_VER=${SP_VER}
 .include <bsd.port.pre.mk>
 
 .if ${ARCH} == amd64
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 .if ${CHOSEN_COMPILER_TYPE} == gcc
