--- Makefile.orig	2013-08-17 16:27:24.000000000 +0000
+++ Makefile
@@ -45,7 +45,7 @@ MAN3=		oyranos-config.3 oyranos.3
 CC=		/usr/bin/clang
 CXX=		/usr/bin/clang++
 .else
-USE_GCC=	yes
+USE_GCC=	4.6+
 .endif
 
 .include <bsd.port.post.mk>
