--- Makefile.orig	2014-09-13 06:44:42 UTC
+++ Makefile
@@ -14,9 +14,7 @@ USE_XORG=	xf86driproto xineramaproto xf8
 
 .include <bsd.port.options.mk>
 
-.if (${OSVERSION} >= 902508 && ${OSVERSION} < 1000000) || ${OSVERSION} >= 1000051
-#  902508: Radeon kernel driver imported in FreeBSD 9.x
-# 1000051: Radeon kernel driver imported in FreeBSD 10.x
+.if ${DFLYVERSION} >= 300900
 . if defined(WITH_NEW_XORG)
 NEW_ATI_DRIVER=	yes
 . else
