--- Makefile.orig	2013-02-18 19:14:27.000126000 +0100
+++ Makefile	2013-02-18 19:14:50.188991000 +0100
@@ -28,10 +28,12 @@
 .include "../evas-core/Makefile.inc"
 CONFIGURE_ARGS+=	--enable-buffer
 
+LDFLAGS+=	-L${LOCALBASE}/lib -levas
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/\.libs,${LOCALBASE}/lib,' \
-		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,-levas,' \
+		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,,' \
 		${BUILD_WRKSRC}/Makefile.in
 
 post-install:
