--- Makefile.orig	2014-03-14 21:47:18.000000000 +0000
+++ Makefile
@@ -77,6 +77,7 @@ PN532_UART_DRIVER=
 
 .if ${PORT_OPTIONS:MPN53X_USB}
 PN53X_USB_DRIVER=pn53x_usb,
+USES+= usb
 .else
 PN53X_USB_DRIVER=
 .endif
