--- Makefile.orig	2021-10-16 11:28:08 UTC
+++ Makefile
@@ -13,7 +13,8 @@ USES=		kde:5 metaport qt:5
 # remove:
 #   * bluedevil we do not have bluez at all
 #   * plasma-pa no plasma-pa (pulseaudio) by default
-USE_KDE=	${_USE_PLASMA_ALL:Nplasma-pa}
+#   * kwrited use is as build/run depends (executable on dragonfly)
+USE_KDE=	${_USE_PLASMA_ALL:Nplasma-pa:Nkwrited:Nkwallet-pam}
 
 OPTIONS_DEFINE=	PHONON PULSEAUDIO
 OPTIONS_DEFAULT=	${OPTIONS_DEFINE}
