--- Makefile.orig	2019-04-05 13:20:34 UTC
+++ Makefile
@@ -15,7 +15,8 @@ USES=		kde:5 metaport qt:5
 #   * bluedevil as we do have bluez
 #   * plasma-pa don't depend on plamsa-pa by default
 #   * breeze-kde4 don't pull in qt4 bits
-USE_KDE=	${_USE_PLASMA_ALL:Nplasma-pa:Nbreeze-kde4}
+#   * kwrited use is as build/run depends (executable on dragonfly)
+USE_KDE=	${_USE_PLASMA_ALL:Nplasma-pa:Nbreeze-kde4:Nkwrited}
 
 OPTIONS_DEFINE=	PHONON PULSEAUDIO
 OPTIONS_DEFAULT=	PHONON
