--- Makefile.orig	2014-05-09 08:49:52.822716000 +0000
+++ Makefile
@@ -8,6 +8,7 @@ COMMENT=	The GIMP User Manual in Sloveni
 
 LICENSE=	GFDL
 
+IGNORE=		Runs away on DragonFly
 MASTERDIR=	${.CURDIR}/../gimp-help-en
 
 DOCLANG=	sl
