--- Makefile.orig	2016-09-04 03:57:17 UTC
+++ Makefile
@@ -21,7 +21,7 @@ USES=		gmake tar:bzip2
 MAKE_ENV=	CCOM="${CC}"
 MAKE_ARGS=	INS_BASE=${PREFIX} DEFMANBASE=. CC="${CC}" CCOM="${CC}"
 
-PLIST_SUB=	RULESUSED="${ARCH}-freebsd-cc"
+PLIST_SUB=	RULESUSED="${ARCH}-${OPSYS:tl}-cc"
 
 MKLINKS=	${WRKSRC}/RULES/MKLINKS
 GCCRULE=	${WRKSRC}/RULES/cc-gcc.rul
@@ -29,9 +29,9 @@ GCCRULE=	${WRKSRC}/RULES/cc-gcc.rul
 pre-build:
 	@${CHMOD} +w ${MKLINKS} ${GCCRULE}
 	@${REINPLACE_CMD} -e 's|gcc$$|${CC}|' ${GCCRULE}
-	@${ECHO_CMD} "\$$symlink i386-freebsd-cc.rul ${ARCH}-freebsd-${CC}.rul" >> ${MKLINKS}
+	@${ECHO_CMD} "\$$symlink i386-freebsd-cc.rul ${ARCH}-${OPSYS:tl}-${CC}.rul" >> ${MKLINKS}
 
 pre-install:
-	${STRIP_CMD} ${WRKSRC}/smake/OBJ/${ARCH}-freebsd-${CC}/smake
+	${STRIP_CMD} ${WRKSRC}/smake/OBJ/${ARCH}-${OPSYS:tl}-${CC}/smake
 
 .include <bsd.port.mk>
