--- Makefile.orig	2019-03-12 09:39:36 UTC
+++ Makefile
@@ -4,7 +4,7 @@ PORTNAME=	fortunate
 PORTVERSION=	3.1
 PORTREVISION=	9
 CATEGORIES=	games gnustep
-MASTER_SITES=	GNUSTEP_CH
+MASTER_SITES=	https://broken_for_developer_mode.z/
 
 MAINTAINER=	ports@FreeBSD.org
 COMMENT=	Graphical front-end to the command-line BSD fortune
