--- Makefile.orig	2013-05-29 12:46:28.000000000 +0000
+++ Makefile
@@ -1,9 +1,5 @@
-# New ports collection makefile for:	pgplot
-# Date created:		21 December 1996
-# Whom:			jmz
-#
+# Created by: jmz
 # $FreeBSD: ports/graphics/pgplot/Makefile,v 1.37 2012/11/17 05:58:18 svnexp Exp $
-#
 
 PORTNAME=	pgplot
 PORTVERSION=	5.2.2
@@ -13,12 +9,13 @@ MASTER_SITES=	ftp://ftp.astro.caltech.ed
 DISTNAME=	${PORTNAME}${PORTVERSION:R}
 
 MAINTAINER=	bf@FreeBSD.org
-COMMENT=	A C/FORTRAN library for drawing graphs on a variety of display devices
+COMMENT=	C/FORTRAN library for drawing graphs on a variety of display devices
 
 LIB_DEPENDS=	png15:${PORTSDIR}/graphics/png
 
 MAKE_JOBS_UNSAFE=	yes
 
+USES=		shebangfix
 USE_FORTRAN=	yes
 USE_LDCONFIG=	yes
 USE_XORG=	x11 xproto xt
@@ -27,6 +24,8 @@ MAKE_ENV=	SSP_CFLAGS=
 SUFFIXES=	flib clib bin
 WRKSRC=		${WRKDIR}/${PORTNAME}
 
+SHEBANG_FILES=	makehtml maketex
+
 .include <bsd.port.pre.mk>
 
 .if !empty(ARCH:M*64*)
@@ -51,8 +50,6 @@ PORTEXAMPLES=	${EXAMPLES:C|.*/||}
 .endif
 
 post-patch:
-	@${REINPLACE_CMD} -e 's|/usr/local/bin/perl|${PERL}|' \
-		${WRKSRC}/makehtml ${WRKSRC}/maketex
 	@${REINPLACE_CMD} -e 's|png_ptr->jmpbuf|png_jmpbuf(png_ptr)|' \
 		${WRKSRC}/drivers/pndriv.c
 	@${REINPLACE_CMD} -e 's|/usr/local/pgplot|${DATADIR}|g' \
