--- Makefile.orig	2014-06-20 13:07:30.721318000 +0000
+++ Makefile
@@ -14,8 +14,9 @@ WRKSRC=		${WRKDIR}/${DISTNAME}/nspr/buil
 USES=		gmake
 USE_LDCONFIG=	yes
 GNU_CONFIGURE=	yes
-CONFIGURE_SCRIPT=../configure
+USE_AUTOTOOLS=	autoconf
 CONFIGURE_ARGS=	--srcdir=${WRKSRC:H}
+CONFIGURE_WRKSRC= ${WRKSRC}/..
 
 MAKE_ENV=	DIST=${WRKSRC}/dist
 
@@ -31,6 +32,10 @@ BROKEN=		Does not compile on arm
 CONFIGURE_ARGS+=--disable-debug
 .endif
 
+do-configure:
+	cd ${WRKSRC} && ${CONFIGURE_ENV} \
+		../${CONFIGURE_SCRIPT} ${CONFIGURE_ARGS}
+
 do-install:
 	${MKDIR} ${STAGEDIR}${PREFIX}/include/nspr
 	${TAR} -C ${WRKSRC}/dist/include --dereference -cf - . | \
