--- Makefile.orig	2017-01-03 16:28:22.000000000 +0200
+++ Makefile
@@ -13,7 +13,7 @@ COMMENT=	Julia Language: A fresh approac
 LICENSE=	MIT
 LICENSE_FILE=	${WRKSRC}/LICENSE.md
 
-LIB_DEPENDS=	libunwind.so:devel/libunwind \
+LIB_DEPENDS=	 \
 		libutf8proc.so:textproc/utf8proc \
 		libopenblas.so:math/openblas \
 		libgit2.so:devel/libgit2 \
@@ -34,11 +34,13 @@ ALL_TARGET=	default
 INSTALL_TARGET=	install
 TEST_TARGET=	test
 
-CXXFLAGS+=	-stdlib=libc++ -std=c++11
+USE_CXXSTD=	c++11 # rest were clang'isms
 MAKE_ARGS+=	prefix=${PREFIX} JCXXFLAGS="${CXXFLAGS}" \
 		FORCE_ASSERTIONS=${FORCE_ASSERTIONS} \
 		USE_GPL_LIBS=${USE_GPL_LIBS}
 
+MAKE_ARGS+= VERBOSE=1 # show what are you doing instead of hiding it
+
 OPTIONS_DEFINE=	EXAMPLES DEBUG DOCS GPL_LIBS DESKTOP
 OPTIONS_SUB=	yes
 
@@ -62,7 +64,7 @@ DESKTOP_VARS=	INSTALL_TARGET+=install-de
 		INSTALLS_ICONS=yes
 
 post-configure:
-	${CC} ${CFLAGS} -lopenblas ${LDFLAGS} -o ${WRKSRC}/check_openblas \
+	${CC} ${CFLAGS} -L${LOCALBASE}/lib -lopenblas ${LDFLAGS} -o ${WRKSRC}/check_openblas \
 		${FILESDIR}/check_openblas.c
 	${WRKSRC}/check_openblas && ( \
 		echo "USE_BLAS64=1" >> ${WRKSRC}/Make.user \
