--- Makefile.orig	2022-01-13 04:20:54 UTC
+++ Makefile
@@ -33,7 +33,7 @@
 		unrtf:textproc/unrtf				\
 		catdvi:print/catdvi				\
 		bash:shells/bash				\
-		${LOCALBASE}/libexec/xpdf/pdftotext:graphics/xpdf
+		pdftotext:graphics/poppler-utils
 
 USE_GITHUB=	yes
 GH_ACCOUNT=	FabriceColin
@@ -74,9 +74,6 @@
 UL2FIX=		Utils/xdgmime/xdgmime.c
 
 pre-configure:
-	${REINPLACE_CMD} -e \
-		'/<command>/s|pdftotext|${LOCALBASE}/libexec/xpdf/pdftotext|' \
-		${WRKSRC}/Tokenize/filters/external-filters.xml
 	${REINPLACE_CMD} -e 's|/usr/share|${LOCALBASE}/share|'	\
 		${LM2FIX:S|^|${WRKSRC}/|}
 	${REINPLACE_CMD} -e 's|/usr/share|${PREFIX}/share|'	\
