--- Makefile.orig	2013-08-09 07:20:53.532611000 +0000
+++ Makefile
@@ -30,7 +30,7 @@ LIB_DEPENDS=	xapian:${PORTSDIR}/database
 RUN_DEPENDS=	update-mime-database:${PORTSDIR}/misc/shared-mime-info	\
 		antiword:${PORTSDIR}/textproc/antiword			\
 		xdg-open:${PORTSDIR}/devel/xdg-utils			\
-		${LOCALBASE}/libexec/xpdf/pdftotext:${PORTSDIR}/graphics/xpdf	\
+		pdftotext:${PORTSDIR}/graphics/poppler-utils		\
 		catppt:${PORTSDIR}/textproc/catdoc			\
 		unzip:${PORTSDIR}/archivers/unzip			\
 		unrtf:${PORTSDIR}/textproc/unrtf			\
@@ -87,11 +87,6 @@ post-extract:
 # remove pre-generated messages catalogs
 	${FIND} ${WRKSRC}/po -name "*.gmo" -delete
 
-post-patch:
-	${REINPLACE_CMD} -e \
-		'/<command>/s|pdftotext|${LOCALBASE}/libexec/xpdf/pdftotext|' \
-		${WRKSRC}/Tokenize/filters/external-filters.xml
-
 pre-configure:
 	${REINPLACE_CMD} -e 's|-lthr|${PTHREAD_LIBS}|' ${WRKSRC}/configure
 	${REINPLACE_CMD} -e 's|/usr/share|${LOCALBASE}/share|'	\
