--- Makefile.orig	2024-09-23 15:01:20 UTC
+++ Makefile
@@ -143,7 +143,7 @@ _IPW2200_FIRMWARE=	iwi/ipw2200-bss \
 			iwi/ipw2200-ibss
 _MT76_FIRMWARE=		2135e201e7a9339e018d4e2d4a33c73266e674d7
 
-_LINUX64_KMOD!=		(kldstat -qn linux64 && echo "found") || echo ""
+_LINUX64_KMOD=
 _LINUX_EMUL_PATH!=	(sysctl -qn compat.linux.emul_path) || echo ""
 _LINUX_EP_EXISTS!=	(test -d "${_LINUX_EMUL_PATH}" && echo "found") || echo ""
 
