--- Makefile.orig	2014-06-02 10:26:15.199969000 +0000
+++ Makefile
@@ -122,6 +122,7 @@ CONFIGURE_ARGS+=	--without-mdb
 
 .if ${LIBGDA4_SLAVE}=="jdbc"
 USE_JAVA=		yes
+JAVA_VERSION=		1.6
 JAVA_VENDOR=		openjdk
 .else
 CONFIGURE_ARGS+=	--without-java
