--- Makefile.orig	2019-07-31 15:03:51 UTC
+++ Makefile
@@ -32,7 +32,5 @@ post-patch:
 
 post-install:
 	@cd ${STAGEDIR}${PREFIX}/lib/${PORTNAME} && ${STRIP_CMD} xcrys xctclsh xsf2xsf
-	@${REINPLACE_CMD} -i '' -e 's|^\.|export LD_PRELOAD=/usr/local/lib/gcc${GCC_DEFAULT}/libgcc_s.so; .|' \
-		${STAGEDIR}${PREFIX}/bin/xcrysden
 
 .include <bsd.port.mk>
