--- Makefile.orig	Tue Apr  1 18:54:06 2025
+++ Makefile	Tue Apr
@@ -16,8 +16,4 @@ CMAKE_ARGS=	-DBUILD_SHARED_LIBS:BOOL=ON \
 		-DCMAKE_CXX_STANDARD=17 # force the same highest C++ standard because of ABI differences: see https://github.com/abseil/abseil-cpp/issues/819
 PATHFIX_CMAKELISTSTXT=	AbseilHelpers.cmake
 
-_GET_SOVER=	${GREP} ABSL_SOVERSION ${WRKSRC}/CMakeLists.txt \
-		2>/dev/null | ${CUT} -d\" -f2
-PLIST_SUB+=	LIBSUFX=${_GET_SOVER:sh}
-
 .include <bsd.port.mk>
