--- Makefile.orig	2021-07-23 13:58:26 UTC
+++ Makefile
@@ -16,8 +16,4 @@ GH_PROJECT=	${PORTNAME}-cpp
 CMAKE_ARGS=	-DBUILD_SHARED_LIBS:BOOL=ON \
 		-DCMAKE_CXX_STANDARD=17 # force the same highest C++ standard because of ABI differences: see https://github.com/abseil/abseil-cpp/issues/819
 
-_GET_SOVER=	${GREP} SOVERSION ${WRKSRC}/CMake/AbseilHelpers.cmake \
-		| ${CUT} -d\" -f2
-PLIST_SUB+=	LIBSUFX=${_GET_SOVER:sh}
-
 .include <bsd.port.mk>
