--- Makefile.orig	2017-05-06 16:47:21 UTC
+++ Makefile
@@ -76,7 +76,7 @@ post-extract:
 	@(cd ${WRKSRC}/scsilib/RULES && ${CP} os-freebsd.id os-dragonfly.id)
 .if ${SCSILIBXARCH} != "i386"
 	@${LN} -sf ${WRKSRC}/scsilib/RULES/i386-freebsd-cc.rul \
-		${WRKSRC}/scsilib/RULES/${SCSILIBXARCH}-${OPSYS:tl}-cc.rul
+		${WRKSRC}/scsilib/RULES/${SCSILIBXARCH}-freebsd-cc.rul
 .endif
 
 post-patch:
