--- Makefile.orig	2015-06-30 09:19:12.000000000 +0300
+++ Makefile
@@ -17,6 +17,9 @@ OPTIONS_DEFINE=
 post-patch:
 	cd ${WRKSRC}/modules/json/c && ${YACC} -b json json.y
 
+dfly-patch:
+	${REINPLACE_CMD} -e 's|typedef unsigned |//|g' ${WRKSRC}/modules/sha1/sha256.h
+
 do-install:
 	${RM} -f ${WRKSRC}/modules/tcllibc/license.terms
 	${MKDIR} ${STAGEDIR}${PREFIX}/lib/tcllib
