--- Makefile.orig	2013-01-26 11:01:40.610275000 +0100
+++ Makefile	2013-01-26 11:01:52.920292000 +0100
@@ -6,6 +6,7 @@
 #
 
 CATEGORIES=	german print linux
+PKGNAMEPREFIX=	de-
 
 MASTERDIR=	${.CURDIR}/../../print/acroread8
 DISTINFO_FILE=	${.CURDIR}/distinfo
