--- Makefile.orig	2020-10-28 15:51:39 UTC
+++ Makefile
@@ -101,6 +101,6 @@ post-install:
 	${MKDIR} ${STAGEDIR}${ETCDIR}/snapshots
 	(cd ${STAGEDIR}${ETCDIR} && for f in *.config *.yaml; do ${MV} $$f $$f.sample; done)
 	${SED} -i '' -e 's|^${STAGEDIR}||g' \
-		${STAGEDIR}${PREFIX}/lib/perl5/${ARCH:C/powerpc64.*/powerpc/}-freebsd-thread-multi/auto/Apache/TS/.packlist
+		${STAGEDIR}${PREFIX}/lib/perl5/${ARCH:C/powerpc64.*/powerpc/}-${OPSYS:tl}-thread-multi/auto/Apache/TS/.packlist
 
 .include <bsd.port.post.mk>
