--- Makefile.orig	2014-01-26 19:05:14.320420000 +0000
+++ Makefile
@@ -50,9 +50,5 @@ post-patch:
 		${WRKSRC}/libcharset/configure \
 		${WRKSRC}/preload/configure
 
-.if exists(/usr/include/iconv.h)
-IGNORE=		converters/libiconv should not be used with iconv from base. \
-Please fix the port which tries to use it
-.endif
 
 .include <bsd.port.mk>
