--- Makefile.orig	2013-09-06 20:02:00.000000000 +0000
+++ Makefile
@@ -49,11 +49,4 @@ post-patch:
 		${WRKSRC}/libcharset/configure \
 		${WRKSRC}/preload/configure
 
-.include <bsd.port.pre.mk>
-
-.if ${OSVERSION} > 1000043
-IGNORE=		converters/libiconv should not be used with OSVERSION > 1000043. \
-Please fix the port which tries to use it
-.endif
-
-.include <bsd.port.post.mk>
+.include <bsd.port.mk>
