--- Makefile.orig	2017-10-05 17:52:03 UTC
+++ Makefile
@@ -102,7 +102,7 @@ PLIST_FILES=		lib/rustlib/components \
 EXTRA_PATCHES+=		${PATCHDIR}/extra-patch-ino64
 .endif
 
-X_PY_ENV=	HOME="${WRKDIR}" \
+X_PY_ENV+=	HOME="${WRKDIR}" \
 		OPENSSL_DIR="${OPENSSLBASE}"
 X_PY_CMD=	${PYTHON_CMD} ${WRKSRC}/x.py
 
