--- Makefile.orig	2019-12-17 10:22:38 UTC
+++ Makefile
@@ -97,7 +97,7 @@ IGNORE=	fails to run due to a bug in rtl
 IGNORE=	fails to build with qemu-user-static
 .endif
 
-X_PY_ENV=	HOME="${WRKDIR}" \
+X_PY_ENV+=	HOME="${WRKDIR}" \
 		LIBGIT2_SYS_USE_PKG_CONFIG=1 \
 		LIBSSH2_SYS_USE_PKG_CONFIG=1 \
 		OPENSSL_DIR="${OPENSSLBASE}"
