--- Makefile.orig	2013-02-18 18:43:58.323382000 +0100
+++ Makefile	2013-02-18 18:44:46.580977000 +0100
@@ -27,10 +27,12 @@
 
 CONFIGURE_ARGS+=	--enable-ecore-input
 
+LDFLAGS+=	-L${LOCALBASE}/lib -lecore
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/ecore/\.libs,${LOCALBASE}/lib,'\
-		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,-lecore,'\
+		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,,'\
 		${BUILD_WRKSRC}/Makefile.in
 
 post-install:
