--- Makefile.orig	2015-09-29 00:06:04 UTC
+++ Makefile
@@ -43,17 +43,8 @@ DRI_DRIVERS=	${ALL_DRI_DRIVERS}
 CONFIGURE_ARGS+=--enable-texture-float
 .endif
 
-.if 0 #${PORT_OPTIONS:MVDPAU}
-.if ${PORT_OPTIONS:MGALLIUM} == ""
-IGNORE=	VDPAU option requires GALLIUM support to be enabled
-.endif
-CONFIGURE_ARGS+=--enable-vdpau
 LIB_DEPENDS+=	libvdpau.so:${PORTSDIR}/multimedia/libvdpau
 PLIST_SUB+=	VDPAU=""
-.else
-CONFIGURE_ARGS+=--disable-vdpau
-PLIST_SUB+=	VDPAU="@comment "
-.endif
 
 .if ${ARCH} == powerpc || ${ARCH} == powerpc64
 DRI_DRIVERS=	RADEON SWRAST
