--- Makefile.orig	2022-01-13 04:21:08 UTC
+++ Makefile
@@ -50,7 +50,7 @@
 			XY=${PYTHON_SUFFIX} \
 			XYDOT=${PYTHON_VER} \
 			XYZDOT=${DISTVERSION:C/[a-z].*//} \
-			OSMAJOR=${OSVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. https://bugs.python.org/issue19554
+			OSMAJOR=${DFLYVERSION:C/([0-9]*)[0-9]{5}/\1/}
 
 OPTIONS_DEFINE=		DEBUG IPV6 LIBMPDEC NLS PYMALLOC
 OPTIONS_DEFAULT=	LIBMPDEC PYMALLOC
