
OPTIONS_DEFAULT:=	${OPTIONS_DEFAULT:NSMARTCARD:NWACOM}

# no pulse
LIB_DEPENDS:=	${LIB_DEPENDS:Nlibpulse*}

dfly-patch:
	${REINPLACE_CMD} -e '/pulse/d' ${WRKSRC}/meson.build
	${REINPLACE_CMD} -e '/sound/d' -e '/media-keys/d' ${WRKSRC}/plugins/meson.build
	${RM} -r ${WRKSRC}/plugins/media-keys
	${RM} -r ${WRKSRC}/plugins/sound
