--- Makefile.orig	2016-04-06 16:27:11 UTC
+++ Makefile
@@ -82,8 +82,6 @@ LIB_DEPENDS+=		libsasl2.so:security/cyru
 # GNUTLS
 LIB_DEPENDS+=		libgcrypt.so:security/libgcrypt
 LIB_DEPENDS+=		libgnutls.so:security/gnutls
-# NFS4 ACL glue
-LIB_DEPENDS+=		libsunacl.so:sysutils/libsunacl
 # External Samba dependencies
 # IDL compiler
 BUILD_DEPENDS+=		p5-Parse-Pidl>=4.0.0:devel/p5-Parse-Pidl
@@ -149,9 +147,12 @@ BIND99_DESC=		Use bind99 as AD DC DNS se
 BIND910_DESC=		Use bind910 as AD DC DNS server frontend
 NSUPDATE_DESC=		Use samba NSUPDATE utility for AD DC
 
+OPTIONS_EXCLUDE_DragonFly=	ACL_SUPPORT
+
 .include <bsd.port.options.mk>
 
 CONFIGURE_ARGS+=	\
+			--without-regedit \
 			--with-pam \
 			--with-iconv \
 			--with-winbind \
