--- Makefile.orig	2013-12-28 14:59:13.865383000 +0000
+++ Makefile
@@ -89,8 +89,6 @@ LIB_DEPENDS+=		libsasl2.so:${PORTSDIR}/s
 # GNUTLS
 LIB_DEPENDS+=		libgcrypt.so:${PORTSDIR}/security/libgcrypt
 LIB_DEPENDS+=		libgnutls.so:${PORTSDIR}/security/gnutls
-# NFS4 ACL glue
-LIB_DEPENDS+=		libsunacl.so:${PORTSDIR}/sysutils/libsunacl
 # External Samba dependencies
 # IDL compiler
 BUILD_DEPENDS+=		p5-Parse-Pidl>=4.0.0:${PORTSDIR}/devel/p5-Parse-Pidl
@@ -236,14 +234,18 @@ WANT_EXP_MODULES=	idmap_ad vfs_cacheprim
 .endif
 
 .if ${PORT_OPTIONS:MACL_SUPPORT}
+.  if ${OPSYS} == FreeBSD
 .	if ${OSVERSION} > 800000
 LIB_DEPENDS+=		libsunacl.so:${PORTSDIR}/sysutils/libsunacl
 WANT_EXP_MODULES+=	vfs_zfsacl
 SAMBA4_MODULES+=	vfs_zfsacl
-.	endif
 CONFIGURE_ARGS+=	--with-acl-support
-.else
+.       else
+CONFIGURE_ARGS+=	--without-acl-support
+.       endif
+.  else
 CONFIGURE_ARGS+=	--without-acl-support
+.  endif
 .endif
 
 .if ${PORT_OPTIONS:MADS}
