--- Makefile.orig	2017-07-17 19:57:42 UTC
+++ Makefile
@@ -94,11 +94,6 @@ CONFIGURE_ARGS+=--disable-dtrace
 .endif
 .endif
 
-# keep in sync with all platforms where libunwind is available
-.if (${ARCH} == amd64 || ${ARCH} == i386)
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
-
 .if (${ARCH} == powerpc64 || ${ARCH} == powerpc)
 USE_GCC=	yes
 .endif
