--- Makefile.orig	2019-01-22 15:45:53 UTC
+++ Makefile
@@ -92,11 +92,6 @@ CONFIGURE_ARGS+=--disable-dtrace
 .endif
 .endif
 
-# keep in sync with all platforms where libunwind is available
-.if (${ARCH} == amd64 || ${ARCH} == i386)
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
-
 .if ${ARCH:Mpowerpc*}
 USE_GCC=	yes
 .endif
