--- Makefile.orig	2018-08-26 18:44:37 UTC
+++ Makefile
@@ -91,11 +91,6 @@ CONFIGURE_ARGS+=--disable-dtrace
 .endif
 .endif
 
-# keep in sync with all platforms where libunwind is available
-.if (${ARCH} == amd64 || ${ARCH} == i386)
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
-
 .if (${ARCH} == powerpc || ${ARCH} == powerpc64)
 USE_GCC=	yes
 .endif
