--- Makefile.orig	2021-02-04 18:49:33 UTC
+++ Makefile
@@ -109,10 +109,6 @@ SLURM_PLIST_FILES=	${MPIDIR}/lib/openmpi
 
 .include <bsd.port.options.mk>
 
-.if ${FORTRAN_DEFAULT} == gfortran && ${GCC_DEFAULT} >= 10
-FCFLAGS+=	-fallow-argument-mismatch
-.endif
-
 post-patch:
 	@${REINPLACE_CMD} -e 's|$$(libdir)/pkgconfig|${LOCALBASE}/libdata/pkgconfig|g' \
 		${WRKSRC}/ompi/tools/wrappers/Makefile.am \
