--- Makefile.orig	2021-11-07 15:19:49 UTC
+++ Makefile
@@ -104,10 +104,6 @@ SLURM_PLIST_FILES=	${MPIDIR}/lib/openmpi
 
 .include <bsd.port.options.mk>
 
-.if ${FORTRAN_DEFAULT} == gfortran && ${GCC_DEFAULT} >= 10
-FCFLAGS+=	-fallow-argument-mismatch
-.endif
-
 .if ${ARCH} != aarch64 && ${ARCH} != amd64 && ${ARCH} != i386 && !${ARCH:Mpowerpc*}
 PLIST_SUB+=	NO_MCA_PATCHER_OVERWRITE="@comment "
 .else
