--- Makefile.orig	2014-09-24 13:16:37.516891000 +0000
+++ Makefile
@@ -83,7 +83,7 @@ FFTW3_SUFX=	q
 FFTW3_PKGNAMESUFFIX=	-quad
 CONFIGURE_ARGS+=--enable-quad-precision
 ONLY_FOR_ARCHS=		i386 amd64
-USE_GCC=	yes
+USE_GCC=	4.8+
 .endif
 
 .if ${FFTW3_FLAVOR} == "default"
