--- Makefile.orig	2015-04-20 08:20:36 UTC
+++ Makefile
@@ -83,7 +83,12 @@ FFTW3_SUFX=	q
 FFTW3_PKGNAMESUFFIX=	-quad
 CONFIGURE_ARGS+=--enable-quad-precision
 ONLY_FOR_ARCHS=		i386 amd64
-USE_GCC=	yes
+USES+=		fortran
+CC=		gcc${_GCC_VER}
+CXX=		g++${_GCC_VER}
+CPP=		cpp${_GCC_VER}
+CFLAGS+=	-Wl,-rpath=${LOCALBASE}/lib/gcc${_GCC_VER}
+CXXFLAGS+=	-Wl,-rpath=${LOCALBASE}/lib/gcc${_GCC_VER}
 .endif
 
 .if ${FFTW3_FLAVOR} == "default"
