--- Makefile.orig	2013-03-31 10:20:36.000000000 +0000
+++ Makefile
@@ -19,8 +19,4 @@ USE_LDCONFIG=	yes
 
 .include <bsd.port.pre.mk>
 
-.if ${OSVERSION} >= 900004
-IGNORE=		is now contained in the base system
-.endif
-
 .include <bsd.port.post.mk>
