--- Makefile.orig	2016-04-07 08:07:40.000000000 +0300
+++ Makefile
@@ -13,10 +13,10 @@ COMMENT=	Genetic Algorithm Utility Libra
 
 LIB_DEPENDS=	libslang.so:devel/libslang2
 
-USES=		gmake libtool tar:bzip2
+USES=		gmake libtool ncurses tar:bzip2
 GNU_CONFIGURE=	yes
 CPPFLAGS+=	-I${LOCALBASE}/include
-LDFLAGS+=	-L${LOCALBASE}/lib -lcurses
+LDFLAGS+=	-L${LOCALBASE}/lib -lncurses
 INSTALL_TARGET=	install-strip
 USE_LDCONFIG=	yes
 
