--- Makefile.orig	2015-02-14 18:38:13 UTC
+++ Makefile
@@ -76,9 +76,6 @@ DEBUG_CONFIGURE_OFF=	--disable-debug-sym
 
 .include <bsd.port.options.mk>
 
-# Shutup warning spam
-CXXFLAGS+=	-Wno-c++11-extensions
-
 .if ${ARCH} == powerpc64
 CFLAGS+=	-mminimal-toc
 .endif
@@ -95,6 +92,7 @@ CONFIGURE_ENV+=	FLEX="${LOCALBASE}/bin/f
 .endif
 
 .if ${CHOSEN_COMPILER_TYPE} == clang
+CXXFLAGS+=	-Wno-c++11-extensions # Shutup warning spam
 CXXFLAGS+=	-Qunused-arguments
 .endif
 
