--- Makefile.orig	2020-10-28 10:57:40 UTC
+++ Makefile
@@ -47,7 +47,7 @@ RUBY_NO_BUILD_DEPENDS=	yes
 RUBY_NO_RUN_DEPENDS=	yes
 
 OPTIONS_DEFINE=		CAPIDOCS DEBUG DOCS EXAMPLES GMP RDOC
-OPTIONS_DEFAULT=	RDOC LIBEDIT
+OPTIONS_DEFAULT=	LIBEDIT
 OPTIONS_SINGLE=		EDIT
 OPTIONS_SINGLE_EDIT=	LIBEDIT READLINE
 OPTIONS_SUB=		yes
@@ -92,11 +92,6 @@ CONFIGURE_ARGS+=--disable-dtrace
 .endif
 .endif
 
-# keep in sync with all platforms where libunwind is available
-.if (${ARCH} == aarch64 || ${ARCH} == amd64 || ${ARCH} == i386 || ${ARCH:Mpowerpc64*})
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
-
 .if (${ARCH} == powerpc || ${ARCH} == powerpc64)
 USE_GCC=	yes
 .endif
