--- Makefile.orig	2018-01-15 06:51:56 UTC
+++ Makefile
@@ -46,7 +46,7 @@ RUBY_NO_BUILD_DEPENDS=	yes
 RUBY_NO_RUN_DEPENDS=	yes
 
 OPTIONS_DEFINE=		CAPIDOCS DEBUG DOCS EXAMPLES GMP RDOC
-OPTIONS_DEFAULT=	RDOC LIBEDIT
+OPTIONS_DEFAULT=	LIBEDIT
 OPTIONS_SINGLE=		EDIT
 OPTIONS_SINGLE_EDIT=	LIBEDIT READLINE
 OPTIONS_SUB=		yes
@@ -91,11 +91,6 @@ CONFIGURE_ARGS+=--disable-dtrace
 .endif
 .endif
 
-# keep in sync with all platforms where libunwind is available
-.if (${ARCH} == amd64 || ${ARCH} == i386)
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
-
 .if (${ARCH} == powerpc || ${ARCH} == powerpc64)
 USE_GCC=	yes
 .endif
