--- Makefile.orig	2019-02-26 16:28:26 UTC
+++ Makefile
@@ -61,10 +61,12 @@ OPENBLAS_BROKEN=	hits the number of thre
 
 # use clang from ports because cmake can't find OpenMP with base clang, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223678
 # have the same compiler for both serial and parallel flavors so that performance numbers can be compared
+.if ${OPSYS} == "FreeBSD"
 BUILD_DEPENDS+=	clang${LLVM_DEFAULT}:devel/llvm${LLVM_DEFAULT}
 CPP=		clang-cpp${LLVM_DEFAULT}
 CC=		clang${LLVM_DEFAULT}
 CXX=		clang++${LLVM_DEFAULT}
+.endif
 
 .if ${FLAVOR} == parallel
 post-install:
