--- Makefile.orig	2012-12-03 14:12:55.000000000 +0100
+++ Makefile	2012-12-10 18:26:31.838105000 +0100
@@ -32,7 +32,7 @@
 
 .include <bsd.port.pre.mk>
 
-JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.? -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1
+JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.? -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1 ; echo
 .if ${JDK_API} != ""
 MAKE_ARGS+=	-Dj2se.javadoc="${JDK_API}"
 .endif
