--- Makefile.orig	2023-07-28 19:49:25 UTC
+++ Makefile
@@ -37,14 +37,7 @@ PORTEXAMPLES=	openssl.cnf.sample
 OPTIONS_DEFINE=	EXAMPLES
 
 post-patch:
-	(${CAT} ${OPENSSLINC}/openssl/opensslv.h; \
-	 ${ECHO_CMD} "#if OPENSSL_VERSION_NUMBER < 0x10100000L"; \
-	 ${ECHO_CMD} "lib/openssl/engines/libtpm.so"; \
-	 ${ECHO_CMD} "#else"; \
-	 ${ECHO_CMD} "lib/openssl/engines/tpm.so"; \
-	 ${ECHO_CMD} "#endif"; \
-	) | ${CPP} | ${GREP} -v \# > ${WRKDIR}/.tpmso; \
-	${REINPLACE_CMD} "s|%%TPMSO%%|${PREFIX}/$$(cat ${WRKDIR}/.tpmso)|g" \
+	${REINPLACE_CMD} "s|%%TPMSO%%|${PREFIX}/lib/openssl/engines/tpm.so|g" \
 	    ${WRKSRC}/dist/openssl.cnf.sample
 
 .if defined(INSTALL_AS_USER)
