--- Makefile.orig	2015-08-24 12:38:44 UTC
+++ Makefile
@@ -58,7 +58,7 @@ UTF8_CFLAGS=		-DJS_C_STRINGS_ARE_UTF8
 .include <bsd.port.pre.mk>
 
 .if ${ARCH} == amd64
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 .if ${PORT_OPTIONS:MDTRACE}
