--- Makefile.orig	2014-09-15 18:49:28 UTC
+++ Makefile
@@ -11,11 +11,15 @@ MAINTAINER=	ports@FreeBSD.org
 COMMENT=	Anti-aliased font support for gtk+
 
 LIB_DEPENDS=	libXft.so:${PORTSDIR}/x11-fonts/libXft
+LIB_DEPENDS+=	libfontconfig.so:${PORTSDIR}/x11-fonts/fontconfig \
+		libfreetype.so:${PORTSDIR}/print/freetype2
 
 USE_GNOME=	gtk12
 USES=		iconv pkgconfig libtool
+USE_XORG=	x11 xft
+USES+=		gettext
 GNU_CONFIGURE=	yes
-LDFLAGS+=	-L${LOCALBASE}/lib -lgnuregex ${ICONV_LIB}
+LDFLAGS+=	-L${LOCALBASE}/lib ${ICONV_LIB}
 CFLAGS+=	`pkg-config xft --cflags`
 CONFIGURE_ARGS=	--sbindir=${PREFIX}/bin \
 		--without-gnome
@@ -29,7 +33,6 @@ post-patch:
 		's|src capplet|src @BUILD_CAPPLET_TRUE@capplet|g ; \
 		 s|DESTDIR)\$$(datadir|DESTDIR)\$$(pkgdatadir|g ; \
 		 s|la_LDFLAGS =.*$$|la_LDFLAGS = -module -avoid-version|g'
-	@${REINPLACE_CMD} 's/<regex\.h>/<gnuregex.h>/' ${WRKSRC}/src/gdkxft.c
 
 post-install:
 	@${MKDIR} ${STAGEDIR}${DOCSDIR}
