--- Makefile.orig	2013-10-13 18:19:09.801534000 +0000
+++ Makefile
@@ -11,12 +11,15 @@ MAINTAINER=	ports@FreeBSD.org
 COMMENT=	Anti-aliased font support for gtk+
 
 LIB_DEPENDS=	libXft.so:${PORTSDIR}/x11-fonts/libXft
+LIB_DEPENDS+=	fontconfig:${PORTSDIR}/x11-fonts/fontconfig
+LIB_DEPENDS+=	freetype:${PORTSDIR}/print/freetype2
 
 USE_AUTOTOOLS=	libtool
 USE_GNOME=	gtk12
-USES=		iconv pkgconfig
+USE_XORG+=	x11 xft
+USES=		iconv pkgconfig gettext
 GNU_CONFIGURE=	yes
-LDFLAGS+=	-L${LOCALBASE}/lib -lgnuregex ${ICONV_LIB}
+LDFLAGS+=	-L${LOCALBASE}/lib ${ICONV_LIB}
 CFLAGS+=	`pkg-config xft --cflags`
 CONFIGURE_ARGS=	--sbindir=${PREFIX}/bin \
 		--without-gnome
@@ -38,8 +41,8 @@ post-patch:
 		 s|DESTDIR)\$$(datadir|DESTDIR)\$$(pkgdatadir|g ; \
 		 s|la_LDFLAGS =.*$$|la_LDFLAGS = -module -avoid-version|g'
 .for file in gdkxft_sysinstall.in gdkxft.c generate.pl
-	@${REINPLACE_CMD} -e 's|<regex.h>|<gnuregex.h>|g ; \
-		 s|gtk-config |${GTK_CONFIG:T} |g' ${WRKSRC}/src/${file}
+	@${REINPLACE_CMD} -e 's|gtk-config |${GTK_CONFIG:T} |g' \
+	  ${WRKSRC}/src/${file}
 .endfor
 
 post-install:
