--- Makefile.orig	2022-07-12 22:34:37 UTC
+++ Makefile
@@ -11,10 +11,10 @@ COMMENT=	Portable hex editor with vi lik
 LICENSE=	BSD2CLAUSE
 LICENSE_FILE=	${WRKSRC}/COPYING
 
-USES=		python:3.6+
+USES=		python:3.6+ gettext-runtime
 USE_GITHUB=	yes
 GH_ACCOUNT=	kusumi
-USE_PYTHON=	autoplist concurrent distutils optsuffix
+USE_PYTHON=	autoplist concurrent distutils
 
 PLIST_FILES=	man/man1/fileobj.1.gz
 
