--- Makefile.orig	2023-07-28 18:04:51 UTC
+++ Makefile
@@ -10,10 +10,10 @@ WWW=		https://github.com/kusumi/fileobj
 LICENSE=	BSD2CLAUSE
 LICENSE_FILE=	${WRKSRC}/COPYING
 
-USES=		python
+USES=		python gettext-runtime
 USE_GITHUB=	yes
 GH_ACCOUNT=	kusumi
-USE_PYTHON=	autoplist concurrent distutils optsuffix
+USE_PYTHON=	autoplist concurrent distutils
 
 PLIST_FILES=	man/man1/fileobj.1.gz
 
