--- Makefile.orig	2017-02-14 11:05:30.000000000 +0200
+++ Makefile
@@ -44,12 +44,18 @@ USE_XORG+=	bigreqsproto compositeproto d
 		xineramaproto xkbfile xproto xshmfence xtrans
 CONFIGURE_ARGS+=--without-doxygen --without-xmlto --without-fop \
 		--localstatedir=/var --with-shared-memory-dir=/tmp \
-		--without-dtrace --enable-glamor
+		--without-dtrace --enable-glamor --disable-dri3
 INSTALL_TARGET=	install-strip
 
 .if ${SLAVE_PORT} == "no" || ${PORTNAME} == "xephyr" || ${PORTNAME} == "xwayland"
 LIB_DEPENDS+=	libdrm.so:graphics/libdrm \
 		libepoxy.so:graphics/libepoxy
+# Recommended by M.Dillon for sane security defaults
+CONFIGURE_ARGS+=	--enable-xcsecurity
+# zrj: no glamor for xwayland (needs DRI3)
+. if ${PORTNAME} == "xwayland"
+CONFIGURE_ARGS+= --disable-glamor
+. endif
 .else
 BUILD_DEPENDS+=	libepoxy>0:graphics/libepoxy	# only for configure
 .endif
@@ -86,9 +92,9 @@ CONFIGURE_ARGS+=	--disable-config-hal
 # We handle Xorg setuid in the plist. This allows to build xorg-server as a user.
 CONFIGURE_ARGS+=--disable-install-setuid
 
-.if ${ARCH} == "i386" || ${ARCH} == "amd64"
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
+#.if ${ARCH} == "i386" || ${ARCH} == "amd64"
+#LIB_DEPENDS+=	libunwind.so:devel/libunwind
+#.endif
 
 .if ${ARCH} == "sparc64"
 PLIST_SUB+=	SPARC64=""
