--- Makefile.orig	2023-04-11 19:28:35 UTC
+++ Makefile
@@ -69,8 +69,8 @@ MESON_ARGS+=	-D${f}=false
 .endfor
 
 .if ${FLAVOR} == xorg
-LIB_DEPENDS+=		libudev.so:devel/libudev-devd \
-			libxcvt.so:x11/libxcvt
+LIB_DEPENDS+=	libudev.so:devel/libudev-devd \
+		libxcvt.so:x11/libxcvt
 MESON_ARGS+=	-Dudev=true \
 		-Dlog_dir=/var/log \
 		-Dsuid_wrapper=true
@@ -82,6 +82,10 @@ MESON_ARGS+=	-Dudev=false
 MESON_ARGS+=	-Ddrm=true
 LIB_DEPENDS+=	libdrm.so:graphics/libdrm \
 		libepoxy.so:graphics/libepoxy
+# zrj: no glamor for xwayland (needs DRI3)
+. if ${PORTNAME} == "xwayland"
+CONFIGURE_ARGS+= --disable-dri3 --disable-glamor
+. endif
 .endif
 
 .if ${FLAVOR} == xephyr
@@ -120,7 +124,7 @@ USE_XORG+=	pciaccess
 MESON_ARGS+=	-Dsha1=libmd
 .endif
 
-.if ${ARCH} == aarch64 || ${ARCH} == amd64 || ${ARCH} == armv7 || ${ARCH} == i386 || ${ARCH} == powerpc64 || ${ARCH} == powerpc64le
+.if ${ARCH} == aarch64 || ${ARCH} == x86_64 || ${ARCH} == armv7 || ${ARCH} == i386 || ${ARCH} == powerpc64 || ${ARCH} == powerpc64le
 LIB_DEPENDS+=	libunwind.so:devel/libunwind
 .endif
 
