--- Makefile.orig	2014-07-17 16:34:48.201427000 +0000
+++ Makefile
@@ -55,8 +55,8 @@ MVN_LOCAL_REPO=	-Dmaven.repo.local=${WRK
 MVN_TEST_FLAG=	-Dmaven.test.skip=true
 MVN_SETTINGS+=	--offline
 ECLIPSE_WS=	gtk
-ECLIPSE_ARCH=	x86${ARCH:C/^i.86//:C/^amd/_/}
-E_SHORTARCH=	${ARCH:C/^i.86//:C/^amd//}
+ECLIPSE_ARCH=	x86${ARCH:C/^i.86//:C/^amd/_/:S/x86_64/_64/}
+E_SHORTARCH=	${ARCH:C/^i.86//:C/^amd//:S/x86_64/64/}
 ECLIPSE_BUILDID=M20140224-0627
 SCRIPTS_ENV+=	ECLIPSE_ARCH=${ECLIPSE_ARCH} \
 		E_SHORTARCH=${E_SHORTARCH}
@@ -84,6 +84,8 @@ post-patch:
 	  ${ECHO_MSG} "Updating ECLIPSE_ARCH in file $$f"; \
 	  ${REINPLACE_CMD} -e "s|%%ECLIPSE_ARCH%%|${ECLIPSE_ARCH}|g" ${WRKSRC}/$$f; \
 	done)
+	find ${WRKSRC} -name "build.sh" -print0 | \
+		${XARGS} -0 ${REINPLACE_CMD} -e 's|`uname -s|`echo FreeBSD|g'
 
 do-build:
 	@(cd ${WRKSRC}; ${SETENV} JAVA_HOME=${JAVA_HOME} M2_HOME=${LOCALBASE}/share/java/maven31 ${MVN_OPTS} \
