diff --git a/devel/xsd/Makefile b/devel/xsd/Makefile
index 010b73e6e9e..fe54513871f 100644
--- a/devel/xsd/Makefile
+++ b/devel/xsd/Makefile
@@ -31,7 +31,7 @@ USE_CXXSTD=   c++11
 MAKEFILE=      makefile
 MAKE_ARGS=     EXTERNAL_LIBCUTL=y \
                install_prefix=${STAGEDIR}${PREFIX} \
-               install_man_dir=${STAGEDIR}${MANPREFIX}/man \
+               install_man_dir=${STAGEDIR}${PREFIX}/share/man \
                verbose=1
 ALL_TARGET=    # no default target should be passed to gmake.

