--- Makefile.orig	2020-07-28 23:01:28 UTC
+++ Makefile
@@ -40,10 +40,6 @@ CONFIGURE_ARGS=	--disable-dependency-tra
 
 CFLAGS_i386=	-march=i486
 
-# This port has a problem with -pthread,
-# force to use -lthr until it's not fixed.
-LDFLAGS+=	-lthr
-
 SUB_FILES=	pkg-deinstall
 SUB_LIST+=	DBDIR=${DBDIR} \
 		LOGDIR=${LOGDIR} \
