--- Makefile.orig	2016-02-22 17:23:17 UTC
+++ Makefile
@@ -82,10 +82,7 @@ CONFIGURE_ARGS=	--libdir=${PREFIX}/lib \
 		--disable-dependency-tracking \
 		--enable-clamdtop
 CPPFLAGS+=	-I${LOCALBASE}/include
-
-# This port has a problem with -pthread,
-# force to use -lthr until it's not fixed.
-LDFLAGS+=	-lthr -L${LOCALBASE}/lib
+LDFLAGS+=	-L${LOCALBASE}/lib
 
 CONFLICTS?=	clamav-milter-[0-9]*
 
