--- Makefile.orig	2012-12-03 14:20:19.000000000 +0100
+++ Makefile	2012-12-10 18:30:52.215582000 +0100
@@ -29,7 +29,7 @@
 
 .include <bsd.port.pre.mk>
 
-JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.? -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1
+JDK_API!=	(${FIND} -s ${LOCALBASE}/share/doc/jdk1.? -maxdepth 1 -name api -type d 2>/dev/null || ${TRUE}) | ${TAIL} -n 1 ; echo
 .if ${JDK_API} != ""
 MAKE_ARGS+=	-Djavadoc.srcdir.j2se=${JDK_API}
 
