--- Makefile.orig	2014-06-02 10:27:19.146109000 +0000
+++ Makefile
@@ -90,6 +90,7 @@ CONFIGURE_ARGS+=	--without-mdb
 
 .if ${LIBGDA5_SLAVE}==jdbc
 USE_JAVA=		yes
+JAVA_VERSION=		1.6
 JAVA_VENDOR=		bsdjava openjdk
 .else
 CONFIGURE_ARGS+=	--without-java
