--- Makefile.orig	2013-06-14 09:41:54.032806000 +0000
+++ Makefile
@@ -31,8 +31,8 @@ CMAKE_ARGS+=	-DINSTALL_DOCDIR="share/doc
 		-DINSTALL_SHAREDIR="share" \
 		-DINSTALL_SQLBENCHDIR="share/mysql" \
 		-DINSTALL_SUPPORTFILESDIR="share/mysql" \
-		-DWITH_EDITLINE=system \
-		-DWITH_LIBWRAP=1
+		-DWITH_EDITLINE=0 \
+		-DWITH_READLINE=1
 
 .ifdef USE_MYSQL
 .error You have `USE_MYSQL' variable defined either in environment or in make(1) arguments. Please undefine and try again.
