--- Makefile.orig	2014-08-02 11:10:06.856441000 +0000
+++ Makefile
@@ -63,7 +63,6 @@ MAN1=		my_print_defaults.1 myisam_ftdump
 
 CMAKE_ARGS+=	-DWITH_EMBEDDED_SERVER="ON"
 .else
-USES+=		readline
 .endif
 
 post-patch:
