--- Makefile.orig	2013-08-14 22:35:50.000000000 +0000
+++ Makefile
@@ -13,7 +13,7 @@ MAINTAINER=	ale@FreeBSD.org
 COMMENT?=	Multithreaded SQL database (server)
 
 SLAVEDIRS=	databases/mysql56-client
-USES=		cmake
+USES=		cmake shebangfix
 
 CMAKE_ARGS+=	-DINSTALL_DOCDIR="share/doc/mysql" \
 		-DINSTALL_DOCREADMEDIR="share/doc/mysql" \
@@ -33,6 +33,8 @@ CMAKE_ARGS+=	-DINSTALL_DOCDIR="share/doc
 		-DWITH_EDITLINE=system \
 		-DWITH_LIBWRAP=1
 
+SHEBANG_FILES=	scripts/*.pl* scripts/*.sh
+
 .ifdef USE_MYSQL
 .error You have `USE_MYSQL' variable defined either in environment or in make(1) arguments. Please undefine and try again.
 .endif
