--- Makefile.orig	2013-08-18 08:11:57.260965000 +0000
+++ Makefile
@@ -1,16 +1,12 @@
-# New ports collection makefile for:	uk-webalizer
-# Date created:		22 May 2001
-# Whom:			mike@LITech.lviv.ua
-#
+# Created by: mike@LITech.lviv.ua
 # $FreeBSD: ports/ukrainian/webalizer/Makefile,v 1.8 2012/11/17 06:02:26 svnexp Exp $
-#
 
 MASTERDIR=	${.CURDIR}/../../www/webalizer
 CATEGORIES=	ukrainian
 
 MAINTAINER=	mikef@LITech.lviv.ua
 
-LIB_DEPENDS=	gd.4:${PORTSDIR}/ukrainian/gd
+LIB_DEPENDS=	gd:${PORTSDIR}/ukrainian/gd
 
 WEBALIZER_LANG=	ukrainian
 
