--- Makefile.orig	2013-08-11 02:32:30.000000000 +0000
+++ Makefile
@@ -21,11 +21,11 @@ USE_GCC=	any
 USE_GL=		yes
 USE_AUTOTOOLS=	libtool
 CFLAGS+=	${PTHREAD_CFLAGS}
-CONFIGURE_ENV=	ARCH="${OPSYS:tl}"
+CONFIGURE_ENV=	ARCH=freebsd
 CPPFLAGS+=	${CXXFLAGS} -I${LOCALBASE}/include
 LDFLAGS+=	-L${LOCALBASE}/lib
 NO_MTREE=	yes
-PLIST_SUB=	ARCH=${OPSYS:tl}
+PLIST_SUB=	ARCH=freebsd
 PKGMESSAGE=	${WRKDIR}/pkg-message
 
 .if defined(WITH_HDF) && !defined(WITHOUT_NETCDF)
