--- Makefile.orig	2016-01-05 22:32:04 UTC
+++ Makefile
@@ -1,5 +1,5 @@
 # Created by: Michael Johnson <ahze@FreeBSD.org>
-# $FreeBSD: head/multimedia/gstreamer1-plugins-all/Makefile 405242 2016-01-04 14:21:56Z kwm $
+# $FreeBSD$
 
 PORTNAME=	gstreamer1-plugins-all
 PORTVERSION=	${GST1_VERSION}
@@ -7,35 +7,38 @@ PORTREVISION=	2
 CATEGORIES=	multimedia
 
 MAINTAINER=	multimedia@FreeBSD.org
-COMMENT=	Meta-port of all GStreamer 1.x plugins with options
+COMMENT=	Meta-port of all gstreamer 1.x plugins with options
 
 USES=		metaport
-
 USE_GSTREAMER1=	yes
 
 .include "${.CURDIR}/../../Mk/bsd.gstreamer.mk"
 
-.for all in ${_GSTREAMER_PLUGINS}
-OPTIONS_DEFINE+=	${all:tu}
+ALL_PLUGINS:=	${_GSTREAMER_PLUGINS}
+# Weed out gst-plugins that can not be packaged. or are broken.
+.if defined(PACKAGE_BUILDING)
+# FAAC:    Mp4 Dolby license , no package
+# LAME:    MP3 License , no package
+# VDPAU:   Needs to be build agains running kernel
+DEF_PLUGINS:=	${_GSTREAMER_PLUGINS:Nfaac:Nlame:Nvdpau}
+.else
+DEF_PLUGINS:=	${_GSTREAMER_PLUGINS}
+.endif
+
+.for all in ${ALL_PLUGINS}
 ${all:tu}_DESC=	${all} plugin
-OPTIONS_DEFAULT+=	${all:tu}
+${all:tu}_USE=	GSTREAMER=${all}
 .endfor
 
-.include <bsd.port.options.mk>
+# Pull out i386-only plugins, add back conditionally
+ALL_PLUGINS:=	${ALL_PLUGINS:Nspc}
+DEF_PLUGINS:=	${DEF_PLUGINS:Nspc}
 
-# Weed out gst-plugins that can not be packaged. or are broken.
-.if defined(PACKAGE_BUILDING)
-PORT_OPTIONS:=	${PORT_OPTIONS:NFAAC} # Mp4 Dolby license , no package
-PORT_OPTIONS:=	${PORT_OPTIONS:NLAME} # MP3 License , no package
-PORT_OPTIONS:=	${PORT_OPTIONS:NVDPAU} # Needs to be build agains running kernel
-.endif
+OPTIONS_DEFINE=	${ALL_PLUGINS:tu}
+OPTIONS_DEFAULT=	${DEF_PLUGINS:tu}
 
 OPTIONS_DEFINE_i386=	SPC
+OPTIONS_DEFAULT_i386=	SPC
 
-.for f in ${OPTIONS_DEFINE}
-.if ${PORT_OPTIONS:M${f:tu}}
-USE_GSTREAMER1+=${f:tl}
-.endif
-.endfor
-
+.include <bsd.port.options.mk>
 .include <bsd.port.mk>
