# Created by: Pakhom Golynga <pg@pakhom.spb.ru>

PORTNAME=	zabbix6
CATEGORIES=	net-mgmt
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix6-server

OPTIONS_SINGLE_DB=	MYSQL PGSQL SQLITE ORACLE

.include "${MASTERDIR}/Makefile"
