--- Makefile.orig	2017-01-24 05:54:53 UTC
+++ Makefile
@@ -14,7 +14,7 @@ COMMENT=	Julia Language: A fresh approac
 LICENSE=	MIT
 LICENSE_FILE=	${WRKSRC}/LICENSE.md
 
-LIB_DEPENDS=	libunwind.so:devel/libunwind \
+LIB_DEPENDS=	 \
 		libutf8proc.so:textproc/utf8proc \
 		libopenblas.so:math/openblas \
 		libgit2.so:devel/libgit2 \
@@ -36,11 +36,13 @@ ALL_TARGET=	default
 INSTALL_TARGET=	install
 TEST_TARGET=	test
 
-CXXFLAGS+=	-stdlib=libc++ -std=c++11
+USE_CXXSTD=	c++11 # rest were clang'isms
 MAKE_ARGS+=	prefix=${PREFIX} JCXXFLAGS="${CXXFLAGS}" \
 		FORCE_ASSERTIONS=${FORCE_ASSERTIONS} \
 		USE_GPL_LIBS=${USE_GPL_LIBS}
 
+MAKE_ARGS+= VERBOSE=1 # show what are you doing instead of hiding it
+
 OPTIONS_DEFINE=	EXAMPLES DEBUG DOCS GPL_LIBS DESKTOP NATIVE
 OPTIONS_SUB=	yes
 
@@ -83,7 +85,7 @@ EXTRA_PATCHES+=	${PATCHDIR}/extra-patch-
 .endif
 
 post-configure:
-	${CC} ${CFLAGS} -lopenblas ${LDFLAGS} -o ${WRKSRC}/check_openblas \
+	${CC} ${CFLAGS} -L${LOCALBASE}/lib -lopenblas ${LDFLAGS} -o ${WRKSRC}/check_openblas \
 		${FILESDIR}/check_openblas.c
 	${WRKSRC}/check_openblas && ( \
 		echo "USE_BLAS64=1" >> ${WRKSRC}/Make.user \
