--- Makefile.orig	2013-03-28 13:43:19.000000000 +0000
+++ Makefile
@@ -85,6 +85,8 @@ CONFIGURE_ARGS+=	--disable-optimize
 
 .if ${PORT_OPTIONS:MREADLINE}
 CONFIGURE_ARGS+=	--enable-readline
+LIB_DEPENDS+=		readline:${PORTSDIR}/devel/readline
+LDFLAGS+=		-L${LOCALBASE}/lib
 .else
 CONFIGURE_ARGS+=	--disable-readline
 .endif
