--- Makefile.orig	2022-12-16 18:08:00.168486000 +0100
+++ Makefile	2022-12-16 18:08:13.189019000 +0100
@@ -77,7 +77,7 @@ post-extract:
 	@cd ${QL_DIR}/dists/quicklisp/software && ${TAR} xzf ${DISTDIR}/${DIST_SUBDIR}/${t}
 .  endfor
 	# fixups: same effect as https://github.com/cffi/cffi/pull/332
-	@${REINPLACE_CMD} -e 's|:openbsd "libffi.so"|:freebsd "libffi.so"|' ${QL_DIR}/dists/quicklisp/software/cffi_0.24.1/libffi/libffi.lisp
+	@${REINPLACE_CMD} -e 's|:openbsd "libffi.so"|:dragonfly "libffi.so"|' ${QL_DIR}/dists/quicklisp/software/cffi_0.24.1/libffi/libffi.lisp
 
 post-install:
 	${INSTALL_LIB} ${QL_DIR}/dists/quicklisp/software/magicl-v0.9.1/expokit/libexpokit.so ${STAGEDIR}${PREFIX}/lib
