OPTIONS_DEFAULT+= PULSEAUDIO

post-extract:
	@${REINPLACE_CMD} -e 's|_SAFE|_MUTABLE|g' \
		${WRKSRC}/netwerk/sctp/src/netinet/sctp_asconf.c \
		${WRKSRC}/netwerk/sctp/src/netinet/sctp_bsd_addr.c \
		${WRKSRC}/netwerk/sctp/src/netinet/sctp_indata.c \
		${WRKSRC}/netwerk/sctp/src/netinet/sctp_input.c \
		${WRKSRC}/netwerk/sctp/src/netinet/sctp_output.c \
		${WRKSRC}/netwerk/sctp/src/netinet/sctp_pcb.c \
		${WRKSRC}/netwerk/sctp/src/netinet/sctp_timer.c \
		${WRKSRC}/netwerk/sctp/src/netinet/sctputil.c
