--- Makefile.orig	2013-08-26 09:28:27.000000000 +0000
+++ Makefile
@@ -33,6 +33,7 @@ USE_OPENSSL=	yes
 USES=		gettext
 GNU_CONFIGURE=	yes
 USE_LDCONFIG=	yes
+MAKE_JOBS_UNSAFE=yes
 CONFIGURE_ARGS+=	--with-libintl=${LOCALBASE} \
 			--with-readline=${DESTDIR}/usr \
 			--enable-pthread-support \
