--- Makefile.orig	2016-08-20 18:29:22 UTC
+++ Makefile
@@ -28,4 +28,9 @@ OPTIONS_EXCLUDE=	DOCS EXAMPLES
 CONFIGURE_ENV=	PYTHON_INCLUDEDIR="${PYTHON_INCLUDEDIR}" \
 		PYTHON_VERSION="${PYTHON_VERSION}"
 
+# total hack for python distutils garbage
+# It's too stupid to use c++ for .cpp files
+CC=		c++
+USE_CSTD=	c++11
+
 .include "${MASTERDIR}/Makefile"
