--- Makefile.orig	2013-02-18 19:42:49.111383000 +0100
+++ Makefile	2013-02-18 19:43:15.320212000 +0100
@@ -31,12 +31,14 @@
 			--enable-ecore-imf \
 			--enable-ecore-imf_evas
 
+LDFLAGS+=	-L${LOCALBASE}/lib
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/ecore/\.libs,${LOCALBASE}/lib,'\
 		-e 's,\$$\(top_builddir\)/src/lib/ecore_imf/\.libs,${LOCALBASE}/lib,'\
-		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,-lecore,'\
-		-e 's,\$$\(top_builddir\)/src/lib/ecore_imf/libecore_imf\.la,-lecore_imf,'\
+		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,,'\
+		-e 's,\$$\(top_builddir\)/src/lib/ecore_imf/libecore_imf\.la,,'\
 		${BUILD_WRKSRC}/Makefile.in
 
 post-install:
