--- Makefile.orig	2018-11-22 03:27:21 UTC
+++ Makefile
@@ -71,9 +71,8 @@ IGNORE=		cannot build node.js with Libre
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} == armv6 || ${ARCH} == armv7
+# something is wrong with configure wrt to DF I think
 CONFIGURE_ARGS+=--openssl-no-asm
-.endif
 
 .if ${COMPILER_TYPE} == gcc
 # GCC does not expose std::snprintf() without this define
