--- Makefile.orig	2014-05-27 19:47:06.859706000 +0000
+++ Makefile
@@ -13,10 +13,13 @@ MASTER_SITES=	http://download.java.net/o
 		http://icedtea.classpath.org/download/drops/:jaxws \
 		https://java.net/downloads/jax-ws/JDK7/:jaf \
 		http://icedtea.classpath.org/download/drops/:jaf \
+		http://dl.wolfpond.org/openjdk7/:bootstrap \
 		${MASTER_SITE_APACHE:S,%SUBDIR%/,ant/binaries/:ant,}
 DISTFILES=	${JDK_SRC_DISTFILE}${EXTRACT_SUFX} \
+		${BOOTSTRAP_DISTFILE}:bootstrap \
 		${ANT_DISTFILE}${EXTRACT_SUFX}:ant
 EXTRACT_ONLY=	${JDK_SRC_DISTFILE}${EXTRACT_SUFX} \
+		${BOOTSTRAP_DISTFILE} \
 		${ANT_DISTFILE}${EXTRACT_SUFX}
 
 MAINTAINER=	glewis@FreeBSD.org
@@ -61,9 +64,12 @@ RUN_DEPENDS+=	javavm:${PORTSDIR}/java/ja
 
 DOS2UNIX_FILES=	jdk/src/share/classes/com/sun/org/apache/xml/internal/security/resource/xmlsecurity_en.properties
 
-OPENJDK_OSARCH=	bsd-${ARCH:S/i386/i586/}
+JDK_ARCH=	${ARCH:S/x86_64/amd64/}
+OPENJDK_OSARCH=	bsd-${JDK_ARCH:S/i386/i586/}
 INSTALLDIR=	${PREFIX}/${PORTNAME}${JDK_MAJOR_VERSION}
 
+BOOTSTRAP_DISTFILE=	bootstrap-openjdk-7.9.05_2.dfly-3.3-${JDK_ARCH}.tar.xz
+BOOTSTRAP_LIBDIRS=	${BOOTSTRAPJDKDIR}/jre/lib/${JDK_ARCH}
 NOPRECIOUSMAKEVARS=	yes
 
 ONLY_FOR_ARCHS=	i386 amd64
@@ -72,7 +78,7 @@ MAKE_ENV+=	LANG="C" \
 		LC_ALL="C" \
 		JAVA_HOME="" \
 		CLASSPATH="" \
-		LD_LIBRARY_PATH="" \
+		LD_LIBRARY_PATH="${BOOTSTRAP_LIBDIRS}" \
 		MAKEFLAGS="" \
 		ALT_BOOTDIR="${BOOTSTRAPJDKDIR}" \
 		ALT_FREETYPE_HEADERS_PATH="${LOCALBASE}/include" \
@@ -98,10 +104,7 @@ MAKE_ENV+=	LANG="C" \
 		BUILD_NUMBER="b${PORT_BUILD_NUMBER}"
 
 MAKE_ENV+=	HOTSPOT_BUILD_JOBS=${MAKE_JOBS_NUMBER}
-
-BOOTSTRAP_JDKS=	${LOCALBASE}/openjdk7 \
-		${LOCALBASE}/openjdk6 \
-		${LOCALBASE}/bootstrap-openjdk
+MAKE_ENV+=	ALT_PARALLEL_COMPILE_JOBS=${MAKE_JOBS_NUMBER}
 
 DEBUG_MAKE_ENV=	ALT_OBJCOPY=${NONEXISTENT}
 POLICY_MAKE_ENV=	UNLIMITED_CRYPTO=1
@@ -109,19 +112,16 @@ TZUPDATE_RUN_DEPENDS=	${LOCALBASE}/share
 
 .include <bsd.port.options.mk>
 
-# do we have valid native jdk installed?
-.for BJDK in ${BOOTSTRAP_JDKS}
-.  if !defined(BOOTSTRAPJDKDIR) && exists(${BJDK}/bin/javac)
-BOOTSTRAPJDKDIR=	${BJDK}
+.if ${OPSYS} == DragonFly && ${DFLYVERSION} > 300500
+.  if ${DFLYVERSION} < 300503
+BOOTSTRAP_DISTFILE= bootstrap-openjdk-7.21.11.dfly-3.5-${JDK_ARCH}.tar.xz
+.  else
+BOOTSTRAP_DISTFILE= bootstrap-openjdk-7.25.15.dfly-3.5-${JDK_ARCH}.tar.xz
 .  endif
-.endfor
-
-# if no valid jdk found, set dependency
-.if !defined(BOOTSTRAPJDKDIR)
-BOOTSTRAPJDKDIR?=	${LOCALBASE}/bootstrap-openjdk
-BUILD_DEPENDS+=		${BOOTSTRAPJDKDIR}/bin/javac:${PORTSDIR}/java/bootstrap-openjdk
 .endif
 
+BOOTSTRAPJDKDIR=	${WRKDIR}/bootstrap
+
 .include <bsd.port.pre.mk>
 
 .if empty(ICONV_LIB)
@@ -140,6 +140,11 @@ post-patch:
 		${WRKSRC}/jdk/make/java/instrument/Makefile
 .endif
 
+# override do-build to filter out _MAKE_JOBS to enable parallel build
+do-build:
+	@cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} ${MAKE_CMD} \
+		${MAKE_FLAGS} ${MAKEFILE} ${MAKE_ARGS} ${ALL_TARGET}
+
 .if ${PORT_OPTIONS:MTZUPDATE}
 pre-install:
 	@# Update time zones
@@ -152,6 +157,7 @@ do-install:
 	@${MKDIR} ${STAGEDIR}${INSTALLDIR}
 	@cd ${WRKSRC}/build/${OPENJDK_OSARCH}/j2sdk-image && \
 		${PAX} -rw . ${STAGEDIR}${INSTALLDIR}
+	@cd ${STAGEDIR}${PREFIX}/openjdk7/include && ln -s dragonfly freebsd
 	@${INSTALL_DATA} ${WRKSRC}/build/${OPENJDK_OSARCH}/btjars/compilefontconfig.jar ${WRKSRC}/build/${OPENJDK_OSARCH}/btjars/javazic.jar ${STAGEDIR}${INSTALLDIR}/jre/lib/
 	@${INSTALL_DATA} ${FILESDIR}/cacerts ${STAGEDIR}${INSTALLDIR}/jre/lib/security/cacerts
 	@${ECHO} "@unexec ${LOCALBASE}/bin/unregistervm ${INSTALLDIR}/bin/java" >> ${TMPPLIST}
