--- Makefile.orig	2015-09-10 17:00:18 UTC
+++ Makefile
@@ -11,13 +11,17 @@ MASTER_SITES=	http://download.java.net/o
 		http://icedtea.classpath.org/download/drops/:jaxp \
 		http://download.java.net/glassfish/components/jax-ws/openjdk/jdk7/:jaxws \
 		http://icedtea.classpath.org/download/drops/:jaxws \
+		http://dl.wolfpond.org/openjdk7/:bootstrap \
+		http://leaf.dragonflybsd.org/~marino/dports-src/:bootstrap \
 		https://java.net/downloads/jax-ws/JDK7/:jaf \
 		http://icedtea.classpath.org/download/drops/:jaf \
 		APACHE/ant/binaries/:ant
 PATCH_SITES=	LOCAL/glewis/openjdk7
 DISTFILES=	${JDK_SRC_DISTFILE}${EXTRACT_SUFX} \
+		${BOOTSTRAP_DISTFILE}:bootstrap \
 		${ANT_DISTFILE}${EXTRACT_SUFX}:ant
 EXTRACT_ONLY=	${JDK_SRC_DISTFILE}${EXTRACT_SUFX} \
+		${BOOTSTRAP_DISTFILE} \
 		${ANT_DISTFILE}${EXTRACT_SUFX}
 PATCHFILES=	patch-7u45-b30.xz \
 		patch-7u51-b30.xz \
@@ -78,8 +82,10 @@ RUN_DEPENDS+=	javavm:${PORTSDIR}/java/ja
 
 DOS2UNIX_FILES=	jdk/src/share/classes/com/sun/org/apache/xml/internal/security/resource/xmlsecurity_en.properties
 
-OPENJDK_OSARCH=	bsd-${ARCH:S/i386/i586/}
+JDK_ARCH=	${ARCH:S/x86_64/amd64/}
+OPENJDK_OSARCH=	bsd-${JDK_ARCH:S/i386/i586/}
 
+BOOTSTRAP_LIBDIRS=	${BOOTSTRAPJDKDIR}/jre/lib/${JDK_ARCH}
 NOPRECIOUSMAKEVARS=	yes
 
 ONLY_FOR_ARCHS=	i386 amd64
@@ -89,7 +95,7 @@ MAKE_ENV+=	LANG="C" \
 		LC_ALL="C" \
 		JAVA_HOME="" \
 		CLASSPATH="" \
-		LD_LIBRARY_PATH="" \
+		LD_LIBRARY_PATH="${BOOTSTRAP_LIBDIRS}" \
 		MAKEFLAGS="" \
 		ALT_BOOTDIR="${BOOTSTRAPJDKDIR}" \
 		ALT_FREETYPE_HEADERS_PATH="${LOCALBASE}/include" \
@@ -115,10 +121,7 @@ MAKE_ENV+=	LANG="C" \
 		BUILD_NUMBER="b${PORT_BUILD_NUMBER}"
 
 MAKE_ENV+=	HOTSPOT_BUILD_JOBS=${MAKE_JOBS_NUMBER}
-
-BOOTSTRAP_JDKS=	${LOCALBASE}/openjdk7 \
-		${LOCALBASE}/openjdk6 \
-		${LOCALBASE}/bootstrap-openjdk
+MAKE_ENV+=	ALT_PARALLEL_COMPILE_JOBS=${MAKE_JOBS_NUMBER}
 
 DEBUG_MAKE_ENV=	ALT_OBJCOPY=${NONEXISTENT}
 POLICY_MAKE_ENV=	UNLIMITED_CRYPTO=1
@@ -126,23 +129,21 @@ TZUPDATE_RUN_DEPENDS=	java-zoneinfo>0:${
 
 .include <bsd.port.options.mk>
 
-# do we have valid native jdk installed?
-.for BJDK in ${BOOTSTRAP_JDKS}
-.  if !defined(BOOTSTRAPJDKDIR) && exists(${BJDK}/bin/javac)
-BOOTSTRAPJDKDIR=	${BJDK}
+.if ${OPSYS} == DragonFly
+.  if ${DFLYVERSION} < 400303 # after verification, openjdk6 can be used for all DF versions
+BOOTSTRAP_DISTFILE= bootstrap-openjdk-7.25.15.dfly-3.5-${JDK_ARCH}.tar.xz
+.  else
+BOOTSTRAP_DISTFILE= bootstrap-openjdk6-6.0.tar.xz
+BUILD_DEPENDS+=	gcc48:${PORTSDIR}/lang/gcc
 .  endif
-.endfor
-
-# if no valid jdk found, set dependency
-.if !defined(BOOTSTRAPJDKDIR)
-BOOTSTRAPJDKDIR?=	${LOCALBASE}/bootstrap-openjdk
-BUILD_DEPENDS+=		${BOOTSTRAPJDKDIR}/bin/javac:${PORTSDIR}/java/bootstrap-openjdk
 .endif
 
+BOOTSTRAPJDKDIR=	${WRKDIR}/bootstrap
+
 .include <bsd.port.pre.mk>
 
 # GCC is broken with PCH: https://lists.freebsd.org/pipermail/svn-src-all/2015-March/101722.html
-.if ${COMPILER_TYPE} == gcc
+.if ${OPSYS} == FreeBSD && ${COMPILER_TYPE} == gcc
 MAKE_ENV+=	USE_PRECOMPILED_HEADER=0
 .endif
 
@@ -162,6 +163,11 @@ post-patch:
 		${WRKSRC}/jdk/make/java/instrument/Makefile
 .endif
 
+# override do-build to filter out _MAKE_JOBS to enable parallel build
+do-build:
+	@cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} ${MAKE_CMD} \
+		${MAKE_FLAGS} ${MAKEFILE} ${MAKE_ARGS} ${ALL_TARGET}
+
 .if ${PORT_OPTIONS:MTZUPDATE}
 pre-install:
 	@# Update time zones
@@ -181,6 +187,7 @@ do-install:
 .if !defined(BUILD_JRE)
 	cd ${WRKSRC}/build/${OPENJDK_OSARCH}/j2sdk-image && \
 	    ${PAX} -rw . ${STAGEDIR}${INSTALLDIR}
+	@cd ${STAGEDIR}${PREFIX}/openjdk7/include && ln -s dragonfly freebsd
 	${INSTALL_DATA} \
 	    ${WRKSRC}/build/${OPENJDK_OSARCH}/btjars/compilefontconfig.jar \
 	    ${WRKSRC}/build/${OPENJDK_OSARCH}/btjars/javazic.jar \
