--- Makefile.orig	2014-03-29 22:36:12.939466000 +0000
+++ Makefile
@@ -13,10 +13,13 @@ MASTER_SITES=	http://download.java.net/o
 		http://icedtea.classpath.org/download/drops/:jaxws \
 		https://java.net/downloads/jax-ws/JDK7/:jaf \
 		http://icedtea.classpath.org/download/drops/:jaf \
+		http://dl.wolfpond.org/openjdk7/:bootstrap \
 		${MASTER_SITE_APACHE:S,%SUBDIR%/,ant/binaries/:ant,}
 DISTFILES=	${JDK_SRC_DISTFILE}${EXTRACT_SUFX} \
+		${BOOTSTRAP_DISTFILE}:bootstrap \
 		${ANT_DISTFILE}${EXTRACT_SUFX}:ant
 EXTRACT_ONLY=	${JDK_SRC_DISTFILE}${EXTRACT_SUFX} \
+		${BOOTSTRAP_DISTFILE} \
 		${ANT_DISTFILE}${EXTRACT_SUFX}
 
 MAINTAINER=	glewis@FreeBSD.org
@@ -56,15 +59,19 @@ LIB_DEPENDS+=	freetype:${PORTSDIR}/print
 		asound:${PORTSDIR}/audio/alsa-lib
 BUILD_DEPENDS+=	zip:${PORTSDIR}/archivers/zip \
 		${UNZIP_CMD}:${PORTSDIR}/archivers/unzip \
+		javavm:${PORTSDIR}/java/javavmwrapper \
 		${LOCALBASE}/include/cups/cups.h:${PORTSDIR}/print/cups-client
 RUN_DEPENDS+=	javavm:${PORTSDIR}/java/javavmwrapper \
 		${LOCALBASE}/lib/X11/fonts/dejavu:${PORTSDIR}/x11-fonts/dejavu
 
 USE_DOS2UNIX=	jdk/src/share/classes/com/sun/org/apache/xml/internal/security/resource/xmlsecurity_en.properties
 
-OPENJDK_OSARCH=	bsd-${ARCH:S/i386/i586/}
+JDK_ARCH=	${ARCH:S/x86_64/amd64/}
+OPENJDK_OSARCH=	bsd-${JDK_ARCH:S/i386/i586/}
 INSTALLDIR=	${PREFIX}/${PORTNAME}${JDK_MAJOR_VERSION}
 
+BOOTSTRAP_DISTFILE=	bootstrap-openjdk-7.9.05_2.dfly-3.3-${JDK_ARCH}.tar.xz
+BOOTSTRAP_LIBDIRS=	${BOOTSTRAPJDKDIR}/jre/lib/${JDK_ARCH}
 NOPRECIOUSMAKEVARS=	yes
 
 ONLY_FOR_ARCHS=	i386 amd64
@@ -73,7 +80,7 @@ MAKE_ENV+=	LANG="C" \
 		LC_ALL="C" \
 		JAVA_HOME="" \
 		CLASSPATH="" \
-		LD_LIBRARY_PATH="" \
+		LD_LIBRARY_PATH="${BOOTSTRAP_LIBDIRS}" \
 		MAKEFLAGS="" \
 		ALT_BOOTDIR="${BOOTSTRAPJDKDIR}" \
 		ALT_FREETYPE_HEADERS_PATH="${LOCALBASE}/include" \
@@ -98,15 +105,20 @@ MAKE_ENV+=	LANG="C" \
 		BUILD_NUMBER="b${PORT_BUILD_NUMBER}"
 
 MAKE_ENV+=	HOTSPOT_BUILD_JOBS=${MAKE_JOBS_NUMBER}
-
-BOOTSTRAP_JDKS=	${LOCALBASE}/openjdk7 \
-		${LOCALBASE}/openjdk6 \
-		${LOCALBASE}/bootstrap-openjdk
+MAKE_ENV+=	ALT_PARALLEL_COMPILE_JOBS=${MAKE_JOBS_NUMBER}
 
 NO_STAGE=	yes
 
 .include <bsd.port.options.mk>
 
+.if ${OPSYS} == DragonFly && ${DFLYVERSION} > 300500
+.  if ${DFLYVERSION} < 300503
+BOOTSTRAP_DISTFILE= bootstrap-openjdk-7.21.11.dfly-3.5-${JDK_ARCH}.tar.xz
+.  else
+BOOTSTRAP_DISTFILE= bootstrap-openjdk-7.25.15.dfly-3.5-${JDK_ARCH}.tar.xz
+.  endif
+.endif
+
 .if empty(PORT_OPTIONS:MDEBUG)
 MAKE_ENV+=	ALT_OBJCOPY="/nonexistent"
 .endif
@@ -119,23 +131,7 @@ MAKE_ENV+=	UNLIMITED_CRYPTO=1
 RUN_DEPENDS+=  ${LOCALBASE}/share/java/zi:${PORTSDIR}/java/java-zoneinfo
 .endif
 
-# do we have valid native jdk installed?
-.for BJDK in ${BOOTSTRAP_JDKS}
-.  if !defined(BOOTSTRAPJDKDIR) && exists(${BJDK}/bin/javac)
-BOOTSTRAPJDKDIR=	${BJDK}
-.  endif
-.endfor
-
-# if no valid jdk found, set dependency
-.if !defined(BOOTSTRAPJDKDIR)
-BOOTSTRAPJDKDIR?=	${LOCALBASE}/bootstrap-openjdk
-BUILD_DEPENDS+=		${BOOTSTRAPJDKDIR}/bin/javac:${PORTSDIR}/java/bootstrap-openjdk
-.endif
-
-.if ${OSVERSION} < 800000
-PATCH_DEPENDS+=	gpatch:${PORTSDIR}/devel/patch
-PATCH=		gpatch
-.endif
+BOOTSTRAPJDKDIR=	${WRKDIR}/bootstrap
 
 .include <bsd.port.pre.mk>
 
@@ -154,6 +150,11 @@ post-patch:
 		${WRKSRC}/jdk/make/java/instrument/Makefile
 .endif
 
+# override do-build to filter out _MAKE_JOBS to enable parallel build
+do-build:
+	@cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} ${MAKE_CMD} \
+		${MAKE_FLAGS} ${MAKEFILE} ${MAKE_ARGS} ${ALL_TARGET}
+
 .if ${PORT_OPTIONS:MTZUPDATE}
 pre-install:
 	@# Update time zones
@@ -171,8 +172,9 @@ do-install:
 		${CHOWN} -h -R ${BINOWN}:${BINGRP} $$dir; \
 		${FIND} $$dir -type f -exec ${CHMOD} ${BINMODE} "{}" \; ; \
 	done
-	@${CHOWN} ${BINOWN}:${BINGRP} ${INSTALLDIR}/jre/lib/${ARCH}/jexec
-	@${CHMOD} ${BINMODE} ${INSTALLDIR}/jre/lib/${ARCH}/jexec
+	@cd ${INSTALLDIR}/include && ln -s dragonfly freebsd
+	@${CHOWN} ${BINOWN}:${BINGRP} ${INSTALLDIR}/jre/lib/${JDK_ARCH}/jexec
+	@${CHMOD} ${BINMODE} ${INSTALLDIR}/jre/lib/${JDK_ARCH}/jexec
 	@${INSTALL_DATA} ${FILESDIR}/cacerts ${INSTALLDIR}/jre/lib/security/cacerts
 	@${ECHO} "@unexec ${LOCALBASE}/bin/unregistervm ${INSTALLDIR}/bin/java" >> ${TMPPLIST}
 	@${FIND} -s ${INSTALLDIR} -not -type d | ${SORT} | \
