--- Makefile.orig	2013-10-29 13:03:04.426945000 +0000
+++ Makefile
@@ -4,7 +4,8 @@ PORTNAME=	guake
 PORTVERSION=	0.4.4.0
 #PORTREVISION=	0
 CATEGORIES=	x11
-MASTER_SITES=	http://www.guake.org/downloads/5?dummy=empty/
+DISTNAME=	guake-0.4.4
+MASTER_SITES=	http://distfiles.gentoo.org/distfiles/
 
 MAINTAINER=	nivit@FreeBSD.org
 COMMENT=	Dropdown terminal made for the GNOME desktop
@@ -58,7 +59,6 @@ USE_GMAKE=	yes
 USE_GNOME=	desktopfileutils gtk20 pygnome2
 USE_PYTHON=	-2.7
 
-WRKSRC=	${WRKDIR}/${DISTNAME:R}
 
 post-patch:
 	cd ${WRKSRC}/src && ${REINPLACE_CMD} ${REINPLACE_FILES}
