--- Makefile.orig	2013-01-26 11:36:27.793191000 +0100
+++ Makefile	2013-01-26 11:36:39.513207000 +0100
@@ -7,6 +7,7 @@
 
 CATEGORIES=	korean
 PKGNAMESUFFIX=	-lib
+PKGNAMEPREFIX=	ko-
 
 COMMENT=	A Japanese/Chinese/Korean input method (Korean client libraries)
 
