--- Makefile.orig	2018-02-23 23:39:13 UTC
+++ Makefile
@@ -50,6 +50,7 @@ post-patch:
 	 -e 's|@localstatedir@/sym/|${PREFIX}/share/flow-tools/|' \
 	 -e 's|@localstatedir@/cfg/|${PREFIX}/etc/flow-tools/|' \
 	  ${WRKSRC}/docs/flow-*.1.in ${WRKSRC}/docs/flow-*.html.in
+	${REINPLACE_CMD} -e 's|inline ||' ${WRKSRC}/lib/ftfil.c
 
 post-install:
 	${INSTALL_MAN} ${WRKSRC}/docs/*.1 ${STAGEDIR}${MAN1PREFIX}/man/man1/
