# Note verion has not been updated since 2007
MANUAL_PACKAGE_BUILD=	1.7G package - skip until someone complains \
			it does not build anymore
.if !defined(DPORTS_BUILDER)
MANUAL_PACKAGE_BUILD=	1.7G package (too big for mirrors)
.endif
