--- Makefile.orig	2014-02-04 17:18:21.951079000 +0000
+++ Makefile
@@ -8,6 +8,7 @@ COMMENT=	The GIMP User Manual in Greek
 
 LICENSE=	GFDL
 
+IGNORE=		Runs away on DragonFly
 MASTERDIR=	${.CURDIR}/../gimp-help-en
 
 DOCLANG=	el
