--- mkspecs/dragonfly-clang/qmake.conf.orig	2023-02-19 15:24:53 UTC
+++ mkspecs/dragonfly-clang/qmake.conf
@@ -0,0 +1,18 @@
+#
+# qmake configuration for dragonfly-clang
+#
+
+MAKEFILE_GENERATOR      = UNIX
+QMAKE_PLATFORM          = dragonfly
+
+include(../common/bsd/bsd.conf)
+
+# Addon software goes into /usr/local on DragonFly, by default we will look there
+QMAKE_INCDIR_POST       = /usr/local/include
+QMAKE_LIBDIR_POST       = /usr/local/lib
+
+QMAKE_LFLAGS_NOUNDEF    = -Wl,--no-undefined
+
+include(../common/gcc-base-unix.conf)
+include(../common/clang.conf)
+load(qt_config)
