--- Makefile.orig	2022-11-05 22:40:46.406110000 +0100
+++ Makefile	2022-11-05 22:40:52.015985000 +0100
@@ -37,7 +37,6 @@
 		-Dxcsecurity=false \
 		-Ddri3=true \
 		-Dglamor=true \
-		-Dsha1=libmd \
 		-Dipv6=true \
 		-Dxkb_dir=${LOCALBASE}/share/X11/xkb \
 		-Dxkb_output_dir=/var/lib/xkb \
