--- Makefile.orig	2015-04-26 14:07:55 UTC
+++ Makefile
@@ -14,6 +14,9 @@ COMMENT=	Reliable, highly configurable m
 CONFLICTS?=	courier-0.* postfix-1.* postfix-2.* smail-3.* zmailer-2.* opensmtpd-*
 NEED_ROOT=	yes
 
+USERS=		smmsp
+GROUPS=		smmsp
+
 USES=		cpe
 WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}
 DOCS=		KNOWNBUGS LICENSE PGPKEYS README RELEASE_NOTES \
@@ -211,14 +214,8 @@ pre-install:
 .if ${PORT_OPTIONS:MMILTER}
 	@${CAT} ${FILESDIR}/pkg-milter >>${PLIST}
 .endif
-	if ! pw groupshow smmsp; then pw groupadd smmsp -g 25; fi
-	if ! pw usershow smmsp; then pw useradd smmsp -g smmsp -u 25 \
-		-h - -d /nonexistent -s /nonexistent -c "Sendmail Queue"; fi
 	@cd ${WRKSRC} && ${FIND} cf -type f | \
 	${AWK} '{print "share/sendmail/" $$1}' >>${PLIST}
-	@cd ${WRKSRC} && ${FIND} -d cf -type d | \
-	${AWK} '{print "@dirrm share/sendmail/" $$1}' >>${PLIST}
-	@${ECHO_CMD} "@dirrm share/sendmail" >>${PLIST}
 .if ${PORT_OPTIONS:MDOCS}
 .for i in ${DOCS}
 	@${ECHO_CMD} `${BASENAME} ${i}` | \
@@ -227,7 +224,6 @@ pre-install:
 .if ${PORT_OPTIONS:MCYRUSLOOKUP}
 	@${ECHO_CMD} "share/doc/sendmail/CYRUS_LOOKUP" >>${PLIST}
 .endif
-	@${ECHO_CMD} "@dirrm %%DOCSDIR%%" >>${PLIST}
 .endif
 
 # We want mail.local and rmail for our system.
@@ -284,6 +280,7 @@ post-install:
 	${INSTALL_DATA} ${FILESDIR}/CYRUS_LOOKUP ${STAGEDIR}${DOCSDIR}/CYRUS_LOOKUP
 .endif
 .endif
+	${RM} ${STAGEDIR}${PREFIX}/man/cat*/*
 
 mailer.base:
 	@${SED} \
