--- Makefile.orig	2024-09-08 19:28:10 UTC
+++ Makefile
@@ -1,5 +1,5 @@
 PORTNAME=	telegram-desktop
-DISTVERSION=	4.14.2
+DISTVERSION=	4.14.4
 CATEGORIES=	net-im
 MASTER_SITES=	https://github.com/${GH_ACCOUNT}/${GH_PROJECT}/releases/download/v${DISTVERSION}/
 DISTNAME=	tdesktop-${DISTVERSION}-full
@@ -13,8 +13,6 @@ LICENSE=	GPLv3
 LICENSE_FILE=	${WRKSRC}/LICENSE
 
 BROKEN_i386=	does not build, webrtc related
-BROKEN_SSL=	openssl openssl31
-BROKEN_SSL_REASON=	undefined symbol: ERR_load_BIO_strings
 NOT_FOR_ARCHS=		powerpc powerpc64 powerpcspe
 NOT_FOR_ARCHS_REASON=	Only little endian is supported
 
@@ -28,7 +26,6 @@ BUILD_DEPENDS=	boost-libs>0:devel/boost-
 LIB_DEPENDS=	libabsl_base.so:devel/abseil \
 		libavformat.so:multimedia/ffmpeg \
 		libdbus-1.so:devel/dbus \
-		libdispatch.so:devel/libdispatch \
 		libfmt.so:devel/libfmt \
 		libhunspell-1.7.so:textproc/hunspell \
 		liblz4.so:archivers/liblz4 \
@@ -79,9 +76,6 @@ CMAKE_ON=	DESKTOP_APP_USE_PACKAGED DESKT
 # Since cmake 3.25.0, BSDs are no longer recognised as Linux (in this port).
 CMAKE_ARGS+=	-DLINUX=true
 
-# libdispatch components
-LDFLAGS+=	-lBlocksRuntime
-
 # Telegram uses OpenAL for its audio, but libtgvoip (for voice calls) can use PulseAudio or ALSA.
 # It dynamically loads PulseAudio, and if this fails, it loads ALSA.
 # If both of them are not installed, then voice calls do not work, but other functionalities still work.
@@ -116,12 +110,10 @@ post-extract:
 	# can be safely removed
 	${RM} -rf \
 		${WRKSRC}/Telegram/ThirdParty/QR \
-		${WRKSRC}/Telegram/ThirdParty/dispatch \
 		${WRKSRC}/Telegram/ThirdParty/expected \
 		${WRKSRC}/Telegram/ThirdParty/fcitx5-qt \
 		${WRKSRC}/Telegram/ThirdParty/hime \
 		${WRKSRC}/Telegram/ThirdParty/hunspell \
-		${WRKSRC}/Telegram/ThirdParty/jemalloc \
 		${WRKSRC}/Telegram/ThirdParty/lz4 \
 		${WRKSRC}/Telegram/ThirdParty/minizip \
 		${WRKSRC}/Telegram/ThirdParty/jimf \
@@ -133,7 +125,6 @@ post-extract:
 
 .if ${FLAVOR} == qt5
 	${RM} -rf \
-		${WRKSRC}/Telegram/ThirdParty/kcoreaddons \
 		${WRKSRC}/Telegram/ThirdParty/kimageformats
 .endif
 
