--- Makefile.orig	2016-08-06 15:23:47 UTC
+++ Makefile
@@ -44,7 +44,7 @@ BUILD_WRKSRC?=	${WRKDIR}/build/usession-
 MAKE_ENV+=	PYPY_LOCALBASE=${LOCALBASE}
 PACKAGE_ARGS?=	--without-gdbm --without-sqlite3 --without-tk
 USE_LDCONFIG=	${PREFIX}/${PYPY_DIR}/bin
-USES=		gettext-runtime gmake ssl tar:bzip2
+USES=		gettext-runtime gmake ncurses ssl tar:bzip2
 
 .if ${PORTNAME} != pypy
 PYPY_BUILD_DEPENDS=	pypy:lang/pypy
@@ -82,7 +82,7 @@ post-build:
 	${CP} ${BUILD_WRKSRC}/pypy-c ${BUILD_WRKSRC}/libpypy-c.so ${WRKSRC}/pypy/goal/
 
 do-install:
-	${SETENV} TMPDIR=${WRKDIR}/build \
+	${SETENV} ${MAKE_ENV} TMPDIR=${WRKDIR}/build \
 		${PYTHON_CMD} ${WRKSRC}/pypy/tool/release/package.py --builddir ${WRKDIR}/build --archive-name ${PYPY_DIR} \
 			${PACKAGE_ARGS}
 	${EXTRACT_CMD} -C ${STAGEDIR}${PREFIX} -xf ${WRKDIR}/build/${PYPY_DIR}.tar.bz2
