--- Makefile.orig	2019-04-16 10:53:35 UTC
+++ Makefile
@@ -72,10 +72,12 @@ LICENSE=		GPLv3
 CONFIGURE_ARGS+=	--enable-gpl
 .endif
 
+.if 0 #${OPSYS} == FreeBSD
 # use the fixed compiler version from ports to prevent failures on FreeBSD_10
 LLVM_VERSION=	60
 BUILD_DEPENDS+=	clang${LLVM_VERSION}:devel/llvm${LLVM_VERSION}
 CC=	clang${LLVM_VERSION}
 CXX=	clang++${LLVM_VERSION}
+.endif
 
 .include <bsd.port.mk>
