--- Makefile.orig	2013-12-12 09:03:09.028158000 +0000
+++ Makefile
@@ -20,7 +20,7 @@ WRKSRC=		${WRKDIR}/freera++
 
 SUB_FILES=	pkg-message
 
-PLIST_FILES=	bin/${PORTNMAE}
+PLIST_FILES=	bin/${PORTNAME}
 PORTDATA=	*
 
 post-patch:
