--- Makefile.orig	2021-03-01 14:52:20 UTC
+++ Makefile
@@ -28,2 +28,2 @@
-BUILD_DEPENDS=	as:devel/binutils
-RUN_DEPENDS=	as:devel/binutils
+BUILD_DEPENDS=	as:devel/binutils@native
+RUN_DEPENDS=	as:devel/binutils@native
