Just to oassthru to dports/staged

--- Makefile.orig	2020-08-13 10:38:52 UTC
+++ Makefile
@@ -32,6 +32,11 @@ DESCR?=		${.CURDIR}/pkg-descr
 
 NO_ARCH=	yes
 
+.if defined(DPORTS_BUILDER)
+PLAT=	rk3328
+BL31=	bl31/bl31.elf
+.endif
+
 .if !defined(PLAT)
 PLAT=		NONE
 IGNORE=		is a metaport; there is nothing to build
