--- Makefile.orig	2021-06-15 18:19:33.853698000 +0200
+++ Makefile	2021-06-15 18:22:42.789356000 +0200
@@ -20,7 +20,7 @@
 NO_BUILD=	yes
 USES=		python shebangfix
 
-SHEBANG_FILES=	bin/waagent bin/waagent2.0
+SHEBANG_FILES=	bin/waagent bin/waagent2.0 init/waagent
 
 USE_GITHUB=	yes
 GH_ACCOUNT=	Azure
