--- Makefile.orig	2019-04-26 23:03:45 UTC
+++ Makefile
@@ -35,6 +35,9 @@ OPTIONS_DEFINE=	EXAMPLES STATIC
 
 LDFLAGS+=	-lm
 MAKE_ENV=	CCFLAGS="-Wno-unused-value -Wno-parentheses -Wno-logical-op-parentheses ${CFLAGS}"
+USES=          ssl
+CFLAGS+=       -I${OPENSSLINC}
+LDFLAGS+=      -L${OPENSSLLIB}
 
 KSHVERSION=	2014-12-24
 
