--- Makefile.orig	2013-05-17 18:43:10.964353000 +0000
+++ Makefile
@@ -98,12 +98,8 @@ CONFIGURE_ARGS+=	--with-expat=yes
 CONFIGURE_ARGS+=	--without-expat
 .endif
 
-.if ${ARCH} == "amd64"
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
-.endif
-
 post-patch:
-	@${REINPLACE_CMD} -e 's/$$/ [GDB v${PORTVERSION} for FreeBSD]/' \
+	@${REINPLACE_CMD} -e 's/$$/ [GDB v${PORTVERSION} for ${OPSYS}]/' \
 		${WRKSRC}/gdb/version.in
 .if ${PORT_OPTIONS:MTHREADS}
 	@${CP} ${FILESDIR}/fbsd-threads.c ${WRKSRC}/gdb/
