--- Makefile.orig	2019-07-31 15:03:04 UTC
+++ Makefile
@@ -127,7 +127,7 @@ EXCLUDE+=	zlib
 .endif
 
 .if ${ARCH} == amd64
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 .if ${CHOSEN_COMPILER_TYPE} == clang
@@ -135,7 +135,7 @@ CFLAGS+=	-Wno-extended-offsetof
 .endif
 
 post-patch:
-	@${REINPLACE_CMD} -e 's|$$| [GDB v${PORTVERSION} for FreeBSD]|' \
+	@${REINPLACE_CMD} -e 's|$$| [GDB v${PORTVERSION} for ${OPSYS}]|' \
 		${WRKSRC}/gdb/version.in
 
 post-patch-KGDB-on:
