--- Makefile.orig	2019-06-20 12:40:01 UTC
+++ Makefile
@@ -125,16 +125,12 @@ EXCLUDE+=	readline
 EXCLUDE+=	zlib
 .endif
 
-.if ${ARCH} == amd64
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
-.endif
-
-.if ${CHOSEN_COMPILER_TYPE} == clang
-CFLAGS+=	-Wno-extended-offsetof
-.endif
+# Wow c++ smth.c too on gdb, gcc wasn't enough? throw helpers for c-- and try to kill it
+CFLAGS+=	-D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS
+CONFIGURE_ARGS+=	--disable-build-with-cxx
 
 post-patch:
-	@${REINPLACE_CMD} -e 's|$$| [GDB v${PORTVERSION} for FreeBSD]|' \
+	@${REINPLACE_CMD} -e 's|$$| [GDB v${PORTVERSION} for ${OPSYS}]|' \
 		${WRKSRC}/gdb/version.in
 
 post-patch-KGDB-on:
