--- Makefile.orig	2016-04-06 15:55:40 UTC
+++ Makefile
@@ -27,7 +27,6 @@ RUN_DEPENDS=	five-or-more:games/five-or-
 		iagno:games/iagno \
 		lightsoff:games/lightsoff \
 		quadrapassel:games/quadrapassel \
-		aisleriot>=0:games/aisleriot \
 		swell-foop:games/swell-foop \
 		tali:games/tali
 
