--- Makefile.orig	2013-10-06 11:26:39.977544000 +0000
+++ Makefile
@@ -15,7 +15,7 @@ COMMENT?=	Multithreaded SQL database (se
 LICENSE=	GPLv2
 
 SLAVEDIRS=	databases/mysql55-client
-USES=		cmake shebangfix
+USES=		cmake shebangfix readline
 NO_OPTIONS_SORT=yes
 
 OPTIONS_DEFINE=	SSL FASTMTX
@@ -40,7 +40,7 @@ CMAKE_ARGS+=	-DINSTALL_DOCDIR="share/doc
 		-DINSTALL_SUPPORTFILESDIR="share/mysql" \
 		-DWITH_UNIT_TESTS=0 \
 		-DWITH_LIBEDIT=0 \
-		-DWITH_LIBWRAP=1
+		-DWITH_READLINE=1
 
 SHEBANG_FILES=	scripts/*.pl* scripts/*.sh
 
