--- Makefile.orig	2022-01-13 04:21:12 UTC
+++ Makefile
@@ -32,7 +32,7 @@
 AMD_DESC=	Depend on sysutils/devcpu-data-amd
 INTEL_DESC=	Depend on sysutils/devcpu-data-intel
 
-AMD_RUN_DEPENDS=	${LOCALBASE}/share/cpucontrol/microcode_amd.bin:sysutils/devcpu-data-amd
-INTEL_RUN_DEPENDS=	/boot/firmware/intel-ucode.bin:sysutils/devcpu-data-intel
+AMD_RUN_DEPENDS=	devcpu-data-amd>0:sysutils/devcpu-data-amd
+INTEL_RUN_DEPENDS=	devcpu-data-intel>0:sysutils/devcpu-data-intel
 
 .include <bsd.port.mk>
