--- Makefile.orig	2013-07-13 07:59:42.140453000 +0000
+++ Makefile
@@ -30,6 +30,6 @@ EXTRA_PATCHES=	${PATCHDIR}/utmpx-whowatc
 
 pre-patch:
 	@${FIND} ${WRKSRC} -name 'proc????.c' | ${XARGS} ${REINPLACE_CMD} -E \
-		-e 's/kp_.?proc\.._/ki_/ ; s/pcred\.p_//'
+		-e 's/kp_.?proc\.._/kp_/ ; s/pcred\.p_//'
 
 .include <bsd.port.post.mk>
