--- Makefile.orig	2013-04-04 08:46:54.808355000 +0000
+++ Makefile
@@ -100,7 +100,7 @@ PLIST_SUB+=	MARBLE="@comment "
 USE_MYSQL=	yes
 PLIST_SUB+=	MYSQL=""
 .else
-CMAKE_ARGS+=	-DWITH_MySQL:BOOL=FASE
+CMAKE_ARGS+=	-DWITH_MySQL:BOOL=FALSE
 PLIST_SUB+=	MYSQL="@comment "
 .endif
 
