--- config/shlib.conf.orig	2026-09-10 21:18:43 UTC
+++ config/shlib.conf
@@ -159,7 +159,7 @@ mips-*-netbsd*)
 	lib_unload_prevented=yes
 	;;
 
-*-*-freebsd*)
+*-*-freebsd* | *-*-dragonfly*)
 	case $krb5_cv_host in
 		sparc64-*)
 			PICFLAGS=-fPIC
