--- Makefile.orig	2016-11-06 00:38:31 UTC
+++ Makefile
@@ -13,8 +13,8 @@ USE_RC_SUBR=	bareos-fd
 PLIST=		${PKGDIR}/pkg-plist.client
 MASTERDIR=	${.CURDIR}/../../sysutils/bareos-server
 
-OPTIONS_DEFINE=	NLS PYTHON LMDB
-OPTIONS_DEFAULT=#
+OPTIONS_DEFINE=	NLS PYTHON LMDB SSL
+OPTIONS_DEFAULT=	SSL
 LMDB_DESC=	Enable build of LMDB support
 
 .include "${MASTERDIR}/Makefile"
