--- Makefile.orig	2013-02-28 10:51:58.000000000 +0000
+++ Makefile
@@ -22,7 +22,6 @@ PLIST_SUB+=	MAJOR=${PORTVERSION:R:R}
 GNU_CONFIGURE=	yes
 USE_LDCONFIG=	yes
 
-CPPFLAGS+=	-I/usr/include/readline -I${LOCALBASE}/include
 LDFLAGS+=	-L${LOCALBASE}/lib
 
 OPTIONS_DEFINE?=	SQLITE3 MYSQL PGSQL MTX NLS OPENSSL
@@ -49,7 +48,6 @@ CONFIGURE_ARGS+=--with-tcp-wrappers=/usr
 		--enable-smartalloc \
 		--with-working-dir=${BACULA_DIR} \
 		--with-scriptdir=${PREFIX}/share/${PORTNAME} \
-		--with-readline=yes \
 		--disable-conio \
 		--enable-batch-insert \
 		--with-plugindir=${PREFIX}/lib \
