# $FreeBSD$

PORTNAME=	dsynth
DISTVERSION=	1.0.2
CATEGORIES=	ports-mgmt

MAINTAINER=	tuxillo@quantumachine.net
COMMENT=	Tool to build DPorts

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		autoreconf gmake libtool pkgconfig ssl ncurses
USE_GITHUB=	yes

GH_ACCOUNT=	DragonFlyBSD

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
