--- Makefile.orig	2017-04-02 22:52:11 UTC
+++ Makefile
@@ -23,7 +23,7 @@ COMMENT?=	Free Pascal compiler with Turb
 
 USES=		gmake iconv
 ONLY_FOR_ARCHS=	i386 amd64
-BOOTVER=	3.0.2
+BOOTVER=	3.0.0
 MANVER=		3.0.2
 
 #USE_GITHUB=	yes
