--- Makefile.orig	2014-10-01 22:57:25 UTC
+++ Makefile
@@ -31,7 +31,7 @@ CFLAGS+=	-fPIC
 CONFIGURE_ARGS=	--datadir=${DATADIR} \
 		--enable-static=yes \
 		--with-liblzma=yes --with-libz=/usr --with-threads=yes \
-		--without-libtool
+
 GNU_CONFIGURE=	yes
 LDFLAGS+=	-L${LOCALBASE} -pthread
 MAKE_JOBS_UNSAFE=	yes
@@ -139,12 +139,18 @@ XERCES_CONFIGURE_OFF=	--with-xerces=no
 XERCES_CONFIGURE_ON=	--with-xerces=${LOCALBASE}
 XERCES_LIB_DEPENDS=	libxerces-c.so:${PORTSDIR}/textproc/xerces-c3
 
+USES+=			libtool
+AGE!=			expr ${PORTVERSION:R:E} + 1
+
 post-patch:
+	@${REINPLACE_CMD} -e 's/^LIBGDAL_AGE.*/LIBGDAL_AGE := ${PORTVERSION:R:E}/' \
+		-e 's/^LIBGDAL_REV.*/LIBGDAL_REVISION := ${PORTVERSION:E}/' \
+		-e 's/^LIBGDAL_CUR.*/LIBGDAL_CURRENT := ${AGE}/' \
+		${WRKSRC}/GDALmake.opt.in
 	@${REINPLACE_CMD} -e 's|$$(INST_LIB)/pkgconfig|${PREFIX}/libdata/pkgconfig|' ${WRKSRC}/GNUmakefile
 	@${REINPLACE_CMD} -e 's|-lpthread|-pthread|g' ${WRKSRC}/configure
 
 post-install:
-	${INSTALL_LIB} ${WRKSRC}/libgdal.a ${STAGEDIR}${PREFIX}/lib/
 	${TOUCH} ${STAGEDIR}${PREFIX}/lib/gdalplugins/.keepme
 	${INSTALL_DATA} ${WRKSRC}/GDALmake.opt ${STAGEDIR}${DATADIR}/
 	-${STRIP_CMD} ${STAGEDIR}${PREFIX}/bin/* ${STAGEDIR}${PREFIX}/lib/libgdal.so.${PORTVERSION}
