--- Makefile.orig	2013-01-26 11:56:11.284844000 +0100
+++ Makefile	2013-01-26 11:56:22.554859000 +0100
@@ -7,6 +7,7 @@
 
 CATEGORIES=	german www
 DISTNAME=	MTOS-${PORTVERSION}-${PKGNAMEPREFIX:S,-,,}
+PKGNAMEPREFIX=	de-
 
 COMMENT=	German localization of the MovableType publishing system
 
