--- Makefile.orig	2022-06-26 00:57:13 UTC
+++ Makefile
@@ -2,7 +2,7 @@
 
 PORTNAME=	poppler
 DISTVERSION=	22.01.0
-PORTREVISION=	1
+PORTREVISION=	2
 CATEGORIES=	graphics print
 MASTER_SITES=	https://poppler.freedesktop.org/
 
