--- Makefile.orig	2013-10-13 18:11:59.638101000 +0000
+++ Makefile
@@ -45,17 +45,16 @@ do-configure:
 	@cd ${WRKSRC} && ${SETENV} ${CONFIGURE_ENV} \
 		${QMAKE} ${QMAKEFLAGS} PREFIX=${PREFIX} F1LT.pro
 
-post-build-script:
-	@${REINPLACE_CMD} -e 's|-$$(INSTALL_FILE)|${INSTALL} -o ${SHAREOWN} -g ${SHAREGRP} -m 644|g' \
-		${WRKSRC}/Makefile
-	@${REINPLACE_CMD} -e 's|-$$(INSTALL_PROGRAM)|${INSTALL} -s -o ${SHAREOWN} -g ${SHAREGRP} -m 755|g' \
-		${WRKSRC}/Makefile
-
 post-install:
 .if ${PORT_OPTIONS:MDOCS}
 	@${MKDIR} ${STAGEDIR}${DOCSDIR}
 	${INSTALL_DATA} ${WRKSRC}/CHANGELOG ${STAGEDIR}${DOCSDIR}
 .endif
+	${STRIP_CMD} ${STAGEDIR}${PREFIX}/bin/F1LT
+	${CHOWN} ${BINOWN}:${BINGRP} ${STAGEDIR}${PREFIX}/bin/F1LT
+	${CHMOD} 755 ${STAGEDIR}${PREFIX}/bin/F1LT
+	${CHOWN} ${SHAREOWN}:${SHAREGRP} ${STAGEDIR}${PREFIX}/share/f1lt/*.dat
+	${CHMOD} 644 ${STAGEDIR}${PREFIX}/share/f1lt/*.dat
 	${LN} -sf F1LT ${STAGEDIR}${PREFIX}/bin/${PORTNAME}
 
 .include <bsd.port.mk>
