--- Makefile.orig	2017-12-29 02:21:33 UTC
+++ Makefile
@@ -539,6 +539,12 @@ post-extract:
 	@cd ${WRKDIR} && ${TAR} ${EXTRACT_BEFORE_ARGS} ${_DISTDIR}/sa-exim-${SA_EXIM_VERSION}.tar.gz ${EXTRACT_AFTER_ARGS}
 .endif
 
+dfly-patch:
+	(cd ${WRKSRC}/OS && \
+		${CP} os.h-FreeBSD os.h-DragonFly && \
+		${CP} os.c-FreeBSD os.c-DragonFly && \
+		${CP} Makefile-FreeBSD Makefile-DragonFly)
+
 do-configure:
 	@${MKDIR} ${WRKSRC}/Local
 	@${SED} -E ${SEDLIST} ${WRKSRC}/src/EDITME > ${WRKSRC}/Local/Makefile
@@ -566,7 +572,7 @@ do-configure:
 	    ${WRKDIR}/sa-exim-${SA_EXIM_VERSION}/sa-exim.conf
 .endif
 	@${REINPLACE_CMD} -E -e 's/XX_STRIPCMD_XX/${STRIP_CMD:S,/,\/,g}/' \
-		${WRKSRC}/OS/Makefile-FreeBSD
+		${WRKSRC}/OS/Makefile-${OPSYS}
 	@(cd ${WRKSRC}; ${SETENV} ${MAKE_ENV} ${MAKE} ${MAKE_FLAGS} ${MAKEFILE} ${MAKE_ARGS} configure)
 
 post-build:
