--- Makefile.orig	2023-07-28 19:40:44 UTC
+++ Makefile
@@ -588,6 +588,12 @@ post-extract:
 	@@${CP} ${WRKDIR}/sa-exim-${SA_EXIM_VERSION}/sa-exim.conf ${WRKSRC}/Local
 .endif
 
+dfly-patch:
+	(cd ${WRKSRC}/OS && \
+		${CP} os.h-FreeBSD os.h-DragonFly && \
+		${CP} os.c-FreeBSD os.c-DragonFly && \
+		${CP} Makefile-FreeBSD Makefile-DragonFly)
+
 do-configure:
 	@${MKDIR} ${WRKSRC}/Local
 	@${SED} -E ${SEDLIST} ${WRKSRC}/src/EDITME > ${WRKSRC}/Local/Makefile
