--- Makefile.orig	2013-04-05 23:08:48.798105000 +0000
+++ Makefile
@@ -112,9 +112,9 @@ do-install:
 	@${MKDIR} ${DOCSDIR}
 . for portdoc in ${PORTDOCS}
 	@if [ -f ${WRKDIR}/${portdoc} ]; then \
-		${INSTALL_DATA} -v ${WRKDIR}/${portdoc} ${DOCSDIR}/;  \
+		${INSTALL_DATA} ${WRKDIR}/${portdoc} ${DOCSDIR}/;  \
 	else \
-		${INSTALL_DATA} -v ${WRKSRC}/${portdoc} ${DOCSDIR}/;  \
+		${INSTALL_DATA} ${WRKSRC}/${portdoc} ${DOCSDIR}/;  \
 	fi
 . endfor
 .endif
