--- Makefile.orig	2017-05-03 14:04:15 UTC
+++ Makefile
@@ -100,10 +100,6 @@ PLIST_SUB+=	DC1394="@comment "
 CFLAGS+=	-fPIC
 .endif
 
-.if (${ARCH} == "amd64") || (${ARCH} == "i386") || (${ARCH} == "powerpc") || (${ARCH} == "sparc64")
-PLIST_SUB+=	BSDVIDEO=""
-.else
 PLIST_SUB+=	BSDVIDEO="@comment "
-.endif
 
 .include <bsd.port.post.mk>
