--- src/config/wireplumber.conf.orig
+++ src/config/wireplumber.conf
@@ -393,10 +393,15 @@ wireplumber.components = [
   ## Device monitors
   {
     name = monitors/alsa.lua, type = script/lua
     provides = monitor.alsa
     requires = [ support.export-core, pw.client-device ]
     wants = [ monitor.alsa.reserve-device ]
   }
+  {
+    name = monitors/oss.lua, type = script/lua
+    provides = monitor.oss
+    requires = [ support.export-core ]
+  }
   {
     name = monitors/bluez.lua, type = script/lua
     provides = monitor.bluez
@@ -755,6 +761,6 @@ wireplumber.components = [
   ## Load targets
   {
     type = virtual, provides = hardware.audio
-    wants = [ monitor.alsa, monitor.alsa-midi ]
+    wants = [ monitor.alsa, monitor.alsa-midi, monitor.oss ]
   }
   {
