--- Makefile.orig	2013-01-24 18:52:05.320486000 +0100
+++ Makefile	2013-01-24 18:52:17.830504000 +0100
@@ -8,6 +8,7 @@
 MASTERDIR=	${.CURDIR}/../../lang/ruby-man
 
 CATEGORIES=	japanese
+PKGNAMEPREFIX=	ja-
 
 MAINTAINER=	ruby@FreeBSD.org
 COMMENT=	Ruby reference manual (Japanese version), in HTML format
