--- Makefile.orig	2013-04-02 10:38:36.000000000 +0000
+++ Makefile
@@ -21,7 +21,7 @@ BUILD_DEPENDS=	rexx:${PORTSDIR}/lang/rex
 LIB_DEPENDS=	curl.6:${PORTSDIR}/ftp/curl
 RUN_DEPENDS=	rexx:${PORTSDIR}/lang/rexx-regina
 
-BROKEN=		fails to build
+#BROKEN=		fails to build
 USE_GMAKE=	yes
 GNU_CONFIGURE=	yes
 CPPFLAGS+=	${PTHREAD_CFLAGS}
