--- Makefile.orig	2017-11-19 19:10:14 UTC
+++ Makefile
@@ -7,5 +7,6 @@ CATEGORIES=	devel
 MASTERDIR=	${.CURDIR}/../../lang/php70
 
 PKGNAMESUFFIX=	-intl
+USE_CXXSTD=	c++11
 
 .include "${MASTERDIR}/Makefile"
