--- Makefile.orig	2023-01-16 23:35:24 UTC
+++ Makefile
@@ -78,6 +78,7 @@ REMOVE_TARGETS=	.envrc .runner.sh .vimrc
 		vagrant.gemspec
 
 post-patch:
+	@${REINPLACE_CMD} -e 's|@DATADIR@|${DATADIR}|g' ${WRKSRC}/lib/vagrant/plugin/manager.rb
 	@${REINPLACE_CMD} -e 's|@PREFIX@|${PREFIX}|g' \
 		${WRKSRC}/bin/vagrant \
 		${WRKSRC}/plugins/providers/virtualbox/action/network.rb \
@@ -96,6 +97,8 @@ do-build:
 		${STAGEDIR}${DATADIR}/embedded/rgloader/loader.rb
 
 post-install:
+	${MKDIR} ${STAGEDIR}${DATADIR}/plugins.d
+	${ECHO} '{}' > ${STAGEDIR}${DATADIR}/plugins.json
 	${RMDIR} ${STAGEDIR}${PREFIX}/lib/ruby/gems/${RUBY_VER}/doc
 	${RM} -r ${STAGEDIR}${PREFIX}/lib/ruby/gems/${RUBY_VER}/gems/${PORTNAME}-${PORTVERSION}/nix
 .for FILE in ${REMOVE_TARGETS}
