--- Makefile.orig	2013-01-26 14:23:44.387210000 +0100
+++ Makefile	2013-01-26 14:23:58.667230000 +0100
@@ -7,6 +7,7 @@
 
 PORTNAME=	nap
 CATEGORIES=	russian
+PKGNAMEPREFIX=	ru-
 
 MAINTAINER=	sam@brj.pp.ru
 COMMENT=	Client for the OpenNAP network with koi8 <> win1251 encoding patch
