--- Makefile.orig	2015-09-15 07:05:51 UTC
+++ Makefile
@@ -323,7 +323,13 @@ CXXFLAGS_WARN+=	-Wno-inconsistent-missin
 		-Wno-unused-local-typedefs
 .endif
 .else
-CXXFLAGS_WARN=	-Wshadow -Woverloaded-virtual
+CXXFLAGS_WARN=	-Wno-deprecated-declarations \
+		-Wno-undef \
+		-Wno-unused-parameter \
+		-Wno-unused-function \
+		-Wno-unused-local-typedefs \
+		-Wno-ignored-qualifiers \
+		-Woverloaded-virtual
 .endif
 
 pre-configure:
