--- Makefile.orig	2021-10-22 07:24:14 UTC
+++ Makefile
@@ -37,7 +37,7 @@ MESON_ARGS+=	-Dgallium-drivers="" \
 		-Dgallium-va=disabled \
 		-Dgallium-xa=disabled \
 		-Dgallium-nine=false \
-		-Dosmesa=false \
+		-Dosmesa=none \
 		-Dtools="" \
 		-Degl=enabled \
 		-Dgbm=enabled \
