--- Makefile.orig	2019-05-23 11:38:24 UTC
+++ Makefile
@@ -40,7 +40,7 @@ PLIST_FILES+=	share/icons/hicolor/${SZ}x
 OPTIONS_DEFINE=		OPENMP
 OPTIONS_DEFAULT=	OPENMP
 
-OPENMP_LIB_DEPENDS=	libgomp.so:devel/openmp
+OPENMP_LIB_DEPENDS=	
 
 post-patch:
 	@${REINPLACE_CMD} 's|/usr/|${PREFIX}/|; s| -O2| ${CFLAGS}|; s|gcc|${CC}|' ${WRKSRC}/CONFIG
