--- Makefile.orig	2013-12-08 21:55:15.509954000 +0000
+++ Makefile
@@ -164,7 +164,7 @@ CONFIGURE_ARGS+=	--disable-threads
 
 .if ${PORT_OPTIONS:MGSSAPI}
 CONFIGURE_ARGS+=	--with-gssapi
-LDFLAGS+=		-L${LIBDIR} -lgssapi_krb5
+LIB_DEPENDS+=		libgssapi_krb5.so:${PORTSDIR}/security/krb5
 .else
 CONFIGURE_ARGS+=        --without-gssapi
 .endif
