--- Makefile.orig	2016-04-28 08:02:47 UTC
+++ Makefile
@@ -19,7 +19,8 @@ BUILD_WRKSRC=	${WRKSRC}/scripts_linux
 USE_JAVA=	yes
 JAVA_VERSION=	1.6+
 #java-linux required
-JAVA_OS=	linux
+#JAVA_OS=	linux
+IGNORE=		Only builds with linux-jdk java
 DATADIR=	${JAVASHAREDIR}/dimes
 
 post-extract:
