--- Makefile.orig	2016-04-06 16:10:52 UTC
+++ Makefile
@@ -40,22 +40,27 @@ SUB_FILES=		pkg-message
 SUB_LIST=		PYTHON_SUFFIX=${PORTVERSION:R:S/.//g}
 
 PLIST_SUB=		ABI=${ABIFLAGS} \
-			OSMAJOR=${OSVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
+			OSMAJOR=${DFLYVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
 
 OPTIONS_DEFINE=		DEBUG IPV6 LIBFFI NLS PYMALLOC THREADS TSC
 OPTIONS_DEFAULT=	LIBFFI PYMALLOC THREADS
 OPTIONS_SUB=		yes
+OPTIONS_DEFINE+=	EXPAT
+OPTIONS_DEFAULT+=	EXPAT
 
 LIBFFI_DESC=		Use libffi from ports instead of bundled version
 NLS_DESC=		Enable gettext support for the locale module
 PYMALLOC_DESC=		Enable specialized mallocs
 TSC_DESC=		Enable rocessor timestamp counter profiling
+EXPAT_DESC=		Use expat from ports instead of bundled version
 
+EXPAT_CONFIGURE_ON=	--with-system-expat
 DEBUG_CONFIGURE_WITH=	pydebug
 IPV6_CONFIGURE_ENABLE=	ipv6
 
 LIBFFI_CONFIGURE_ON=	--with-system-ffi
 LIBFFI_LIB_DEPENDS=	libffi.so:devel/libffi
+EXPAT_LIB_DEPENDS=	libexpat.so:textproc/expat2
 
 # Use CPPFLAGS over CFLAGS due to -I ordering, causing elementtree and pyexpat
 # to break in Python 2.7, or preprocessor complaints in Python >= 3.3
@@ -112,6 +117,8 @@ post-patch:
 	@${REINPLACE_CMD} -e 's/disabled_module_list =[^]]*/&, "nis"/' \
 		${WRKSRC}/setup.py
 .endif
+	${REINPLACE_CMD} -e 's|`uname -r`|"${_OSRELEASE}"|g' \
+		${WRKSRC}/configure
 
 post-install:
 .if ! ${PORT_OPTIONS:MDEBUG}
