--- Makefile.orig	2014-08-02 14:04:12.866788000 +0000
+++ Makefile
@@ -31,7 +31,7 @@ MAKE_ARGS+=		INSTALL_SHARED="${INSTALL_L
 MAKE_ARGS+=		LIBPC="${PREFIX}/libdata/pkgconfig"			# Until pathfix gets support for files other than Makefile.in
 
 PLIST_SUB=		ABI=${ABIFLAGS} \
-			OSMAJOR=${OSVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
+			OSMAJOR=${DFLYVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
 
 OPTIONS_DEFINE=		DEBUG IPV6 NLS PYMALLOC THREADS TSC
 OPTIONS_DEFAULT=	IPV6 NLS PYMALLOC THREADS
