--- Makefile.orig	2017-07-02 23:12:29 UTC
+++ Makefile
@@ -12,12 +12,12 @@ COMMENT=	Cisco 1700/2600/3600/3700/7200
 
 LICENSE=	GPLv2
 
-LIB_DEPENDS=	libelf.so:devel/libelf
+LIB_DEPENDS=	libelf.so.0:devel/libelf
 
 BROKEN_powerpc=		fails to compile: invokes x86 assembler
 BROKEN_sparc64=		fails to compile: invokes x86 assembler
 
-CFLAGS+=	-I${PREFIX}/include/libelf
+CFLAGS+=	-I${PREFIX}/include -I${PREFIX}/include/libelf
 
 CONFLICTS=	dynamips-[0-9]* dynamips-devel-[0-9]*
 
