--- Makefile.orig	2013-03-09 17:44:20.000000000 +0100
+++ Makefile	2013-03-09 17:44:47.000000000 +0100
@@ -15,7 +15,8 @@
 MAINTAINER=	matthieu@labs.fr
 COMMENT=	SSLScan is a fast SSL port scanner
 
-MAKE_ARGS=	CC="${CC}" CFLAGS="-I${LOCALBASE}/include" LDFLAGS="-L${LOCALBASE}/lib"
+MAKE_ARGS=	CC="${CC}" CFLAGS="-I${LOCALBASE}/include"
+MAKE_ARGS+=	LDFLAGS="-lcrypto -L${LOCALBASE}/lib"
 
 MAN1=	sslscan.1
 PLIST_FILES=	bin/sslscan
