--- Makefile.orig	2017-12-28 19:04:35 UTC
+++ Makefile
@@ -113,8 +113,6 @@ LIB_DEPENDS+=			libpopt.so:devel/popt
 LIB_DEPENDS+=			libinotify.so:devel/libinotify
 # GNUTLS
 LIB_DEPENDS+=			libgnutls.so:security/gnutls
-# NFS4 ACL glue
-LIB_DEPENDS+=			libsunacl.so:sysutils/libsunacl
 # Libarchive
 BUILD_DEPENDS+=			libarchive>=3.1.2:archivers/libarchive
 RUN_DEPENDS+=			libarchive>=3.1.2:archivers/libarchive
@@ -154,8 +152,9 @@ CONFIGURE_ARGS+=		\
 				--with-winbind \
 				--disable-rpath \
 				--without-gettext \
+				--without-acl-support \
+				--without-regedit \
 				--enable-pthreadpool \
-				--with-acl-support \
 				--with-sendfile-support \
 				${ICONV_CONFIGURE_BASE}
 
