--- Makefile.orig	2016-04-06 16:31:44 UTC
+++ Makefile
@@ -18,7 +18,6 @@ BUILD_DEPENDS=	ca_root_nss>=0:security/c
 		gnome-autogen.sh:devel/gnome-common
 LIB_DEPENDS=	libstartup-notification-1.so:x11/startup-notification \
 		libupower-glib.so:sysutils/upower \
-		libcheese.so:multimedia/cheese \
 		libcaribou.so:accessibility/caribou \
 		libgtop-2.0.so:devel/libgtop \
 		libmuffin.so:x11-wm/muffin \
