--- Makefile.orig	2014-11-21 15:46:23.448154000 +0000
+++ Makefile
@@ -16,7 +16,6 @@ BUILD_DEPENDS=	ca_root_nss>=0:${PORTSDIR
 		gnome-autogen.sh:${PORTSDIR}/devel/gnome-common
 LIB_DEPENDS=	libstartup-notification-1.so:${PORTSDIR}/x11/startup-notification \
 		libupower-glib.so:${PORTSDIR}/sysutils/upower \
-		libcheese.so:${PORTSDIR}/multimedia/cheese \
 		libcaribou.so:${PORTSDIR}/accessibility/caribou \
 		libgtop-2.0.so:${PORTSDIR}/devel/libgtop \
 		libmuffin.so:${PORTSDIR}/x11-wm/muffin \
