--- Makefile.orig	2016-08-19 15:45:08 UTC
+++ Makefile
@@ -18,7 +18,6 @@ BUILD_DEPENDS=	ca_root_nss>=0:security/c
 		gnome-autogen.sh:devel/gnome-common
 LIB_DEPENDS=	libstartup-notification-1.so:x11/startup-notification \
 		libupower-glib.so:sysutils/upower \
-		libcheese.so:multimedia/cheese \
 		libcaribou.so:accessibility/caribou \
 		libgtop-2.0.so:devel/libgtop \
 		libmuffin.so:x11-wm/muffin \
@@ -26,7 +25,6 @@ LIB_DEPENDS=	libstartup-notification-1.s
 		libtelepathy-logger.so:net-im/telepathy-logger \
 		libgnomekbdui.so:x11/libgnomekbd \
 		libfolks.so:net-im/folks \
-		libpulse.so:audio/pulseaudio \
 		libcroco-0.6.so:textproc/libcroco \
 		libdbus-glib-1.so:devel/dbus-glib \
 		libclutter-glx-1.0.so:graphics/clutter \
