--- Makefile.orig	2019-12-06 19:23:15 UTC
+++ Makefile
@@ -57,7 +57,9 @@ CONFIGURE_ARGS+=	generic
 PLIST_SUB+=	ARCH="generic"
 .endif
 
+.if ${OPSYS} == FreeBSD
 CC=	${LOCALBASE}/bin/clang${LLVM_VER}
 CXX=	${LOCALBASE}/bin/clang++${LLVM_VER}
+.endif
 
 .include <bsd.port.mk>
