--- Makefile.orig	2019-09-04 12:05:52 UTC
+++ Makefile
@@ -35,19 +35,5 @@ PLIST_FILES=	bin/dspdfviewer \
 
 .include <bsd.port.pre.mk>
 
-# Build fails with LLVM 4.0.  Reported upstream as #191:
-# https://github.com/dannyedel/dspdfviewer/issues/191
-CFLAGS+=	-Wno-error=undefined-func-template
-
-.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1200039
-CFLAGS+=	-Wno-error=zero-as-null-pointer-constant
-.endif
-
-# Fixes build failure for Clang 8.0.0
-.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1300014
-CFLAGS+=	-Wno-error=extra-semi-stmt
-.endif
-
-CFLAGS+=	-Wno-error=redundant-parens
 
 .include <bsd.port.post.mk>
