--- Makefile.orig	2013-05-30 08:14:20.000000000 +0000
+++ Makefile
@@ -11,7 +11,6 @@ EXTRACT_ONLY=	# empty
 MAINTAINER=	c.petrik.sosa@gmail.com
 COMMENT=	Objective-C libraries based on the OpenStep standard
 
-BROKEN=		fails to build
 
 NO_BUILD=	yes
 NO_INSTALL=	yes
