--- Makefile.orig	2013-08-19 15:44:19.089563000 +0000
+++ Makefile
@@ -11,7 +11,8 @@ EXTRACT_ONLY=	# empty
 MAINTAINER=	c.petrik.sosa@gmail.com
 COMMENT=	Objective-C libraries based on the OpenStep standard
 
-BROKEN=		gnustep backend dependencies install files into the same place
+# Backends are slave ports with conflicting plists
+WITH_GNUSTEP_SINGLE_BACKEND=yes
 
 NO_BUILD=	yes
 NO_INSTALL=	yes
