--- Makefile.orig	2015-06-29 09:45:57.000000000 +0300
+++ Makefile
@@ -25,7 +25,7 @@ MANPAGES=	dnsfilter.1 dnsip.1 dnsipq.1 d
 
 ALL_TARGET=	it
 
-do-patch:
+pre-patch:
 	@${ECHO_CMD} "${CC} ${CFLAGS}" > ${WRKSRC}/conf-cc
 	@${ECHO_CMD} "${CC} ${STRIP}" > ${WRKSRC}/conf-ld
 	@${ECHO_CMD} "${PREFIX}" > ${WRKSRC}/conf-home
