--- Makefile.orig	2014-01-13 21:29:13.735207000 +0000
+++ Makefile
@@ -61,6 +61,9 @@ post-patch:
 		${WRKSRC}/include/quickmp.h
 	@${REINPLACE_CMD} -e 's|GEN_clamped|btClamped|g' \
 		${WRKSRC}/bullet/BulletDynamics/Dynamics/btRigidBody.cpp
+	@${REINPLACE_CMD} -e 's|isnan|std::isnan|g' \
+		${WRKSRC}/src/cardynamics.cpp ${WRKSRC}/src/car.cpp \
+		${WRKSRC}/src/ai.cpp ${WRKSRC}/include/cartire.h
 
 do-build:
 	@cd ${WRKSRC} && ${SETENV} ${MAKE_ENV} scons ${SCONS_ARGS}
