--- Makefile.orig	2012-12-10 20:24:05.000000000 +0100
+++ Makefile	2012-12-29 00:56:17.233307000 +0100
@@ -16,12 +16,18 @@
 MAINTAINER=	kde@FreeBSD.org
 COMMENT=	A high-level interface for RDF
 
-LIB_DEPENDS=	raptor2.0:${PORTSDIR}/textproc/raptor2 \
-		pcre.3:${PORTSDIR}/devel/pcre
+LIB_DEPENDS=	curl.6:${PORTSDIR}/ftp/curl \
+		icuuc.50:${PORTSDIR}/devel/icu \
+		raptor2.0:${PORTSDIR}/textproc/raptor2 \
+		pcre.3:${PORTSDIR}/devel/pcre \
+		xml2.5:${PORTSDIR}/textproc/libxml2 \
+		xslt.2:${PORTSDIR}/textproc/libxslt \
+		yajl.2:${PORTSDIR}/devel/yajl
 
 USE_GNOME=	gnomehack lthack pkgconfig
 USE_OPENSSL=	yes
 USE_GMAKE=	yes
+USE_ICONV=	yes
 GNU_CONFIGURE=	yes
 
 USE_LDCONFIG=	yes
