--- Makefile.orig	2013-02-09 01:13:13.766290000 +0100
+++ Makefile	2013-02-09 01:16:26.078267000 +0100
@@ -11,6 +11,11 @@
 COMMENT=	High-level interface for RDF
 
 LIB_DEPENDS=	raptor2:${PORTSDIR}/textproc/raptor2 \
+		curl.6:${PORTSDIR}/ftp/curl \
+		icuuc.50:${PORTSDIR}/devel/icu \
+		xml2.5:${PORTSDIR}/textproc/libxml2 \
+		xslt.2:${PORTSDIR}/textproc/libxslt \
+		yajl.2:${PORTSDIR}/devel/yajl \
 		pcre:${PORTSDIR}/devel/pcre
 
 USE_GNOME=	gnomehack lthack
@@ -19,6 +24,7 @@
 USE_PKGCONFIG=	yes
 GNU_CONFIGURE=	yes
 USE_GMAKE=	yes
+USE_ICONV=	yes
 USE_LDCONFIG=	yes
 
 MAN1=		rasqal-config.1 roqet.1
