--- Makefile.orig	2012-12-03 13:13:36.000000000 +0000
+++ Makefile
@@ -44,5 +44,5 @@ post-install:
 	${INSTALL_DATA} ${WRKSRC}/tictactoe/module.dsc ${PREFIX}/share/ggz/tictactoe.dsc
 
 .include <bsd.port.pre.mk>
-.include "${PORTSDIR}/games/libggz/bsd.ggz.mk"
+.include "../../games/libggz/bsd.ggz.mk"
 .include <bsd.port.post.mk>
