--- Makefile.orig	2012-11-17 05:59:16.000000000 +0000
+++ Makefile
@@ -18,7 +18,7 @@ RUN_DEPENDS=	antiword:${PORTSDIR}/textpr
 		catdoc:${PORTSDIR}/textproc/catdoc \
 		xls2csv:${PORTSDIR}/textproc/catdoc \
 		lynx:${PORTSDIR}/www/lynx \
-		${LOCALBASE}/libexec/xpdf/pdftotext:${PORTSDIR}/graphics/xpdf
+		pdftotext:${PORTSDIR}/graphics/poppler-utils
 
 USE_PERL5=	yes
 PLIST_FILES=	bin/${PORTNAME}
