--- Makefile.orig	2013-03-18 09:44:15.094373000 +0000
+++ Makefile
@@ -25,6 +25,7 @@ ALLEGRO_DESC=	Enable allegro support
 LIB_DEPENDS+=	alleg.42:${PORTSDIR}/devel/allegro
 PLIST_SUB+=	ALLEGRO=""
 MAKE_ARGS=	_PORT_ALLEGRO_CFLAGS="`allegro-config --cflags`"
+MAKE_ARGS+=	LINK_ALLEGRO="-lm -L${LOCALBASE}/lib -lalleg ${LOCALBASE}/lib/liballeg_unsharable.a"
 PKGNAMESUFFIX=	-allegro
 CONFLICTS=	dumb-[0-9]*
 .else
