MASTER_SITES+=	https://leaf.dragonflybsd.org/~mneumann/rust/:rust_bootstrap \
		https://leaf.dragonflybsd.org/~mneumann/rust/:cargo_bootstrap
MAKE_ENV="LD_LIBRARY_PATH=${WRKSRC}/build/${RUST_TARGET}/stage0/lib"
