--- Makefile.orig	2013-10-23 14:59:08.721438000 +0000
+++ Makefile
@@ -15,10 +15,10 @@ LIB_DEPENDS=	notify.4:${PORTSDIR}/devel/
 
 GNU_CONFIGURE=	yes
 USE_BZIP2=	yes
-USES=		gettext gmake
+USES=		gettext gmake pkgconfig
 USE_GNOME=	glib20 gtk20 gconf2 libxml2 librsvg2
 USE_GSTREAMER=	good
-LDFLAGS+=	-lintl
+LDFLAGS+=	-L${LOCALBASE}/lib -lintl
 
 NO_STAGE=	yes
 post-patch:
