--- Makefile.orig	2013-05-16 10:32:07.000000000 +0000
+++ Makefile
@@ -31,6 +31,7 @@ MAKE_JOBS_ARGS=	-j${MAKE_JOBS_NUMBER}
 
 do-configure:
 	@(cd ${WRKSRC} && ${SETENV} CC="${CC}" CFLAGS="${CFLAGS}" \
+		LINKFLAGS="-lm" \
 		CPPFLAGS="${CPPFLAGS}" ./waf configure --prefix=${PREFIX})
 
 do-build:
