--- Makefile.orig	2013-05-11 23:39:35.498304000 +0000
+++ Makefile
@@ -21,7 +21,15 @@ MAKE_ARGS=	CC="${CC}" CFLAGS="${CFLAGS}
 SHEBANG_FILES=	app/TeX/sfd2map \
 		app/TeX/cjk-latex-config \
 		other/showdf \
-		other/lst.pl
+		other/lst.pl \
+		other/cntstems.pl \
+		other/showg \
+		scripts/forceiso \
+		scripts/frommap \
+		scripts/inst_dir \
+		scripts/html2man \
+		scripts/t1fdir \
+		scripts/trans
 
 MAN1=		ttf2pt1.1 ttf2pt1_convert.1 ttf2pt1_x2gs.1
 
