--- Makefile.orig	2012-12-03 13:22:01.000000000 +0000
+++ Makefile
@@ -21,7 +21,6 @@ RUN_DEPENDS=	${LOCALBASE}/share/epiphany
 		cog:${PORTSDIR}/sysutils/cog \
 		gnome-blog-poster:${PORTSDIR}/deskutils/gnome-blog \
 		gnomesu:${PORTSDIR}/security/libgnomesu \
-		bpm:${PORTSDIR}/ports-mgmt/bpm \
 		gnome-file-share-properties:${PORTSDIR}/www/gnome-user-share \
 		serpentine:${PORTSDIR}/sysutils/serpentine \
 		devilspie:${PORTSDIR}/x11-wm/devilspie \
