--- Makefile.orig	2013-04-05 19:41:46.328471000 +0000
+++ Makefile
@@ -31,7 +31,7 @@ do-install:
 	@${INSTALL_PROGRAM} ${WRKSRC}/dnsproxy ${PREFIX}/sbin
 	@${INSTALL_MAN} ${WRKSRC}/dnsproxy.1 ${MAN1PREFIX}/man/man1
 	@${MKDIR} ${ETCDIR}
-	@${INSTALL_DATA} -v ${WRKSRC}/dnsproxy.conf ${ETCDIR}/dnsproxy.conf.sample
+	@${INSTALL_DATA} ${WRKSRC}/dnsproxy.conf ${ETCDIR}/dnsproxy.conf.sample
 
 post-install:
 	${CAT} ${PKGMESSAGE}
