--- Makefile.orig	2013-04-22 18:06:05.000000000 +0000
+++ Makefile
@@ -47,14 +47,8 @@ MANLANG=	"" fr
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} == "i386"
-LIB_DEPENDS+=		libEMF.so:${PORTSDIR}/graphics/libemf
-CONFIGURE_ARGS+=	--enable-libemf
-PLIST_SUB+=		WMF=""
-.else
 CONFIGURE_ARGS+=	--disable-libemf
 PLIST_SUB+=		WMF="@comment "
-.endif
 
 post-patch:
 	@${REINPLACE_CMD} -e 's|/usr/local|${LOCALBASE}|g' \
