--- Makefile.orig	2014-12-29 16:24:49 UTC
+++ Makefile
@@ -2,6 +2,7 @@
 
 COMMENT=	GNU binutils for powerpc64 cross-development
 PKGNAMEPREFIX=	powerpc64-
+BUTARGET=	powerpc64-freebsd
 PLIST=	${.CURDIR}/pkg-plist
 
 MASTERDIR=	${.CURDIR}/../binutils
