--- Makefile.orig	2014-02-05 12:45:52.398704000 +0000
+++ Makefile
@@ -47,7 +47,7 @@ WRITEABLES=	cache storage install tabdat
 
 do-patch:
 .for DIR in ${PATCHDIRS}
-	@${INSTALL_DATA} -v ${WRKDIR}/${DIR}/*.php ${WRKSRC}/${DIR}
+	${INSTALL_DATA} ${WRKDIR}/${DIR}/*.php ${WRKSRC}/${DIR}
 .endfor
 
 do-install:
@@ -57,7 +57,7 @@ do-install:
 .endfor
 	@( ${FIND} ${WRKSRC} -type f -maxdepth 1 \( -name \*.php -or -name \*.properties \
 		-or -name Copyright.txt \) -and -not -name config\* ; ${ECHO} ${WWWDIR} ) \
-		| ${XARGS} ${INSTALL_DATA} -v
+		| ${XARGS} ${INSTALL_DATA}
 .for FILE in ${CONFIGS}
 	${INSTALL_DATA}	${WRKSRC}/${FILE} ${WWWDIR}/${FILE}.sample
 .endfor
