--- Makefile.orig	2019-12-24 20:00:51.000000000 +0000
+++ Makefile
@@ -31,7 +31,7 @@ CPE_VENDOR=	apache
 
 .include <bsd.port.pre.mk>
 
-.if ${CHOSEN_COMPILER_TYPE} == gcc
+.if ${CHOSEN_COMPILER_TYPE} == gcc && ${OPSYS} == FreeBSD
 PLIST_SUB+=	MUTEXMGR="PosixMutexMgr"
 .else
 PLIST_SUB+=	MUTEXMGR="StdMutexMgr"
