--- Makefile.orig	2021-12-13 10:52:23 UTC
+++ Makefile
@@ -36,3 +36,3 @@
 
-.if ${OPSYS} == FreeBSD || ${SSL_DEFAULT} == openssl
+.if 0 # ${OPSYS} == FreeBSD || ${SSL_DEFAULT} == openssl
 # Requires LibreSSL for old SSL interface
