--- Makefile.orig	2013-07-26 14:25:16.000000000 +0000
+++ Makefile
@@ -10,7 +10,7 @@ MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}
 MAINTAINER=	ports@FreeBSD.org
 COMMENT=	Window manager that emphasizes efficiency, speed, and beauty
 
-USEs=		gmake
+USES=		gmake
 USE_EFL=	imlib2
 GNU_CONFIGURE=	yes
 CPPFLAGS+=	-I${LOCALBASE}/include
