--- Makefile.orig	2014-01-30 17:54:57.227718000 +0000
+++ Makefile
@@ -207,7 +207,8 @@ post-install:
 		${STAGEDIR}${PREFIX}/lib
 	(cd ${STAGEDIR}${PREFIX}/lib; ${LN} -sf lib${PYTHON_VERSION}.so.1 \
 		lib${PYTHON_VERSION}.so)
-	${LN} -sf lib${PYTHON_VERSION}.so ${STAGEDIR}${PYTHONPREFIX_LIBDIR}/config
+	(cd ${STAGEDIR}${PREFIX}/lib/${PYTHON_VERSION}/config; \
+		${LN} -sf ../../lib${PYTHON_VERSION}.so)
 	${INSTALL_PROGRAM} \
 		${SHARED_WRKSRC}/${PYTHON_VERSION:S/thon/thon-shared/} \
 		${STAGEDIR}${PREFIX}/bin
