--- Makefile.orig	2013-08-19 22:04:31.531428000 +0000
+++ Makefile
@@ -17,7 +17,7 @@ DIST_SUBDIR=	${PORTNAME}-${PORTVERSION}
 MAINTAINER=	stephen@FreeBSD.org
 COMMENT=	Device independent view of the CDF data model
 
-MAKE_FLAGS=	INSTALLDIR=${PREFIX} OS=${OPSYS:L} ENV=gnu      \
+MAKE_FLAGS=	INSTALLDIR=${PREFIX} OS=freebsd ENV=gnu      \
 		FORTRAN=yes FC_freebsd=${F77}
 USE_LDCONFIG=	yes
 MAKE_JOBS_UNSAFE=	yes
