--- Makefile.orig	2012-11-17 06:58:47.000000000 +0100
+++ Makefile	2013-01-04 08:58:03.991427000 +0100
@@ -14,4 +14,6 @@
 EXTRA_PATCHES=	${.CURDIR}/files/patch-*
 MASTERDIR=	${.CURDIR}/../../archivers/unzip
 
+PKGNAMEPREFIX=	ko-
+
 .include "${MASTERDIR}/Makefile"
