--- Makefile.orig	2024-02-02 00:14:07 UTC
+++ Makefile
@@ -20,7 +20,7 @@ NO_BUILD=	yes
 NO_WRKSUBDIR=	yes
 
 OPTIONS_DEFINE=	DOCS MYSQL_JDBC PGSQL_JDBC
-MYSQL_JDBC_RUN_DEPENDS=	${JAVALIBDIR}/mysql-connector-java.jar:databases/mysql-connector-java
+MYSQL_JDBC_RUN_DEPENDS=	${JAVALIBDIR}/mysql-connector-java.jar:databases/mysql-connector-j
 PGSQL_JDBC_RUN_DEPENDS=	${JAVALIBDIR}/postgresql.jar:databases/postgresql-jdbc
 
 pre-install:
