--- Makefile.orig	2017-08-04 03:40:22 UTC
+++ Makefile
@@ -32,12 +32,6 @@ PLIST_SUB=	VERSION=${GST10_VERSION} \
 USE_LDCONFIG=	yes
 GST10_VERSION=	1.0
 
-.include <bsd.port.options.mk>
-
-.if ${ARCH} == i386 || ${ARCH} == amd64
-LIB_DEPENDS+=	libunwind.so:devel/libunwind
-.endif
-
 post-patch:
 	@${REINPLACE_CMD} -e 's|-Wmissing-include-dirs||g' \
 		${WRKSRC}/configure
