--- Makefile.orig	2019-12-06 00:10:19 UTC
+++ Makefile
@@ -16,8 +16,4 @@
 LICENSE_FILE=	${WRKSRC}/LICENSE
 
-DEPRECATED=		OpenSSL 1.0.2 is End-of-Life 2019-12-31 at which \
-			time this port will update to 1.1.1 branch
-EXPIRATION_DATE=	2019-12-31
-
 OPTIONS_DEFINE=		DOCS MAN3 PADLOCK RFC3779 SHARED THREADS ZLIB
 CONFLICTS_INSTALL=	libressl-[0-9]* \
