--- Makefile.orig	2021-02-22 19:05:04 UTC
+++ Makefile
@@ -40,7 +40,7 @@ CONFIGURE_ARGS?=--disable-fsck \
 		--with-root-prefix='${PREFIX}' \
 		--without-included-gettext \
 		LDFLAGS='${LDFLAGS} -L${LOCALBASE}/lib -Wl,--rpath -Wl,${LOCALBASE}/lib/e2fsprogs'
-CONFIGURE_ENV?=	LIBS='-Wl,--as-needed ${LIBS} -lexecinfo -lelf'
+CONFIGURE_ENV?=	LIBS='-Wl,--as-needed ${LIBS} -lexecinfo'
 # apparently HAVE_PTHREAD_H checks go missing if the FUSEFS option is unset, force it:
 CPPFLAGS+=	-I${WRKSRC}/lib -I${LOCALBASE}/include # -D_EXT2_USE_C_VERSIONS
 MAKE_ARGS+=	pkgconfigdir='${PREFIX}/libdata/pkgconfig'
@@ -249,7 +249,7 @@ post-build:
 	cd ${WRKSRC}/e2fsck && ${RM} -f e2fsck \
 		&& ${MAKE_CMD} e2fsck V=1 \
 		LIBS="-static-libgcc -lc -Bstatic ../lib/libsupport.a ../lib/libext2fs.a ../lib/libcom_err.a \
-		${_staticlibs} /usr/lib/libexecinfo.a /usr/lib/libelf.a \
+		${_staticlibs} /usr/lib/libexecinfo.a \
 		${LOCALBASE}/lib/libblkid.a ${LOCALBASE}/lib/libuuid.a ${libintl} ../lib/libe2p.a " \
 		&& ${STRIP_CMD} e2fsck
 # Regression check: avoid a port (not upstream!) regression from 1.40.5,
@@ -291,19 +291,7 @@ post-build:
 .endif
 
 post-install:
-	# pkg workaround time again;
-	# the whole purpose of this dance is to move the necessities for
-	# /etc/fstab fsck'ing into /sbin, and symlink to these guys
-	# in the regular hierarchy, normally $PREFIX/sbin. Hard links may
-	# crash the install if /usr[/local] is a separate file system from /,
-	# and pkg 1.15.4 can't automatically unroll or install relative symlinks.
-	${MKDIR} ${STAGEDIR}/sbin
-	${MV} -f ${STAGEDIR}${PREFIX}/sbin/e2fsck ${STAGEDIR}/sbin/ # from INSTALL_TARGET
-	${INSTALL_PROGRAM} ${WRKSRC}/fsck_ext2fs ${STAGEDIR}/sbin/  # from port
-	# according to TPH 6.1.1 Handling Symbolic Links, these are to be absolute,
-	# yet stage-qa warns about these on 2020-09-16:
-	${LN} -fs /sbin/fsck_ext2fs ${STAGEDIR}${PREFIX}/sbin/
-	${LN} -fs /sbin/e2fsck      ${STAGEDIR}${PREFIX}/sbin/
+	${INSTALL_PROGRAM} ${WRKSRC}/fsck_ext2fs ${STAGEDIR}${PREFIX}/sbin/
 	# these are made hardlinks to symlinks - -P avoids following them to /sbin:
 	${LN} -fP ${STAGEDIR}${PREFIX}/sbin/e2fsck ${STAGEDIR}${PREFIX}/sbin/fsck.ext2
 	${LN} -fP ${STAGEDIR}${PREFIX}/sbin/e2fsck ${STAGEDIR}${PREFIX}/sbin/fsck.ext3
