--- Makefile.orig	2016-04-06 16:01:22 UTC
+++ Makefile
@@ -118,10 +118,8 @@ PLIST_SUB+=		QT4="@comment "
 .endif
 
 .if !defined(WITH_GCJ) && (${ARCH} == "amd64" || ${ARCH} == "i386")
-BUILD_DEPENDS+=		${LOCALBASE}/bootstrap-openjdk/bin/javac:java/bootstrap-openjdk
-JAR?=			${LOCALBASE}/bootstrap-openjdk/bin/jar
-JAVA?=			${LOCALBASE}/bootstrap-openjdk/bin/java
-JAVAC?=			${LOCALBASE}/bootstrap-openjdk/bin/javac
+USE_JAVA=		yes
+JAVA_VERSION=		1.6+
 .else
 USE_BINUTILS=		yes
 USE_GCC=		yes
