--- Makefile.orig	2016-07-26 18:17:53 UTC
+++ Makefile
@@ -43,8 +43,7 @@ MAKE_ARGS+=	GTK_CONFIG=:
 
 .if ${PORT_OPTIONS:MGSSAPI}
 _COMPAT=		-DSTATIC_GSSAPI
-USES+=		gssapi:base,flags
-MAKE_ARGS+=	KRB5CONFIG=${KRB5CONFIG}
+USES+=		gssapi:mit
 .else
 _COMPAT=		-DNO_GSSAPI
 .endif
