--- Makefile.orig	2023-02-19 01:10:20 UTC
+++ Makefile
@@ -254,7 +254,7 @@ post-build:
 	cd ${WRKSRC}/e2fsck && ${RM} -f e2fsck \
 		&& ${MAKE_CMD} e2fsck V=1 \
 		LIBS="-static-libgcc -lc -Bstatic ../lib/libsupport.a ../lib/libext2fs.a ../lib/libcom_err.a \
-		${_staticlibs} /usr/lib/libexecinfo.a /usr/lib/libelf.a \
+		${_staticlibs} /usr/lib/libexecinfo.a ${LOCALBASE}/lib/libelf.a \
 		${LOCALBASE}/lib/libblkid.a ${LOCALBASE}/lib/libuuid.a ${libintl} ../lib/libe2p.a " \
 		&& ${STRIP_CMD} e2fsck
 # Regression check: avoid a port (not upstream!) regression from 1.40.5,
