post-patch:
	${REINPLACE_CMD} -e 's|"FreeBSD"|"DragonFly"|' \
		${WRKSRC}/apps/fgr/configure \
		${WRKSRC}/apps/rodent-pkg/configure \
		${WRKSRC}/apps/rodent-iconmgr/configure \
		${WRKSRC}/apps/rodent-fgr/configure \
		${WRKSRC}/apps/rodent-fm/configure \
		${WRKSRC}/apps/rodent-diff/configure
