--- Makefile.orig	2021-08-31 11:17:14 UTC
+++ Makefile
@@ -132,8 +132,6 @@ LIBXML2_LIB_DEPENDS=	libxml2.so:textproc
 
 OPENSSL_CONFIGURE_WITH=	openssl
 OPENSSL_USES=		ssl
-OPENSSL_VARS=		BROKEN_SSL="libressl libressl-devel" \
-			BROKEN_SSL_REASON="PSK is not provided by LibreSSL"
 
 GNUTLS_CONFIGURE_WITH=	gnutls
 GNUTLS_LIB_DEPENDS=	libgnutls.so:security/gnutls
