--- Makefile.orig	2013-10-20 20:19:02.068824000 +0000
+++ Makefile
@@ -83,7 +83,7 @@ OPERA_ARCH=	${ARCH:S,i386,intel,}
 IGNORE=		only for FreeBSD 7.x and higher
 .endif
 
-.if ${OSVERSION} >= 1000054
+.if ${OPSYS} == FreeBSD && ${OSVERSION} >= 1000054
 RUN_DEPENDS+=	${LOCALBASE}/lib/compat/libstdc++.so.6:${PORTSDIR}/misc/compat9x
 .endif
 
