--- Makefile.orig	2019-01-31 15:22:32.413378000 +0000
+++ Makefile	2019-01-31 15:31:24.310034000 +0000
@@ -51,7 +51,9 @@
 	${RM} ${WRKSRC}/src/qt/qtwebkit/Source/WebCore/DerivedSources.cpp
 
 _ENV=	CC=${CC} CXX=${CXX} GMAKE=${GMAKE} OSTYPE=freebsd MAKEFLAGS= LOCALBASE=${LOCALBASE}
-_BLD=	${PYTHON_CMD} build.py --jobs ${MAKE_JOBS_NUMBER} --confirm
+_BLD=	${PYTHON_CMD} build.py --jobs ${MAKE_JOBS_NUMBER} --confirm --qmake-args='QMAKE_CXXFLAGS+= -Wno-expansion-to-defined -Wno-class-memaccess' \
+	--webkit-qmake-args='QMAKE_CXXFLAGS+= -Wno-expansion-to-defined -Wno-class-memaccess' \
+	--phantomjs-qmake-args='QMAKE_CXXFLAGS+= -Wno-expansion-to-defined -Wno-class-memaccess'
 do-build:
 .if defined(_PHANTOMJS_USE_QT_SYSTEM)
 	cd ${WRKSRC} && ${SETENV} ${_ENV} PATH=${PATH}:${QT_BINDIR} ${_BLD} --qt=system --qtwebkit=system
