--- Makefile.orig	2013-06-23 15:28:03.000000000 +0000
+++ Makefile
@@ -12,8 +12,8 @@ COMMENT=	A simple game about escaping fr
 
 LICENSE=	GPLv2
 
-LIB_DEPENDS=	radius:${PORTSDIR}/graphics/radius-engine \
-		lua-5.1:${PORTSDIR}/lang/lua \
+BUILD_DEPENDS=	${LOCALBASE}/lib/libradius-engine.a:${PORTSDIR}/graphics/radius-engine
+LIB_DEPENDS=	lua-5.1:${PORTSDIR}/lang/lua \
 		png15:${PORTSDIR}/graphics/png \
 		physfs.1:${PORTSDIR}/devel/physfs
 RUN_DEPENDS=	zip:${PORTSDIR}/archivers/zip
