--- Makefile.orig	2013-12-28 13:32:50.514843000 +0000
+++ Makefile
@@ -32,6 +32,9 @@ RUN_DEPENDS=bash:${PORTSDIR}/shells/bash
 RUN_DEPENDS=bash:${PORTSDIR}/shells/bash
 .endif
 
+post-patch:
+	@${REINPLACE_CMD} -e 's|FLAC|&\|flv\|FLV|;' ${WRKSRC}/bash_completion
+
 post-configure:
 	@${REINPLACE_CMD} -e 's|/usr/local|${PREFIX}|g; \
 		s|/etc/bash_completion|${PREFIX}&|g; \
@@ -42,10 +45,7 @@ post-configure:
 		s|/usr/lib\(/aspell\)|${PREFIX}/share\1|g; \
 		s|/usr/share/info|&:${PREFIX}/info|g; \
 		s|\$$(sysconfdir)/profile.d|${PREFIX}/bin|g; \
-		s|FLAC|&\|flv\|FLV|; \
-		s|\(profiledir = \)${PREFIX}/bin|\1${DATADIR}|g; \
-		s|\$$(datadir)/pkgconfig|${PREFIX}/libdata/pkgconfig|' \
-		${WRKSRC}/bash_completion ${WRKSRC}/Makefile.in \
+		s|\(profiledir = \)${PREFIX}/bin|\1${DATADIR}|g;' \
 		${WRKSRC}/completions/*
 
 post-install:
