--- Makefile.orig	2013-01-04 22:27:35.361696000 +0000
+++ Makefile
@@ -33,7 +33,9 @@ BINUTILVERSION=	2.21.1a
 LTSVERSION=	20120406
 PATCHVERSION=	20120406
 BUGS_FIXED=	# For future use
+.if !empty(BUGS_FIXED)
 LTS_PATCHES!=	for bugid in ${BUGS_FIXED} ; do echo ${PKGNAMEPREFIX}${PORTNAME}-${BINUTILVERSION}-${PATCHVERSION}-sf$${bugid}.patch ; done
+.endif
 
 USE_BZIP2=	yes
 USE_GMAKE=	yes
