--- Makefile.orig	2012-12-03 13:13:36.000000000 +0000
+++ Makefile
@@ -34,5 +34,5 @@ PLIST_SUB+=	NLS=""
 .endif
 
 .include <bsd.port.pre.mk>
-.include "${PORTSDIR}/games/libggz/bsd.ggz.mk"
+.include "../../games/libggz/bsd.ggz.mk"
 .include <bsd.port.post.mk>
