--- Uses/ltmainfix.mk.orig	2013-06-02 14:54:53.842009000 +0000
+++ Uses/ltmainfix.mk
@@ -0,0 +1,19 @@
+# $FreeBSD$
+#
+# Fix old configure scripts generated by buggy ltmain ([:space:] bug)
+#
+# MAINTAINER: draco@marino.st
+#
+# Feature:	ltmainfix
+# Usage:	USES=ltmainfix
+#
+
+.if !defined(_INCLUDE_USES_LTMAINFIX_Mk)
+_INCLUDE_USES_LTMAINFIX_MK=	yes
+
+pre-patch: fix-ltmain
+
+fix-ltmain:
+	@cd ${WRKSRC}; ${FIND} * -type f -name configure -print | \
+		${XARGS} ${REINPLACE_CMD} -e 's|\^\[:space:\]\*|^[[:space:]]*|g'
+.endif
