--- Makefile.orig
+++ Makefile
@@ -3,22 +3,27 @@
 
 PORTNAME=	mod_perl
 PORTVERSION=	2.0.8
-PORTREVISION=	1
+PORTREVISION=	2
 PORTEPOCH=	3
 CATEGORIES=	www perl5
 MASTER_SITES=	APACHE/perl
 PKGNAMEPREFIX=	${APACHE_PKGNAMEPREFIX}
 PKGNAMESUFFIX=	2
 
+PATCH_SITES=	${MASTER_SITE_LOCAL}
+PATCH_SITE_SUBDIR=	ohauer
+
 MAINTAINER=	apache@FreeBSD.org
 COMMENT=	Embeds a Perl interpreter in the Apache2 server
 
+LICENSE=	APACHE20
+
 BUILD_DEPENDS=	p5-BSD-Resource>=0:${PORTSDIR}/devel/p5-BSD-Resource
 RUN_DEPENDS:=	${BUILD_DEPENDS}
 
 SUB_FILES=	pkg-message
 SUB_LIST=	APACHEMODDIR=${APACHEMODDIR}
-USE_APACHE=	22
+USE_APACHE=	22+
 USES=		gmake perl5
 USE_PERL5=	configure
 USE_CSTD=	gnu89
@@ -26,7 +31,16 @@
 .include <bsd.port.pre.mk>
 
 .if ${APACHE_VERSION} > 22
-BROKEN=	Does not build with apache24
+# patch shaped against upstream mod_perl
+# Last Changed Rev: 1602105
+PATCHREV=	1602105
+PATCHFILES+= 	${PORTNAME}-${PORTVERSION}-r${PATCHREV}.diff.gz
+PLIST_SUB+=	AP24=""
+PMSED=		's/%AP24%//'
+NO_PACKAGE=	yes
+.else
+PLIST_SUB+=	AP24="@comment "
+PMSED=		'/%AP24%/d'
 .endif
 
 # Using apxs in this way is problematic if apache2 is installed under a
@@ -67,7 +81,10 @@
 	${REINPLACE_CMD} -e 's/-pthread -Wl,-E//g' \
 		${PATCH_WRKSRC}/xs/APR/APR/Makefile
 
+
 post-install:
+# adjust pkg-message
+	${REINPLACE_CMD} -e ${PMSED} ${WRKDIR}/pkg-message
 	${MKDIR} ${STAGEDIR}${PREFIX}/${APACHEINCLUDEDIR}/modules/perl
 	${INSTALL_DATA} ${WRKSRC}/src/modules/perl/*.h \
 		${STAGEDIR}${PREFIX}/${APACHEINCLUDEDIR}/modules/perl
