--- Makefile.orig	2015-10-18 13:32:24 +0200
+++ Makefile
@@ -19,10 +19,16 @@
 USE_XORG+=	glproto dri2proto xext xdamage xfixes presentproto \
 		xshmfence
 
+OPTIONS_DEFINE=		WAYLAND
+OPTIONS_DEFAULT=	WAYLAND
+
 .include <bsd.port.options.mk>
 .include "${.CURDIR}/../../graphics/libGL/Makefile.common"
 
-MESA_BUILD_WRKSRC=	src/mapi src/gbm
+.if ${PORT_OPTIONS:MWAYLAND}
+MESA_BUILD_WRKSRC=	src/egl/wayland/wayland-drm
+.endif
+MESA_BUILD_WRKSRC+=	src/mapi src/gbm
 MESA_INSTALL_WRKSRC=	src/gbm
 
 .include "${.CURDIR}/../../graphics/libGL/Makefile.targets"
