--- Makefile.orig	2017-07-03 21:51:30 UTC
+++ Makefile
@@ -21,8 +21,6 @@ CMAKE_ARGS+=	-DDOC_INSTALL_DIR:PATH=${DO
 # Parallel jobs breaks when the DOCS option is on
 MAKE_JOBS_UNSAFE=	yes
 
-EXTRACT_AFTER_ARGS=	--exclude '*/libmd5'
-
 PLIST_FILES=	bin/doxygen
 
 OPTIONS_DEFINE=	DOCS GRAPHVIZ LATEX SEARCH
