--- Makefile.orig	2021-05-09 12:09:33 UTC
+++ Makefile
@@ -22,8 +22,6 @@ CMAKE_ARGS+=	-DDOC_INSTALL_DIR:PATH=${DO
 # Parallel jobs breaks when the DOCS option is on
 MAKE_JOBS_UNSAFE=	yes
 
-EXTRACT_AFTER_ARGS=	--exclude '*/libmd5'
-
 DOS2UNIX_FILES=	doc/translator.py
 PLIST_FILES=	bin/doxygen
 
