--- Makefile.orig	2013-09-09 16:05:11.926605000 +0000
+++ Makefile
@@ -30,7 +30,7 @@ CONFIGURE_ARGS=	--program-suffix=${PORTV
 		--enable-tui ${ICONV_CONFIGURE_ARG}
 CFLAGS:=	${CFLAGS:C/ +$//}	# blanks at EOL creep in sometimes
 CFLAGS+=	-DRL_NO_COMPAT
-EXCLUDE=	dejagnu expect readline sim texinfo intl
+EXCLUDE=	dejagnu expect sim texinfo intl
 EXTRACT_AFTER_ARGS=	${EXCLUDE:S/^/--exclude /}
 VER=	${PORTVERSION:S/.//}
 PLIST_SUB=	VER=${VER}
@@ -78,19 +78,6 @@ CONFLICTS+=	gdb-insight*
 BROKEN=		Does not configure on ia64 or powerpc
 .endif
 
-.if ${ARCH} == "amd64"
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
-.endif
-
-post-patch:
-	@${REINPLACE_CMD} -e 's/$$/ [GDB v${PORTVERSION} for FreeBSD]/' \
-		${WRKSRC}/gdb/version.in
-	@${REINPLACE_CMD} -e 's/^READLINE/#READLINE/' \
-		-e 's/^readline/#readline/' \
-		-e 's,^LIBICONV =.*,LIBICONV=-L${LOCALBASE}/lib ${ICONV_LIB},' \
-		${WRKSRC}/gdb/Makefile.in
-	${ECHO} 'READLINE = -lreadline' >> ${WRKSRC}/gdb/Makefile.in
-
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/gdb/gdb ${PREFIX}/bin/gdb${VER}
 	${LN} ${PREFIX}/bin/gdb${VER} ${PREFIX}/bin/gdbtui${VER}
