--- Makefile.orig	2021-12-13 10:52:20 UTC
+++ Makefile
@@ -16,6 +16,7 @@
 		--disable-wallet
 
 PLIST_FILES=	bin/bitcoin-cli bin/bitcoin-tx \
+		bin/bitcoin-util man/man1/bitcoin-util.1.gz \
 		man/man1/bitcoin-cli.1.gz man/man1/bitcoin-tx.1.gz
 
 .include "${MASTERDIR}/Makefile"
