--- Makefile.orig	2016-04-07 08:08:19.000000000 +0300
+++ Makefile
@@ -71,12 +71,12 @@ do-install:
 	@${MKDIR} ${SITE_PERL:S|${LOCALBASE}|${STAGEDIR}${PREFIX}|}/AmphetaDesk
 	@(cd ${WRKSRC}/lib && \
 		${FIND} * -type d ! -empty -print0 | \
-		${XARGS} -0 -x -n 10 -I {} \
+		${XARGS} -0 -x -n 1 -I {} \
 		${MKDIR} ${SITE_PERL:S|${LOCALBASE}|${STAGEDIR}${PREFIX}|}/AmphetaDesk/{})
 # files
 	(cd ${WRKSRC}/lib && \
 		${FIND} * -type f -name "*pm" -print0 | \
-		${XARGS} -0 -x -n 10 -I {} \
+		${XARGS} -0 -x -n 1 -I {} \
 		${INSTALL_DATA} {} ${SITE_PERL:S|${LOCALBASE}|${STAGEDIR}${PREFIX}|}/AmphetaDesk/{})
 # script
 	${INSTALL_DATA} ${WRKSRC}/AmphetaDesk.pl \
@@ -101,13 +101,13 @@ do-install:
 # dirs
 	(cd ${WRKSRC} && \
 		${FIND} templates -type d ! -empty -print0 | \
-		${XARGS} -0 -x -n 10 -I {} \
+		${XARGS} -0 -x -n 1 -I {} \
 		${MKDIR} ${STAGEDIR}${DATADIR}/{})
 # files
 .for ext in gif html ico png pict
 	(cd ${WRKSRC} && \
 		${FIND} templates -type f -name "*.${ext}" -print0 | \
-		${XARGS} -0 -x -n 10 -I {} \
+		${XARGS} -0 -x -n 1 -I {} \
 		${INSTALL_DATA} {} ${STAGEDIR}${DATADIR}/{})
 .endfor
 
