--- Makefile.orig	2025-11-17 19:53:04.974171000 +0100
+++ Makefile	2025-11-17 19:53:15.804258000 +0100
@@ -20,8 +20,6 @@ LIB_DEPENDS=	libgcrypt.so:security/libgcrypt \
 		libgudev-1.0.so:devel/libgudev \
 		libudisks2.so:sysutils/libudisks \
 		libsecret-1.so:security/libsecret
-RUN_DEPENDS=	bsdisks>0:sysutils/bsdisks \
-		lsof:sysutils/lsof
 PORTSCOUT=	limitw:1,even
 
 USES=		cpe gettext gnome libarchive localbase meson \
