--- Makefile.orig	2014-07-30 19:35:12.618892000 +0000
+++ Makefile
@@ -22,6 +22,11 @@ USE_LDCONFIG=	yes
 USES=		libtool tar:xz
 GNU_CONFIGURE=	yes
 INSTALL_TARGET=	install-strip
+.if defined(PACKAGE_BUILDING)
+MAKE_ARGS+=	PKG_PORTSDIR=/usr/dports
+.else
+MAKE_ARGS+=	PKG_PORTSDIR=${PORTSDIR}
+.endif
 
 # Use a submake as 'deinstall install' needs to reevaluate PKG_CMD
 # so that pkg-static is used from the wrkdir
