--- Makefile.orig	2020-08-03 17:17:00 UTC
+++ Makefile
@@ -7,8 +7,6 @@ CATEGORIES=	devel kde kde-frameworks
 MAINTAINER=	kde@FreeBSD.org
 COMMENT=	KF5 hardware integration and detection
 
-RUN_DEPENDS=	bsdisks:sysutils/bsdisks
-
 USES=		bison cmake compiler:c++11-lib kde:5 qt:5 tar:xz
 USE_KDE=	ecm
 USE_QT=		concurrent core dbus declarative gui linguisttools \
