--- Makefile.orig	2014-04-17 13:48:03.488925000 +0000
+++ Makefile
@@ -8,7 +8,7 @@ PKGNAMESUFFIX=	-lite
 
 COMMENT=	The "meta-port" of the GNOME desktop slimmed down for FreeBSD releases
 
-RUN_DEPENDS=	${LOCALBASE}/libexec/gweather-applet-2:${PORTSDIR}/x11/gnome-applets \
+RUN_DEPENDS=	\
     		gnome-audio-profiles-properties:${PORTSDIR}/audio/gnome-media \
 	 	gnome-dictionary:${PORTSDIR}/deskutils/gnome-utils \
 		eog:${PORTSDIR}/graphics/eog \
