"""PR title/body + diffstat formatting and configurable committer
identity for the delivery orchestrator.

Covers:
- ``format_commit_message`` produces a sectioned markdown body with
  Summary / What changed / Verification / Provenance, and a clean
  title free of internal target jargon.
- ``_diffstat`` summarizes a unified diff.
- The config loader defaults the committer identity to
  "Fred [bot]" / "github@dragonflybsd.org" and honors overrides.
"""

from __future__ import annotations

from pathlib import Path

from dportsv3.delivery.config import load_delivery_config
from dportsv3.delivery.orchestrator import (
    _diffstat,
    _md_inline,
    _md_section,
    format_commit_message,
)


_TRIAGE_MD = """\
## Classification
patch-error

## Platform
DragonFly

## Root Cause
The bundled patch no longer applies — upstream renamed the function
the patch targets, so the hunk context drifted.

## Evidence
- `Hunk #1 FAILED at 42.`
- `1 out of 1 hunk FAILED -- saving rejects to file foo.c.rej`

## Suggested Fix
Regenerate the patch against the new upstream.

## Confidence
high
"""


def test_md_section_extracts_full_body():
    rc = _md_section(_TRIAGE_MD, "Root Cause")
    assert rc.startswith("The bundled patch no longer applies")
    assert "hunk context drifted." in rc
    # Stops at the next heading.
    assert "Evidence" not in rc


def test_md_section_caps_length():
    long = "## H\n" + ("x" * 5000) + "\n"
    out = _md_section(long, "H", max_chars=100)
    assert out.endswith("…(truncated)")
    assert len(out) < 200


def test_md_section_absent_returns_blank():
    assert _md_section(_TRIAGE_MD, "Nonexistent") == ""
    assert _md_section(None, "Root Cause") == ""


def test_md_inline_first_nonempty_line():
    assert _md_inline(_TRIAGE_MD, "Classification") == "patch-error"
    assert _md_inline(_TRIAGE_MD, "Confidence") == "high"
    assert _md_inline(None, "Classification") == ""


_SAMPLE_DIFF = """\
diff --git a/devel/foo/Makefile b/devel/foo/Makefile
index 111..222 100644
--- a/devel/foo/Makefile
+++ b/devel/foo/Makefile
@@ -1,3 +1,4 @@
 PORTNAME=foo
+USES=gmake
-OLD=line
diff --git a/devel/foo/files/patch-x b/devel/foo/files/patch-x
new file mode 100644
--- /dev/null
+++ b/devel/foo/files/patch-x
@@ -0,0 +1,2 @@
+hunk one
+hunk two
"""


def test_diffstat_counts_files_and_lines():
    stat = _diffstat(_SAMPLE_DIFF)
    assert "2 files changed" in stat
    # +USES, +hunk one, +hunk two = 3 insertions; -OLD = 1 deletion.
    assert "+3/-1" in stat
    assert "`devel/foo/Makefile`" in stat
    assert "`devel/foo/files/patch-x`" in stat


def test_diffstat_empty_diff_returns_blank():
    assert _diffstat("") == ""


def test_commit_message_title_has_no_internal_target_jargon():
    title, _ = format_commit_message(
        origin="devel/foo", target="@2026Q2", operator="alice",
        model=None, attempts=None, tokens=None, verified_at=None,
    )
    assert title == "devel/foo: fix build failure on DragonFly"
    assert "@2026Q2" not in title


def test_commit_message_body_full_narrative():
    _, body = format_commit_message(
        origin="devel/foo", target="@2026Q2",
        operator="alice", model="opus", attempts=2, tokens=12345,
        verified_at="2026-05-28T10:00:00Z",
        diff_text=_SAMPLE_DIFF,
        patch_summary="Add USES=gmake to fix the build.",
        root_cause="The Makefile invoked gmake without declaring it.",
        classification="patch-error",
        confidence="high",
        evidence="- `gmake: command not found`",
    )
    # Disclosure header.
    assert "> Generated by the DragonFly agentic build-fix loop" in body
    assert "operator `alice`" in body
    # Problem: classification/confidence + root cause + evidence.
    assert "## Problem" in body
    assert "classified `patch-error`" in body
    assert "confidence `high`" in body
    assert "The Makefile invoked gmake without declaring it." in body
    assert "**Evidence:**" in body
    assert "gmake: command not found" in body
    # Fix.
    assert "## Fix\n\nAdd USES=gmake to fix the build." in body
    # What changed.
    assert "2 files changed, +3/-1" in body
    # Verification.
    assert "for target `@2026Q2`." in body
    assert "Verified 2026-05-28T10:00:00Z." in body
    # Provenance (no tracker URL).
    assert "- Operator: alice" in body
    assert "- Agent: model=opus attempts=2 tokens=12345" in body
    assert "Bundle:" not in body


def test_commit_message_degrades_without_triage_or_patch_prose():
    _, body = format_commit_message(
        origin="devel/foo", target="@2026Q2", operator="alice",
        model=None, attempts=None, tokens=None, verified_at=None,
    )
    # Problem still renders (header line), Fix synthesizes a default.
    assert "## Problem" in body
    assert "The build failed on `@2026Q2`." in body
    assert "## Fix" in body
    assert "Automated fix for the build failure in `devel/foo`." in body
    # No diff → no "What changed" section.
    assert "## What changed" not in body
    # No classification → no "classified" clause.
    assert "classified" not in body


def _write_toml(tmp_path: Path, text: str) -> Path:
    p = tmp_path / "delivery.toml"
    p.write_text(text)
    return p


def test_config_defaults_committer_identity(tmp_path):
    cfg = load_delivery_config(
        _write_toml(tmp_path, """
[provider]
type = "github"
repo = "DragonFlyBSD/DeltaPorts"
clone_dir = "/tmp/clone"
"""),
        env={"DPORTSV3_DELIVERY_TOKEN": "tok"},
    )
    assert cfg.committer_name == "Fred [bot]"
    assert cfg.committer_email == "github@dragonflybsd.org"


def test_config_committer_identity_override(tmp_path):
    cfg = load_delivery_config(
        _write_toml(tmp_path, """
[provider]
type = "github"
repo = "DragonFlyBSD/DeltaPorts"
clone_dir = "/tmp/clone"
committer_name = "Custom Bot"
committer_email = "custom@example.org"
"""),
        env={"DPORTSV3_DELIVERY_TOKEN": "tok"},
    )
    assert cfg.committer_name == "Custom Bot"
    assert cfg.committer_email == "custom@example.org"
