--- Makefile.orig	2016-12-27 15:33:20 UTC
+++ Makefile
@@ -13,7 +13,7 @@ LICENSE=	BSD3CLAUSE
 LICENSE_FILE=	${WRKSRC}/LICENSE
 
 LIB_DEPENDS=	libexpat.so:textproc/expat2 \
-		libldns.so:dns/ldns
+		libldns.so.1.6.17:dns/ldns
 
 BROKEN_aarch64=	Fails to link: missing sbrk
 
