--- Makefile.orig	2016-01-04 16:23:04 UTC
+++ Makefile
@@ -41,7 +41,7 @@ FILTER_AAAA_DESC=	Build with AAAA filter
 .include <bsd.port.options.mk>
 
 LIB_DEPENDS+=	libexpat.so:${PORTSDIR}/textproc/expat2 \
-		libldns.so:${PORTSDIR}/dns/ldns
+		libldns.so.1.6.17:${PORTSDIR}/dns/ldns
 
 STRIP_FILES=	.libs/libunbound.so unbound-checkconf unbound \
 		unbound-control .libs/unbound-host .libs/unbound-anchor
