--- Makefile.orig	2016-04-06 15:52:17 UTC
+++ Makefile
@@ -42,7 +42,7 @@ DNSTAP_DESC=	Enable dnstap logging suppo
 .include <bsd.port.options.mk>
 
 LIB_DEPENDS+=	libexpat.so:textproc/expat2 \
-		libldns.so:dns/ldns
+		libldns.so.1.6.17:dns/ldns
 
 STRIP_FILES=	.libs/libunbound.so unbound-checkconf unbound \
 		unbound-control .libs/unbound-host .libs/unbound-anchor
