--- Makefile.orig	2012-12-03 14:16:06.000000000 +0100
+++ Makefile	2012-12-10 14:52:00.421484000 +0100
@@ -118,9 +118,9 @@
 do-build: ${MAN_TARGET} build-profile build-shared build-static
 
 .for o in PROFILE SHARED STATIC
-build-${o:L}: patch
+build-${o:tl}: patch
 .if defined(WITH_${o})
-	${PRINTF} "\n\nBuilding ${o:L} libraries:\n\n\n"
+	${PRINTF} "\n\nBuilding ${o:tl} libraries:\n\n\n"
 	cd ${WRKSRC_${o}}; ${SETENV} ${MAKE_ENV} EXTRAFLAGS="${FFLAGS_${o}}" \
 	${MAKE} ${_MAKE_JOBS} ${MAKE_ARGS} ARCH="${AR}" ${ALL_TARGET}
 
@@ -154,9 +154,9 @@
 check regression-test test: ${TESTS}
 
 .for o in PROFILE SHARED STATIC
-test-${o:L}: build-${o:L}
+test-${o:tl}: build-${o:tl}
 .if defined(WITH_${o})
-	@${PRINTF} "\n\nTesting ${o:L} libraries:\n\n\n"
+	@${PRINTF} "\n\nTesting ${o:tl} libraries:\n\n\n"
 	@cd ${WRKSRC_${o}}; ${SETENV} ${MAKE_ENV} EXTRAFLAGS="${FFLAGS_${o}}" \
 	${MAKE} ${_MAKE_JOBS} ${MAKE_ARGS} ARCH="${AR}" ${TEST_TARGET}
 .if defined(BLAS_SLAVEPORT)
