--- Makefile.orig	2021-07-13 22:56:38 UTC
+++ Makefile
@@ -123,6 +123,8 @@ post-build:
 
 .include "${FILESDIR}/manpages"
 
+ALL_MAN3=	${MAN3L:S|^|man3/|}
+
 post-install:
 .if defined(BLAS_SLAVEPORT)
 	${INSTALL_DATA} ${CONFIGURE_WRKSRC}/BLAS/SRC/${BLASLIB} ${STAGEDIR}${PREFIX}/lib
@@ -164,8 +166,7 @@ post-install:
 	${LN} -sf libtmglib.so.${PORTVERSION} ${STAGEDIR}${PREFIX}/lib/libtmglib.so.${SVERSION}
 .endif
 .if !(defined(BLAS_SLAVEPORT) || defined(CBLAS_SLAVEPORT) || defined(XLAPACK_SLAVEPORT) || defined(LAPACKE_SLAVEPORT))
-	cd ${WRKDIR}/man ; ${ECHO_CMD} ${MAN3L:S|^|man3/|} \
+	cd ${WRKDIR}/man ; ${MAKE} -V ALL_MAN3 \
 	| ${XARGS} -J @ ${INSTALL_MAN} @ ${STAGEDIR}${MAN3PREFIX}/man/man3
 .endif
-
 .include <bsd.port.post.mk>
