--- Makefile.orig	2016-03-03 11:43:37 UTC
+++ Makefile
@@ -54,11 +54,6 @@ BINS=		${DIST}/${OPSYS}${OSREL}_OPT.OBJ
 BINS=		${DIST}/${OPSYS}${OSREL}_DBG.OBJ
 .endif
 
-.if ${ARCH} == amd64
-USE_BINUTILS=	# intel-gcm.s
-CC+=	-B${LOCALBASE}/bin
-.endif
-
 check regression-test test:
 	cd ${WRKSRC}/tests;	\
 		${SETENV} PATH="${BINS}/bin:${PATH}" \
