--- Makefile.orig	2013-04-14 09:57:19.596645000 +0000
+++ Makefile
@@ -780,7 +780,7 @@ post-patch:
 			   s!QUEUE_EXTRALEN 0!QUEUE_EXTRALEN 5!g' \
 			   ${WRKSRC}/extra.h
 .endif
-.if ( ${ARCH} == "amd64" || ${ARCH} == "ia64" ) && !defined(SLAVE_LDAP)
+.if !defined(SLAVE_LDAP)
 	@${PATCH} -d ${WRKSRC} < ${FILESDIR}/extra-patch-amd64
 .endif
 	@${REINPLACE_CMD} -e "s/void *main/int main/g" ${WRKSRC}/*.c
