--- Makefile.orig	2024-01-06 19:29:33 UTC
+++ Makefile
@@ -1,6 +1,6 @@
 PORTNAME=	pkgconf
 PORTVERSION=	2.0.3
-PORTEPOCH=	1
+PORTEPOCH=	2
 CATEGORIES=	devel
 MASTER_SITES=	https://distfiles.ariadne.space/${PORTNAME}/
 
