--- Makefile.orig	2016-09-13 17:47:47 UTC
+++ Makefile
@@ -19,7 +19,7 @@ OPTIONS_SINGLE=	GSSAPI
 OPTIONS_RADIO_RESOLV=	CARES THREADED_RESOLVER
 OPTIONS_RADIO_SSL=	GNUTLS NSS OPENSSL POLARSSL WOLFSSL
 OPTIONS_SINGLE_GSSAPI=	GSSAPI_BASE GSSAPI_HEIMDAL GSSAPI_MIT GSSAPI_NONE
-OPTIONS_DEFAULT=	CA_BUNDLE COOKIES OPENSSL PROXY RESOLV THREADED_RESOLVER TLS_SRP
+OPTIONS_DEFAULT=	CA_BUNDLE COOKIES OPENSSL PROXY RESOLV THREADED_RESOLVER
 CA_BUNDLE_DESC=		Install CA bundle for OpenSSL
 CA_BUNDLE_IMPLIES=	OPENSSL
 COOKIES_DESC=		Cookies support
@@ -31,13 +31,8 @@ RESOLV_DESC=		DNS resolving options
 THREADED_RESOLVER_DESC=	Threaded DNS resolver
 TLS_SRP_DESC=		TLS-SRP (Secure Remote Password) support
 
-.include <${.CURDIR}/../../Mk/bsd.default-versions.mk>
-
-.if ${SSL_DEFAULT} != base
-OPTIONS_DEFAULT+=	GSSAPI_NONE
-.else
-OPTIONS_DEFAULT+=	GSSAPI_BASE
-.endif
+OPTIONS_EXCLUDE=	GSSAPI_BASE
+OPTIONS_DEFAULT+=	GSSAPI_MIT
 
 CONFIGURE_ARGS+=--disable-werror \
 		--enable-imap --enable-pop3 --enable-rtsp --enable-smtp \
@@ -141,6 +136,16 @@ WOLFSSL_LIB_DEPENDS=	libwolfssl.so:secur
 
 .include <bsd.port.pre.mk>
 
+# SSL_DEFAULT only available here if defined in make.conf
+.if ${SSL_DEFAULT:Nlibressl*}
+OPTIONS_DEFAULT+=	TLS_SRP
+.else
+# Maintain original option for pre-LibreSSL platforms
+.  if !exists(/usr/lib/priv/libprivate_ssl.so)
+OPTIONS_DEFAULT+=	TLS_SRP
+.  endif
+.endif
+
 .if !${PORT_OPTIONS:MGNUTLS} && !${PORT_OPTIONS:MOPENSSL} && ${PORT_OPTIONS:MTLS_SRP}
 IGNORE=		only supports TLS-SRP with either OpenSSL or GnuTLS
 .endif
