--- Makefile.orig	2021-06-19 14:00:20 UTC
+++ Makefile
@@ -2,7 +2,7 @@
 
 PORTNAME=	go
 PORTVERSION?=	1.16.5
-PORTREVISION?=	0
+PORTREVISION?=	1
 PORTEPOCH?=	1
 CATEGORIES=	lang
 MASTER_SITES?=	https://golang.org/dl/ \
