--- Makefile.orig	2022-06-13 21:00:33 UTC
+++ Makefile
@@ -26,7 +26,7 @@ CONFIGURE_ARGS=	--program-transform-name
 
 TEST_TARGET=	test
 
-OPTIONS_DEFAULT=	LIBPCAP_BASE
+OPTIONS_DEFAULT=	LIBPCAP_PORTS
 OPTIONS_SINGLE=		LIBPCAP
 OPTIONS_SINGLE_LIBPCAP=	LIBPCAP_BASE LIBPCAP_PORTS
 
@@ -34,6 +34,6 @@ LIBPCAP_BASE_DESC=	Build with libpcap fr
 LIBPCAP_PORTS_DESC=	Build with net/libpcap
 
 LIBPCAP_BASE_CONFIGURE_ON=	--with-libpcap=/usr/lib
-LIBPCAP_PORTS_LIB_DEPENDS=	libpcap.so:net/libpcap
+LIBPCAP_PORTS_LIB_DEPENDS=	libpcap.so.1:net/libpcap
 
 .include <bsd.port.mk>
