--- Makefile.orig	2018-04-27 21:01:33 UTC
+++ Makefile
@@ -31,7 +31,6 @@ USES=		cpe libtool pathfix pkgconfig
 USE_LDCONFIG=	yes
 OPTIONS_SUB=	yes
 CFLAGS+=	-fpic -DPIC -Wl,-rpath,${PREFIX}/lib -Wl,--as-needed
-LDFLAGS+=	-lthr
 
 INSTALL_TARGET=	install-strip
 TEST_TARGET=	check
