--- Makefile.orig	2013-02-09 14:41:28.000000000 +0000
+++ Makefile
@@ -3,9 +3,9 @@
 
 PORTNAME=	minecraft-server
 PORTVERSION=	1.4.6
+PORTREVISION=	1
 CATEGORIES=	games java
-MASTER_SITES=	http://s3.amazonaws.com/MinecraftDownload/launcher/ \
-		http://denkrobat.de/minecraft/ \
+MASTER_SITES=	http://assets.minecraft.net/${PORTVERSION:S|.|_|g}/ \
 		http://media-mcw.cursecdn.com/f/f7/:icon
 DISTNAME=	minecraft_server
 DISTFILES=	minecraft_server.jar \
