--- Makefile.orig	2014-05-27 11:27:59.413902000 +0000
+++ Makefile
@@ -36,6 +36,8 @@ vi_PORT=	vietnamese/kde4-l10n
 zh_CN_PORT=	chinese/kde4-l10n-zh_CN
 zh_TW_PORT=	chinese/kde4-l10n-zh_TW
 
+KDE4_LANG_ALL:=	${KDE4_LANG_ALL:Npt}
+
 .include <${.CURDIR}/files/kde4-lang-names>
 # kde4-lang-names is encoded in UTF, override with plain ASCII:
 nb_NAME=	Norwegian Bokmal
