--- Makefile.orig	2013-09-11 23:47:31.626274000 +0000
+++ Makefile
@@ -29,7 +29,7 @@ GCC_VERSION=	${PORTVERSION:C/(.+)\.[0-9]
 SUFFIX=		${PORTVERSION:C/([0-9]+).([0-9]+).*/\1\2/}
 LATEST_LINK=	gcc${SUFFIX}${PKGNAMESUFFIX}
 ONLY_FOR_ARCHS=	amd64 i386 powerpc powerpc64 sparc64
-USES=		bison gmake iconv
+USES=		gmake iconv
 USE_BINUTILS=	yes
 USE_BZIP2=	yes
 USE_PERL5_BUILD=yes
@@ -48,9 +48,9 @@ BOOTSTRAP_DESC=		Build using a full boot
 .include <bsd.port.pre.mk>
 
 .if ${ARCH} == "amd64"
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .else
-CONFIGURE_TARGET=	${ARCH}-portbld-freebsd${OSREL}
+CONFIGURE_TARGET=	${ARCH}-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 .if ${ARCH} == powerpc64
