--- Makefile.orig	2019-01-22 16:56:45 UTC
+++ Makefile
@@ -19,7 +19,7 @@ BUILD_DEPENDS=	gauche-config:lang/gauche
 
 USES=		tar:tgz
 
-GAUCHE_LIBDIR=	${:!gauche-config --sitelibdir!:S,^${PREFIX}/,,}
+GAUCHE_LIBDIR=	share/gauche/site/lib
 PLIST_SUB+=	GAUCHE_LIBDIR=${GAUCHE_LIBDIR}
 
 DOCSDIR=	${PREFIX}/share/doc/gauche/${PORTNAME}
