--- Makefile.orig	2020-01-17 18:35:20 UTC
+++ Makefile
@@ -11,9 +11,6 @@ EXTRACT_ONLY=	# empty
 MAINTAINER=	python@FreeBSD.org
 COMMENT=	The "meta-port" for version 2 of the Python interpreter
 
-DEPRECATED=	EOLed upstream
-EXPIRATION_DATE=	2020-12-31
-
 USES=		python:2.7,run
 
 NO_ARCH=	yes
