--- Makefile.orig	2013-02-18 19:13:02.764248000 +0100
+++ Makefile	2013-02-18 19:13:28.253001000 +0100
@@ -29,10 +29,12 @@
 .include "../evas-core/Makefile.inc"
 CONFIGURE_ARGS+=	--enable-software-xlib
 
+LDFLAGS+=	-L${LOCALBASE}/lib -levas
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/\.libs,${LOCALBASE}/lib,' \
-		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,-levas,' \
+		-e 's,\$$\(top_builddir\)/src/lib/libevas\.la,,' \
 		${BUILD_WRKSRC}/Makefile.in
 
 post-install:
