
MAINTAINER=	zrj@ef.irc
COMMENT=	Web browser based on the browser portion of Mozilla (lite package)

LITE=		yes
MASTERDIR=	${.CURDIR}/../firefox
IGNORE=		no longer builds

.include "${MASTERDIR}/Makefile"
