--- Makefile.orig	2017-01-27 18:06:34 UTC
+++ Makefile
@@ -33,6 +33,7 @@ USE_LDCONFIG=	yes
 CFLAGS+=	-I${LOCALBASE}/include -fPIC
 CXXFLAGS+=	-I${LOCALBASE}/include -fPIC
 LDFLAGS+=	-lpthread
+CONFIGURE_ENV=	CFLAGS="${CFLAGS}"
 CMAKE_ARGS+=	-DDOCDIR="${DOCSDIR}" \
 		-DCREDITSDIR="${DOCSDIR}" \
 		-DLICENCEDIR="${DOCSDIR}" \
@@ -71,8 +72,7 @@ OPTIMIZED_CFLAGS_CFLAGS_gcc=	-fexpensive
 #
 
 .if !empty(PORT_OPTIONS:MOPENMP) && ${ARCH} == "amd64"
-LIB_DEPENDS+=	libomp.so.0:devel/openmp
-OPENMP_FLAGS=	-lm -lomp
+OPENMP_FLAGS=	-lm -lgomp
 LDFLAGS+=	${OPENMP_FLAGS}
 .if ${OSVERSION} < 1100101
 # clang 3.4 doesn't support OpenMP,
