--- Makefile.orig	2015-01-20 01:00:56 UTC
+++ Makefile
@@ -14,13 +14,12 @@ LICENSE=	LGPL21
 LICENSE_FILE=	${WRKSRC}/COPYING
 
 LIB_DEPENDS=	libsrtp.so:${PORTSDIR}/net/libsrtp \
-		libzrtpcppcore.so:${PORTSDIR}/security/libzrtpcppcore
 
 CONFLICTS_INSTALL=	linphone-base-[0-9]*
 
 GNU_CONFIGURE=	yes
 CONFIGURE_ARGS=	--disable-silent-rules --disable-strict \
-		--enable-zrtp --with-srtp
+		--with-srtp
 INSTALL_TARGET=	install-strip
 USES=		libtool pathfix pkgconfig
 USE_LDCONFIG=	yes
