--- Makefile.orig	2017-07-06 14:29:18 UTC
+++ Makefile
@@ -48,6 +48,6 @@ post-patch:
 
 post-install:
 # XXX: palliative; better fix installation routine not to pollute ${STAGEDIR}
-	@${RMDIR} ${STAGEDIR}${PREFIX}/share/mitsuba/data/ior/CMakeFiles
+	@${RM} -r ${STAGEDIR}${PREFIX}/share/mitsuba/data/ior/CMakeFiles
 
 .include <bsd.port.mk>
