--- Makefile.orig	2020-04-07 08:41:57.817572000 +0200
+++ Makefile	2020-04-07 08:43:36.528006000 +0200
@@ -18,7 +18,6 @@
 			evdev \
 			joystick \
 			keyboard \
-			libinput \
 			mouse \
 			synaptics \
 			void \
@@ -27,29 +26,30 @@
 VIDEO_DRIVERS=		apm \
 			ark \
 			ast \
-			chips \
-			cirrus \
 			dummy \
 			glint \
 			i128 \
 			i740 \
-			mach64 \
 			mga \
+			s3 \
+			scfb \
+			tdfx \
+			trident \
+			tseng \
+			vesa \
+			vmware
+
+VIDEO_DRIVERS_REMOVED=	libinput \
+			mach64 \
+			chips \
+			cirrus \
 			neomagic \
-			nv \
-			openchrome \
 			r128 \
 			rendition \
-			s3 \
 			s3virge \
 			savage \
-			scfb \
 			siliconmotion \
 			sis \
-			tdfx \
-			trident \
-			tseng \
-			vesa \
 			voodoo
 
 OPTIONS_DEFAULT=	KEYBOARD \
@@ -64,8 +64,8 @@
 . endfor
 .endfor
 
-OPTIONS_DEFINE_amd64=	AMDGPU ATI INTEL VMMOUSE VMWARE
-OPTIONS_DEFAULT_amd64=	VESA
+OPTIONS_DEFINE_x86_64=	AMDGPU ATI INTEL VMMOUSE VMWARE
+OPTIONS_DEFAULT_x86_64=	ATI INTEL VESA
 
 OPTIONS_DEFINE_i386:=	${OPTIONS_DEFINE_amd64} GEODE
 OPTIONS_DEFAULT_i386:=	${OPTIONS_DEFAULT_amd64}
@@ -87,7 +87,7 @@
 .include <bsd.port.options.mk>
 
 # Manual add arch specific drivers so they be added to depend lines.
-.if ${ARCH}==i386 || ${ARCH}==amd64
+.if ${ARCH}==i386 || ${ARCH}==x86_64
 INPUT_DRIVERS+= vmmouse
 VIDEO_DRIVERS+=	amdgpu ati intel vmware
 .endif
