--- Makefile.orig	2015-09-09 11:34:30 UTC
+++ Makefile
@@ -5,11 +5,13 @@ PORTVERSION=	${JDK_MAJOR_VERSION}.${JDK_
 CATEGORIES=	java devel
 MASTER_SITES=	http://download.java.net/openjdk/jdk${JDK_MAJOR_VERSION}/promoted/b${DIST_BUILD_NUMBER}/:jdk \
 		https://adopt-openjdk.ci.cloudbees.com/job/jtreg/${JTREG_JENKINS_BUILD}/artifact/:jtreg \
+		http://dl.wolfpond.org/openjdk8/:bootstrap \
+		http://leaf.dragonflybsd.org/~marino/dports-src/:bootstrap \
 		LOCAL/jkim:jdk,jtreg
 PATCH_SITES=	LOCAL/glewis/openjdk8
 PKGNAMESUFFIX?=	${JDK_MAJOR_VERSION}
 DISTNAME=	${PORTNAME}-${JDK_MAJOR_VERSION}-src-b${DIST_BUILD_NUMBER}-03_mar_2014
-DISTFILES=	${DISTNAME}.zip:jdk
+DISTFILES=	${DISTNAME}.zip:jdk ${BOOTSTRAP_DISTFILE}
 PATCHFILES=	patch-8u05-b13.xz \
 		patch-8u11-b13.xz \
 		patch-8u20-b26.xz \
@@ -178,7 +180,7 @@ _MAKE_JOBS=	#
 CPPFLAGS+=	-I${LOCALBASE}/include
 LDFLAGS+=	-L${LOCALBASE}/lib
 MAKE_ENV=	LANG="C" LC_ALL="C"
-MAKE_ENV+=	CLASSPATH="" JAVA_HOME="" LD_LIBRARY_PATH="" MAKEFLAGS=""
+MAKE_ENV+=	CLASSPATH="" JAVA_HOME="" MAKEFLAGS=""
 MAKE_ENV+=	IGNORE_OLD_CONFIG=true
 MAKE_ENV+=	COMPILER_WARNINGS_FATAL="false"
 
@@ -189,6 +191,7 @@ JRE_IMAGEDIR=	${JDK_BUILDDIR}/images/j2s
 .else
 JRE_IMAGEDIR=	${JDK_BUILDDIR}/images/j2re-image
 .endif
+JDK_ARCH=       ${ARCH:S/x86_64/amd64/}
 JDK_OSARCH=	bsd-${ARCH:S/i386/x86/:S/amd64/x86_64/}
 INSTALLDIR=	${PREFIX}/${PKGBASE}
 
@@ -283,8 +286,15 @@ BOOTSTRAPJDKDIR=	${BJDK}
 
 # if no valid jdk found, set dependency
 .if !defined(BOOTSTRAPJDKDIR)
+.  if ${OSREL:S/.//} < 41
 BOOTSTRAPJDKDIR?=	${LOCALBASE}/openjdk7
 BUILD_DEPENDS+=		${BOOTSTRAPJDKDIR}/bin/javac:${PORTSDIR}/java/openjdk7
+MAKE_ENV+=		LD_LIBRARY_PATH=""
+.  else
+BOOTSTRAPJDKDIR=	${WRKDIR}/bootstrap
+BOOTSTRAP_DISTFILE=	bootstrap-openjdk8-8.40.25.tar.xz:bootstrap
+MAKE_ENV+=		LD_LIBRARY_PATH="${BOOTSTRAPJDKDIR}/jre/lib/amd64"
+.  endif
 .endif
 
 # PR193009: work around the rtld bug
@@ -377,14 +387,15 @@ do-install:
 	@cd ${JDK_IMAGEDIR} && ${COPYTREE_SHARE} . ${STAGEDIR}${INSTALLDIR}
 	@cd ${STAGEDIR}${INSTALLDIR} && \
 	    ${FIND} bin jre/bin -type f -exec ${CHMOD} ${BINMODE} {} \; && \
-	    ${CHMOD} ${BINMODE} jre/lib/${ARCH}/jexec \
-	    jre/lib/${ARCH}/jspawnhelper lib/${ARCH}/jexec
+	    ${CHMOD} ${BINMODE} jre/lib/${JDK_ARCH}/jexec \
+	    jre/lib/${JDK_ARCH}/jspawnhelper lib/${JDK_ARCH}/jexec
+	cd ${STAGEDIR}${INSTALLDIR}/include && ln -s dragonfly freebsd
 	@${ECHO} "@dir ${INSTALLDIR}/jre/lib/applet" >> ${TMPPLIST}
 .else
 	@cd ${JRE_IMAGEDIR} && ${COPYTREE_SHARE} . ${STAGEDIR}${INSTALLDIR}
 	@cd ${STAGEDIR}${INSTALLDIR} && \
 	    ${FIND} bin -type f -exec ${CHMOD} ${BINMODE} {} \; && \
-	    ${CHMOD} ${BINMODE} lib/${ARCH}/jexec lib/${ARCH}/jspawnhelper
+	    ${CHMOD} ${BINMODE} lib/${JDK_ARCH}/jexec lib/${JDK_ARCH}/jspawnhelper
 	@${ECHO} "@dir ${INSTALLDIR}/lib/applet" >> ${TMPPLIST}
 .endif
 	@${ECHO} "@unexec ${LOCALBASE}/bin/unregistervm ${INSTALLDIR}/bin/java" >> ${TMPPLIST}
