--- Makefile.orig	2020-01-23 17:52:13 UTC
+++ Makefile
@@ -49,10 +49,6 @@ CONFIGURE_ENV=	HOST_CC=${CC} HOST_CXX=${
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} == amd64
-CONFIGURE_TARGET=x86_64-portbld-freebsd${OSREL}
-.endif
-
 .if ${ARCH} == i386
 # ld: error: undefined symbol: __atomic_load
 USE_GCC=	9+
