--- Makefile.orig	2014-08-20 09:47:14.825958000 +0000
+++ Makefile
@@ -22,7 +22,9 @@ LIB_DEPENDS=	libcurl.so:${PORTSDIR}/ftp/
 		libopenjp2.so:${PORTSDIR}/graphics/openjpeg
 
 LIBS+=		-L${LOCALBASE}/lib
-MAKE_ARGS=	build=release prefix=${PREFIX} mandir=${PREFIX}/man verbose=yes
+MAKE_ARGS=	build=release prefix=${PREFIX} mandir=${PREFIX}/man verbose=yes \
+		XCFLAGS="-I${LOCALBASE}/include -I${LOCALBASE}/include/freetype2" \
+		XLIBS="-lXext -lX11 -L${LOCALBASE}/lib"
 USES=		pkgconfig gmake
 USE_XORG=	x11 xext
 
