--- Makefile.orig	2014-05-30 12:18:27.268634000 +0000
+++ Makefile
@@ -21,7 +21,8 @@ LIB_DEPENDS=	libfreetype.so:${PORTSDIR}/
 		libopenjpeg.so:${PORTSDIR}/graphics/openjpeg15
 
 MAKE_ARGS+=	build=release prefix=${PREFIX} verbose=1 mandir=${PREFIX}/man \
-		XCFLAGS=-I${LOCALBASE}/include
+		XCFLAGS="-I${LOCALBASE}/include -I${LOCALBASE}/include/freetype2" \
+		XLIBS="-lXext -lX11 -L${LOCALBASE}/lib"
 USES=		pkgconfig gmake zip
 USE_XORG=	x11 xext
 
