--- Makefile.orig	2019-07-31 15:04:13 UTC
+++ Makefile
@@ -22,16 +22,6 @@ USE_QT=		qmake_build buildtools_build co
 		network sql widgets graphicaleffects_run \
 		quickcontrols_run sql-sqlite3_run
 
-.include <bsd.port.pre.mk>
-
-.if ${ARCH:Mmips*} || ${ARCH:Mpowerpc*} || ${ARCH} == sparc64
-USE_GCC=	yes
-.else
-CC=		clang
-CXX=		clang++
-CPP=		clang-cpp
-.endif
-
 post-extract:
 	@${RMDIR} ${WRKSRC}/qmltermwidget
 	@${LN} -s ../qmltermwidget-0.2.0 ${WRKSRC}/qmltermwidget
@@ -48,4 +38,4 @@ post-install:
 	${INSTALL_MAN} ${WRKSRC}/packaging/debian/cool-retro-term.1 \
 		${STAGEDIR}${MANPREFIX}/man/man1
 
-.include <bsd.port.post.mk>
+.include <bsd.port.mk>
