--- Makefile.orig	2015-08-26 11:05:22 UTC
+++ Makefile
@@ -26,9 +26,12 @@ PLIST_SUB+=	MAJOR=${PORTVERSION:R:R}
 GNU_CONFIGURE=	yes
 USE_LDCONFIG=	yes
 
-CPPFLAGS+=	-I/usr/include/readline -I${LOCALBASE}/include
+USES+=		readline
+CPPFLAGS+=	-I${LOCALBASE}/include/readline -I${LOCALBASE}/include
 LDFLAGS+=	-L${LOCALBASE}/lib
 
+CONFIGURE_ENV+=		ac_cv_header_regex_h=no
+
 OPTIONS_DEFINE?=	SQLITE3 MYSQL PGSQL MTX PYTHON NLS OPENSSL
 OPTIONS_DEFAULT?=	NLS OPENSSL PGSQL
 MTX_DESC=		Install mtx for control of autochanger devices
