--- Makefile.orig	2014-01-25 17:01:02.556562000 +0000
+++ Makefile
@@ -19,6 +19,10 @@ USES=		perl5
 GNU_CONFIGURE=		yes
 USE_GMAKE=		yes
 
+# Make DragonFly default to mit (heimdal fails to configure)
+# Source builder can override in make.conf or command line
+KRB5_IMPL?= mit
+
 .if defined(KRB5_IMPL) && ${KRB5_IMPL} == heimdal
 .if defined(HEIMDAL_HOME)
 KRB5_DIR?=		${HEIMDAL_HOME}
