--- Makefile.orig	2014-07-17 09:21:33.620722000 +0000
+++ Makefile
@@ -26,6 +26,7 @@ HEIMDAL_DESC=		Link against Heimdal Kerb
 .include <bsd.port.pre.mk>
 
 .if ${PORT_OPTIONS:MHEIMDAL}
+LIB_DEPENDS=		libkrb5.so:${PORTSDIR}/security/heimdal
 .if defined(HEIMDAL_HOME)
 KRB5_DIR?=		${HEIMDAL_HOME}
 .endif
