--- Makefile.orig	2016-11-06 02:44:09 UTC
+++ Makefile
@@ -18,7 +18,8 @@ CONFIGURE_ENV=	OS_DEFS="-DSETPROCTITLE $
 CONFIGURE_ARGS=	--enable-nonauth-file=${POPUSERS_FILE} \
 		--without-gdbm \
 		--enable-keep-temp-drop
-LIBS+=		-L${LOCALBASE}/lib -lcrypt -lmd -lutil
+LIBS+=		-L${LOCALBASE}/lib -lcrypt -lutil
+CFLAGS+=	-DUINT4=u_int32_t
 
 PLIST_SUB=	EPOPPASSD=${EPOPPASSD} \
 		USERS=${USERS} \
@@ -127,7 +128,6 @@ post-patch:
 .if ${COMPILER_TYPE} == clang
 	@${REINPLACE_CMD} -e 's|-freg-struct-return||' ${WRKSRC}/configure.in
 .endif
-	@${RM} ${WRKSRC}/popper/md5.h
 	@${REINPLACE_CMD} -e 's|%%PREFIX%%|${PREFIX}|g' ${WRKSRC}/man/*
 	@${REINPLACE_CMD} -e \
 		's|\$${sbindir}/sendmail|${LOCALBASE}/sbin/sendmail|g' \
