--- Makefile.orig	2023-01-16 19:32:26 UTC
+++ Makefile
@@ -23,7 +23,7 @@ CONFIGURE_ARGS=	--enable-usbdropdir=${PR
 INSTALL_TARGET=	install-strip
 
 PLIST_FILES=	bin/RSA_SecurID_getpasswd \
-		lib/pcsc/drivers/ifd-ccid.bundle/Contents/FreeBSD/libccid.so \
+		lib/pcsc/drivers/ifd-ccid.bundle/Contents/DragonFly/libccid.so \
 		lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist \
 		share/man/man1/RSA_SecurID_getpasswd.1.gz
 
@@ -32,6 +32,6 @@ post-install:
 		${STAGEDIR}${PREFIX}/bin
 	${INSTALL_MAN} ${WRKSRC}/contrib/RSA_SecurID/RSA_SecurID_getpasswd.1 \
 		${STAGEDIR}${MAN1PREFIX}/share/man/man1
-	${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/pcsc/drivers/ifd-ccid.bundle/Contents/FreeBSD/libccid.so
+	${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/pcsc/drivers/ifd-ccid.bundle/Contents/${OPSYS}/libccid.so
 
 .include <bsd.port.mk>
