--- Makefile.orig	Tue Apr  1 21:48:43 2025
+++ Makefile	Tue Apr
@@ -24,7 +24,7 @@ BUNDLE_DIR=	${USBDROPDIR}/ifd-ccid.bundle
 PLIST_DIRS=	${USBDROPDIR}
 PLIST_FILES=	bin/RSA_SecurID_getpasswd \
 		bin/Kobil_mIDentity_switch \
-		${BUNDLE_DIR}/Contents/FreeBSD/libccid.so \
+		${BUNDLE_DIR}/Contents/DragonFly/libccid.so \
 		${BUNDLE_DIR}/Contents/Info.plist \
 		share/man/man1/RSA_SecurID_getpasswd.1.gz \
 		share/man/man8/Kobil_mIDentity_switch.8.gz
