--- Makefile.orig	2013-04-07 14:06:01.550261000 +0000
+++ Makefile
@@ -45,7 +45,7 @@ post-patch:
 		 s|^(LOADLIB=).*|\1 -DUSE_DLOPEN=1|; \
 		 s|^(CC=).*|\1 ${CC}|; \
 		 s|^#(USERCONF.*READLINE.*)|\1|; \
-		 s|^(EXTRA_LIBS=).*|\1 -lm -lreadline -lhistory -lncurses|; \
+		 s|^(EXTRA_LIBS=).*|\1 -lm -lncurses -L${LOCALBASE}/lib -lreadline -lhistory|; \
 		 s|^(V=[[:digit:]])\.0|\1|' \
 		${WRKSRC}/config
 	@${REINPLACE_CMD} -Ee 's|(ld -o lib/(liblua(lib)?)\.so\.\$$V)|\1 -soname=\2-${LUA_VER}.so.${LUA_VER_SH}|' \
