--- Makefile.orig	2012-12-31 12:00:50.220374000 +0100
+++ Makefile	2012-12-31 12:01:37.710440000 +0100
@@ -19,9 +19,11 @@
 
 .include <bsd.port.pre.mk>
 
+.if ${OPSYS} == "FreeBSD"
 .if ${OSVERSION} >= 800069
 IGNORE=		has been already included into base system
 .endif
+.endif
 
 .if ${PORT_OPTIONS:MSGML}
 BUILD_DEPENDS+=	${LOCALBASE}/share/sgml/jade/catalog:${PORTSDIR}/textproc/jade \
