--- Makefile.orig	2019-12-06 19:34:49 UTC
+++ Makefile
@@ -5,6 +5,7 @@ PORTNAME=	glassfish
 PORTVERSION=	4.1
 CATEGORIES=	www java
 MASTER_SITES=	http://dlc.sun.com.edgesuite.net/glassfish/${PORTVERSION}/release/
+PKGNAMESUFFIX=	4
 
 MAINTAINER=	jmd@FreeBSD.org
 COMMENT=	Reference implementation of the Java EE application server
