--- Makefile.orig	2020-01-12 12:34:08 UTC
+++ Makefile
@@ -16,7 +16,7 @@ LICENSE_FILE=	${WRKSRC}/LICENSE
 LIB_DEPENDS=	libitcl.so:lang/itcl
 
 USES+=		apache:2.2-2.4 gmake \
-		libtool tcl:85+,tea
+		libtool tcl:tea
 USE_LDCONFIG=	${PREFIX}/lib/rivet
 
 INSTALL_TARGET=	install-strip
