--- Makefile.orig	2013-10-06 22:46:51.377913000 +0000
+++ Makefile
@@ -19,6 +19,8 @@ SRC=		${.CURDIR}/src
 
 MAN1=		portlint.1
 PLIST_FILES=	bin/portlint
+USES+=		shebangfix
+SHEBANG_FILES=	*.pl
 
 .if !defined(NOPORTEXAMPLES)
 PLIST_FILES+=	%%EXAMPLESDIR%%/portlintgrep
@@ -29,13 +31,12 @@ NO_STAGE=	yes
 do-fetch:
 	@${DO_NADA}
 
-pre-patch:
-	@${CP} -R ${SRC} ${WRKDIR}
+do-extract:
+	@${MKDIR} ${WRKSRC}
+	@${CP} ${SRC}/* ${WRKSRC}/
 
 post-patch:
-	@${REINPLACE_CMD} -e 's|/usr/bin/perl|${PERL}|' ${WRKSRC}/portlint.pl
-	@${REINPLACE_CMD} -e 's|/usr/bin/perl|${PERL}|' \
-		${WRKSRC}/portlintgrep.pl
+	@${REINPLACE_CMD} -e 's|/usr/ports|/usr/dports|g' ${WRKSRC}/portlint*
 
 do-install:
 	${INSTALL_SCRIPT} ${WRKSRC}/portlint.pl ${PREFIX}/bin/portlint
