--- Makefile.orig	2013-10-20 18:02:08.340779000 +0000
+++ Makefile
@@ -21,16 +21,17 @@ SRC=		${.CURDIR}/src
 
 PLIST_FILES=	bin/portlint \
 		man/man1/portlint.1.gz
+USES+=		shebangfix
+SHEBANG_FILES=	*.pl
 
 PORTEXAMPLES=	portlintgrep
 
-pre-patch:
-	@${CP} -R ${SRC} ${WRKDIR}
+do-extract:
+	@${MKDIR} ${WRKSRC}
+	@${CP} ${SRC}/* ${WRKSRC}/
 
 post-patch:
-	@${REINPLACE_CMD} -e 's|/usr/bin/perl|${PERL}|' \
-		${WRKSRC}/portlint.pl \
-		${WRKSRC}/portlintgrep.pl
+	@${REINPLACE_CMD} -e 's|/usr/ports|/usr/dports|g' ${WRKSRC}/portlint*
 
 do-install:
 	${INSTALL_SCRIPT} ${WRKSRC}/portlint.pl \
