--- Makefile.orig	2013-12-28 04:39:49.687655000 +0000
+++ Makefile
@@ -33,7 +33,7 @@ post-patch:
 	@${RM} -f ${WRKSRC}/src/documentation/html/gettingstarted.html.orig
 	@${REINPLACE_CMD} -e 's|%%DOCSDIR%%|${DOCSDIR}|g' \
 	    ${WRKSRC}/src/configdialog.cpp ${WRKSRC}/src/src.pro
-	@${REINPLACE_CMD} -e 's|%%PREFIX%%|${PREFIX}|g' \
+	@${REINPLACE_CMD} -e 's|%%PREFIX%%|${STAGEDIR}${PREFIX}|g' \
 	    ${WRKSRC}/src/src.pro
 
 .include <bsd.port.mk>
