--- Makefile.orig	2013-12-11 18:08:52.000000000 +0000
+++ Makefile
@@ -82,6 +82,7 @@ PLIST_SUB+=		WITHSYBASE="@comment "
 
 .if ${PORT_OPTIONS:MNLS}
 USES+=		gettext
+LDFLAGS+=	-lintl
 PLIST_SUB+=		NLS=""
 .else
 CONFIGURE_ARGS+=	--disable-nls
