--- Makefile.orig	2024-02-09 23:47:30 UTC
+++ Makefile
@@ -209,7 +209,7 @@ LLVM_VERSION=	10
 RUN_DEPENDS+=	llc${LLVM_VERSION}:devel/llvm${LLVM_VERSION}
 .endif
 
-.if ${ARCH} != powerpc64
+.if ${OPSYS} == FreeBSD && ${ARCH} != powerpc64
 LIB_DEPENDS+=	libncursesw.so.8:misc/compat12x
 .endif
 
