--- Makefile.orig	2013-05-12 09:11:15.346607000 +0000
+++ Makefile
@@ -80,6 +80,9 @@ INTENDED_COMPILER=BOOTSTRAP
 FULL_GNATGCC=${BOOTSTRAP_PREFIX}/bin/gnatgcc
 FULL_PATH=${BOOTSTRAP_PREFIX}/bin:/sbin:/bin:/usr/sbin:/usr/bin:${PREFIX}/bin
 DISTFILES+=	${BOOTSTRAP_COMPILER}:boot
+.if ${OPSYS} == DragonFly && ${DFLYVERSION} > 300500
+BUILD_DEPENDS+=	c.7:${PORTSDIR}/misc/compat34x
+.endif
 .endif
 
 ###########
