--- Makefile.orig	2014-11-25 21:22:48.974173000 +0000
+++ Makefile
@@ -31,7 +31,7 @@ MAKE_ARGS+=		INSTALL_SHARED="${INSTALL_L
 MAKE_ARGS+=		LIBPC="${PREFIX}/libdata/pkgconfig"			# Until pathfix gets support for files other than Makefile.in
 
 PLIST_SUB=		ABI=${ABIFLAGS} \
-			OSMAJOR=${OSVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
+			OSMAJOR=${DFLYVERSION:C/([0-9]*)[0-9]{5}/\1/}		# For plat-freebsd* in pkg-plist. http://bugs.python.org/issue19554
 
 OPTIONS_DEFINE=		DEBUG IPV6 NLS PYMALLOC THREADS TSC UCS4 LIBFFI
 OPTIONS_DEFAULT=	IPV6 NLS PYMALLOC THREADS UCS4 LIBFFI
@@ -117,6 +117,7 @@ post-patch:
 # Since side effects for other modules can't be foreseen, do not fix
 # it on a source level yet.
 	@${CHMOD} a-x ${WRKSRC}/Lib/keyword.py ${WRKSRC}/Lib/token.py
+	@${REINPLACE_CMD} -e 's|`uname -r`|"${OSREL}"|g' ${WRKSRC}/configure
 
 post-install:
 .if !${PORT_OPTIONS:MDEBUG}
