--- Makefile.orig	2014-01-30 17:59:50.413411000 +0000
+++ Makefile
@@ -1,4 +1,4 @@
-# $FreeBSD: lang/python32/Makefile 341192 2014-01-26 14:47:56Z mva $
+\# $FreeBSD: lang/python32/Makefile 341192 2014-01-26 14:47:56Z mva $
 
 PORTNAME=		python32
 PORTVERSION=		3.2.5
@@ -198,8 +198,8 @@ post-install:
 		${STAGEDIR}${PREFIX}/lib
 	(cd ${STAGEDIR}${PREFIX}/lib; ${LN} -sf lib${PYTHON_VERSION}${PYABIVER}.so.1 \
 		lib${PYTHON_VERSION}${PYABIVER}.so)
-	${LN} -sf lib${PYTHON_VERSION}${PYABIVER}.so \
-		${STAGEDIR}${PYTHONPREFIX_LIBDIR}/config
+	(cd ${STAGEDIR}${PREFIX}/lib/${PYTHON_VERSION}/config-${PYTHON_VER}${PYABIVER}; \
+		${LN} -sf ../../lib${PYTHON_VERSION}${PYABIVER}.so)
 	${INSTALL_PROGRAM} \
 		${SHARED_WRKSRC}/${PYTHON_VERSION:S/thon/thon-shared/} \
 		${STAGEDIR}${PREFIX}/bin
