--- Makefile.orig	2019-04-16 10:53:29 UTC
+++ Makefile
@@ -54,4 +54,9 @@ post-install:
 		-e "s|%%PYTHON_LIBDIR%%|${PYTHON_LIBDIR}|g" \
 		-e "s|%%PYTHON_VERSION%%|${PYTHON_VERSION}|g" ${PKGMESSAGE}
 
+	${RM} -r ${STAGEDIR}${PREFIX}/lib/cmake/boost_math_c99l-*
+	${RM} -r ${STAGEDIR}${PREFIX}/lib/cmake/boost_math_tr1l-*
+	${RM} ${STAGEDIR}${PREFIX}/lib/libboost_math_tr1l.*
+	${RM} ${STAGEDIR}${PREFIX}/lib/libboost_math_c99l.*
+
 .include <bsd.port.mk>
