--- Makefile.orig	2020-07-09 16:55:57.676392000 +0200
+++ Makefile	2020-07-09 16:56:32.356499000 +0200
@@ -14,7 +14,6 @@
 LICENSE_FILE_APACHE20=	${WRKSRC}/LICENSE.Apache
 LICENSE_FILE_GPLv2=	${WRKSRC}/COPYING
 
-BROKEN_DragonFly=	does not build on DragonFly BSD using GCC with -Werror
 BROKEN_armv6?=		does not build: db/c.cc:2281:44: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int')
 BROKEN_armv7?=		does not build: /nxb-bin/usr/bin/ld: undefined reference to symbol `__gnu_Unwind_Find_exidx@@FBSD_1.4' (try adding -lc) #'`
 BROKEN_powerpc64=	does not build: util/crc32c.cc:435:22: 'arch_ppc_probe' was not declared in this scope
@@ -58,13 +57,13 @@
 
 .if !defined(LITE)
 CONFLICTS_INSTALL=	rocksdb-lite
-PLIST_SUB+=	LITE="@comment "
+PLIST_SUB+=	LITE="@comment " NOLITE=""
 .else
 PKGNAMESUFFIX=	-lite
 CONFLICTS_INSTALL=	rocksdb
 CFLAGS+=	-DROCKSDB_LITE=1
 MAKE_ENV+=	LIBNAME=librocksdb${PKGNAMESUFFIX} DISABLE_JEMALLOC=1
-PLIST_SUB+=	LITE=""
+PLIST_SUB+=	LITE="" NOLITE="@comment "
 .endif
 
 .include <bsd.port.pre.mk>
