--- Makefile.orig	2016-04-10 08:59:16 UTC
+++ Makefile
@@ -79,7 +79,7 @@ ALL_TARGET=	compile-core-native compile-
 .include <bsd.port.options.mk>
 
 .if ${ARCH} == "amd64"
-_HADOOP_ARCH=	FreeBSD-amd64-64
+_HADOOP_ARCH=	DragonFlyBSD-amd64-64
 .else
 _HADOOP_ARCH=	FreeBSD-${ARCH}-32
 .endif
