--- Makefile.orig	2013-08-15 13:42:03.000000000 +0000
+++ Makefile
@@ -24,6 +24,7 @@ USE_GL=		glut glew glu
 USE_XORG=	xrandr
 USE_QT4=	moc_build qmake_build rcc_build uic_build iconengines imageformats \
 		corelib svg xml opengl network
+QMAKEFLAGS+=	QMAKE_LFLAGS="-L${LOCALBASE}/lib -lX11 -lSDL-1.2"
 
 
 PORTDOCS=	README
