--- Makefile.orig	2013-01-26 12:58:35.650074000 +0100
+++ Makefile	2013-01-26 12:58:45.680088000 +0100
@@ -9,6 +9,7 @@
 # Don't reset PORTREVISION and keep bumping it even if PORTVERSION is changed.
 PORTREVISION=	6
 CATEGORIES=	chinese
+PKGNAMEPREFIX=	zh-
 
 MAINTAINER=	ports@FreeBSD.org
 
