--- Makefile.orig	2016-04-06 16:42:24 UTC
+++ Makefile
@@ -59,9 +59,7 @@ USE_PHP+=	pdo_pgsql pgsql
 .  endif
 .endif
 
-LIB_DEPENDS+=	libcurl.so:ftp/curl \
-		libstdc++.so:lang/gcc \
-		libutil.so:misc/compat8x
+IGNORE=		FreeBSD BLOB that will not work on DragonFly
 
 SUB_FILES=	pkg-message log.sh test-deps.sh
 SUB_LIST=	"GREP=${GREP}"
