# zrj lets just use upstream c++11 std:: way
--- Makefile.orig	2018-02-23 23:32:49 UTC
+++ Makefile
@@ -69,8 +69,6 @@ OPTIONS_DEFINE=	NLS
 OPTIONS_SUB=	yes
 
 post-patch:
-	@${FIND} ${WRKSRC} -name "*.cc" | ${XARGS} \
-	    ${REINPLACE_CMD} -e 's|isinf[ ]*(|::isinf(|g' -e 's|isnan|::isnan|g'
 	@${REINPLACE_CMD} -e 's|<FlexLexer.h>|"/usr/include/FlexLexer.h"|' \
 	    ${WRKSRC}/lily/include/includable-lexer.hh
 		${SED} -e 's|%%FONTDIR%%|${WRKDIR}/fontconfig/cache/|'  \
