--- Makefile.orig	2013-05-07 19:16:56.248395000 +0000
+++ Makefile
@@ -106,6 +106,9 @@ PLIST_SUB+=	NUT_SERIAL="@comment "
 .endif
 
 .if ${PORT_OPTIONS:MUSB}
+.if ${OPSYS} == DragonFly
+USES+=		usb
+.endif
 #EXTRA_PATCHES=	${FILESDIR}/extra-patch-m4_nut_check_libusb.m4
 CONFIGURE_ARGS+=	--with-usb=auto
 MAN8+=		bcmxcp_usb.8 richcomm_usb.8 tripplite_usb.8 usbhid-ups.8
