--- Makefile.orig	2013-03-08 23:13:08.565453000 +0000
+++ Makefile
@@ -17,8 +17,6 @@ COMMENT=		Curses library for Ada
 
 LICENSE=	MIT
 
-BUILD_DEPENDS=		gnat:${PORTSDIR}/lang/gnat
-
 USE_AUTOTOOLS=	libtool
 GNU_CONFIGURE=	yes
 USE_GMAKE=	yes
