--- Makefile.orig
+++ Makefile
@@ -336,27 +336,11 @@ PLIST_SUB+=		BACK_BDB="@comment " \
 			BACK_HDB="@comment "
 .else
 
-WITH_BDB_VER?=		46
-INVALID_BDB_VER=	42
-USE_BDB=		yes
-
-# XXX Can BDB 5.x use XY instead of X as version?
-.if ${WITH_BDB_VER} >= 43 || ${WITH_BDB_VER} == 5
-CONFIGURE_ARGS+=	--enable-bdb=${BACKEND_ENABLE} \
-			--enable-hdb=${BACKEND_ENABLE}
-PLIST_SUB+=		BACK_BDB=${BACKEND_PLIST} \
-			BACK_HDB=${BACKEND_PLIST}
-.elif ${WITH_BDB_VER} >= 4
-CONFIGURE_ARGS+=	--disable-bdb \
-			--enable-hdb=${BACKEND_ENABLE}
-PLIST_SUB+=		BACK_BDB="@comment " \
-			BACK_HDB=${BACKEND_PLIST}
-.elif ${WITH_BDB_VER} == 3
-CONFIGURE_ARGS+=	--disable-bdb \
-			--disable-hdb
-PLIST_SUB+=		BACK_BDB="@comment " \
-			BACK_HDB="@comment "
-.endif
+USE_BDB=		43+
+CONFIGURE_ARGS+=	--enable-bdb=${BACKEND_ENABLE}
+CONFIGURE_ARGS+=	--enable-hdb=${BACKEND_ENABLE}
+PLIST_SUB+=		BACK_BDB=${BACKEND_PLIST}
+PLIST_SUB+=		BACK_HDB=${BACKEND_PLIST}
 
 CPPFLAGS+=		-I${BDB_INCLUDE_DIR}
 CONFIGURE_SED+=		-e 's,ol_DB_LIB=$$,&-l${BDB_LIB_NAME:R},' \
