--- Makefile.orig	2013-05-07 16:56:30.036742000 +0000
+++ Makefile
@@ -25,7 +25,7 @@ RUN_DEPENDS+=	cdrdao:${PORTSDIR}/sysutil
 		pstree:${PORTSDIR}/sysutils/pstree \
 		transcode:${PORTSDIR}/multimedia/transcode \
 		vcdimager:${PORTSDIR}/multimedia/vcdimager \
-		rar:${PORTSDIR}/archivers/rar \
+		unrar:${PORTSDIR}/archivers/unrar \
 		${LOCALBASE}/sbin/fping:${PORTSDIR}/net/fping \
 		cdrecord:${PORTSDIR}/sysutils/cdrtools
 
