--- Makefile.orig	2017-11-08 10:26:44 UTC
+++ Makefile
@@ -37,7 +37,7 @@ post-patch:
 	@${REINPLACE_CMD} -i '' \
 		-e 's|"installationMethod": "tar"|"installationMethod": "pkg"|g' \
 		${WRKSRC}/package.json
-	@${REINPLACE_CMD} -i '' -e 's%Linux)%Linux|FreeBSD)%g' \
+	@${REINPLACE_CMD} -i '' -e 's%Linux)%Linux|FreeBSD|DragonFly)%g' \
 		${WRKSRC}/bin/yarn
 
 do-install:
