--- Makefile.orig	2015-06-14 17:05:31 UTC
+++ Makefile
@@ -45,7 +45,6 @@ CONFIGURE_ARGS+=	--localstatedir=/var
 CUPS_CACHEDIR?=	/var/db/cups
 CUPS_SPOOLDIR=	/var/spool/cups
 CUPS_SOCKET?=	/var/run/cups.sock
-CUPS_PDFTOPS?=	${LOCALBASE}/libexec/xpdf/pdftops
 WRKSRC=		${WRKDIR}/${PORTNAME}-${DISTVERSION}
 
 CUPSSYSGRP=	wheel
@@ -224,7 +223,7 @@ post-patch:
 	@${REINPLACE_CMD} -e 's|@PIEFLAGS@||' ${WRKSRC}/Makedefs.in
 .endif
 .if ${PORT_OPTIONS:MMDNSRESPONDER}
-	@${REINPLACE_CMD} -e 's|Darwin|FreeBSD|' \
+	@${REINPLACE_CMD} -e 's|Darwin|${OPSYS}|' \
 		${WRKSRC}/backend/Makefile
 .endif
 .if  ${PORT_OPTIONS:MXDG_OPEN}
