--- Makefile.orig	2012-12-18 14:00:41.222157000 +0100
+++ Makefile	2012-12-18 14:13:10.407552000 +0100
@@ -225,7 +225,9 @@
 .else
 CONFIGURE_ARGS+=	--disable-libusb
 .endif
-.if ${OSVERSION} >= 800000
+
+DFLY_GCC!=	gcc -dumpversion
+.if ${DFLY_GCC} != "4.4.7"
 CONFIGURE_ARGS+=	LIBS="-lssp_nonshared"
 .endif
 
