--- Makefile.orig	2018-02-03 00:51:55 UTC
+++ Makefile
@@ -36,6 +36,13 @@ CPE_VENDOR=	gnu
 GNU_CONFIGURE=	yes
 
 .if defined(PKGNAMEPREFIX)
+.  if !defined(BUTARGET)
+IGNORE=		target ${PKGNAMEPREFIX}${OPSYS:tl} will never build
+.  else
+.    if ${BUTARGET:M*-${OPSYS:tl}}
+IGNORE=		target ${BUTARGET} will never build
+.    endif
+.  endif
 BUTARGET?=	${PKGNAMEPREFIX}${OPSYS:tl}
 OPTIONS_EXCLUDE=	NLS
 INFO_PATH=	${PKGNAMEPREFIX:S/-$//}/info
@@ -64,6 +71,7 @@ INFO=		as \
 .endif
 
 CONFIGURE_ARGS+=	--disable-werror \
+			--with-lib-path=/lib:/usr/lib \
 			--enable-deterministic-archives \
 			--with-sysroot=/ \
 			--enable-x86-relax-relocations=no
@@ -89,11 +97,6 @@ PLIST_SUB+=	GOLD=""
 PLIST_SUB+=	GOLD="@comment "
 .endif
 
-.if ${ARCH} == "amd64"
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
-.else
-CONFIGURE_TARGET=	${ARCH}-portbld-freebsd${OSREL}
-.endif
 
 post-patch:
 	${REINPLACE_CMD} -e "s/-ldl//g" ${WRKSRC}/gold/testsuite/Makefile.in
