--- Makefile.orig	2016-04-10 14:42:40 UTC
+++ Makefile
@@ -28,6 +28,13 @@ USES=		bison gmake libtool tar:bzip2 com
 GNU_CONFIGURE=	yes
 
 .if defined(PKGNAMEPREFIX)
+.  if !defined(BUTARGET)
+IGNORE=		target ${PKGNAMEPREFIX}${OPSYS:tl} will never build
+.  else
+.    if ${BUTARGET:M*-${OPSYS:tl}}
+IGNORE=		target ${BUTARGET} will never build
+.    endif
+.  endif
 BUTARGET?=	${PKGNAMEPREFIX}${OPSYS:tl}
 OPTIONS_EXCLUDE=	NLS
 INFO_PATH=	${PKGNAMEPREFIX:S/-$//}/info
@@ -47,6 +54,7 @@ INFO=		as \
 .endif
 
 CONFIGURE_ARGS+=	--disable-werror \
+			--with-lib-path=/lib:/usr/lib \
 			--with-sysroot=/
 
 MAKE_ENV+=	ac_cv_func_sbrk=0
@@ -65,12 +73,6 @@ PLIST_SUB+=	GOLD=""
 PLIST_SUB+=	GOLD="@comment "
 .endif
 
-.if ${ARCH} == "amd64"
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
-.else
-CONFIGURE_TARGET=	${ARCH}-portbld-freebsd${OSREL}
-.endif
-
 post-install:
 .if !defined(PKGNAMEPREFIX)
 	${INSTALL_DATA} ${WRKSRC}/include/plugin-api.h ${STAGEDIR}${PREFIX}/include/
