--- Makefile.orig	2013-04-26 10:44:28.000000000 +0000
+++ Makefile
@@ -65,6 +65,7 @@ CONFIGURE_ARGS+=	--disable-pcre
 
 .if ${PORT_OPTIONS:MID3}
 LIB_DEPENDS+=	id3tag:${PORTSDIR}/audio/libid3tag
+LDFLAGS+=	-lz
 .else
 CONFIGURE_ARGS+=	--disable-id3tag
 .endif
