--- Makefile.orig	2026-02-14 13:29:29.169549000 +0100
+++ Makefile	2026-02-14 13:28:52.889275000 +0100
@@ -32,7 +32,7 @@ LIB_DEPENDS=	libFLAC.so:audio/flac \
 
 USES=		compiler:c11 dos2unix gl gmake gnome localbase pkgconfig sdl tar:xz
 USE_GL=		gl glu
-USE_GNOME=	gtk20
+USE_GNOME=	gtk20 gdkpixbufextra
 USE_SDL=	sdl2 mixer2
 WRKSRC=		${WRKDIR}/${PORTNAME}_${PORTVERSION}-${GITREVISION}
 GITREVISION=	10600-d384b22ac
@@ -41,7 +41,7 @@ SUB_FILES=	pkg-message
 MAKEFILE=	GNUmakefile
 MAKE_ARGS=	CC=${CC} CXX=${CXX} CLANG=1 PRETTY_OUTPUT=0 USE_MIMALLOC=0
 
-PLIST_FILES=	bin/eduke32 bin/mapster32
+PLIST_FILES=	bin/eduke32 bin/mapster32 share/applications/eduke32.desktop share/pixmaps/game_icon.png
 PORTEXAMPLES=	*
 
 OPTIONS_DEFINE=		ERP EXAMPLES OFFENSIVE
@@ -100,6 +100,8 @@ post-patch:
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/eduke32 ${STAGEDIR}${PREFIX}/bin/
 	${INSTALL_PROGRAM} ${WRKSRC}/mapster32 ${STAGEDIR}${PREFIX}/bin/
+	${INSTALL_DATA} ${WRKSRC}/eduke32.desktop ${STAGEDIR}${PREFIX}/share/applications/
+	${INSTALL_DATA} ${WRKSRC}/source/sw/rsrc/game_icon.png ${STAGEDIR}${PREFIX}/share/pixmaps/
 
 do-install-EXAMPLES-on:
 	@${MKDIR} ${STAGEDIR}${EXAMPLESDIR}
