--- Makefile.orig
+++ Makefile
@@ -40,3 +40,3 @@
 
-PLIST_FILES=	bin/eduke32 bin/mapster32
+PLIST_FILES=	bin/eduke32 bin/mapster32 share/applications/eduke32.desktop share/pixmaps/game_icon.png
 PORTEXAMPLES=	*
@@ -107,6 +107,8 @@
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/eduke32 ${STAGEDIR}${PREFIX}/bin/
 	${INSTALL_PROGRAM} ${WRKSRC}/mapster32 ${STAGEDIR}${PREFIX}/bin/
+	${INSTALL_DATA} ${WRKSRC}/eduke32.desktop ${STAGEDIR}${PREFIX}/share/applications/
+	${INSTALL_DATA} ${WRKSRC}/source/sw/rsrc/game_icon.png ${STAGEDIR}${PREFIX}/share/pixmaps/
 
 do-install-EXAMPLES-on:
 	@${MKDIR} ${STAGEDIR}${EXAMPLESDIR}
