--- Makefile.orig	2013-03-08 23:13:08.745442000 +0000
+++ Makefile
@@ -15,8 +15,6 @@ DISTNAME=	SGL-${PORTVERSION}
 MAINTAINER=	david@realityrift.com
 COMMENT=	STL implementation for ADA95
 
-RUN_DEPENDS=	gnatmake:${PORTSDIR}/lang/gnat
-
 NO_BUILD=	yes
 
 WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}
