--- Makefile.orig	2015-07-15 18:22:01.897670000 +0200
+++ Makefile	2015-08-08 01:38:42.428698000 +0200
@@ -34,6 +34,8 @@
 
 SODIUM_DESC=		Prefer libsodium
 SODIUM_LIB_DEPENDS=	libsodium.so:${PORTSDIR}/security/libsodium
+SODIUM_CONFIGURE_ON=	--with-libsodium-libs=${LOCALBASE}/lib \
+			--with-libsodium-headers=${LOCALBASE}/include
 
 NACL_DESC=		Prefer NaCl
 NACL_CONFIGURE_ENABLE=	nacl
