--- Makefile.orig	2014-03-29 20:19:46.656457000 +0000
+++ Makefile
@@ -28,8 +28,11 @@ OPTIONS_DEFINE=	DOCS
 
 .include <bsd.port.options.mk>
 
+USES+=	usb
+.if ${OPSYS} == DragonFly && ${DFLYVERSION} > 300702
 CONFIGURE_ENV+=	LIBUSB_CFLAGS="-I/usr/include" \
 		LIBUSB_LIBS="-L/usr/lib -lusb"
+.endif
 
 post-patch:
 	@${REINPLACE_CMD} -i '' \
