--- Makefile.orig	2013-10-13 18:50:45.078285000 +0000
+++ Makefile
@@ -36,9 +36,6 @@ CONFIGURE_SCRIPT=../configure
 IGNORE=		requires X11; use lang/racket-textual instead
 .endif
 
-.if ${ARCH} == "i386"
-MANUAL_PACKAGE_BUILD=	i386 requires kern.maxdsiz="640M" to build
-.endif
 
 LIB_DEPENDS+=	ffi:${PORTSDIR}/devel/libffi		\
 		cairo:${PORTSDIR}/graphics/cairo	\
