--- Makefile.orig	2014-06-19 22:56:18.745109000 +0000
+++ Makefile
@@ -12,16 +12,10 @@ COMMENT=	Multiwindow mouse-based text ed
 USE_XORG=	x11
 GNU_CONFIGURE=	yes
 CONFIGURE_ARGS=	--libdir=${PREFIX}/share
-LIBS+=		-lgnuregex
 MAKE_JOBS_UNSAFE=	yes
 
 PLIST_SUB=	VERSION="${PORTVERSION}"
 
-post-patch:
-	@${REINPLACE_CMD} -e 's| regex\.c | |g ; \
-		 s| -g | |g' ${WRKSRC}/Makefile.in
-	@${REINPLACE_CMD} -e \
-		's|"regex\.h"|<gnu/regex.h>|g' ${WRKSRC}/bm_search.c
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/xcoral ${STAGEDIR}${PREFIX}/bin
