--- Makefile.orig	2013-10-13 18:03:12.790641000 +0000
+++ Makefile
@@ -11,19 +11,12 @@ COMMENT=	A multiwindow mouse-based text
 
 USE_XORG=	x11
 GNU_CONFIGURE=	yes
-CONFIGURE_ENV=	LIBS="-lgnuregex"
 CONFIGURE_ARGS=	--libdir=${PREFIX}/share
 MAKE_JOBS_UNSAFE=	yes
 
 PLIST_SUB=	VERSION="${PORTVERSION}"
 
 NO_STAGE=	yes
-post-patch:
-	@${REINPLACE_CMD} -e 's| regex\.c | |g ; \
-		 s| -g | |g' ${WRKSRC}/Makefile.in
-	@${REINPLACE_CMD} -e \
-		's|"regex\.h"|<gnu/regex.h>|g' ${WRKSRC}/bm_search.c
-
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/xcoral ${PREFIX}/bin
 	@${MKDIR} ${DATADIR}
