--- Makefile.orig	2015-01-01 04:37:00 UTC
+++ Makefile
@@ -19,15 +19,11 @@ USE_XORG=	x11
 USES=		bison
 GNU_CONFIGURE=	yes
 CONFIGURE_ARGS=	--libdir=${PREFIX}/share
-LIBS+=		-lgnuregex
 
 PLIST_SUB=	VERSION="${PORTVERSION}"
 
 OPTIONS_DEFINE=	DOCS
 
-post-patch:
-	@${REINPLACE_CMD} -e 's| regex\.[co] | |g ; \
-		 s| -g | |g' ${WRKSRC}/Makefile.in
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/xcoral ${STAGEDIR}${PREFIX}/bin
