--- Makefile.orig	2022-02-24 00:00:39 UTC
+++ Makefile
@@ -30,6 +30,6 @@ ALSA_CXXFLAGS+=	-D__LINUX_ALSA__
 JACK_CXXFLAGS+=	-D__UNIX_JACK__
 
 CXXFLAGS+=	-I${LOCALBASE}/include -I${LOCALBASE}/include/tcl${TCL_VER}
-LIBS+=		-L${LOCALBASE}/lib -ltcl${TCL_SHLIB_VER} -lthr -ljack
+LIBS+=		-L${LOCALBASE}/lib -ltcl${TCL_SHLIB_VER} -ljack
 
 .include <bsd.port.mk>
