--- Makefile.orig	2013-01-26 14:30:18.107760000 +0100
+++ Makefile	2013-01-26 14:30:29.787776000 +0100
@@ -7,6 +7,7 @@
 
 CATEGORIES=	japanese
 PKGNAMESUFFIX=	-img
+PKGNAMEPREFIX=	ja-
 
 MAINTAINER=	nobutaka@FreeBSD.org
 COMMENT=	A pager/text-based WWW browser with Japanese and inline image support
