--- Makefile.orig	2013-02-18 22:03:39.720811000 +0100
+++ Makefile	2013-02-18 22:04:13.979304000 +0100
@@ -30,12 +30,14 @@
 CONFIGURE_ARGS+=	--enable-ecore-sdl \
 			--enable-ecore-input
 
+LDFLAGS+=	-L${LOCALBASE}/lib -lecore -lecore_input
+
 post-patch:
 	@${REINPLACE_CMD} -E \
 		-e 's,\$$\(top_builddir\)/src/lib/ecore/\.libs,${LOCALBASE}/lib,'\
 		-e 's,\$$\(top_builddir\)/src/lib/ecore_input/\.libs,${LOCALBASE}/lib,'\
-		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,-lecore,'\
-		-e 's,\$$\(top_builddir\)/src/lib/ecore_input/libecore_input\.la,-lecore_input,'\
+		-e 's,\$$\(top_builddir\)/src/lib/ecore/libecore\.la,,'\
+		-e 's,\$$\(top_builddir\)/src/lib/ecore_input/libecore_input\.la,,'\
 		${BUILD_WRKSRC}/Makefile.in
 
 post-install:
