--- Makefile.orig	2019-02-17 00:23:27.348831000 +0100
+++ Makefile	2019-02-17 00:23:37.029006000 +0100
@@ -3,6 +3,7 @@
 
 PORTNAME=	google-cloud-sdk
 PORTVERSION=	230.0.0
+PORTREVISION=	1
 CATEGORIES=	net
 MASTER_SITES=	https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/
 DISTNAME=	google-cloud-sdk-${PORTVERSION}-linux-x86_64
