--- Makefile.orig	2018-02-28 15:15:24 UTC
+++ Makefile
@@ -12,7 +12,6 @@ COMMENT=	Runtime components for KDE Plas
 LIB_DEPENDS=	libexiv2.so:graphics/exiv2 \
 		libwebp.so:graphics/webp \
 		libslp.so:net/openslp \
-		libssh.so:security/libssh \
 		libqzeitgeist.so:sysutils/qzeitgeist \
 		libImath-2_2.so:graphics/ilmbase \
 		libassuan.so:security/libassuan \
@@ -21,11 +20,13 @@ LIB_DEPENDS=	libexiv2.so:graphics/exiv2
 		libgpgme.so:security/gpgme
 # Explicitly depend on libssh to avoid interference with ssh.4 from
 # compat7x.
-BUILD_DEPENDS=	${LOCALBASE}/lib/libssh.so:security/libssh
+BUILD_DEPENDS=	libssh>0.7:security/libssh
 RUN_DEPENDS=	cagibid:net/cagibi
+RUN_DEPENDS+=	libssh>0.7:security/libssh
 
 USES=		cmake:outsource gettext jpeg kde:4 samba:lib shared-mime-info \
 		shebangfix tar:xz
+USES+=		gmake
 USE_KDE=	kactivities kdelibs oxygen-icons5 \
 		attica automoc4 pimlibs soprano strigi nepomuk-core
 USE_QT4=	corelib dbus declarative designer_build gui phonon \
