--- Makefile.orig	2018-07-05 23:41:56 UTC
+++ Makefile
@@ -14,7 +14,6 @@ CONFLICTS_INSTALL=	plasma5-kde-cli-tools
 LIB_DEPENDS=	libexiv2.so:graphics/exiv2 \
 		libwebp.so:graphics/webp \
 		libslp.so:net/openslp \
-		libssh.so:security/libssh \
 		libqzeitgeist.so:sysutils/qzeitgeist \
 		libImath-2_2.so:graphics/ilmbase \
 		libassuan.so:security/libassuan \
@@ -23,11 +22,13 @@ LIB_DEPENDS=	libexiv2.so:graphics/exiv2
 		libgpgme.so:security/gpgme
 # Explicitly depend on libssh to avoid interference with ssh.4 from
 # compat7x.
-BUILD_DEPENDS=	${LOCALBASE}/lib/libssh.so:security/libssh
+BUILD_DEPENDS=	libssh>0.7:security/libssh
 RUN_DEPENDS=	cagibid:net/cagibi
+RUN_DEPENDS+=	libssh>0.7:security/libssh
 
 USES=		cmake:outsource gettext jpeg kde:4 qt:4 samba:lib shared-mime-info \
 		shebangfix tar:xz
+USES+=		gmake
 USE_KDE=	kactivities kdelibs oxygen-icons5 \
 		attica automoc4 pimlibs soprano strigi nepomuk-core
 USE_QT=		corelib dbus declarative designer_build gui phonon \
