--- Makefile.orig	2015-06-02 11:49:35 UTC
+++ Makefile
@@ -33,10 +33,8 @@ PLIST_FILES=	bin/mosh bin/mosh-server bi
 
 .include <bsd.port.pre.mk>
 
-.if ${OSVERSION} < 900004
 LIB_DEPENDS+=	libutempter.so:${PORTSDIR}/sysutils/libutempter
 CFLAGS+=	-I${LOCALBASE}/include
 LDFLAGS+=	-L${LOCALBASE}/lib
-.endif
 
 .include <bsd.port.post.mk>
