--- Makefile.orig	2013-03-02 01:00:14.394218000 +0100
+++ Makefile	2013-03-02 01:08:23.812750000 +0100
@@ -22,6 +22,8 @@
 MAN1=		biconv.1
 MAN3=		biconv.3 biconv_open.3 biconv_close.3
 
+REPLACE_PERL=	iconv_builtin ccs/iconv_mktbl
+
 .if defined(NO_PROFILE) || defined(NOPROFILE) || defined(WITHOUT_PROFILE)
 PLIST_SUB=	PROFILE:="@comment "
 .else
