--- Makefile.orig	2015-12-21 01:57:49 UTC
+++ Makefile
@@ -107,7 +107,6 @@ ZLIB_DESC=		Interface to the zlib compre
 .if !exists(/usr/include/lwres)	# directory only exists on FreeBSD 9
 # On FreeBSD 9, CAIRO is built with GCC which pulls in binutils
 # binutils and BFD conflict, so BFD and CAIRO cannot coexist on F9
-OPTIONS_DEFAULT+=	BFD
 .endif
 
 .include <bsd.port.options.mk>
