--- Makefile.orig	2013-10-19 16:16:29.404003000 +0000
+++ Makefile
@@ -68,6 +68,7 @@ OPTIONS_DEFAULT+=	MAXKEY
 
 .include <bsd.port.options.mk>
 
+.if ${OPSYS} == FreeBSD
 .if ${OSVERSION} < 1000052
 LIB_DEPENDS=	libexecinfo.so:${PORTSDIR}/devel/libexecinfo
 .endif
@@ -77,6 +78,7 @@ CMAKE_ARGS+=	-DWITH_JEMALLOC="bundled"
 .else
 CMAKE_ARGS+=	-DWITH_JEMALLOC="system"
 .endif
+.endif
 
 .if ${PORT_OPTIONS:MSSL}
 .if ${PORT_OPTIONS:MOPENSSL}
