--- Makefile.orig	2019-10-26 10:50:18 UTC
+++ Makefile
@@ -23,6 +23,7 @@ CONFLICTS=	elasticsearch-[0-9]* elastics
 USES=		cpe shebangfix
 NO_ARCH=	yes
 USE_JAVA=	yes
+JAVA_RUN=	yes
 NO_BUILD=	yes
 JAVA_VERSION=	8+
 USE_RC_SUBR=	${PORTNAME}
@@ -112,7 +113,7 @@ do-install:
 	(cd ${WRKSRC}/modules && ${COPYTREE_SHARE} . ${STAGEDIR}${PREFIX}/lib/elasticsearch/modules/)
 	${MKDIR} ${STAGEDIR}${PREFIX}/lib/elasticsearch/plugins
 	${MKDIR} ${STAGEDIR}${PREFIX}/libexec/elasticsearch
-	${INSTALL} -lrs ${STAGEDIR}${ETCDIR} ${STAGEDIR}${PREFIX}/lib/elasticsearch/config
+	(cd ${STAGEDIR}${ETCDIR} && ${LN} -s ${STAGEDIR}${PREFIX}/lib/elasticsearch/config config)
 	${LN} -s ${JAVASHAREDIR}/classes/jna.jar ${STAGEDIR}${PREFIX}/lib/elasticsearch/lib/jna.jar
 
 do-install-DOCS-on:
