--- Makefile.orig	2024-09-23 15:02:24 UTC
+++ Makefile
@@ -15,7 +15,6 @@ EXTRACT_DEPENDS=	rcs:devel/rcs57
 USES=		tar:bzip2
 LDFLAGS=	-Wl,--allow-multiple-definition
 NO_WRKSUBDIR=	yes
-PORTDOCS=	paper.ascii.gz
 
 OPTIONS_DEFINE=	DOCS
 
@@ -23,14 +22,9 @@ post-extract:
 	cd ${WRKSRC} ; co RCS/*,v; chmod u+w *
 	cd ${WRKSRC}/USD.doc ; co RCS/*,v
 
-post-build:
-	cd ${WRKSRC}/USD.doc ; ${MAKE}
-
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/csh ${STAGEDIR}${PREFIX}/bin/44bsd-csh
 	${INSTALL_MAN} ${WRKSRC}/csh.1 ${STAGEDIR}${PREFIX}/share/man/man1/44bsd-csh.1
-	@${MKDIR} ${STAGEDIR}${DOCSDIR}
-	${INSTALL_DATA} ${WRKSRC}/USD.doc/paper.ascii.gz ${STAGEDIR}${DOCSDIR}
 
 tarup:
 	cd ${WRKSRC} ; rm * USD.doc/*
