--- Makefile.orig	2013-04-02 16:53:21.402150000 +0000
+++ Makefile
@@ -56,7 +56,6 @@ HTDIG_DESC=		Use htdig to build manual i
 .include "${.CURDIR}/../../x11/kde3/Makefile.kde"
 .include <bsd.port.pre.mk>
 
-EXTRA_PATCHES+=	${FILESDIR}/extrapatch-libusb20
 
 .if ${PORT_OPTIONS:MARTSWRAPPER}
 RUN_DEPENDS+=	artswrapper:${PORTSDIR}/audio/artswrapper
