--- Makefile.orig	2017-02-20 20:41:44 UTC
+++ Makefile
@@ -20,7 +20,7 @@ STRIP=		# stripping can break go binarie
 TARGET_ORDER_OVERRIDE=	680:post-extract
 
 post-extract:
-	@${MV} ${WRKSRC}/vendor/ ${WRKSRC}/src/
+	${MV} ${WRKSRC}/vendor ${WRKSRC}/src
 
 do-build:
 	@cd ${WRKSRC}/src/github.com/${GH_ACCOUNT}/${PORTNAME}; ${SETENV} GOPATH=${WRKSRC} go build -o bin/${PORTNAME}
