--- Makefile.orig	2013-03-19 22:50:38.094011000 +0000
+++ Makefile
@@ -25,6 +25,8 @@ USE_QT4=	qmake_build uic_build moc_build
 		corelib svg xml opengl network
 MAKE_JOBS_SAFE=	yes
 
+QMAKEFLAGS+=	QMAKE_LFLAGS="-L${LOCALBASE}/lib -lX11"
+
 post-patch:
 	@${REINPLACE_CMD} -e 's|/usr/local/games/jag|${DATADIR}|' \
 		${WRKSRC}/main.cpp ${WRKSRC}/Game.pro
