--- Makefile.orig	2012-12-03 14:22:54.000000000 +0100
+++ Makefile	2012-12-10 14:05:43.819432000 +0100
@@ -124,7 +124,7 @@
 		${WRKSRC}/util/fluxbox-generate_menu.in
 	@${REINPLACE_CMD} -e 's|%%LOCALBASE%%|${LOCALBASE}|g' \
 		${WRKSRC}/util/fbsetbg
-.if empty(PORT_OPTIONS:MNLS}
+.if empty(PORT_OPTIONS:MNLS)
 	@${REINPLACE_CMD} -e 's|HAVE_ICONV=yes|HAVE_ICONV=no|g' \
 		${WRKSRC}/configure
 .endif
