--- Makefile.orig	2013-03-29 00:44:53.000000000 +0000
+++ Makefile
@@ -17,7 +17,7 @@ LICENSE_COMB=	dual
 RUN_DEPENDS=	p5-Filter>=0:${PORTSDIR}/devel/p5-Filter \
 		p5-HTTP-Message>=1.43:${PORTSDIR}/www/p5-HTTP-Message \
 		p5-Scalar-List-Utils>=1.14:${PORTSDIR}/lang/p5-Scalar-List-Utils \
-		ja-p5-WWW-MobileCarrierJP>=0.04:${PORTSDIR}/japanese/p5-WWW-MobileCarrierJP \
+		p5-WWW-MobileCarrierJP>=0.04:${PORTSDIR}/japanese/p5-WWW-MobileCarrierJP \
 		p5-XML-Simple>=0:${PORTSDIR}/textproc/p5-XML-Simple \
 		p5-YAML>0:${PORTSDIR}/textproc/p5-YAML
 BUILD_DEPENDS:=	${RUN_DEPENDS}
