--- Makefile.orig
+++ Makefile
@@ -24,7 +24,7 @@ ONLY_FOR_ARCHS=	amd64 i386 powerpc powerpc64 # XXX someone wants to debug sparc6
 
 OPTIONS_DEFINE=	SAMBA X11 GTK2 OPENGL GNUTLS SASL JPEG PNG CURL \
 		CDROM_DMA PCAP USBREDIR GNS3 X86_TARGETS \
-		STATIC_LINK DOCS
+		STATIC_LINK DOCS VKNET
 SAMBA_DESC=		samba dependency (for -smb)
 GNUTLS_DESC=		gnutls dependency (vnc encryption)
 SASL_DESC=		cyrus-sasl dependency (vnc encryption)
@@ -32,12 +32,13 @@ JPEG_DESC=		jpeg dependency (vnc lossy compression)
 PNG_DESC=		png dependency (vnc compression)
 CDROM_DMA_DESC=		IDE CDROM DMA
 PCAP_DESC=		pcap dependency (networking with bpf)
+VKNET_DESC=		vknet network backend for simple userspace bridge
 USBREDIR_DESC=		usb device network redirection (experimental!)
 GNS3_DESC=		gns3 patches (promiscuous multicast)
 X86_TARGETS_DESC=	Don't build non-x86 system targets
 BSD_USER_DESC=		Also build bsd-user targets (for testing)
 STATIC_LINK_DESC=	Statically link the executables
-OPTIONS_DEFAULT=X11 GTK2 OPENGL GNUTLS SASL JPEG PNG CDROM_DMA CURL PCAP
+OPTIONS_DEFAULT=X11 GTK2 OPENGL GNUTLS SASL JPEG PNG CDROM_DMA CURL PCAP VKNET
 
 .if !defined(QEMU_USER_STATIC)
 CONFLICTS_INSTALL=	qemu-[0-9]* qemu-sbruno-[0-9]*
@@ -183,6 +184,10 @@ RUN_DEPENDS+=	usbredir>=0.6:${PORTSDIR}/net/usbredir
 CONFIGURE_ARGS+=	--enable-pcap
 .endif
 
+.if ${PORT_OPTIONS:MVKNET}
+CONFIGURE_ARGS+=	--enable-vknet
+.endif
+
 .if ${PORT_OPTIONS:MSTATIC_LINK}
 .if ${PORT_OPTIONS:MGTK2} || ${PORT_OPTIONS:MX11}
 IGNORE=		X11 ui cannot be built static
@@ -232,6 +237,9 @@ post-patch:
 .if ${PORT_OPTIONS:MPCAP}
 	@cd ${WRKSRC} && ${PATCH} --quiet < ${FILESDIR}/pcap-patch
 .endif
+.if ${PORT_OPTIONS:MVKNET}
+	@cd ${WRKSRC} && ${PATCH} --quiet < ${DFLY_FILESDIR}/vknet-patch
+.endif
 .if empty(PORT_OPTIONS:MCDROM_DMA)
 	@cd ${WRKSRC} && ${PATCH} --quiet < ${FILESDIR}/cdrom-dma-patch
 .endif
