--- Makefile.orig	2020-04-16 14:53:34 UTC
+++ Makefile
@@ -65,7 +65,7 @@ OPTIONS_DEFAULT=	EFI ISO
 EFI_DESC=	Create EFI image
 ISO_DESC=	Create bootable CD image
 
-_EFI_ARCHS=		${ARCH:Mamd64:S/amd64/x86_64/} i386
+_EFI_ARCHS=	x86_64
 .for _arch in ${_EFI_ARCHS}
 EFI_PLIST_FILES+=	${DATADIR}/ipxe.efi-${_arch}
 .endfor
