i386 needs patched binutils with i386-efi target for dragonfly

--- Makefile.orig	2018-04-30 13:24:13 UTC
+++ Makefile
@@ -70,7 +70,7 @@ OPTIONS_DEFINE=         ISO EFI
 EFI_DESC=	Create EFI image
 ISO_DESC=	Create bootable CD image
 
-EFI_ARCHS=	i386 ${ARCH:Mamd64:S/amd64/x86_64/}
+EFI_ARCHS=	x86_64
 .for _arch in ${EFI_ARCHS}
 EFI_PLIST_FILES+=	${DATADIR}/ipxe.efi-${_arch}
 .endfor
