--- Makefile	(revision 353037)
+++ Makefile	(working copy)
@@ -3,6 +3,7 @@
 
 PORTNAME=	cfitsio
 PORTVERSION=	3.360
+PORTREVISION=	1
 CATEGORIES=	astro
 MASTER_SITES=	http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/ \
 		http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/oldvers/ \
@@ -22,8 +23,9 @@
 
 ALL_TARGET=	libcfitsio.a shared
 CFLAGS+=	-I${INCLUDEDIR}
-CONFIGURE_ARGS=	ZLIB_SOURCES="" ac_cv_prog_FC=f2c
+CONFIGURE_ARGS=	ac_cv_prog_FC=f2c
 GNU_CONFIGURE=	yes
+MAKE_ARGS=	ZLIB_SOURCES="zlib/zcompress.c zlib/zuncompress.c"
 LDFLAGS+=	-L${LIBDIR} -lz
 USE_LDCONFIG=	yes
 USES=		pkgconfig
@@ -36,9 +38,6 @@
 SHLIB_MAJOR_VER=2
 SHLIB_MINOR_VER=${PORTVERSION:S/0$//}
 
-post-patch:
-	@${REINPLACE_CMD} -e 's|$${ZLIB_SOURCES[:=a-z\.]*}||' ${WRKSRC}/Makefile.in
-
 do-install:
 	cd ${WRKSRC}/ && ${INSTALL_DATA} drvrsmem.h fitsio.h fitsio2.h longnam.h ${STAGEDIR}${PREFIX}/include/
 	cd ${WRKSRC}/ && ${INSTALL_LIB} libcfitsio.a libcfitsio.so.${SHLIB_MAJOR_VER}.${SHLIB_MINOR_VER} ${STAGEDIR}${PREFIX}/lib/
