--- Makefile.orig	2012-11-17 06:55:46.000000000 +0100
+++ Makefile	2013-01-17 00:33:28.328174000 +0100
@@ -41,8 +41,8 @@
 
 .include <bsd.port.options.mk>
 
-.if ${ARCH} == "amd64"
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+.if ${ARCH} == "x86_64"
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 CONFIGURE_ARGS+=	--with-gmp=${PREFIX}
