--- Makefile.orig	2013-04-29 08:57:12.000000000 +0000
+++ Makefile
@@ -23,7 +23,8 @@ USE_MYSQL=	yes
 USE_BZIP2=	yes
 PLUGIN=		plugins/src/sqldrivers/${DB}
 DRIVER=		src/sql/drivers/${DB}
-EXTRACT_AFTER_ARGS?=	${DISTNAME}/${DRIVER} ${DISTNAME}/src/sql/drivers/cache
+EXTRACT_AFTER_ARGS?=	${DISTNAME}/${PLUGIN} ${DISTNAME}/${DRIVER} \
+		${DISTNAME}/src/sql/drivers/cache
 MAKEFILE=	${FILESDIR}/Makefile.bsd
 MAKE_ENV+=	DB="${DB}" DRIVER="${DRIVER}" PLUGIN="${PLUGIN}" \
 		PTHREAD_CFLAGS="${PTHREAD_CFLAGS}" \
