# no pulse
BUILD_DEPENDS:=	${BUILD_DEPENDS:N${LOCALBASE}/include/pulse*:Nllvm*}

LIB_DEPENDS+=	libasound.so:audio/alsa-lib
RUN_DEPENDS+=	${LOCALBASE}/lib/alsa-lib/libasound_module_pcm_oss.so:audio/alsa-plugins
RUN_DEPENDS+=	alsa-lib>=1.1.1_1:audio/alsa-lib
