--- Makefile.orig	2023-02-22 09:53:19 UTC
+++ Makefile
@@ -104,10 +104,6 @@ post-install-DOCS-on:
 
 .include <bsd.port.pre.mk>
 
-.if (${OPSYS} == FreeBSD && ${OSVERSION} < 1400072) || ${OPSYS} != FreeBSD
-CONFIGURE_ARGS+=	--enable-opie
-.endif
-
 .if ${OPSYS} == FreeBSD && (${ARCH:Mpowerpc*} && ${OSREL:R} < 13)
 # as of 2019-10-02, powerpc's base compiler does not yield a working fetchmail.
 # https://svnweb.freebsd.org/ports?view=revision&revision=513614 -- pkubaj@
