--- Makefile.orig	2024-02-10 00:59:21 UTC
+++ Makefile
@@ -101,8 +101,4 @@ post-install-DOCS-on:
 
 .include <bsd.port.pre.mk>
 
-.if (${OPSYS} == FreeBSD && ${OSVERSION} < 1400072) || ${OPSYS} != FreeBSD
-CONFIGURE_ARGS+=	--enable-opie
-.endif
-
 .include <bsd.port.post.mk>
