--- Makefile.orig	2013-01-12 01:08:13.777535000 +0100
+++ Makefile	2013-01-12 01:22:43.348750000 +0100
@@ -28,8 +28,8 @@
 
 .include <bsd.port.pre.mk>
 
-.if ${ARCH} == "x86_64"
-CONFIGURE_TARGET=	x86_64-portbld-freebsd${OSREL}
+.if ${ARCH:S///} == "amd64"
+CONFIGURE_TARGET=	x86_64-portbld-${OPSYS:tl}${OSREL}
 .endif
 
 .include <bsd.port.post.mk>
