--- Makefile.orig	2013-08-30 08:19:28.000000000 +0000
+++ Makefile
@@ -35,8 +35,8 @@ GEN_LIB_DEPENDS=curl:${PORTSDIR}/ftp/cur
 		event-2.0.6:${PORTSDIR}/devel/libevent2
 GEN_RUN_DEPENDS=${LOCALBASE}/share/transmission/web/index.html:${PORTSDIR}/www/transmission-web
 
-USE_GMAKE=	yes
-USES=		pkgconfig
+# USES+= because this is a master port
+USES+=		gmake pkgconfig
 USE_OPENSSL=	yes
 GNU_CONFIGURE=	yes
 CPPFLAGS+=	-I${LOCALBASE}/include
@@ -49,6 +49,9 @@ EXTRA_CONF_ARGS?=--enable-cli \
 		 --disable-mac \
 		 --disable-nls
 
+USES+= 		iconv
+LDFLAGS+=	${ICONV_LIB}
+
 .if ${PORT_OPTIONS:MLITE}
 CONFIGURE_ARGS+=--enable-lightweight
 .endif
