--- Makefile.orig	2013-03-17 23:17:24.677185000 +0000
+++ Makefile
@@ -43,7 +43,7 @@ MAN1=		snownews.1
 MANLANG=	"" de nl fr it ru_RU.KOI8-R
 
 post-patch:
-	@${REINPLACE_CMD} -e 's|#!/usr/local/bin/perl|#!${PERL}|g' ${WRKSRC}/configure
+	@${REINPLACE_CMD} -e 's|#!/usr/bin/perl|#!${PERL}|g' ${WRKSRC}/configure
 	@${REINPLACE_CMD} -e 's|ncurses|ncursesw|g' ${WRKSRC}/configure
 	@${REINPLACE_CMD} -e 's|gcc|${CC}|' ${WRKSRC}/Makefile
 	@${REINPLACE_CMD} -e 's|make|${GMAKE}|' ${WRKSRC}/Makefile
