--- Makefile.orig	2023-10-24 09:16:20 UTC
+++ Makefile
@@ -15,7 +15,6 @@ USES=		cpe libtool pathfix python:env,te
 CONFIGURE_ENV=	ac_cv_func_getopt_long=yes
 GNU_CONFIGURE=	yes
 INSTALL_TARGET=	install-strip
-LDFLAGS+=	-lmd
 TEST_TARGET=	check
 USE_LDCONFIG=	yes
 
@@ -29,7 +28,4 @@ OPTIONS_DEFAULT=PNG
 PNG_CONFIGURE_WITH=	libpng=${LOCALBASE}
 PNG_LIB_DEPENDS=	libpng.so:graphics/png
 
-post-patch:
-	@${RM} ${WRKSRC}/getopt* ${WRKSRC}/sha1.h
-
 .include <bsd.port.mk>
