--- Makefile.orig	2020-10-28 10:24:24 UTC
+++ Makefile
@@ -12,6 +12,9 @@ LICENSE=	GPLv3
 LICENSE_FILE=	${WRKSRC}/COPYING
 
 USES=		autoreconf libtool
+USES+=		ssl
+LDFLAGS+=	-L${OPENSSLLIB} -lcrypto
+FILESDIR=	${.CURDIR}/does-not-exist
 
 CONFIGURE_ENV=	ac_cv_func_getopt_long=yes
 GNU_CONFIGURE=	yes
@@ -25,10 +28,6 @@ PNG_CONFIGURE_OFF=	--without-libpng
 PNG_CONFIGURE_ON=	--with-libpng=${LOCALBASE}
 PNG_LIB_DEPENDS=	libpng.so:graphics/png
 
-post-patch:
-	@${RM} ${WRKSRC}/getopt* ${WRKSRC}/sha1.h
-	@${REINPLACE_CMD} -E 's|SHA1_Final\( *([^,]+), *([^\)]+)\)|SHA1_Final(\2, \1)|' ${WRKSRC}/jbig2dec.c ${WRKSRC}/sha1.c
-
 pre-configure:
 	@cd ${WRKSRC}/ && ${SH} autogen.sh
 
