--- Makefile.orig       2023-08-05 04:42:25.309312000 +0000
+++ Makefile
@@ -54,7 +54,7 @@
 USE_GL=                gl glew glu
 USE_SDL=       sdl2
 USE_XORG=      ice sm x11 xext xi xrandr
-USE_QT=                buildtools_build core gui widgets
+USE_QT=                buildtools core gui widgets

 CMAKE_ARGS+=   -DUSE_UPNP:BOOL=ON \
                -DENABLE_QT:BOOL=ON \
