--- Makefile.orig	2014-10-20 15:14:54 UTC
+++ Makefile
@@ -80,7 +80,7 @@ DIST_EXT=	gtk-linux-x86
 .endif
 
 post-extract:
-	@(cd ${WRKSRC} && ${UNZIP_NATIVE_CMD} -qo *.zip)
+	@(cd ${WRKSRC} && ${UNZIP_CMD} -qo *.zip)
 	@${RM} -f ${WRKSRC}/*.o ${WRKSRC}/*.so ${WRKSRC}/*.jar
 
 post-patch:
