--- Makefile.orig	2019-08-12 11:59:39 UTC
+++ Makefile
@@ -23,10 +23,6 @@ GH_PROJECT=	libfuse
 
 .include <bsd.port.pre.mk>
 
-.if ${OPSYS} == DragonFly
-IGNORE=	fusefs has not been implemented on DragonFly
-.endif
-
 .if ${CHOSEN_COMPILER_TYPE} == gcc
 post-patch:
 	${REINPLACE_CMD} -e '/-Wno-unused-result/d' ${WRKSRC}/meson.build
