--- Makefile.orig	2021-10-16 11:26:22 UTC
+++ Makefile
@@ -25,9 +25,6 @@ PLIST_SUB=	VERSION=${PORTVERSION}
 .if ${OPSYS} == "FreeBSD" && ${OSVERSION} < 1400014
 EXTRA_PATCHES=	${FILESDIR}/extra-patch-test_meson.build
 .endif
-.if ${OPSYS} == DragonFly
-IGNORE=	fusefs has not been implemented on DragonFly
-.endif
 
 .if ${CHOSEN_COMPILER_TYPE} == gcc
 post-patch:
