--- Makefile.orig	2017-08-23 21:54:37 UTC
+++ Makefile
@@ -73,6 +73,8 @@ do-configure:
 .for module in ${MODULES}
 	@echo "================================="
 	@echo "Configuring ${module}"
+	${REINPLACE_CMD} -e 's/FreeBSD-\*/FreeBSD-*|DragonFly-*/g' \
+		${WRKDIR}/${module}${PORTVERSION}/configure
 	cd ${WRKDIR}/${module}${PORTVERSION} && \
 	    ${SETENV} ${CONFIGURE_ENV} ${SH} configure \
 	    ${CONFIGURE_ARGS} ${${module}_CONFIGURE_ARGS}
