--- Makefile.orig	2016-01-05 07:29:04 UTC
+++ Makefile
@@ -80,8 +80,6 @@ LIB_DEPENDS+=		libsasl2.so:${PORTSDIR}/s
 # GNUTLS
 LIB_DEPENDS+=		libgcrypt.so:${PORTSDIR}/security/libgcrypt
 LIB_DEPENDS+=		libgnutls.so:${PORTSDIR}/security/gnutls
-# NFS4 ACL glue
-LIB_DEPENDS+=		libsunacl.so:${PORTSDIR}/sysutils/libsunacl
 # Libarchive
 BUILD_DEPENDS+=		libarchive>=3.1.2:${PORTSDIR}/archivers/libarchive
 RUN_DEPENDS+=		libarchive>=3.1.2:${PORTSDIR}/archivers/libarchive
@@ -120,7 +118,7 @@ OPTIONS_DEFINE=		ACL_SUPPORT AD_DC ADS A
 			DNSUPDATE DOCS FAM LDAP PAM_SMBPASS \
 			PTHREADPOOL QUOTAS SYSLOG UTMP
 
-OPTIONS_DEFAULT:=	ACL_SUPPORT AD_DC ADS AIO_SUPPORT DEBUG \
+OPTIONS_DEFAULT:=	AD_DC ADS AIO_SUPPORT DEBUG \
 			DNSUPDATE DOCS FAM LDAP \
 			PTHREADPOOL QUOTAS SYSLOG UTMP
 
@@ -154,6 +152,7 @@ NSUPDATE_DESC=		Use samba NSUPDATE utili
 .include <bsd.port.options.mk>
 
 CONFIGURE_ARGS+=	\
+			--without-regedit \
 			--with-pam \
 			--with-iconv \
 			--with-winbind \
