--- Makefile.orig	2017-02-20 21:00:11 UTC
+++ Makefile
@@ -55,7 +55,7 @@ PLIST_SUB+=	GRAFANAHOMEDIR=${GRAFANAHOME
 STRIP=	# stripping can break go binaries
 
 post-extract:
-	@${MV} ${WRKSRC}/vendor/ ${WRKSRC}/src/
+	${MV} ${WRKSRC}/vendor ${WRKSRC}/src
 	@${MKDIR} ${WRKSRC}/src/github.com/grafana/grafana
 .for src in CHANGELOG.md Gruntfile.js LICENSE.md Makefile NOTICE.md README.md \
 	bower.json build.go circle.yml conf docker docs emails examples \
