--- Makefile.orig	2015-10-30 09:33:25 UTC
+++ Makefile
@@ -8,6 +8,7 @@ CATEGORIES=	www
 MASTER_SITES=	http://www.akherb.com/FreeBSD/source/ \
 		LOCAL/beech
 DISTNAME=	zen-cart-v1.3.9h-full-fileset-10262010
+EXTRACT_SUFX=	.zip
 
 MAINTAINER=	ports@FreeBSD.org
 COMMENT=	PHP-based user-friendly, open source shopping cart
@@ -15,7 +16,7 @@ COMMENT=	PHP-based user-friendly, open s
 LICENSE=	GPLv2
 LICENSE_FILE=	${WRKSRC}/license.txt
 
-USES=		dos2unix shebangfix zip
+USES=		dos2unix shebangfix
 SHEBANG_FILES=	editors/htmlarea/examples/2-areas.cgi \
 		editors/htmlarea/examples/test.cgi \
 		editors/htmlarea/plugins/SpellChecker/spell-check-logic.cgi
