--- Makefile.orig	2022-07-08 00:07:25 UTC
+++ Makefile
@@ -76,6 +76,7 @@ do-install:
 	@(cd ${INSTALL_WRKSRC}; ${SETENV} ${GEM_ENV} ${RUBYGEMBIN} install ${RUBYGEM_ARGS} pkg/${GEMFILES} -- ${CONFIGURE_ARGS})
 	@${RM} -r ${STAGEDIR}${PREFIX}/${GEMS_BASE_DIR}/build_info
 	@${RMDIR} ${STAGEDIR}/${PREFIX}/${GEMS_BASE_DIR}/extensions
+	@${RMDIR} ${STAGEDIR}/${PREFIX}/${GEMS_BASE_DIR}/plugins
 
 post-install:
 	@${ECHO} ${GEM_CACHE} >> ${TMPPLIST}
