--- Makefile.orig	2013-04-05 22:54:51.974574000 +0000
+++ Makefile
@@ -94,7 +94,7 @@ do-install:
 # Integrated dependencies insist on using lib/pkgconfig -- instead of huge
 # patches, we'll symlink it temporarily
 	@${MKDIR} ${ZENHOME}/lib \
-		&& ${LN} -sF ${ZENHOME}/libdata/pkgconfig \
+		&& ${LN} -fs ${ZENHOME}/libdata/pkgconfig \
 		${ZENHOME}/lib/pkgconfig
 
 	@cd ${WRKSRC} && ${ENV} ${BUILD_ENV} SVNVERSION=${FALSE} bash ./build.sh 2>/dev/null
