--- Makefile.orig	2017-11-02 19:31:13 UTC
+++ Makefile
@@ -97,7 +97,7 @@ post-patch:
 post-install:
 	${LN} -sf libzorba_simplestore.so.${PORTVERSION} ${STAGEDIR}${PREFIX}/lib/libzorba_simplestore.so.${PORTVERSION:R:R}
 .if ${PORT_OPTIONS:MDOCS} && !${PORT_OPTIONS:MDOXYGEN}
-	cd ${STAGEDIR}${DOCSDIR} && ${RMDIR} c/html code/html code cxx/html zorba/html zorba/xqdoc zorba
+	cd ${STAGEDIR}${DOCSDIR} && ${RM} -r c/html code/html code cxx/html zorba/html zorba/xqdoc zorba
 .endif
 
 test:	build
