--- Makefile.orig	2013-12-28 06:02:42.286999000 +0000
+++ Makefile
@@ -151,7 +151,7 @@ post-extract:
 post-patch:
 	${REINPLACE_CMD} -e "s|%%PREFIX%%|${PREFIX}|g" \
 		${WRKSRC}/man/vice.1
-	${REINPLACE_CMD} -e "s|^localedir.*|localedir = ${LOCALBASE}/share/locale|" \
+	${REINPLACE_CMD} -e "s|^localedir.*|localedir = ${STAGEDIR}${PREFIX}/share/locale|" \
 		${WRKSRC}/po/Makefile.in.in
 	${REINPLACE_CMD} -e 's|lungif|lgif|g' -e 's|== "x|= "x|' \
 		-e 's|"DATADIRNAME"/locale|share/locale|' \
