--- Makefile.orig	2021-09-18 11:14:02 UTC
+++ Makefile
@@ -127,8 +127,6 @@ LIBXML2_LIB_DEPENDS=	libxml2.so:textproc
 
 OPENSSL_CONFIGURE_WITH=	openssl
 OPENSSL_USES=		ssl
-OPENSSL_VARS=		BROKEN_SSL="libressl libressl-devel" \
-			BROKEN_SSL_REASON="PSK is not provided by LibreSSL"
 
 GNUTLS_CONFIGURE_WITH=	gnutls
 GNUTLS_LIB_DEPENDS=	libgnutls.so:security/gnutls
