--- Makefile.orig	2012-11-17 05:56:41.000000000 +0000
+++ Makefile
@@ -11,4 +11,6 @@ MASTERDIR=	${.CURDIR}/../../lang/php52
 
 PKGNAMESUFFIX=	-readline
 
+USES+=		readline
+
 .include "${MASTERDIR}/Makefile"
