--- Makefile.orig	2013-11-30 23:27:03.547471000 +0000
+++ Makefile
@@ -27,7 +27,7 @@ PORTDOCS=	FAQ NEWS README
 
 .include <bsd.port.pre.mk>
 
-.if ${OSVERSION} > 1000000
+.if ${OPSYS} == FreeBSD && ${OSVERSION} > 1000000
 BUILD_DEPENDS+=	cvs:${PORTSDIR}/devel/cvs
 RUN_DEPENDS+=	cvs:${PORTSDIR}/devel/cvs
 .endif
