name: Build on Pull Request
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]
jobs:
  get-changed-files:
    name: Retrieve changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DeltaPorts repository (depth 2)
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        uses: tj-actions/changed-files@v37
        id: changed-files
      - name: Save all changed files to a temp file
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}
          do
            echo "$file" >> changed-files.txt
          done
      - name: Display changed files
        run: |
          cat changed-files.txt
      - name: Upload changed files
        uses: actions/upload-artifact@v3
        with:
          name: changed-files
          path: changed-files.txt

  generate-and-build:
    name: Generate index and build ports
    runs-on: [ self-hosted, dports ]
    timeout-minutes: 1200
    needs: get-changed-files
    steps:
      - name: Retrieve changed files
        uses: actions/download-artifact@v3
        with:
          name: changed-files
          path: downloads
      - name: Display changed files
        run: |
          cat downloads/changed-files.txt
      - name: Parse changes
        id: parsing
        run: echo "dport=$(/root/bin/parse.sh $GITHUB_WORKSPACE/downloads/changed-files.txt)" >> $GITHUB_OUTPUT
      - name: Setup chroot
        run: /root/bin/setup_chroot.sh $GITHUB_WORKSPACE
      - name: Checkout DeltaPorts repository
        if: ${{ steps.parsing.outputs.dport  != 'NOPORT' }}
        uses: actions/checkout@v3
        with:
          path: DeltaPorts
      - name: Checkout DPorts repository
        if: ${{ steps.parsing.outputs.dport  != 'NOPORT' }}
        uses: actions/checkout@v3
        with:
          repository: DragonFlyBSD/DPorts
          path: DPorts
          ref: staged
      - name: Checkout freebsd-ports repository
        if: ${{ steps.parsing.outputs.dport  != 'NOPORT' }}
        uses: actions/checkout@v3
        with:
          ref: 2023Q4
          repository: freebsd/freebsd-ports
          path: freebsd-ports
          persist-credentials: false
      - name: Generate INDEX, merge DeltaPorts
        if: ${{ steps.parsing.outputs.dport  != 'NOPORT' }}
        run: /root/bin/generate.sh "${{ steps.parsing.outputs.dport }}"
      - name: Build port
        if: ${{ steps.parsing.outputs.dport  != 'NOPORT' }}
        run: /root/bin/run.sh "${{ steps.parsing.outputs.dport }}"
      - name: Cleanup chroot
        if: always()
        run: /root/bin/cleanup_chroot.sh $GITHUB_WORKSPACE
