--- Makefile.orig	2013-06-02 21:38:33.000000000 +0000
+++ Makefile
@@ -26,7 +26,6 @@ RUN_DEPENDS=	p5-Cairo>=0:${PORTSDIR}/gra
 
 MAKE_JOBS_UNSAFE=	yes
 
-BROKEN=		fails to build
 
 MAN1=		perltetris.pl.1 perlmine.pl.1
 MAN3=		Goo::Canvas::Item.3 \
