--- Makefile.orig	2016-05-30 16:45:57.000000000 +0300
+++ Makefile
@@ -15,7 +15,7 @@ LIB_DEPENDS=	libpcsclite.so:devel/pcsc-l
 
 USES=	perl5 pkgconfig tar:bz2
 
-PLIST_FILES=	lib/pcsc/drivers/ifd-acsccid.bundle/Contents/FreeBSD/libacsccid.so \
+PLIST_FILES=	lib/pcsc/drivers/ifd-acsccid.bundle/Contents/${OPSYS}/libacsccid.so \
 		lib/pcsc/drivers/ifd-acsccid.bundle/Contents/Info.plist
 
 GNU_CONFIGURE=	yes
@@ -23,12 +23,12 @@ GNU_CONFIGURE=	yes
 .include <bsd.port.pre.mk>
 
 # Old versions don't have pkgconfig files for libusb
-.if ${OSVERSION} < 1000024
+.if ${OPSYS} == FreeBSD && ${OSVERSION} < 1000024
 CONFIGURE_ENV+=	LIBUSB_CFLAGS="-I${LOCALBASE}/include" \
 		LIBUSB_LIBS="-L${LOCALBASE}/lib -lusb"
 .endif
 
 post-install:
-	${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/pcsc/drivers/ifd-acsccid.bundle/Contents/FreeBSD/libacsccid.so
+	${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/pcsc/drivers/ifd-acsccid.bundle/Contents/${OPSYS}/libacsccid.so
 
 .include <bsd.port.post.mk>
