--- Makefile.orig	2016-02-22 17:05:52 UTC
+++ Makefile
@@ -9,11 +9,6 @@ MASTER_SITES=	http://virtual-estates.net
 MAINTAINER=	mi@aldan.algebra.com
 COMMENT=	Cache earlier sendmail's verdicts for the relays
 
-.if !exists( /usr/include/libmilter/mfapi.h )
-BUILD_DEPENDS+=	${LOCALBASE}/include/libmilter/mfapi.h:${PORTSDIR}/mail/sendmail
-CFLAGS+=	-I${LOCALBASE}/include
-.endif
-
 USES=		tar:bzip2 uidfix
 
 PLIST_FILES=	sbin/skem \
@@ -29,6 +24,7 @@ SKEM_NETINET_DESC=	Support IPv4 addresse
 OPTIONS_DEFAULT=	SKEM_NETINET
 
 .include <bsd.port.options.mk>
+.include "${.CURDIR}/../sendmail/bsd.milter.mk"
 
 MAKE_ENV+=	PTHREAD_LIBS="-lpthread"
 
