--- Makefile.orig	2024-01-26 00:44:51 UTC
+++ Makefile
@@ -11,8 +11,8 @@ WWW=		https://www.lazarus-ide.org/
 
 CONFLICTS?=	lazarus-gtk2 lazarus-qt5 lazarus-qt5-devel lazarus-qt6-devel
 
-BUILD_DEPENDS?=	${LOCALBASE}/bin/as:devel/binutils
-RUN_DEPENDS?=	${LOCALBASE}/bin/as:devel/binutils \
+BUILD_DEPENDS?=	${LOCALBASE}/bin/as:devel/binutils@native
+RUN_DEPENDS?=	${LOCALBASE}/bin/as:devel/binutils@native \
 		gmake:devel/gmake \
 		${LOCALBASE}/share/fpc-source-${FPC_DEFAULT}/Makefile.fpc:lang/fpc-source
 
@@ -52,7 +52,7 @@ SUB_LIST+=	PORTSDIR="${PORTSDIR}"
 RUN_DEPENDS+=	${LOCALBASE}/bin/gdb:devel/gdb
 .endif
 
-.if ${PKGNAMESUFFIX} == "-gtk2"
+.if ${PKGNAMESUFFIX} == "-gtk2-devel"
 USES+=		gnome
 USE_GNOME=	cairo gtk20 gdkpixbuf2
 .endif
