--- Makefile.orig	2013-02-04 16:02:11.000000000 +0000
+++ Makefile
@@ -1,7 +1,7 @@
 # $FreeBSD: ports/finance/skrooge/Makefile,v 1.13 2013/02/04 16:02:11 svnexp Exp $
 
 PORTNAME=	skrooge
-PORTVERSION=	1.4.0
+PORTVERSION=	1.6.0
 CATEGORIES=	finance kde
 MASTER_SITES=	http://skrooge.org/files/
 
