--- Makefile.orig	2013-03-18 09:05:12.294302000 +0000
+++ Makefile
@@ -36,7 +36,7 @@ DESKTOP_ENTRIES="Defendguin" "${COMMENT}
 do-build:
 	cd ${WRKSRC} && ${CC} ${CFLAGS} -DDATA_PREFIX=\"${DATADIR}/\" \
 		`${SDL_CONFIG} --cflags` defendguin.c -o defendguin \
-		`${SDL_CONFIG} --libs` -lSDL_mixer
+		`${SDL_CONFIG} --libs` -lSDL_mixer -lm
 
 do-install:
 	${INSTALL_PROGRAM} ${WRKSRC}/${PORTNAME} ${PREFIX}/bin/
