--- Makefile.orig	2013-04-14 20:45:28.143896000 +0000
+++ Makefile
@@ -27,7 +27,10 @@ FT_PROGRAMS=	ftbench ftchkwd ftdiff ftdu
 
 .include <bsd.port.pre.mk>
 
-FREETYPE_WRKSRC!=	cd ${PORTSDIR}/print/freetype2; ${MAKE} -V WRKSRC
+.if exists(../../print/freetype2)
+FREETYPE2VER!=		awk '{ if ($$1 == "PORTVERSION=") print $$2 }' ../../print/freetype2/Makefile ; echo
+.endif
+FREETYPE_WRKSRC=	${WRKDIR:S,ft2demos/work,freetype2/work/freetype-${FREETYPE2VER},}
 
 do-install:
 	@(cd ${WRKSRC}/bin/.libs/; ${INSTALL_PROGRAM} ${FT_PROGRAMS} ${PREFIX}/bin)
